### ISSUE TITLE
数学公式编号问题

### ISSUE THREAD

**Issue by FengHZ** [TheNetAdmin/zjuthesis#1]
在`config/package.tex`下没有对数学公式以及相应编号的环境。可以增加以下语句解决:
```
\usepackage{amsmath}
\renewcommand{\thesection}{%
  \ifnum\c@chapter<1 \@arabic\c@section
  \else \thechapter.\@arabic\c@section
  \fi
}
\numberwithin{equation}{section}% reset equation counter for sections
\numberwithin{equation}{subsection}
% Omit `.0` in equation numbers for non-existent subsections.
\renewcommand*{\theequation}{%
  \ifnum\value{subsection}=0 %
    \thesection
  \else
    \thesubsection
  \fi
  .\arabic{equation}%
}
```
这样采用以下带编号的数学公式环境时可以自动生成`(section.subsection)`的编号
```
\begin{equation}
\end{equation}
```

**Comment by TheNetAdmin** [comment]
根据编写规则2.3.1.2节，公式编号从1开始。那你的这个编号规则是学院格式要求的一部分么？如果是学院要求，能否提供一下专业名称与专业英文简称，我更新一下专业格式。

**Comment by FengHZ** [comment]
@TheNetAdmin 您好，我的专业是数学科学学院，英文简称就是School of Math。我没有注意到原来的编写规则，以为都是和数院一样按章节编号的通用规则，真是抱歉了。

我上面添加的语句可以直接在`package.tex`里添加，然后亲测是可以使用的。麻烦您了。

**Comment by TheNetAdmin** [comment]
我更新了v1.2.0版本，尝试把新版本`config/format`目录下的内容迁移过来，并在`config/format/format.tex`中，将cs格式引入改为math格式引入（参考README.md），然后编译看一下结果怎么样。

**Comment by FengHZ** [comment]
@TheNetAdmin 您好，编码公式会出现`(0.x.y)`的格式，`0`好像是章节的标号，不知能不能去掉~我原来在`config/package.tex`里加了
```
\renewcommand{\thesection}{%
  \ifnum\c@chapter<1 \@arabic\c@section
  \else \thechapter.\@arabic\c@section
  \fi
}
```
去掉了章节编号。

**Comment by TheNetAdmin** [comment]
@FengHZ 我在v1.2.0里`config/format/general/numbering.tex`中去掉了section的chapter前缀，你看这个文件你有更新吗

```latex
\renewcommand*{\thesection}{\arabic{section}}
```

我编译得到的结果是
![image](https://user-images.githubusercontent.com/18525442/39859218-abdcc6de-546b-11e8-8482-983ea3c615a1.png)

**Comment by FengHZ** [comment]
@TheNetAdmin 我重新更新了这个文件，现在可以了~谢谢！

**Comment by FengHZ** [comment]
@TheNetAdmin 不用保留章节编号，用`section.subsection`即可~谢谢

**Comment by TheNetAdmin** [comment]
OK，issue关闭，如有问题可以重开此issue。
