### ISSUE TITLE
cs硕士模板的正文行间距的问题

### ISSUE THREAD

**Issue by ye-yechen** [TheNetAdmin/zjuthesis#100]
## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.2.0

Degree:
  - [ ] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

**截图**

![image](https://user-images.githubusercontent.com/13674685/102015114-950c5680-3d94-11eb-86de-99a02dcf3d48.png)

**其他信息**

您好，我想问一下，cs硕士的模板的正文行间距是1.25倍吗，要求应该是1.5倍，我跟同学的对比了一下，行间距好像确实不一样，想问一下想改的话要怎么改？感谢

**Comment by TheNetAdmin** [comment]
https://github.com/TheNetAdmin/zjuthesis/blob/59f28cfcad504be16c1211cd05b6771e6aeb6b08/config/format/general/layout.tex#L25

**Comment by TheNetAdmin** [comment]
Latex和word的间距并不通用，要把这个值调大一点，具体数值可以搜一下

**Comment by ye-yechen** [comment]
好的，感谢
