### ISSUE TITLE
CS master 模板间距

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#102]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [x] Linux/Docker
- [x] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [x] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

https://github.com/TheNetAdmin/zjuthesis/commit/0608a80595422265c6e2f5133184e4bcea7c4fbe#commitcomment-45209852

本来是要修复 #88 的 CS PhD bug，但造成了CS Master 模板的 bug

**截图**

**其他信息**

**Comment by TheNetAdmin** [comment]
尝试使用原来的代码：

```LaTeX
% config/format/major/cs/layout.tex
    \ifthenelse{\equal{\GradLevel}{master}}
    {
        \geometry{
            a4paper,	
            marginpar=0pt,	
            includeheadfoot,	
            vmargin={3.0cm, 3.0cm},	
            hmargin={3.1cm, 3.1cm},	
            headsep=4mm,
            showframe
        }
    }{}

```

发现 #88 所报告的问题是 `fancyhdr` 没有遵循 `geometry` 的设定造成的

![image](https://user-images.githubusercontent.com/18525442/102532545-011ee100-4059-11eb-8d24-ab71485037fa.png)


**具体设定**
  1. 在 `config/format/general/layout.tex` 中先调用 `geometry` 进行 general 版面设置，然后进行了 `fancyhdr` 的设定
  2. 在 `config/format/major/cs/layout.tex` 中覆盖了 `geometry` 和 `fancyhdr` 的一些设定

**结果**
正文版面遵循了 `cs/layout.tex` 的设定，但 `fancyhdr` 没有遵循 `cs/layout.tex` 内的 `geometry` 设定

**Comment by TheNetAdmin** [comment]
似乎在 `cs/layout.tex` 中加入如下代码可以缓解问题

```LaTeX
\pagestyle{common}
\tocloftpagestyle{previous}
```

因为在 `general/layout.tex` 中设置了以上代码，可能造成后续的 `cs/layout.tex` 内的 `fancyhdr` 没有完全生效，即只有格式生效，但间距设定无效

**Comment by TheNetAdmin** [comment]
将 `general/layout.tex` 内的 `geometry` 设定注释，保留 `cs/layout.tex` 的 `geometry`，版面恢复正常

![image](https://user-images.githubusercontent.com/18525442/102533709-9ff80d00-405a-11eb-91ef-d1474a411421.png)

**Comment by TheNetAdmin** [comment]
类似问题 https://tex.stackexchange.com/a/33877

**Comment by Woolseyyy** [comment]
按这样修改后仍然会有正文和页眉不对齐的问题，并且奇偶页的空白不一样

**Comment by TheNetAdmin** [comment]
新开一个issue附个截图？
