### ISSUE TITLE
PDF 文件比较

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#103]
## 可改进的内容

当前的 Release 流程只是编译完所有 PDF 文件后直接创建 Release，并没有将新的 PDF 与之前 Release 的 PDF 进行对比。

自动对比前后 PDF 的区别可以更好的定位一些隐性 BUG，例如为了修复一个 BUG 却造成了另一个 BUG 的情况。

## 代码与步骤

1. 添加一个脚本用于 PDF 文件比较，例如像素级 PDF 文件比较
2. 在 GitHub Action 中，创建 Release 时，对比新的 PDF 与之前 Release 中的 PDF， 并创建一个报告文件，用于快速定位代码修改带来的变化

一些可能有用的链接

- https://www.pdftron.com/documentation/web/guides/compare/pixels/
- https://pypi.org/project/diff-pdf-visually/

**Comment by zepinglee** [comment]
这个想法不错。`thuthesis` 的测试是基于 `l3build`，把 TeX 的中间表示作为比对内容，见 https://github.com/tuna/thuthesis/tree/master/testfiles 的 `.tlg` 文件。这种基于文本的比对方式显然不如基于 pdf 的直观。其实 `l3build` 也可以基于 pdf 进行测试，但是会进行 normalize 操作，比如去掉 pdf 的 `/ID` 的，经过这样处理后的文件不能用阅读器打开，`l3build` 也没有提供比对的工具。

另外 https://github.com/vslavik/diff-pdf 也是个不错的工具，直接将 diff 的结果输出到 pdf，比基于图片像素的比较要好一些，尤其是细微的 kerning 差异。

不过我比较担心的是引入 pdf 这样的二进制文件会把仓库搞得太大。

**Comment by TheNetAdmin** [comment]
> 这个想法不错。`thuthesis` 的测试是基于 `l3build`，把 TeX 的中间表示作为比对内容，见 https://github.com/tuna/thuthesis/tree/master/testfiles 的 `.tlg` 文件。这种基于文本的比对方式显然不如基于 pdf 的直观。其实 `l3build` 也可以基于 pdf 进行测试，但是会进行 normalize 操作，比如去掉 pdf 的 `/ID` 的，经过这样处理后的文件不能用阅读器打开，`l3build` 也没有提供比对的工具。
> 
> 另外 https://github.com/vslavik/diff-pdf 也是个不错的工具，直接将 diff 的结果输出到 pdf，比基于图片像素的比较要好一些，尤其是细微的 kerning 差异。
> 
> 不过我比较担心的是引入 pdf 这样的二进制文件会把仓库搞得太大。

感谢建议！pdf-diff 这个工具我正在尝试，确实不错也比较方便。

我认为这些比较结果的 report 可以作为 GitHub Action 的 Artifact 上传，或者上传到 Release 中，就不会占用代码仓库。

**Comment by zepinglee** [comment]
> 我认为这些比较结果的 report 可以作为 GitHub Action 的 Artifact 上传，或者上传到 Release 中，就不会占用代码仓库。

这样似乎也可以。我之前理解的是用 git 跟踪测试的标准文件，每次修改模板后，都会编译测试文件跟标准文件比对，确认无误后再把标准文件一起 commit 到 git 仓库。另外你可以试下是每次 commit 测试还是每次发布时测试。

**Comment by TheNetAdmin** [comment]
> 另外你可以试下是每次 commit 测试还是每次发布时测试。

有道理，我暂时的设想是：

1. 新建一个 Release，将所有符合标准的文件发布到这个 Release 中
2. 之后每次 Commit 或 Release 时，都和标准 Release 中的 pdf 进行对比，如果对比有出入，就 fail 掉 GitHub Action

近期有空我会尝试写一些脚本来做这个功能，然后在这个 Issue 中总结一下开发中遇到的问题

**Comment by muzimuzhi** [comment]
> 我认为这些比较结果的 report 可以作为 GitHub Action 的 Artifact 上传，或者上传到 Release 中，就不会占用代码仓库。

https://github.com/pgf-tikz/pgf 的做法是，每次把编译得到的二进制文件 `pgfmanual.pdf` force push 到单独的分支。作为结果的二进制输出并没有保持版本管理的必要，这么也有一定合理性。

**Comment by muzimuzhi** [comment]
- 看了看，`diff-pdf` 应该是用 `cairo` 把 pdf 转成点阵图片，然后进行比较的。这样实际上依赖了具体的 pdf 阅读器。
 - `l3build` 有直接比较 pdf 文件内容的办法，一些使用例子可以见 [`ctex-kit` 中 `ctex` 部分的测试集](https://github.com/CTeX-org/ctex-kit/tree/master/ctex/test/testfiles)。
 - [`mutool`](https://mupdf.com) 也能把 pdf 转换成方便进行比较的形式（所有 steam 都不压缩，所有内嵌二进制信息如图片字体都以 ascii 表示），`mutool clean -ad input.pdf output.pdf`。后两种的好处是不依赖 pdf 阅读器，坏处是依赖各 tex 引擎的稳定性（pdf 内部表示不同，视觉输出可能相同）。

**Comment by TheNetAdmin** [comment]
我刚刚开发完了这个功能，代码位于 `zjuthesis/script/ci/pdf-diff/` 目录下：
  - `download_standard_pdf.sh` 负责从指定的 GitHub Release 中下载 Baseline PDF 文件
  - `diff_report.sh` 负责比较当前 CI 生成的 PDF 与 Baseline PDF

经过一番比较，我选择了 [diff-pdf-visually](https://pypi.org/project/diff-pdf-visually/) 这个工具，它提供的 Python 包方便后续开发，命令行选项足够直观，而且可以用命令的返回值来判断比较结果

一个比较样例：

我在 [v6.4.0](https://github.com/TheNetAdmin/zjuthesis/releases/tag/v6.4.0) 中修复了 `cs master` 模板的页边距问题，导致 `v6.4.0` 与 `v6.3.4` 的 `zjuthesis-graduate-master-cs-thesis-final.pdf` 文件有所差异，但其他 PDF 文件应当保持一致。

使用当前的工具进行判断后生成的报告如下：

```
zjuthesis-graduate-doctor-general-thesis-final-blind: 0
zjuthesis-graduate-doctor-general-thesis-final-english: 0
zjuthesis-graduate-doctor-general-thesis-final: 0
zjuthesis-graduate-master-cs-thesis-final: 2
zjuthesis-graduate-master-general-thesis-final: 0
zjuthesis-undergraduate-cs-design-final: 0
zjuthesis-undergraduate-cs-design-proposal: 0
zjuthesis-undergraduate-cs-thesis-final: 0
zjuthesis-undergraduate-cs-thesis-proposal: 0
zjuthesis-undergraduate-general-thesis-final-blind: 0
zjuthesis-undergraduate-general-thesis-final: 0
zjuthesis-undergraduate-general-thesis-proposal: 0
zjuthesis-undergraduate-isee-thesis-final: 0
zjuthesis-undergraduate-math-thesis-final: 0
zjuthesis-undergraduate-physics-thesis-final: 0
```

其中 `zjuthesis-graduate-master-cs-thesis-final` 文件发现了显著差异，进一步查阅 `diff-pdf-visually` 的输出如下：

```
  Temporary directory: /tmp/diffpdfb3dko76g
  Converting each page of the PDFs to an image...
  PDFs have same number of pages. Checking each pair of converted images...
- Page 01: significance=16.2555
- Page 02: significance=inf
- Page 03: significance=16.0901
- Page 04: significance=inf
- Page 05: significance=23.8679
- Page 06: significance=25.6932
- Page 07: significance=24.5513
- Page 08: significance=25.6324
- Page 09: significance=20.1719
- Page 10: significance=25.7163
- Page 11: significance=23.252
- Page 12: significance=25.6542
- Page 13: significance=24.0079
- Page 14: significance=25.6926
- Page 15: significance=15.7653
- Page 16: significance=15.3912
- Page 17: significance=20.2611
- Page 18: significance=25.6526
- Page 19: significance=20.7182
- Page 20: significance=25.6705
- Page 21: significance=17.9468
- Page 22: significance=25.7193
- Page 23: significance=23.0911
Min sig = 15.3912, significant?=True. The PDFs are different. The most different pages are: page 16 (sgf. 15.3912), page 15 (sgf. 15.7653), page 3 (sgf. 16.0901), page 1 (sgf. 16.2555), page 21 (sgf. 17.9468).
```

同时对比前后 PDF 的变化如下 (`zjuthesis-graduate-master-cs-thesis-final.pdf`)：

**v6.4.0: [对应 PDF](https://github.com/TheNetAdmin/zjuthesis/releases/download/v6.4.0/zjuthesis-graduate-master-cs-thesis-final.pdf)**
![image](https://user-images.githubusercontent.com/18525442/102949530-5b66da00-447d-11eb-8b0f-b97ae90ab31a.png)


**v6.3.4: [对应 PDF](https://github.com/TheNetAdmin/zjuthesis/releases/download/v6.3.4/zjuthesis-graduate-master-cs-thesis-final.pdf)**
![image](https://user-images.githubusercontent.com/18525442/102949680-abde3780-447d-11eb-88b5-000d57a4e47a.png)

**Comment by hushidong** [comment]
呀，pdf比较已经进展到这个程度啦，我之前都是傻傻的用阅读器手工比较，落后啊。

后面需要时借用下你的代码
@TheNetAdmin

**Comment by TheNetAdmin** [comment]
> 呀，pdf比较已经进展到这个程度啦，我之前都是傻傻的用阅读器手工比较，落后啊。
> 
> 后面需要时借用下你的代码
> @TheNetAdmin

前面大家提到过的工具都挺好用的，我选了 `diff-pdf-visually` 是因为安装方便，只需要 `pip` 安装即可。另外我的脚本里用了默认的分辨率，你也可以尝试设置更高分辨率来获得更好的比较效果。

@zepinglee 提到的 `diff-pdf` 工具效果也很好，但安装略麻烦，在 `apt` 里没有现成的包，所以我暂时没有用。

**Comment by hushidong** [comment]
好的，感谢！
