### ISSUE TITLE
某些段落、小节前的空白大小不一致

### ISSUE THREAD

**Issue by SonpKing** [TheNetAdmin/zjuthesis#104]
## 系统信息

**操作系统**

- [x] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [ ] TeXLive 2020 或更新的版本
- [x] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.3.4

Degree:
  - [x] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5714316/zjuthesis.log)

## 遇到的问题

一些节和小节前空白太大，一些又是正常的。之前图片没有固定时，段落也出现这样的情况。

**截图**

正常空白
![image](https://user-images.githubusercontent.com/28184306/102588866-13784800-4149-11eb-9566-314dfaca84ba.png)

-----------------------------------
非正常空白

![image](https://user-images.githubusercontent.com/28184306/102588779-f3488900-4148-11eb-9914-abedcbd04bce.png)

**其他信息**

我在模板的基础上添加了这些包
% add subfig package
\usepackage[labelformat=simple]{subfig}
% add blod hline of table
\usepackage{booktabs}
% add amsmath
\usepackage{amsmath}
% add amsmath
\usepackage{algorithm}
\usepackage{algorithmic}

因为mac字体有问题，所以修改了cs/font.tex, 主要将判断条件由"mac"换成了"windows",应该不会影响。
\ifthenelse{\equal{\Degree}{graduate}}
{
% ctex package stores one of "windows", "mac", and "fandol" in \g__ctex_fontset_tl
\ifthenelse{\equal{\csname g__ctex_fontset_tl\endcsname}{windows}}
{
    % Windows or other platform
    \setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{SimSun}
}
{
\IfFileExists{ /System/Library/Fonts/PingFang.ttc }
{
    % MacOS El Capitan and later version
    % https://github.com/CTeX-org/ctex-kit/issues/351
    \setCJKmainfont[BoldFont={Songti SC Bold}]{Songti SC Light}
}
{
    % Older MacOS
    % Fonts
    \setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{STSong}
}
}
}
{}

**Comment by TheNetAdmin** [comment]
把你觉得有问题的那些页面填满字呢？

**Comment by TheNetAdmin** [comment]
另外，mac上的字体有什么问题吗，可以新开一个issue我尝试解决一下？
