### ISSUE TITLE
怎么去掉封面和开题报告要求之间的多余空白页

### ISSUE THREAD

**Issue by Kyfafyd** [TheNetAdmin/zjuthesis#105]
## 系统信息

**操作系统**

- [ ] Windows
- [* ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [* ] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [ *] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：
6.4.0-rc1

Degree:
  - [ ] graduate
    - [ ] master
    - [ ] doctor
  - [ *] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [*] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5719177/zjuthesis.log)
## 遇到的问题

怎么去掉封面和开题报告要求之间的多余空白页
**截图**

<img width="257" alt="Screen Shot 2020-12-19 at 6 08 20 PM" src="https://user-images.githubusercontent.com/42490513/102686828-2fe9b280-4225-11eb-840c-a44463f05127.png">

**其他信息**

**Comment by TheNetAdmin** [comment]
这不是多余的空白页，这是为双面打印设计的，使正文每一章的第一页位于单数页

**Comment by TheNetAdmin** [comment]
想去掉就自行搜索\cleardoublepage换成\clearpage

**Comment by yingzhaozhang** [comment]
> 想去掉就在代码里搜索\cleardoublepage换成\clearpage

这两个命令是否可以合并成一个命令的两个选择，进而修改一个命令就可以修改全部了。

**Comment by TheNetAdmin** [comment]
> > 想去掉就在代码里搜索\cleardoublepage换成\clearpage
> 
> 这两个命令是否可以合并成一个命令的两个选择，进而修改一个命令就可以修改全部了。

几天前就改过了

https://github.com/TheNetAdmin/zjuthesis/blob/c1e3f59f68059e0037d519bdf8fde34761fb879e/config/commands.tex#L24-L26

**Comment by t3isuan** [comment]
请问应该如何删去空白页的页码呢？

**Comment by TheNetAdmin** [comment]
@t3isuan 不要在旧的issue提问，有问题新开一个issue并提供必要信息
