### ISSUE TITLE
算法过长会导致超出页面

### ISSUE THREAD

**Issue by rosefun** [TheNetAdmin/zjuthesis#111]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [ ] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.0

Degree:
  - [ ] graduate
  - [x] master
  - [ ] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

无

## 遇到的问题

采用algorithm算法包，如果内容过长（篇幅大于一页），排版不自动到下一页。

**截图**

![image](https://user-images.githubusercontent.com/32197447/103187538-9ba3dd80-48ff-11eb-8443-974dd1dff845.png)

**其他信息**

**Comment by muzimuzhi** [comment]
这和模板无关，和算法包有关。

你没有提供相应的输入，只能猜。合理的猜测是，你用的算法包，是把每个算法作为浮动体环境排版的，而浮动体内无法断页。

TeX-SX 上有类似问答，见 [Algorithm over 2 pages](https://tex.stackexchange.com/q/29816) 和打开后页面右侧 Linked 和 Related 栏的问题列表。

**Comment by TheNetAdmin** [comment]
感谢 @muzimuzhi 耐心的解答。

@rosefun 你提到的问题与本模板无关，超出了本模板提供的技术支持的范围，请自行上网学习相关的排版功能。
