### ISSUE TITLE
参考文献一行内超出边界

### ISSUE THREAD

**Issue by Kyfafyd** [TheNetAdmin/zjuthesis#112]
## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.0-rc1

Degree:
  - [ ] graduate
    - [ ] master
    - [ ] doctor
  - [x] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [x] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5747206/zjuthesis.log)

## 遇到的问题

参考文献一行内超出边界, 没有自动换行（图里的international）

**截图**

<img width="357" alt="Screen Shot 2020-12-28 at 8 00 41 PM" src="https://user-images.githubusercontent.com/42490513/103213007-5e633e00-4947-11eb-9bac-a7b94cd01151.png">

**其他信息**

**Comment by zepinglee** [comment]
@hushidong 可以在 `//` 后加 `\allowbreak`，这样断行效果更好一些。

**Comment by Kyfafyd** [comment]
谢谢您的解答，我是用的Bibtex，请问是把\allowbreak 加在bib文件嘛？但是我加了好像没啥作用的样子。。。

**Comment by Kyfafyd** [comment]
解决了，可以通过添加 `\linebreak` 来解决

**Comment by zepinglee** [comment]
> 谢谢您的解答，我是用的Bibtex，请问是把\allowbreak 加在bib文件嘛？但是我加了好像没啥作用的样子。。。
> […](#)
> On Dec 28, 2020, at 9:13 PM, Zeping Lee ***@***.***> wrote: \allowbreak

我是发给宏包作者的。

不要把 `\linebreak` 加到 bib 里，另外你确定是 bibtex 不是 biblatex？

**Comment by hushidong** [comment]
> @hushidong 可以在 `//` 后加 `\allowbreak`，这样断行效果更好一些。

好的，我先记下来，有几个需要修改的地方了，到时空了一起改。

**Comment by TheNetAdmin** [comment]
> 谢谢您的解答，我是用的Bibtex，请问是把\allowbreak 加在bib文件嘛？但是我加了好像没啥作用的样子。。。
> […](#)
> On Dec 28, 2020, at 9:13 PM, Zeping Lee ***@***.***> wrote: \allowbreak

@Kyfafyd 请用 `latexmk` 编译，这样就不用手动调用 `biblatex` 了。
