### ISSUE TITLE
参考文献字号和行间距设置

### ISSUE THREAD

**Issue by Yanxingang** [TheNetAdmin/zjuthesis#113]
## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [ ] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [ ] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [ ] graduate
    - [√ ] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

硕士论文模板，我看到往年师兄师姐的硕士论文参考文献字号都是和正文一样的，行间距也比目前模板里面的大。请问怎么修改参考文献的字号大小和行间距呢？

**截图**

**其他信息**

**Comment by TheNetAdmin** [comment]
把信息填写全

**Comment by TheNetAdmin** [comment]
#46
