### ISSUE TITLE
VScode中参考文献无法生成问题

### ISSUE THREAD

**Issue by Rongjiehuang** [TheNetAdmin/zjuthesis#115]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

6.3.3

版本号：

Degree:
  - [ ] graduate
    - [ ] master
    - [ ] doctor
  - [x] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5759813/zjuthesis.log)

## 遇到的问题

vscode命令行输入latexmk时会发生报错，无法生成pdf。在vscode latexworkshop 中使用xelatex->biber->xelatex->xelatex时不会报错，能够生成pdf，但没有参考文献。

**截图**

![image](https://user-images.githubusercontent.com/60837310/103451682-df348800-4d01-11eb-8760-2db8f0b4f843.png)

**其他信息**

latexmk报错信息集中在类似于以下等的内容，感觉有点奇怪

\begin{itemize}
    \item[-] 信息处理。现代信息处理要解决的问题很复... 
    \item[-] 模式识别。模式识别是对表征事物...
    \item[-] 自动控制。自动控制...
 \end{itemize}

**Comment by TheNetAdmin** [comment]
用 `latexmk` 直接编译没有内容的原始模板，能生成参考文献吗

**Comment by Rongjiehuang** [comment]
可以的

**Comment by TheNetAdmin** [comment]
尝试将中间文件全部清理干净再编译呢？

如果还不行，那说明工具都没有问题，可能是代码出错了

那样的话，新下载一个模板，一点一点添加你修改过的代码，直到报类似错误，然后将有报错的代码打包发上来看一下

**Comment by muzimuzhi** [comment]
@Rongjiehuang 
根据你上传的 `zjuthesis.log`，line 1464 开始，你的 tex 文件包含错误，尤其注意 `review.tex`。
```
(./body/undergraduate/proposal/review/review.tex
一、
File: figure//review/review_1.png Graphic file (type bmp)
<figure//review/review_1.png>
[1





]
! Illegal parameter number in definition of \NewCount.
<to be read again> 
                   1
l.36     \item
              [-] 信息处理。现代信息处理要解决的问题很复杂，人工神经网络具有模仿和重建人的思维的可能，实现自动诊断、问题求解，解决传统...

? 
```

**Comment by muzimuzhi** [comment]
第一处报错要更早一些，在 line 1379 就有了。能从 log 猜测的信息是，这是在 `\begin{document}` 附近的报错。如果你调试有困难，可以删去敏感内容后，把整个文件夹打包上传。
```tex
Runaway argument?
{Sequential models achieve state-of-the-art results in audio, visual \ETC.
! File ended while scanning use of \field.
<inserted text> 
                \par 
l.131 \begin{document}
                      
? 
```

**Comment by Rongjiehuang** [comment]
谢谢你们，我将文件夹传一下：
[latex.zip](https://github.com/TheNetAdmin/zjuthesis/files/5759854/latex.zip)

**Comment by TheNetAdmin** [comment]
在你的 reference 第84行，去掉这个 `abstract` field

```TeX
@article{Kalchbrenner2018Efficient,
  title={Efficient Neural Audio Synthesis},
  author={Kalchbrenner, Nal and Elsen, Erich and Simonyan, Karen and Noury, Seb and Casagrande, Norman and Lockhart, Edward and Stimberg, Florian and Oord, Aaron Van Den and Dieleman, Sander and Kavukcuoglu, Koray},
  year={2018},
 abstract={Sequential models achieve state-of-the-art results in audio, visual and textual domains with respect to both estimating the data distribution and generating high-quality samples. Efficient sampling for this class of models has however remained an elusive problem. With a focus on text-to-speech synthesis, we describe a set of general techniques for reducing sampling time while maintaining high output quality. We first describe a single-layer recurrent neural network, the WaveRNN, with a dual softmax layer that matches the quality of the state-of-the-art WaveNet model. The compact form of the network makes it possible to generate 24kHz 16-bit audio 4x faster than real time on a GPU. Second, we apply a weight pruning technique to reduce the number of weights in the WaveRNN. We find that, for a constant number of parameters, large sparse networks perform better than small dense networks and this relationship holds for sparsity levels beyond 96%. The small number of weights in a Sparse WaveRNN makes it possible to sample high-fidelity audio on a mobile CPU in real time. Finally, we propose a new generation scheme based on subscaling that folds a long sequence into a batch of shorter sequences and allows one to generate multiple samples at once. The Subscale WaveRNN produces 16 samples per step without loss of quality and offers an orthogonal method for increasing sampling efficiency.},
}
```

改为
```TeX
@article{Kalchbrenner2018Efficient,
  title={Efficient Neural Audio Synthesis},
  author={Kalchbrenner, Nal and Elsen, Erich and Simonyan, Karen and Noury, Seb and Casagrande, Norman and Lockhart, Edward and Stimberg, Florian and Oord, Aaron Van Den and Dieleman, Sander and Kavukcuoglu, Koray},
  year={2018}
}
```

然后**清理所有中间文件**，再使用 `latexmk` 编译，看能否成功

**Comment by muzimuzhi** [comment]
> 谢谢你们，我将文件夹传一下：
> [latex.zip](https://github.com/TheNetAdmin/zjuthesis/files/5759854/latex.zip)

文件 `./body/ref.bib` 84 行，`abstract={...levels beyond 96%...}`，把 `96%` 改成 `96\%`。

**Comment by TheNetAdmin** [comment]
> > 谢谢你们，我将文件夹传一下：
> > [latex.zip](https://github.com/TheNetAdmin/zjuthesis/files/5759854/latex.zip)
> 
> 文件 `./body/ref.bib` 84 行，`abstract={...levels beyond 96%...}`，把 `96%` 改成 `96\%`。

是的

@Rongjiehuang  这个 `%` 作为 TeX 的注释符号，导致后面的内容没有被读取，进一步导致编译错误

**Comment by Rongjiehuang** [comment]
现在可以了！谢谢你们
真被这个注释搞死了

**Comment by muzimuzhi** [comment]
回头看 issue 标题，这是个 X-Y problem。真正的问题至少是编译报错，但报告的问题是没有参考文献。建议在关注 pdf 内容对不对的同时，也要关注 0 errors。若有报错，提问时带例子，排查时从第一处报错开始看。

如果 bib 信息是导出的，可以把问题和修正反馈给源头（软件或网站），让世界变好一丁点。

**Comment by IMBINGO95** [comment]
> 用 `latexmk` 直接编译没有内容的原始模板，能生成参考文献吗

我直接latexmk编译没有内容的原始模板也会报错。
错误是
Undefined control sequence. \GenericError  ...
