### ISSUE TITLE
latexmk 配置：建议生成并保留 synctex.gz 文件、删除 "-outdir=out" 选项

### ISSUE THREAD

**Issue by muzimuzhi** [TheNetAdmin/zjuthesis#116]
## 可改进的内容

1. 用 latexmk 编译后，用户可能希望通过 tex-pdf 的双向跳转来修改和查看内容。目前的 latexmk 配置会删除 `synctex.gz` 文件，建议保留。
2. `-outdir` 是 latexmk 的选项，texlive 和 miktex 下的 `xelatex` 都不接受它。使用 latexmk 编译时能在 stdout 看到报错
    ```
    Running 'xelatex -outdir=out -no-pdf -recorder -output-directory="out"  "zjuthesis.tex"'
    ------------
    xelatex: unrecognized option `-outdir=out'
    ````

https://github.com/TheNetAdmin/zjuthesis/blob/ae48e26bca28562c9a5689efd71e3c2c4396735b/.latexmkrc#L3-L5

## 代码与步骤

```diff
diff --git a/.latexmkrc b/.latexmkrc
index fc34c2a..8c71044 100644
--- a/.latexmkrc
+++ b/.latexmkrc
@@ -1,8 +1,8 @@
 $out_dir="out";
 $pdf_mode=5;
-$xelatex="xelatex -outdir=out";
+$xelatex="xelatex -synctex=1";
 $xdvipdfmx="xdvipdfmx -q -E -o %D %O %S";
-$clean_ext = 'thm bbl hd loe synctex.gz xdv run.xml';
+$clean_ext = 'thm bbl hd loe xdv run.xml';
 $makeindex = 'makeindex -s gind.ist %O -o %D %S';
 
 @default_files=('zjuthesis.tex')
```

**Comment by TheNetAdmin** [comment]
感谢建议！我已经将 `outdir` 修复了。

关于 `synctex` 我有个问题：当使用 `xelatex -synctex=1` 编译之后，将生成的 pdf 文件复制到其他文件夹，或使用 email 发送，或上传到提交网站之后（即同文件夹下只有 pdf 文件，没有 `synctex` 文件），双击 pdf 中的内容是否还会弹出 TeX 相关源码呢？

我之前没有加入这个功能的考虑是，如果同学直接上传带有 `synctex` 的 pdf，导致审核教师双击 pdf 内容显示了一些 TeX 源码，破坏学校的盲审而导致一些麻烦。

**Comment by muzimuzhi** [comment]
双向跳转需要匹配的 pdf，tex 和 synctex 文件同时存在，以及使用的 pdf 阅读器和 tex 编辑器支持。synctex 里记录的是双向位置信息，解压后就能看到，它的文档里有格式说明。开启 synctex 不影响 pdf 的内容，所以在只发送 pdf 时是 100% 安全的，即使把整个项目打包发送了，只打开 pdf 时大部分时候也无法触发跳转。

**Comment by TheNetAdmin** [comment]
感谢解答！我已经加上了 `synctex` 相关代码。
