### ISSUE TITLE
去掉参考文献中的双斜线

### ISSUE THREAD

**Issue by xijiz** [TheNetAdmin/zjuthesis#117]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeLaTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.0.2

Degree:
  - [x] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

我发现参考文献中只要是会议文献，都会在标题之后出现双斜线//，这个该如何去掉呢？

**截图**

![image](https://user-images.githubusercontent.com/12234085/103475457-42004f00-4de8-11eb-9847-31f795b8f386.png)

**其他信息**

**Comment by yuwl798180** [comment]
你好，我也遇到了相同的问题。
请问该如何解决呀

**Comment by yuwl798180** [comment]
你好，请问解决了吗

**Comment by zepinglee** [comment]
ZJU 没规定参考文献的格式吗？

**Comment by TheNetAdmin** [comment]
本模板默认使用了 `GB/T 7714 - 2015` 格式，研究生院规定的格式是 `GB/T 7714－2005`，见 https://github.com/TheNetAdmin/zjuthesis/issues/94 ，经过 https://github.com/TheNetAdmin/zjuthesis/issues/23#issuecomment-613730860 的说明，`2005` 与 `2015` 没有格式方面的差异

@xijiz @yuwl798180 这些参考文献格式建议你们不要手动修改，不过一定要去掉 `//` 的话，参考 [文献模板的文档](https://github.com/hushidong/biblatex-gb7714-2015#usage)，在这里

https://github.com/TheNetAdmin/zjuthesis/blob/104b692c4d4d29e1ddb8d813c04ebee20e175a00/config/packages.tex#L14-L18

新增选项 `gbpunctin=false`，即

```TeX
\usepackage[
    style=gb7714-2015,
    gbpunctin=false
]{biblatex}
```

即可，示例如下

```Bibtex
@inproceedings{LENS-VANS,
  author={Zixuan Wang and Xiao Liu and Jian Yang and Theodore Michailidis and Steven Swanson and Jishen Zhao},
  booktitle={2020 53rd Annual IEEE/ACM International Symposium on Microarchitecture (MICRO)}, 
  title={Characterizing and Modeling Non-Volatile Memory Systems}, 
  year={2020},
  pages={496-508},
  doi={10.1109/MICRO50266.2020.00049}
}
```

![image](https://user-images.githubusercontent.com/18525442/103488700-d1473b80-4dc3-11eb-8376-bae897a781ce.png)

**Comment by muzimuzhi** [comment]
根据 [GB/T 7714 - 2005](https://github.com/saccohuo/GBT-Standard/blob/master/GBT%207714-2005%20%E6%96%87%E5%90%8E%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E8%91%97%E5%BD%95%E8%A7%84%E5%88%99.pdf)，第 4.2.2 节和 8.6.1 节的规定，从专著中析出的，有独立著者、独立篇名的文献，用 `//` 分隔析出文献和源文献的信息。又根据附录 B.1，`C` 代表文献类型中的会议录。

如果觉得引用的是从专著中析出的文献，且希望严格遵循 GB/T 7714 - 2005，那么必须保留 `//`。

**Comment by du33169** [comment]
在设置gbpunctin=false后，如果连`in:`也要去掉的话，可以在引入biblatex后增加一句`\renewbibmacro{in:}{. }`，即：
```latex
\usepackage[
    style=gb7714-2015,
    gbpunctin=false
]{biblatex}
\renewbibmacro{in:}{. }
```
编译效果示例：
![图片](https://github.com/TheNetAdmin/zjuthesis/assets/46591250/50109ba3-4f2f-48f4-9ebc-8ff87c138adf)

这一方法来自https://tex.stackexchange.com/questions/10682/suppress-in-biblatex

**Comment by deserve-it** [comment]
可以直接去.bst文件找有双斜杠的那一项
FUNCTION {cap.double.slash} 	{" //\thinspace{}"}
然后把这里面的双斜杠改成英文点号就可以了
FUNCTION {cap.double.slash} 	{".\thinspace{}"}
然后保存，重新跑一遍bibtex再跑PDFtex就可以了
