### ISSUE TITLE
软件学院硕士论文的格式要求

### ISSUE THREAD

**Issue by logic2333** [TheNetAdmin/zjuthesis#119]
## 可改进的内容

软件学院硕士论文的格式要求与general和cs模板都略有区别，大概是二者的折中，与general的区别主要表现在：

- [ ] “摘要”、“Abstract”和各章一级标题均居中
- [ ] 以“第x章”为章节序号
- [ ] 从摘要开始编页眉和页码，页码均居中，摘要用一套页码（小写罗马数字i, ii, iii...），目录、图目录、表目录用一套页码（大写罗马数字I, II, III...），正文开始到最后致谢结束用一套页码。页眉和页码均使用宋体10.5磅
- [ ] 表的标题“表x.x xxxx”在表的上方，图、表标题使用仿宋10.5磅
- [ ] 偶数页不留空
- [ ] 目录页使用单倍行距

我没有general模板的具体要求，所以不确定上面罗列的是否全面，具体还请参考下面的word模板和具体的格式要求。

## 预期结果

论文模板https://drive.google.com/file/d/1oR1uBvObwklPLQz4J4V0Sw6UlHbI2x-v/view?usp=sharing
具体的格式要求https://drive.google.com/file/d/1JoiILUTqrym0OF_cXZ5cf0-Hm347iCVk/view?usp=sharing
（要下载下来看，谷歌文档显示有问题）

很感谢如果能据此制作一份软件工程硕士的论文模板，或指出如何编辑模板来满足上述要求。

**Comment by TheNetAdmin** [comment]
好的我看下怎么做，如有进度我会写在这里

**Comment by TheNetAdmin** [comment]
目前的软件学院硕士模板：
- [ ] “摘要”、“Abstract”和各章一级标题均居中
- [ ] 以“第x章”为章节序号
- [ ] 从摘要开始编页眉和页码，页码均居中，摘要用一套页码（小写罗马数字i, ii, iii...），目录、图目录、表目录用一套页码（大写罗马数字I, II, III...），正文开始到最后致谢结束用一套页码。页眉和页码均使用宋体10.5磅
- [ ] 表的标题“表x.x xxxx”在表的上方，图、表标题使用仿宋10.5磅
- [ ] 偶数页不留空
- [ ] 目录页使用单倍行距

**Comment by TheNetAdmin** [comment]
@logic2333 我暂时没有时间仔细检查每一项具体的格式要求，请你自行检查一下当前模板是否符合相关要求，如有违反要求之处，请在此 issue 下留言，我会尽快修复

**Comment by logic2333** [comment]
> @logic2333 我暂时没有时间仔细检查每一项具体的格式要求，请你自行检查一下当前模板是否符合相关要求，如有违反要求之处，请在此 issue 下留言，我会尽快修复

好的十分感谢！请问general模板参考的具体格式要求的文件是？我逐条对照一下

**Comment by logic2333** [comment]
> @logic2333 我暂时没有时间仔细检查每一项具体的格式要求，请你自行检查一下当前模板是否符合相关要求，如有违反要求之处，请在此 issue 下留言，我会尽快修复

好的十分感谢！我看一看

**Comment by logic2333** [comment]
- [ ] 虽然我们确实是专业学位，但是“浙江大学”四个大字下面，用的是“硕士学位论文”而不是“硕士专业学位论文”。。。模板可以考虑合并到学硕去，因为我们学院只有专硕没有学硕。。。
- [ ] 图、表标题的字体没有改过来，应为仿宋10.5磅
- [ ] 页眉字体没有改过来，应为宋体10.5磅
- [ ] 正文页码也居中，而不是在右下角
- [ ] 公式编号，用(x.x)而不是(x-x)
- [ ] 页面设置：上、下 3.8 cm，左、右 3.2 cm，页眉、页脚 3.0 cm，装订线 0 cm

几个看情况改的小细节
- [ ] 封面“浙江大学”四个大字字间没有空格，具体使用的图片可从word模板中拿过来。我自己替换一下zjuchar.pdf就行，但是能在模板里把这个改好最好
- [ ] 从“中文论文题目：”“英文论文题目：”一直到第二页的“答辩日期”，这些提示字在word模板中都是宋体（后面下划线上要填的内容，除了“论文提（not 递）交日期”为加粗宋体外，其他仍是仿宋。这一条如果改起来很麻烦，就不改吧，因为在具体的格式要求文件中写的不明确。。）
- [ ] 论文最后有致谢，我把thanksto.tex挪到body/graduate/post下面就好了，但是能在模板里把这个改好最好

师兄辛苦啦！

**Comment by TheNetAdmin** [comment]
抱歉这两天比较忙没时间修复这些问题，过两天会统一修复，请关注 #126 的进度

**Comment by logic2333** [comment]
> 抱歉这两天比较忙没时间修复这些问题，过两天会统一修复，请关注 #126 的进度

现因急用此模板，可否烦请师兄近日帮忙看一看上面提到的几个小问题？感激不尽！

**Comment by TheNetAdmin** [comment]
> > 抱歉这两天比较忙没时间修复这些问题，过两天会统一修复，请关注 #126 的进度
> 
> 现因急用此模板，可否烦请师兄近日帮忙看一看上面提到的几个小问题？感激不尽！

催我更新？还发了邮件给我催我？我还是第一次碰到这么理直气壮的伸手党。本来我都懒得理你。

我开源这个模板使用的 LICENSE 已经说明我不提供任何 Warranty，使用模板造成的任何后果与我无关。另一方面，我维护这个开源项目只是出于个人爱好，我有自己的工作，我并未从这个开源项目里收获一分钱的工资。更何况我从浙大毕业已经好几年，维护这个模板并非我的本职工作，我没有义务给你修复任何 BUG。

再退一步讲，你有和毕业相关的问题需要紧急修复，第一时间想到的是依靠别人？我不修复你就不毕业了？你难道不会学习一下 LaTeX 怎么用吗？我处理过的很多 issue 也是同学碰到了问题需要修复，但人家大多是询问代码修改的方式去自行修改，你这倒是方便，直接给我提需求还给我设 DDL 是不是？

我最近是刚忙完一些事情会看一下这个模板的遗留问题，但你这里列出来的问题我不会修的，你自己想办法吧。
