### ISSUE TITLE
Encountered } without corresponding {

### ISSUE THREAD

**Issue by MARMOTatZJU** [TheNetAdmin/zjuthesis#120]
## 系统信息

**操作系统**

- [ ] Windows
- [X] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [X] TeXLive 2020 或更新的版本 `Latexmk, John Collins, 29 September 2020. Version 4.70b`
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [X] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.3

Degree:
  - [X] graduate
    - [X] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [X] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5764678/zjuthesis.log)

## 遇到的问题

编译正常完成，但是使用`script/utils/word_count.sh`统计字数是遇到如下error

```
!!! Encountered } without corresponding {. !!!
Deep recursion on subroutine "main::_parse_unit" at /Library/TeX/texbin/texcount line 2179.
```

使用`sudo tlmgr update --self --all`更新所有宏包，更新成功但依然无效。

**截图**

**其他信息**

**Comment by TheNetAdmin** [comment]
尝试在一个全新的模板里使用 `word_count.sh` 是否可行呢？

如果不可行，能否提供以下内容呢：

1. `which texcount` 的输出
2. `which perl` 和 `perl --version` 的输出
3. 通过 `which texcount` 找到该文件，作为附件附在这里（该文件应该是一个 perl 代码文件）

**Comment by MARMOTatZJU** [comment]
1. `/Library/TeX/texbin/texcount`
2. `/usr/bin/perl`, 
```
This is perl 5, version 18, subversion 4 (v5.18.4) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

Copyright 1987-2013, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```
3. 
[texcount.txt](https://github.com/TheNetAdmin/zjuthesis/files/5767517/texcount.txt)

**Comment by MARMOTatZJU** [comment]
@TheNetAdmin 试用了`5d6d3d2ea11ffd5df208e2d1b9913d048f30d293` "Word count script: more precise rules"，问题依然存在。

我贴一下stdout的log吧：
[wc.log](https://github.com/TheNetAdmin/zjuthesis/files/5767732/wc.log)

**Comment by TheNetAdmin** [comment]
> @TheNetAdmin 试用了`5d6d3d2ea11ffd5df208e2d1b9913d048f30d293` "Word count script: more precise rules"，问题依然存在。
> 
> 我贴一下stdout的log吧：
> [wc.log](https://github.com/TheNetAdmin/zjuthesis/files/5767732/wc.log)
> 

这个 commit 不是修复 bug 的，只是防止脚本过多地排除文件

**Comment by MARMOTatZJU** [comment]
按照如下规则过滤了pdf和png之后显示正常：

```
diff --git a/script/utils/word_count.sh b/script/utils/word_count.sh
index 6c69749..a5d999e 100644
--- a/script/utils/word_count.sh
+++ b/script/utils/word_count.sh
@@ -15,6 +15,8 @@ cat out/zjuthesis.fls                 \
     | grep -v review.tex              \
     | grep -v original.tex            \
     | grep -v cv.tex                  \
+    | grep -v pdf                     \
+    | grep -v png                     \
     | cut -d ' ' -f 2                 \
     | awk '{ print "\\input{"$1"}" }' \
     > out/zjuthesis.wordcnt           \
```

正常的log：[wc.log](https://github.com/TheNetAdmin/zjuthesis/files/5767756/wc.log)

感觉设置过滤后缀名是有必要的（否则会遍历一些非文本文件），应当将规则设置为识别路径并检查文本文件还是二进制文件。请问正确的过滤方式是？

**Comment by TheNetAdmin** [comment]
我看了一下log，是不是因为texcount读取了pdf呀，尝试在word_count.sh中排除pdf文件呢？

即加上这一行 `grep -v pdf`

**Comment by MARMOTatZJU** [comment]
> 我看了一下log，是不是因为texcount读取了pdf呀，尝试在word_count.sh中排除pdf文件呢？
> 
> 即加上这一行 `grep -v pdf`

已尝试，确实可行，还应该排除掉png相关的。

我觉得一个简单的解法是不是可以考虑硬编码一下放置resources的路径（比如zju-thesis/body/resources），然后直接过滤掉这个路径下的所有文件？

**Comment by TheNetAdmin** [comment]
能贴一下你的 zjuthesis.fls 吗？

图片和pdf都放figures目录，这是设置过的

**Comment by MARMOTatZJU** [comment]
zjuthesis.fls：[zjuthesis.fls.txt](https://github.com/TheNetAdmin/zjuthesis/files/5767782/zjuthesis.fls.txt)

好吧，是我把resources都放在body下了。

body下只放tex这一点，可能需要加进tutorial里？

**Comment by MARMOTatZJU** [comment]
我在word count脚本里没有看到过滤figure下相关pdf的规则。请问这个过滤是在哪里做到的？

**Comment by TheNetAdmin** [comment]
> 我在word count脚本里没有看到过滤figure下相关pdf的规则。请问这个过滤是在哪里做到的？

还没做，我刚说"设置过的"是指模板里设置过图片路径，没有强制性的设置

**Comment by TheNetAdmin** [comment]
> > 我看了一下log，是不是因为texcount读取了pdf呀，尝试在word_count.sh中排除pdf文件呢？
> > 
> > 即加上这一行 `grep -v pdf`
> 
> 已尝试，确实可行，还应该排除掉png相关的。
> 
> 我觉得一个简单的解法是不是可以考虑硬编码一下放置resources的路径（比如zju-thesis/body/resources），然后直接过滤掉这个路径下的所有文件？

在 word_count.sh 的规则最前面加一个 `grep .tex` 只保留 TeX 文件就好了

**Comment by MARMOTatZJU** [comment]
@TheNetAdmin 已提PR：https://github.com/TheNetAdmin/zjuthesis/pull/121

**Comment by TheNetAdmin** [comment]
OK
