### ISSUE TITLE
寻找更合理的存储 Baseline PDF 文件的方式

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#123]
## 可改进的内容

当前的 Baseline PDF 文件是以 [GitHub Release Artifact](https://github.com/TheNetAdmin/zjuthesis/releases/tag/standard) 的形式保存于此 repo 中，见 #103 的讨论

这种方式避免了将 PDF 文件加入代码树，但却造成了另外一个问题：

当本仓库和 Fork 的仓库使用 GitHub CI 时，每次都会从上述 GitHub Release 下载 PDF，导致了本仓库代码下载量统计失准，每一次 CI 都会贡献 10 次以上的下载量。

这不是什么严重的问题，但为了统计数字的准确性，可以尝试如下方式之一：

1. 将 Baseline PDF 保存到共享云盘，如 Google Drive，供 CI 下载
2. 将 Baseline PDF 分离到另一个 GitHub repo，每次 CI 下载时使用 `--depth=1` 来减少下载量

方式 2 还有一个额外的便利之处，即将新的 repo 作为 git submodule 加入本仓库，方便管理与测试

**Comment by muzimuzhi** [comment]
或放在当前 repo 的另一个分支？

**Comment by zepinglee** [comment]
git clone 的时候会把全部分支下到本地，也会导致本地仓库过大，除非往这个 baseline pdf 分支一直 force push。

**Comment by MARMOTatZJU** [comment]
> git clone 的时候会把全部分支下到本地，也会导致本地仓库过大，除非往这个 baseline pdf 分支一直 force push。

感觉使用git lfs可以解决这个问题？新建一个仓库，专门用来用git lfs存baseline pdf等编译非必须的文件，正常使用的时候不需要clone，仅在CI/CD期间clone。

**Comment by TheNetAdmin** [comment]
暂时的做法是开了一个新 repo，将 baseline pdf 直接 push 到一个文件夹下，然后通过一个 baseline.json 文件记录每个 baseline pdf 所使用的参数。

https://github.com/TheNetAdmin/zjuthesis-std

可以改进的一个做法是，只记录 baseline.json 的变化，然后在该 repo 中通过 GitHub Action 自动编译 baseline pdf 到 resease 中，这样既追踪了每个 pdf 的设置与所用代码版本，又缩减了 git repo 的体积，后续可能考虑在该 repo 中开发这个功能。
