### ISSUE TITLE
表格的字体不是仿体，且偏大

### ISSUE THREAD

**Issue by rosefun** [TheNetAdmin/zjuthesis#124]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.0

Degree:
  - [ ] graduate
  - [x] master
  - [ ] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

表格的字体不是仿宋，而且大小偏大。

**截图**

![image](https://user-images.githubusercontent.com/32197447/103894826-70549600-512a-11eb-8a89-15758c823625.png)

正文字体及大小：

![image](https://user-images.githubusercontent.com/32197447/103894942-8febbe80-512a-11eb-8699-1227dbe0122c.png)

可以看到，表格的字体和大小都和正文不一样。

**其他信息**

**Comment by TheNetAdmin** [comment]
这个设定来源于 《2018 浙江大学本科生毕业论文（设计） 编写规则》 #94

>2.3.2.2 图、表等标号
> 论文中的图、表、附注、公式、算式等，一律用阿拉伯数字分章依序连续编码。其标注形式应便于互相区别，如：图 l.1(第 1 章第一个图)、图 2.2(第二章第二个图)；表 3.2(第三章第二个表)等。图、表标题均采用五号宋体加粗。表格中文字采用 5 号宋体，行距为单倍行间距。图、表与下文空一行。

具体设定位于

https://github.com/TheNetAdmin/zjuthesis/blob/c1e3f59f68059e0037d519bdf8fde34761fb879e/config/format/general/tables.tex#L5-L6

https://github.com/TheNetAdmin/zjuthesis/blob/c1e3f59f68059e0037d519bdf8fde34761fb879e/config/format/general/caption.tex#L4

但《浙江大学研究生学位论文编写规则》没有具体的规定，所以开发模板时就沿用了本科生得设定。你可以暂时修改一下以上设定，我之后有空会更新一下这部分格式
