### ISSUE TITLE
关于固定行距问题

### ISSUE THREAD

**Issue by fengyang95** [TheNetAdmin/zjuthesis#125]
现在的研究生模板里，设置的1.5倍行距，但是latex会自动根据文章内容调整节与节之间的间距，造成间距不统一，想请教下如何设置固定行距

**Comment by muzimuzhi** [comment]
试试 `\raggedbottom`。如果还不行，就去掉章节标题前后纵向间距里 `plus xxx minus xxx` 的部分了。

**Comment by yingzhaozhang** [comment]
> 试试 `\raggedbottom`。如果还不行，就去掉章节标题前后纵向间距里 `plus xxx minus xxx` 的部分了。

这个具体放在那个位置呀？还有后面这个章节的具体位置在哪？我找了一下没找到。

**Comment by muzimuzhi** [comment]
- `\raggedbottom` 放在 `\begin{document}` 之后
 - 章节标题是指 `\chapter` `\section` 这样的命令，它们的样式修改一般借助宏包来完成。

如果你能提供一个间距不统一的例子，也许我可以实际帮忙看看。

**Comment by yingzhaozhang** [comment]
问题暂时解决了，但是有个问题是我生成的PDF行距看起来不到1.5倍行距。我用【Adobe Acrobat DC】转化后显示的行距是1.4倍，在这个软件中显示的倍数1.8.

**Comment by zepinglee** [comment]
`ctex` 设置的 `\baselineskip` 已经是字号的 1.2 倍，如果设置 `\linespread{1.5}\selectfont`，实际行距相当于 word 里的 1.2 * 1.5 = 1.8 倍行距。正确的是 `\linespread{1.25}\selectfont`（需要 `\selectfont` 才能生效）。

**Comment by zepinglee** [comment]
我看到另外几处的 `\linespread` 可能也有问题，Word 里的“单倍行距”跟字体有关，中易几个字体的“单倍行距”是字号的约 1.30 倍，Times New Roman 的是字号的 1.15 倍，见 `texdoc zhlineskip`。

**Comment by TheNetAdmin** [comment]
## 问题分析

我感觉是有必要系统性地修复一下模板的行间距问题。这个历史遗留问题来源于最初的 zjuthesis 版本，即计算机学院本科生毕业设计模板。

### 问题来源

最初开发模板时追求与 Word 模板视觉上的统一性，所以当《编写规范》与《Word样例模板》有所出入时，优先追求与《Word样例模板》的视觉统一性。行间距问题就是由此而来，示例如下：

| 文件 | 说明 |
| :----: | :----: |
| [2020届浙江大学计算机、软件、信息安全本科生毕业论文（设计）模板.docx](https://github.com/TheNetAdmin/zjuthesis/files/5789621/2020.docx) | 2020 年计算机学院的样例 Word 模板 |
| [zjuthesis-1.5-linespread.pdf](https://github.com/TheNetAdmin/zjuthesis/files/5789623/zjuthesis-1.5-linespread.pdf) | 使用 `\linespread{1.5}\selectfont` |
| [zjuthesis-1.25-linespread.pdf](https://github.com/TheNetAdmin/zjuthesis/files/5789627/zjuthesis-1.25-linespread.pdf) | 使用 `\linespread{1.25}\selectfont` |

对比结果如下，我使用 MS Office 365 将 Word 模板转为 PDF，后通过 SumatraPDF 打开各个 PDF 文件，设置缩放为 “实际大小”：

### `zjuthesis-1.5-linespread`（左） 对比 `计算机学院模板`（右）

**承诺书**
![image](https://user-images.githubusercontent.com/18525442/104072341-e8b96680-51bf-11eb-978a-4724b62cbb17.png)

**正文（注意画面底部的正文部分）**

![image](https://user-images.githubusercontent.com/18525442/104072451-1bfbf580-51c0-11eb-9451-53551a04e689.png)

### `zjuthesis-1.25-linespread`（左） 对比 `计算机学院模板`（右）

**承诺书**

![image](https://user-images.githubusercontent.com/18525442/104072546-4c439400-51c0-11eb-9bc0-17186e1d743e.png)

**正文（注意画面底部的正文部分）**

![image](https://user-images.githubusercontent.com/18525442/104072576-641b1800-51c0-11eb-8071-829cd59ca240.png)

### 对比总结

1. 计算机学院给出的 Word 模板有诸多不一致的地方：
    1. 参杂使用 `仿宋_GB2312`，`华文仿宋` 等多种仿宋字体
    2. 承诺书部分的行间距并不一致，上半部分似乎大于 `1.5倍行间距`，但 Word 中的设置均显示 `1.5倍`
2. 相对来讲，`\linespread{1.5}` 设定视觉上更接近于 Word 模板的效果，特别是正文部分（虽然仍有偏差）
3. `\linespread{1.25}` 虽然符合编写规则（见 Word 模板正文段落最后的要求），但视觉上讲与 Word 模板偏差较大

### 分析

@fengyang95 提到的问题存在与研究生模板，是由本科生模板开发而来，继承了本科生模板的行距设定。

通过对比两种 `\linespread` 设定与 [研究生论文编写规则](https://github.com/TheNetAdmin/zjuthesis/files/5784225/2016-grad-rules.pdf) (#94)，`\linespread{1.25}\selectfont` 更符合研究生模板的要求。（注意截图底部的正文对齐）

![image](https://user-images.githubusercontent.com/18525442/104073118-bad52180-51c1-11eb-950d-80d19a3cb309.png)

![image](https://user-images.githubusercontent.com/18525442/104073082-aa24ab80-51c1-11eb-8d35-61411c5bb114.png)


## 解决方案

请几位正在使用研究生模板的同学暂时使用 `\linespread{1.25}\selectfont` 替换原有的 `\linespread{1.5}`：

https://github.com/TheNetAdmin/zjuthesis/blob/c1e3f59f68059e0037d519bdf8fde34761fb879e/config/format/general/layout.tex#L1-L2

近期我会对样式做一次整体性的调整，整理各个学院的相关规范和样例，并排查样式错误之处，其中会包括各个模板的行间距问题

**Comment by fengyang95** [comment]
> ## 问题分析
> 我感觉是有必要系统性地修复一下模板的行间距问题。这个历史遗留问题来源于最初的 zjuthesis 版本，即计算机学院本科生毕业设计模板。
> 
> ### 问题来源
> 最初开发模板时追求与 Word 模板视觉上的统一性，所以当《编写规范》与《Word样例模板》有所出入时，优先追求与《Word样例模板》的视觉统一性。行间距问题就是由此而来，示例如下：
> 
> 文件	说明
> [2020届浙江大学计算机、软件、信息安全本科生毕业论文（设计）模板.docx](https://github.com/TheNetAdmin/zjuthesis/files/5789621/2020.docx)	2020 年计算机学院的样例 Word 模板
> [zjuthesis-1.5-linespread.pdf](https://github.com/TheNetAdmin/zjuthesis/files/5789623/zjuthesis-1.5-linespread.pdf)	使用 `\linespread{1.5}\selectfont`
> [zjuthesis-1.25-linespread.pdf](https://github.com/TheNetAdmin/zjuthesis/files/5789627/zjuthesis-1.25-linespread.pdf)	使用 `\linespread{1.25}\selectfont`
> 对比结果如下，我使用 MS Office 365 将 Word 模板转为 PDF，后通过 SumatraPDF 打开各个 PDF 文件，设置缩放为 “实际大小”：
> 
> #### `zjuthesis-1.5-linespread`（左） 对比 `计算机学院模板`（右）
> **承诺书**
> ![image](https://user-images.githubusercontent.com/18525442/104072341-e8b96680-51bf-11eb-978a-4724b62cbb17.png)
> 
> **正文（注意画面底部的正文部分）**
> 
> ![image](https://user-images.githubusercontent.com/18525442/104072451-1bfbf580-51c0-11eb-9451-53551a04e689.png)
> 
> #### `zjuthesis-1.25-linespread`（左） 对比 `计算机学院模板`（右）
> **承诺书**
> 
> ![image](https://user-images.githubusercontent.com/18525442/104072546-4c439400-51c0-11eb-9bc0-17186e1d743e.png)
> 
> **正文（注意画面底部的正文部分）**
> 
> ![image](https://user-images.githubusercontent.com/18525442/104072576-641b1800-51c0-11eb-8071-829cd59ca240.png)
> 
> #### 对比总结
> 1. 计算机学院给出的 Word 模板有诸多不一致的地方：
>    
>    1. 参杂使用 `仿宋_GB2312`，`华文仿宋` 等多种仿宋字体
>    2. 承诺书部分的行间距并不一致，上半部分似乎大于 `1.5倍行间距`，但 Word 中的设置均显示 `1.5倍`
> 2. 相对来讲，`\linespread{1.5}` 设定视觉上更接近于 Word 模板的效果，特别是正文部分（虽然仍有偏差）
> 3. `\linespread{1.25}` 虽然符合编写规则（见 Word 模板正文段落最后的要求），但视觉上讲与 Word 模板偏差较大
> 
> ### 分析
> @fengyang95 提到的问题存在与研究生模板，是由本科生模板开发而来，继承了本科生模板的行距设定。
> 
> 通过对比两种 `\linespread` 设定与 [研究生论文编写规则](https://github.com/TheNetAdmin/zjuthesis/files/5784225/2016-grad-rules.pdf) (#94)，`\linespread{1.25}\selectfont` 更符合研究生模板的要求。（注意截图底部的正文对齐）
> 
> ![image](https://user-images.githubusercontent.com/18525442/104073118-bad52180-51c1-11eb-950d-80d19a3cb309.png)
> 
> ![image](https://user-images.githubusercontent.com/18525442/104073082-aa24ab80-51c1-11eb-8d35-61411c5bb114.png)
> 
> ## 解决方案
> 请几位正在使用研究生模板的同学暂时使用 `\linespread{1.25}\selectfont` 替换原有的 `\linespread{1.5}`：
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/c1e3f59f68059e0037d519bdf8fde34761fb879e/config/format/general/layout.tex#L1-L2
> 
> 近期我会对样式做一次整体性的调整，整理各个学院的相关规范和样例，并排查样式错误之处，其中会包括各个模板的行间距问题，请关注 #126

感谢解答。另外研究生模板来看，linespread参数设成1.625视觉上看起来和要求更一致。

**Comment by zepinglee** [comment]
这个“承诺书”部分主要是因为 1～5 条的段落属性设置了“对齐到网格”，而且文档定义了网格，所以实际行距是按照网格算的。所以，14pt 的文字占两行，每行 15.6pt，正确的 `\linespread` 数值是 15.6 * 2 / 14 / 1.2 \approx 1.86。

第 6 条的段落属性却没有“对齐到网格”，所以就按 1.5 倍行距算。简直坑。

**Comment by TheNetAdmin** [comment]
> 第 6 条的段落属性却没有“对齐到网格”，所以就按 1.5 倍行距算。简直坑。

当初毕业的时候就被这些坑到了，以至于遗留了各种问题在现在的模板里 :sweat:

**Comment by zepinglee** [comment]
> 感谢解答。另外研究生模板来看，linespread参数设成1.625视觉上看起来和要求更一致。

啊，我记错了……Word 里的 xx 倍行距是在“单倍行距”的基础上乘的倍数。所以 Word 里的 1.5 倍行距，是字号的 1.3 * 15 倍（假设中易的字体），对应与 LaTeX 里的 `\linespread` 值是 1.3 * 1.5 / 1.2 = 1.625 。

我把上面回答的错误数值也修改了把。

**Comment by TheNetAdmin** [comment]
暂时使用 `\linespread{1.625}` 指定了 1.5 倍行距，后续研究下 MacOS 的字体的设定

**Comment by Fomalhauthmj** [comment]
如果需要固定正文行距为20pt，该如何处理呢？ #343
