### ISSUE TITLE
整体排查样式相关问题

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#126]
## 可改进的内容

本模板自开发以来一直没有进行过整体性的样式错误排查，从而导致了诸多样式问题。近期有必要进行一次排查，并在这个 Issue 内进行总结。

### 整理各年级各学院的规范与模板

- [x] 已整理部分规范位于 #94 
- [ ] 检查过往 Issue 中遗漏的规范与模板
- [x] 将这些内容整理到 Baseline PDF Repo: https://github.com/TheNetAdmin/zjuthesis-std

### 排查过往 Issue 中提到的样式问题

- [x] #125 
- [ ] #124 
- [x] #132 #133 检查盲审模式下哪些信息是要隐藏的
- [x] #134
- [ ] ...

### 排查 Issue 中尚未提到的样式问题

- [ ] ...

### 更新相关的文档说明

- [x] 正文样例中的说明
- [ ] `docs/` 文件夹下的文档说明

**Comment by TheNetAdmin** [comment]
新建立了一个 repo，用于存放各学院规范文件以及 baseline pdf 文件

https://github.com/TheNetAdmin/zjuthesis-std/

**Comment by ya654** [comment]
#124 表格字体问题这里，如果改成下面这样
` \AtBeginEnvironment{tabular}{\zihao{5}\fangsong}
\AtBeginEnvironment{tabularx}{\zihao{5}\fangsong} `
那么封面的格式也变了，封面也是基于tabular的。有什么好的解决办法吗？

**Comment by zepinglee** [comment]
> #124 表格字体问题这里，如果改成下面这样
> `\AtBeginEnvironment{tabular}{\zihao{5}\fangsong} \AtBeginEnvironment{tabularx}{\zihao{5}\fangsong}`
> 那么封面的格式也变了，封面也是基于tabular的。有什么好的解决办法吗？

参考 <https://www.zhihu.com/question/366803177/answer/977853129>，最合理的方法是 patch `\@floatboxreset`。

`\AtBeginEnvironment{tabular}` 的方式有两个弊端，一是会影响到其他位置的使用 `tabular` 实现的环境，这就很不安全；二是限制了用户使用自定义的字号，比如 `\tiny\begin{tabular}...` 中 `\tiny` 的效果会被覆盖，而 `\begin{tabular}\tiny...` 只有第一个单元格有 `\tiny` 的效果。

**Comment by TheNetAdmin** [comment]
> 
> 
> > #124 表格字体问题这里，如果改成下面这样
> > `\AtBeginEnvironment{tabular}{\zihao{5}\fangsong} \AtBeginEnvironment{tabularx}{\zihao{5}\fangsong}`
> > 那么封面的格式也变了，封面也是基于tabular的。有什么好的解决办法吗？
> 
> 参考 https://www.zhihu.com/question/366803177/answer/977853129，最合理的方法是 patch `\@floatboxreset`。
> 
> `\AtBeginEnvironment{tabular}` 的方式有两个弊端，一是会影响到其他位置的使用 `tabular` 实现的环境，这就很不安全；二是限制了用户使用自定义的字号，比如 `\tiny\begin{tabular}...` 中 `\tiny` 的效果会被覆盖，而 `\begin{tabular}\tiny...` 只有第一个单元格有 `\tiny` 的效果。

感谢说明！我测试一下 `\@floatboxreset`，稍后更新一下代码

@ya654 我猜你遇到的是封面表格的字号有问题？一个解决方法是将如下代码

https://github.com/TheNetAdmin/zjuthesis/blob/870f90c669ef9aa95cb50b3d17e43a2d1581dd6c/config/format/general/tables.tex#L4-L6

移动到这里

https://github.com/TheNetAdmin/zjuthesis/blob/870f90c669ef9aa95cb50b3d17e43a2d1581dd6c/config/format/general/layout.tex#L157-L165

这样就不会影响封面表格的格式了。

如果仍有问题，请单独开一个 issue 讨论下

**Comment by TheNetAdmin** [comment]
> 
> 
> #124 表格字体问题这里，如果改成下面这样
> `\AtBeginEnvironment{tabular}{\zihao{5}\fangsong} \AtBeginEnvironment{tabularx}{\zihao{5}\fangsong}`
> 那么封面的格式也变了，封面也是基于tabular的。有什么好的解决办法吗？


@ya654 我猜你遇到的是封面表格的字号有问题？一个解决方法是将如下代码

https://github.com/TheNetAdmin/zjuthesis/blob/870f90c669ef9aa95cb50b3d17e43a2d1581dd6c/config/format/general/tables.tex#L4-L6

移动到这里

https://github.com/TheNetAdmin/zjuthesis/blob/870f90c669ef9aa95cb50b3d17e43a2d1581dd6c/config/format/general/layout.tex#L157-L165

这样就不会影响封面表格的格式了。

如果仍有问题，请单独开一个 issue 讨论下

**Comment by GoldfischeRUA** [comment]
请问如何修改章节间距
![image](https://user-images.githubusercontent.com/51317701/113514292-564b1800-95a0-11eb-9dd4-667e5dd0bf6c.png)
这一部分的章节间距过大。

**Comment by TheNetAdmin** [comment]
@GoldfischeRUA 填充正文内容，或者用clearpage

**Comment by ZedongPeng** [comment]
请教以下 Move table font style to layout.tex 的更新里好像没有涉及表格字体大小，如果想设置表格内字体大小为五号，需要怎么操作啊？感谢了

**Comment by muzimuzhi** [comment]
> 如果想设置表格内字体大小为五号，需要怎么操作啊？感谢了

这是一个单独的问题，建议提新 issue

**Comment by TheNetAdmin** [comment]
针对本科生各专业模板的排查已经完成，排查工作暂时告一段落，等暑假或年底时硕士研究生开题时再继续排查研究生模板的问题

**Comment by TheNetAdmin** [comment]
一个有趣的功能是，GitHub 可以自动可视化 Action pipeline，通过创建 Action 的 dependency，可以得到如下所示的一张有趣的 pipeline 示意图，可以快速得知 testing pipeline 哪一步出了错。

![image](https://user-images.githubusercontent.com/18525442/114527215-8d52a680-9bfc-11eb-9f12-fb0fa7e353cf.png)

这样做另一个好处是 pipeline 里某一步失败之后，不会再执行下一步，可以有效减少 ci 运行时间，更可以减少错误操作：比如 pipeline 失败后，不会更新 Overleaf 模板
