### ISSUE TITLE
无法正常编译参考文献

### ISSUE THREAD

**Issue by MARMOTatZJU** [TheNetAdmin/zjuthesis#127]
## 系统信息

**操作系统**

- [ ] Windows
- [X] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [X] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [X] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.3

Degree:
  - [X] graduate
    - [X] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5791248/zjuthesis.log)
[stdout_stderr.log](https://github.com/TheNetAdmin/zjuthesis/files/5791249/stdout_stderr.log)

## 遇到的问题

改commit无法成功编译，log如上。

关键部分log如下：
```
------------
Running 'biber  "out/zjuthesis.bcf"'
------------
Latexmk: Examining 'out/zjuthesis.log'
=== TeX engine is 'XeTeX'
Latexmk: applying rule 'biber out/zjuthesis'...
INFO - This is Biber 2.16
INFO - Logfile is 'out/zjuthesis.blg'
INFO - Reading 'out/zjuthesis.bcf'
INFO - Found 0 citekeys in bib section 0
INFO - Found 0 citekeys in bib section 1
INFO - Found 0 citekeys in bib section 0
INFO - Found 1 citekeys in bib section 2
INFO - Found 0 citekeys in bib section 0
INFO - Processing section 2
INFO - Looking for bibtex format file 'body/ref.bib' for section 2
INFO - LaTeX decoding ...
INFO - Found BibTeX data source 'body/ref.bib'
Latexmk: Found biber source file(s) [body/ref.bib out/zjuthesis.bcf]
Latexmk: Summary of warnings from last run of *latex:
  Latex failed to resolve 5 reference(s)
  =====Latex reported missing or unavailable character(s).
=====See log file for details.
  Latex failed to resolve 2 citation(s)
Collected error summary (may duplicate other messages):
  biber out/zjuthesis: Command for 'biber out/zjuthesis' gave return code 2
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
Latexmk: Errors, so I did not complete making targets
```

如果按照提示，使用latexmk -f，则无法正常编译参考文献。

使用的commit如下：

```
* commit 5746e000b6105796a6d6754fec748b905842f836 (HEAD)
| Author: Zixuan Wang <zxwang42@gmail.com>
| Date:   Mon Jan 4 23:12:47 2021 -0800
| 
|     Update README.md
```

**截图**

**其他信息**

**Comment by MARMOTatZJU** [comment]
重启mac后解决😂希望其他人看到该error不必慌张，尝试重启

**Comment by zepinglee** [comment]
我上次也遇到类似问题，可以 `biber -D` 看一下报错，大概跟 `/var` 的缓存文件有关，也是重启大法好。

**Comment by MARMOTatZJU** [comment]
@TheNetAdmin 可能可以加入Troubleshoot（如果有的话）？

@zepinglee 请问是否有手动命令可以清楚/var下latex相关的缓存呢？

**Comment by TheNetAdmin** [comment]
> 可能可以加入Troubleshoot（如果有的话）？

以前的issue里讨论过类似问题，faq里没记错的话有提到清理中间文件。不过重启还是第一次看到

**Comment by TheNetAdmin** [comment]
问题已经解决的话就可以close了

**Comment by zepinglee** [comment]
> @zepinglee 请问是否有手动命令可以清楚/var下latex相关的缓存呢？

好像没有，这个应该跟 perl 有关（biber 是用 perl 写的）

**Comment by MARMOTatZJU** [comment]
@TheNetAdmin 看了下faq里没有，建议还是添加一个吧。关键时刻还挺掉链子😂

**Comment by TheNetAdmin** [comment]
> @TheNetAdmin 看了下faq里没有，建议还是添加一个吧。关键时刻还挺掉链子😂

确实没有……会加的

这种被坑的事情还是难以避免的，以后会碰到更多坑的……

**Comment by woshiZS** [comment]
> > @TheNetAdmin 看了下faq里没有，建议还是添加一个吧。关键时刻还挺掉链子😂
> 
> 确实没有……会加的
> 
> 这种被坑的事情还是难以避免的，以后会碰到更多坑的……

建议添加到FAQ里面，我今天也遇到了，网上找了半天解决方案，然后翻issue翻到了，也是macOS + xelatex

**Comment by lccurious** [comment]
确实是biber的缓存导致的，可以用下面的命令清除缓存：

```shell
rm -rf $(biber --cache)
```
