### ISSUE TITLE
如何在论文前体部分加页眉（比如：摘要，致谢，目录等等）

### ISSUE THREAD

**Issue by t3isuan** [TheNetAdmin/zjuthesis#128]
## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [x] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [ ] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

**截图**

**其他信息**

**Comment by muzimuzhi** [comment]
论文模板的本意是，假设用户需要遵循**相同**的样式要求，然后由模板为 latex 通用标记命令定制样式，尽可能让用户只需要输入内容。

请问你的样式需求，具体源自哪个学院？对页眉的具体要求是什么，和正文的页眉要求一致吗？

**Comment by t3isuan** [comment]
> 论文模板的本意是，假设用户需要遵循**相同**的样式要求，然后由模板为 latex 通用标记命令定制样式，尽可能让用户只需要输入内容。
> 
> 请问你的样式需求，具体源自哪个学院？对页眉的具体要求是什么，和正文的页眉要求一致吗？

是动物科学学院的硕士论文，与正文的页眉要求一致，这部分没有明确文件规定，但是看历届学长学姐都在摘要，致谢，目录等论文前体部分加了页眉。

刚学习用LaTeX有些地方还不太懂，请学长多多指教！

**Comment by TheNetAdmin** [comment]
前置页面（包括摘要等）使用了如下 `previous` 页面设定

https://github.com/TheNetAdmin/zjuthesis/blob/c1e3f59f68059e0037d519bdf8fde34761fb879e/config/format/general/layout.tex#L55-L61

可以将其改为其他有页眉的 `previous` 样式，例如

https://github.com/TheNetAdmin/zjuthesis/blob/c1e3f59f68059e0037d519bdf8fde34761fb879e/config/format/general/layout.tex#L34-L39

也就是把 `\fancyhead{}` 改为 `\commonhead{}`，然后去掉 `\renewcommand{\headrulewidth}{0pt}`

**Comment by t3isuan** [comment]
> > 是动物科学学院的硕士论文，与正文的页眉要求一致，这部分没有明确文件规定，但是看历届学长学姐都在摘要，致谢，目录等论文前体部分加了页眉。
> 
> 前置页面（包括摘要等）使用了如下 `previous` 页面设定
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/c1e3f59f68059e0037d519bdf8fde34761fb879e/config/format/general/layout.tex#L55-L61
> 
> 可以将其改为其他有页眉的 `previous` 样式，例如
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/c1e3f59f68059e0037d519bdf8fde34761fb879e/config/format/general/layout.tex#L34-L39
> 
> 也就是把 `\fancyhead{}` 改为 `\commonhead{}`，然后去掉 `\renewcommand{\headrulewidth}{0pt}`
谢谢学长！

还有个小问题就是我之前用的版本是v6.0.5，这个版本的layout.tex跟最新的v6.4.3有些不一样，在最新版本是可行的，想请问一下如果要更新到最新版本，除了全部复制过去还有别的什么更简便的方法吗？

**Comment by TheNetAdmin** [comment]
>除了复制过去还有别的什么更简便的方法吗？

可以新开一个 Overleaf，上传最新的代码模板，然后将之前的 `body` 和 `figures` 下的内容复制过去

**Comment by t3isuan** [comment]
> > 除了复制过去还有别的什么更简便的方法吗？
> 
> 可以新开一个 Overleaf，上传最新的代码模板，然后将之前的 `body` 和 `figures` 下的内容复制过去

好的！谢谢学长！

**Comment by treasersimplifies** [comment]
最新问题，使用
```
\fancypagestyle{previous} 
 { 
     \commonhead{} 
     \fancyfoot{} 
     \fancyfoot[OC,EC]{\zihao{-5}\thepage} 
 } 
```
后的页眉竟然没有下划线
