### ISSUE TITLE
研究生通用模板的页间距不对

### ISSUE THREAD

**Issue by rosefun** [TheNetAdmin/zjuthesis#129]
## 可改进的内容

根据研究生word模板要求

![image](https://user-images.githubusercontent.com/32197447/104265564-d9406300-54c8-11eb-94c1-aa63db7b81e3.png)

详细文件参见：

[研究生学位论文](https://github.com/TheNetAdmin/zjuthesis/issues/94#issuecomment-758369685)

但是，通用研究生模板与要求有出入。

## 代码与步骤

无

## 预期结果

符合要求文件的页面距。

**Comment by TheNetAdmin** [comment]
你的模板是从哪来的，是你们专业的模板？研究生院的编写规则里没有这一项

https://github.com/TheNetAdmin/zjuthesis/files/5784225/2016-grad-rules.pdf

**Comment by TheNetAdmin** [comment]
![image](https://user-images.githubusercontent.com/18525442/104276560-fb4ecc80-5459-11eb-87c9-de16f4ab7d48.png)

对比了一下研究生院的编写规则（左）和你上传的编写规则（右），可看到第12条规则是额外加上去的（特别是句首的括号与之前条目不一致）。

我猜这是你们学院提供的研究生论文编写规则？如果是的话请提供一下学院名称，以及学院英文简称，我做一个针对你们学院的页边距上去

**Comment by rosefun** [comment]
具体怎么改，我自己来（学院没有页间距的要求，导师叫我和其他word排版的页间距一样）

**Comment by TheNetAdmin** [comment]
https://github.com/TheNetAdmin/zjuthesis/blob/8da2f128ec4fb1c6255b406811fd28ed52c2f7cf/config/format/general/geometry.tex#L18-L19
