### ISSUE TITLE
能否使得引用加上方括号？

### ISSUE THREAD

**Issue by lsmll** [TheNetAdmin/zjuthesis#13]
我们专业要求文献引用的数字两边要加上方括号。例如[1]、[2,4,5]这样子（都是上标）。我试了把config/package.tex里面的biblatex的citestyle改成numeric后有方括号，但这样就不是上标了；而默认的gb7714-2015是上标，但是没有方括号。请问是否有解决方法？

**Comment by hushidong** [comment]
用的什么命令呀？正常用cite命令都是有方括号的呀。

**Comment by lsmll** [comment]
好吧，可能问题解决了。我原来用的是autocite，因为你们content文件夹下默认的样例就是用autocite的，建议你们可以改一下。Feel free to close the issue now.

**Comment by TheNetAdmin** [comment]
OK我更新一下样例文件，谢谢提醒

**Comment by TheNetAdmin** [comment]
样例文件已经更新了
