### ISSUE TITLE
cs硕士参考文献格式问题 行间距

### ISSUE THREAD

**Issue by Marco2018** [TheNetAdmin/zjuthesis#130]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.3

Degree:
  - [x] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5799828/zjuthesis.log)

## 遇到的问题
参考文献格式如何控制行间距？我的文件编译出来之后行间距特别窄（师兄留下来的文件行间距都相对宽一些，师兄的参考文献一页34行，我的有49行），同时想问一下cs硕士毕业论文的参考文献格式要求具体是什么

**截图**

![image](https://user-images.githubusercontent.com/23646963/104270538-b8313f80-54d3-11eb-9fa1-89e95b25055c.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
https://github.com/TheNetAdmin/zjuthesis/issues/57#issuecomment-612537279

**Comment by TheNetAdmin** [comment]
刚点错按钮了，行距问题近期会统一修复，请关注 #126

**Comment by TheNetAdmin** [comment]
> 参考文献格式如何控制行间距？

尝试修改这里以临时修复

https://github.com/TheNetAdmin/zjuthesis/blob/c1e3f59f68059e0037d519bdf8fde34761fb879e/body/graduate/post/ref.tex#L3

**Comment by TheNetAdmin** [comment]
查了一下计算机学院的硕士博士模板，并没有明确定义参考文献行距

https://github.com/TheNetAdmin/zjuthesis-std/tree/834674796e141d473d99cd6bfa25c7cb6dfedfbd/standard/graduate/cs

但本科生模板要求参考文献是单倍行距，所以在研究生模板中也用了单倍参考文献行距

https://github.com/TheNetAdmin/zjuthesis-std/tree/834674796e141d473d99cd6bfa25c7cb6dfedfbd/standard

如果后续有学院明确要求了研究生参考文献行距，可以将具体要求传到

https://github.com/TheNetAdmin/zjuthesis/issues/94

或者

https://github.com/TheNetAdmin/zjuthesis-std
