### ISSUE TITLE
cs master 递交日期 bug

### ISSUE THREAD

**Issue by gemlongman** [TheNetAdmin/zjuthesis#133]
https://github.com/TheNetAdmin/zjuthesis/blob/0c486ea1dc02c00f95195f9dd564884dd39329f2/page/graduate/doctor/cs/cover-chn.tex#L60

递交日期    & \uline{\hfill \SubmitDate \hfill}

英文同样 少了一个  \SubmitDate 

Submitted Date: & \uline{\hfill \SubmitDate \hfill}

**Comment by TheNetAdmin** [comment]
感谢指出！
