### ISSUE TITLE
字体突然变粗

### ISSUE THREAD

**Issue by lpf-gavin** [TheNetAdmin/zjuthesis#134]
## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [x] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5813304/zjuthesis.log)

## 遇到的问题

使用表格，如果表格中使用scalebox或resizebox命令，表格后面的文字会变粗

**截图**

**其他信息**

**Comment by TheNetAdmin** [comment]
在之前的 issue 里讨论过这个问题 #24 

尝试这样做能否解决问题 https://github.com/TheNetAdmin/zjuthesis/issues/24#issuecomment-733162806

如果可行的话，我可以将这些代码插入到模板中

**Comment by lpf-gavin** [comment]
解决了， 感谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TheNetAdmin/zjuthesis"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 凌晨4:09
收件人:&nbsp;"TheNetAdmin/zjuthesis"<zjuthesis@noreply.github.com&gt;;
抄送:&nbsp;"gavin"<lpf.gavin@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TheNetAdmin/zjuthesis] 字体突然变粗 (#134)





 
在之前的 issue 里讨论过这个问题 #24
 
尝试这样做能否解决问题 #24 (comment)
 
如果可行的话，我可以将这些代码插入到模板中
