### ISSUE TITLE
插入表格与图片后的前后空白问题

### ISSUE THREAD

**Issue by xxwywzy** [TheNetAdmin/zjuthesis#135]
## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [x] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.0.2（自己魔改过，所以没有更新）

Degree:
  - [ ] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

在博士论文模板中，当插入较长的图片或表格时，模板一般会另起一页插入这些图片或表格，导致图表前后的留白过多，有时还会引起段落之间的间距（空白）过大，之前有试过引入 \usepackage{setspace}，似乎可以使整体排版更加紧凑，但是发现会导致部分段落之间出现无法调节的较大间距，目前还没有找到比较好的解决方案。

**截图**

使用 setspace 前：
![image](https://user-images.githubusercontent.com/8501941/104996295-9b13e800-5a62-11eb-99c0-f1938798e12c.png)

使用 setspace 后：
![image](https://user-images.githubusercontent.com/8501941/104996559-0e1d5e80-5a63-11eb-9758-04adb5dd4ead.png)

**其他信息**

**Comment by zepinglee** [comment]
`setspace` 可能会破坏其他地方已经设置好的行距，不建议使用。

你的 figure/table 环境是的位置参数是怎么写的？建议给段 MWE 用来测试。

**Comment by xxwywzy** [comment]
我把上面图片里的tex稍微改了一下：

```
\chapter{测试章节}

\section{测试标题}

测试

\begin{table}[htbp]
\caption{\label{tab:economic}测试表 1}
\begin{tabularx}{\linewidth}{l X<{\centering} X<{\centering}}
\toprule[1.5pt]
\multirow{2}{*}{测试} & \multicolumn{2}{c}{测试} \\ \cmidrule[0.75pt](l){2-3} % l 表示左侧修剪
                      & xxxx年         & xxxx年         \\ \midrule[0.75pt]
项目1                    & 9,900           & 9,900               \\ 
项目2                 & 9,900           & 9,900             \\
项目3                   & 9,900         & 9,900             \\ 
项目4                    & 9,900           & 9,900               \\ 
项目5                  & 9,900         & 9,900             \\ \bottomrule[1.5pt]
\end{tabularx}
\end{table}

测试段落1。

\begin{table}[htbp]
\caption{\label{tab:target}测试表2}
\begin{tabularx}{\linewidth}{l X<{\centering}}
\toprule[1.5pt]
测试 & 测试 \\ \midrule[0.75pt]
\multicolumn{2}{l}{\textbf{测试}} \\
测试 & 1. 测试 \\
\multicolumn{2}{l}{\textbf{测试}} \\
测试 & 2. 测试 \\
测试 & 3. 测试 \\ 
测试 & 4. 测试 \\
测试 & 5. 测试 \\
\multicolumn{2}{l}{\textbf{测试}}\\
测试 & 6. 测试  \\ 
测试 & 7. 测试  \\
\multicolumn{2}{l}{\textbf{测试}} \\
测试  & 8. 测试 \\
测试 & 9. 测试 \\ \bottomrule[1.5pt]
\end{tabularx}
\end{table}

测试段落2。
```

编译出来的效果是这样的：
![image](https://user-images.githubusercontent.com/8501941/105003761-0911dc80-5a6e-11eb-8ecd-14c44dd47cde.png)

**Comment by xxwywzy** [comment]
刚才又遇到了类似的问题..在一张占满整页的图片前，段落之间的空白会异常大

![image](https://user-images.githubusercontent.com/8501941/105012652-5778a880-5a79-11eb-9d44-b7980eaaef4f.png)

**Comment by muzimuzhi** [comment]
`\raggedbottom`

**Comment by xxwywzy** [comment]
> `\raggedbottom`

谢谢！可以解决段落间空白过大的问题，不过图片和表格的排版还是无法解决

**Comment by TheNetAdmin** [comment]
@xxwywzy 要压缩表格可以调整表格内行间距

图表位置可以通过浮动体调节

图标环境与文字的垂直间距一般不用太在意，LaTeX 会根据文字和图表所占版面自动调节。如果一定要调节，手动在图表环境里加一些 `\vspace` 好了

**Comment by muzimuzhi** [comment]
> 不过图片和表格的排版还是无法解决

浮动体**不能**跨页。长表格考虑用 `longtable`，多图片考虑分散在多个浮动体环境里。浮动体的排版参数（例如每页最多几个浮动体）和前后间距，可以参考 https://latexref.xyz/Floats.html#Floats 进行调整。

**Comment by xxwywzy** [comment]
谢谢！可以通过手动调整浮动体参数实现更加紧凑的排版，不过具体的参数需要多次尝试才能得知，且当前参数的配置对之后添加的图表排版可能不太兼容，不过暂时就先这样处理了，等全部写完可以再最终调整一下（doge

**Comment by zepinglee** [comment]
> 当插入较长的图片或表格时，模板一般会另起一页插入这些图片或表格，导致图表前后的留白过多

> 编译出来的效果是这样的：
> ![image](https://user-images.githubusercontent.com/8501941/105003761-0911dc80-5a6e-11eb-8ecd-14c44dd47cde.png)
 
这里的表 2 是单独成页，也就是该页只含有浮动体，前后留白是正常的。这主要是因为 LaTeX 的浮动体放置策略比较保守，更容易形成单独的浮动体页。可以设置松弛一些的条件，参考 <https://www.texfaq.org/FAQ-floats>。`\topfraction` 等参数默认的值以及相应的解释可以参考 `texdoc classes` 6.3.5 节。

另外，这里表格内容的字号比表题的还大，显得有些离谱。可以缩小表格内容的字号，减少表格占据的篇幅，参考 <https://www.zhihu.com/question/366803177/answer/977853129>。

**Comment by xxwywzy** [comment]
> > 当插入较长的图片或表格时，模板一般会另起一页插入这些图片或表格，导致图表前后的留白过多
> 
> > 编译出来的效果是这样的：
> > ![image](https://user-images.githubusercontent.com/8501941/105003761-0911dc80-5a6e-11eb-8ecd-14c44dd47cde.png)
> 
> 这里的表 2 是单独成页，也就是该页只含有浮动体，前后留白是正常的。这主要是因为 LaTeX 的浮动体放置策略比较保守，更容易形成单独的浮动体页。可以设置松弛一些的条件，参考 https://www.texfaq.org/FAQ-floats。`\topfraction` 等参数默认的值以及相应的解释可以参考 `texdoc classes` 6.3.5 节。
> 
> 另外，这里表格内容的字号比表题的还大，显得有些离谱。可以缩小表格内容的字号，减少表格占据的篇幅，参考 https://www.zhihu.com/question/366803177/answer/977853129。

感谢！已经重新设置了浮动体参数（似乎还需要再放宽一些才能满足我的要求），关于表格字号的问题，在这个模板中如果全局调整字号，会影响封面页的排版，因此我目前只在正文部分设置了字号的调整（记录一下防止之后有人踩坑）。

**Comment by zepinglee** [comment]
> 感谢！已经重新设置了浮动体参数（似乎还需要再放宽一些才能满足我的要求），关于表格字号的问题，在这个模板中如果全局调整字号，会影响封面页的排版，因此我目前只在正文部分设置了字号的调整（记录一下防止之后有人踩坑）。

封面应该是用了 `tabular`，建议在模板中 patch `\@floatboxreset`，这样只影响 `figure`、`table`等浮动体，而不影响封面的 `tabular`。

对于用户的话就比较灵活了，比如用 `\tiny` 把字号设置得更小：
```latex
\beign{table}
  \caption{...}
  \tiny
  \begin{tabular}...
  \end{tabular}
\end{table}
```

**Comment by TheNetAdmin** [comment]
patch 了 `\@floatboxreset` 来设定宋体字体，感谢建议
