### ISSUE TITLE
MacOS 平台字体识别问题

### ISSUE THREAD

**Issue by Cyan27** [TheNetAdmin/zjuthesis#136]
## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.3.4

Degree:
  - [x] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

现在正文的字体为宋体，请问如何修改为仿宋？

**截图**

**其他信息**

**Comment by TheNetAdmin** [comment]
截图和编译log

**Comment by Cyan27** [comment]
是不是我的字体没有显示正确？

![image](https://user-images.githubusercontent.com/11551747/105229870-85f0a380-5b9f-11eb-823d-a610b49fb785.png)



[Compiling /Users/cyan/git/PhD-Thesis/zjuthesis.tex]

Basic Builder: running xelatex...done.

No errors. Warnings:

/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-fandol.def: Package fontspec Warning: Font "FandolSong-Regular" does not contain requested(fontspec)                Script "CJK".
/Users/cyan/git/PhD-Thesis/zjuthesis.tex: LaTeX Warning: Unused global option(s):    [ Attacks and Defenses of Sound Sensing].
/Users/cyan/git/PhD-Thesis/zjuthesis.bbl: Package fontspec Warning: Font "FandolSong-Regular" does not contain requested(fontspec)                Script "CJK".
/Users/cyan/git/PhD-Thesis/zjuthesis.tex:141: Package todonotes Warning: The length marginparwidth is less than 2cm and will most likely cause issues with the appearance of inserted todonotes. The issue can be solved by adding a line like \setlength {\marginparwidth }{2cm} prior to loading the todonotes package. on input line 141.
/Users/cyan/git/PhD-Thesis/page/graduate/cover-chn.tex: Package fontspec Warning: Font "FandolFang-Regular" does not contain requested(fontspec)                Script "CJK".
/Users/cyan/git/PhD-Thesis/page/graduate/auth-claim.tex: Package fontspec Warning: Font "FandolKai-Regular" does not contain requested(fontspec)                Script "CJK".
/Users/cyan/git/PhD-Thesis/body/graduate/chapter4.tex:275: LaTeX Font Warning: Font shape `TU/FandolSong-Regular(1)/m/it' undefined(Font)              using `TU/FandolSong-Regular(1)/m/n' instead on input line 275.
/Users/cyan/git/PhD-Thesis/body/graduate/chapter4.tex:560: LaTeX Font Warning: Font shape `U/wasy/b/n' in size <10.53937> not available(Font)              size <10.95> substituted on input line 560.
/Users/cyan/git/PhD-Thesis/body/graduate/chapter4.tex:560: LaTeX Font Warning: Font shape `U/wasy/b/n' in size <7> not available(Font)              Font shape `U/wasy/m/n' tried instead on input line 560.
/Users/cyan/git/PhD-Thesis/body/graduate/chapter5.tex: LaTeX Warning: `h' float specifier changed to `ht'.
/Users/cyan/git/PhD-Thesis/body/graduate/chapter6.tex: Package fontspec Warning: Font "FandolFang-Regular" does not contain requested(fontspec)                Script "CJK".
/Users/cyan/git/PhD-Thesis/zjuthesis.tex: LaTeX Font Warning: Size substitutions with differences(Font)              up to 1.22pt have occurred.
/Users/cyan/git/PhD-Thesis/zjuthesis.tex: LaTeX Font Warning: Some font shapes were not available, defaults substituted.

/Users/cyan/git/PhD-Thesis/zjuthesis.log:1: Double-click here to open the full log.

[Done!]

**Comment by TheNetAdmin** [comment]
这是命令行输出吗？直接把log文件拖拽进来。

Doctor 的 general 版用的是仿宋字体，样例 pdf 中有相关效果。你尝试下载一个新的模板代码，不做任何修改，直接编译 doctor general 呢？

**Comment by Cyan27** [comment]
[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5845119/zjuthesis.log)

**Comment by Cyan27** [comment]
直接编译模版有error，我当时是把fonts.tex里 % Windows or other platform 下面那段注释掉才不报错的

这是直接编译模版的log
[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5845160/zjuthesis.log)

**Comment by TheNetAdmin** [comment]
> 直接编译模版有error，我当时是把fonts.tex里 % Windows or other platform 下面那段注释掉才不报错的
> 
> 这是直接编译模版的log
> [zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5845160/zjuthesis.log)

未经修改的原始模板的log中，1167行

```

! Package fontspec Error: The font "FangSong" cannot be found.

For immediate help type H <return>.
 ...                                              
                                                  
l.46 }

```

似乎 font.tex 没有正确识别你的操作系统，而使用了 `FangSong` 字体。

https://github.com/TheNetAdmin/zjuthesis/blob/80a82884bd1d0513688924010aec048709d45297/config/format/general/fonts.tex#L39-L40

我看到你在用 MacOS，请问是什么版本呢？

以及在系统中是否能找到这个文件 `/System/Library/Fonts/PingFang.ttc`？

临时的修复方式是将这里

https://github.com/TheNetAdmin/zjuthesis/blob/80a82884bd1d0513688924010aec048709d45297/config/format/general/fonts.tex#L9-L46

根据你的 MacOS 版本，改为

```TeX
    % MacOS El Capitan and later version
    % https://github.com/CTeX-org/ctex-kit/issues/351

    % Fonts
    %   Fix songti font invocation in `ctex` package on MacOS old version, to enable bold font
    %   Detailes in: https://github.com/TheNetAdmin/zjuthesis/issues/48
    %   Similar implementation: https://github.com/xueruini/thuthesis/blob/a86b0824da527268645571cc5fe3096d65a665b3/thuthesis.dtx#L1447-L1461
    \setCJKfamilyfont{zhfs}   {STFangsong}      [AutoFakeBold={\FakeBoldSize}]
    \setCJKfamilyfont{zhhei}  {Heiti SC Light}  [BoldFont={Heiti SC Medium}]
    \setCJKfamilyfont{zhkai}  {Kaiti SC}        [BoldFont={Kaiti SC Bold}]
    \setCJKfamilyfont{zhsong} {Songti SC Light} [BoldFont={Songti SC Bold}]
    
    \setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{STFangsong}
```

或

```TeX
    % Older MacOS
    % Fonts
    \setCJKfamilyfont{zhfs}   {STFangsong} [AutoFakeBold={\FakeBoldSize}]
    \setCJKfamilyfont{zhhei}  {STHeiti}    [AutoFakeBold={\FakeBoldSize}]
    \setCJKfamilyfont{zhkai}  {STKaiti}    [AutoFakeBold={\FakeBoldSize}]
    \setCJKfamilyfont{zhsong} {STSong}     [AutoFakeBold={\FakeBoldSize}]

    \setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{STFangsong}
```

即只保留第一部分或者第二部分的字体设置，删除其余两个字体设置

**Comment by TheNetAdmin** [comment]
以及尝试 `tlmgr update --self --all` 升级 TeXLive 之后，能否编译未经修改的模板代码呢？

**Comment by muzimuzhi** [comment]
> 直接编译模版有error，我当时是把fonts.tex里 % Windows or other platform 下面那段注释掉才不报错的
> 
> 这是直接编译模版的log
> [zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5845160/zjuthesis.log)

根据 log 文件第 47 行

> Document Class: ctexrep 2019/05/29 v2.4.16 Chinese adapter for class report (CT
EX)

猜测是问题 https://github.com/CTeX-org/ctex-kit/issues/455 ，升级 ctex 宏集到 v2.5.x 能解决问题。另见文章 [[过时] [LaTeX 使用] 升级 macOS 10.15 后 ctex 文档不显示中文的临时方案](https://zhuanlan.zhihu.com/p/90404943)。

**Comment by Cyan27** [comment]
我的系统版本是MacOS 11.1，系统中可以找到 `/System/Library/Fonts/PingFang.ttc`

通过手动删除`fonts.tex`里第二和三部分的字体设置可以让正文显示仿宋字体了，随后发现参考文献无法显示，通过`tlmgr update --self --all`可以解决。感谢！ @TheNetAdmin 

但是编译原模版的时候还是会出现相似的字体warning
[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5846904/zjuthesis.log)

@muzimuzhi 谢谢，还没来得及试升级 ctex ，试过之后再update

**Comment by TheNetAdmin** [comment]
> 我的系统版本是MacOS 11.1，系统中可以找到 `/System/Library/Fonts/PingFang.ttc`
> 
> 通过手动删除`fonts.tex`里第二和三部分的字体设置可以让正文显示仿宋字体了，随后发现参考文献无法显示，通过`tlmgr update --self --all`可以解决。感谢！ @TheNetAdmin 
> 
> 但是编译原模版的时候还是会出现相似的字体warning
> [zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5846904/zjuthesis.log)
> 
> @muzimuzhi 谢谢，还没来得及试升级 ctex ，试过之后再update
> 

看编译日志的第一行，你的 TeX Live 似乎是 2019 版的，建议升级到 2020 看还有没有类似的问题

**Comment by Cyan27** [comment]
> 看编译日志的第一行，你的 TeX Live 似乎是 2019 版的，建议升级到 2020 看还有没有类似的问题

`tex --version`显示是TeX 3.14159265 (TeX Live 2020)，是2020版的吧？

log第一行是`This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex 2021.1.21)  21 JAN 2021 12:42`

我安装了2018和2020版的texlive，texlive utility里已设置默认版本是2020

**Comment by TheNetAdmin** [comment]
> > 看编译日志的第一行，你的 TeX Live 似乎是 2019 版的，建议升级到 2020 看还有没有类似的问题
> 
> `tex --version`显示是TeX 3.14159265 (TeX Live 2020)，是2020版的吧？
> 
> log第一行是`This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex 2021.1.21) 21 JAN 2021 12:42`
> 
> 我安装了2018和2020版的texlive，texlive utility里已设置默认版本是2020

额刚刚在手机上看 log，似乎手机上选错文件了，你的这个确实已经是 2020 了

**Comment by cxzhou35** [comment]
> > 直接编译模版有error，我当时是把fonts.tex里 % Windows or other platform 下面那段注释掉才不报错的
> > 这是直接编译模版的log
> > [zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5845160/zjuthesis.log)
> 
> 未经修改的原始模板的log中，1167行
> 
> ```
> 
> ! Package fontspec Error: The font "FangSong" cannot be found.
> 
> For immediate help type H <return>.
>  ...                                              
>                                                   
> l.46 }
> ```
> 
> 似乎 font.tex 没有正确识别你的操作系统，而使用了 `FangSong` 字体。
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/80a82884bd1d0513688924010aec048709d45297/config/format/general/fonts.tex#L39-L40
> 
> 我看到你在用 MacOS，请问是什么版本呢？
> 
> 以及在系统中是否能找到这个文件 `/System/Library/Fonts/PingFang.ttc`？
> 
> 临时的修复方式是将这里
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/80a82884bd1d0513688924010aec048709d45297/config/format/general/fonts.tex#L9-L46
> 
> 根据你的 MacOS 版本，改为
> 
> ```
>     % MacOS El Capitan and later version
>     % https://github.com/CTeX-org/ctex-kit/issues/351
> 
>     % Fonts
>     %   Fix songti font invocation in `ctex` package on MacOS old version, to enable bold font
>     %   Detailes in: https://github.com/TheNetAdmin/zjuthesis/issues/48
>     %   Similar implementation: https://github.com/xueruini/thuthesis/blob/a86b0824da527268645571cc5fe3096d65a665b3/thuthesis.dtx#L1447-L1461
>     \setCJKfamilyfont{zhfs}   {STFangsong}      [AutoFakeBold={\FakeBoldSize}]
>     \setCJKfamilyfont{zhhei}  {Heiti SC Light}  [BoldFont={Heiti SC Medium}]
>     \setCJKfamilyfont{zhkai}  {Kaiti SC}        [BoldFont={Kaiti SC Bold}]
>     \setCJKfamilyfont{zhsong} {Songti SC Light} [BoldFont={Songti SC Bold}]
>     
>     \setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{STFangsong}
> ```
> 
> 或
> 
> ```
>     % Older MacOS
>     % Fonts
>     \setCJKfamilyfont{zhfs}   {STFangsong} [AutoFakeBold={\FakeBoldSize}]
>     \setCJKfamilyfont{zhhei}  {STHeiti}    [AutoFakeBold={\FakeBoldSize}]
>     \setCJKfamilyfont{zhkai}  {STKaiti}    [AutoFakeBold={\FakeBoldSize}]
>     \setCJKfamilyfont{zhsong} {STSong}     [AutoFakeBold={\FakeBoldSize}]
> 
>     \setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{STFangsong}
> ```
> 
> 即只保留第一部分或者第二部分的字体设置，删除其余两个字体设置

您好，我也在mac上遇到了这个问题，查找之后找到了这个相关的issue，故在此留言，我用的editor是vscode，texlive版本如下：
<img width="500" alt="image" src="https://github.com/TheNetAdmin/zjuthesis/assets/80182956/c4c7b443-05bd-4b4c-92df-5e27503449b2">

遇到的问题是找不到字体，log好像被清除了，贴一些报错在这里：
<img width="1079" alt="image" src="https://github.com/TheNetAdmin/zjuthesis/assets/80182956/92cce153-1f7e-439d-8704-2d9f8cab322b">

所有的中文字符都无法显示了：
<img width="1075" alt="image" src="https://github.com/TheNetAdmin/zjuthesis/assets/80182956/d1af4dff-2e29-48a5-aebc-71b2759ca8a4">

如果需要更多信息请联系我指出，非常感谢！

**Comment by muzimuzhi** [comment]
@cxzhou35 你好，请
- 避免在已经关闭有一阵的 issue 下回复，除非非常确定讨论的是完全相同的问题。建议开一个新的 issue。
- 避免无重点地全文或大段引用之前的评论内容（让每个 issue 的滚动条增长得慢一些）。只引用确切相关的部分、加上自己的回复即可。
- 不用回复我这条评论，直接开新 issue。

> 编译完后log文件好像被清除了，贴一点报错信息在这里：

可以修改 `latex-workshop` 插件的设置，停止清理文件。https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#catching-errors-and-warnings
