### ISSUE TITLE
求助：中文字体不能变为斜体

### ISSUE THREAD

**Issue by ZhengtongDu** [TheNetAdmin/zjuthesis#137]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.3

Degree:
  - [ ] graduate
    - [ ] master
    - [ ] doctor
  - [x] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [ ] isee
  - [x] math
  - [ ] physics

**编译日志**

## 遇到的问题

首先感谢学长提供latex模板
我的问题如截图所示，在使用"\emph{text}"的时候，只有英文部分变成了斜体，中文部分并没有变为斜体。希望学长能够帮助提供解决方案。
出现问题部分code如下：
`插值（Interpolation）问题是研究如何通过构建低维简单函数$p$，来对复杂的未知函数$f$拟合，使其与$f$在给定点集上具有相同函数值的一类问题。对一般的\emph{Lagrange插值问题}`
**截图**

![fig01](https://user-images.githubusercontent.com/48506525/105633911-4b845080-5e96-11eb-9dcd-ded4a3f8cc89.png)
![fig02](https://user-images.githubusercontent.com/48506525/105633923-563ee580-5e96-11eb-8f70-62d30ed16934.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
中文字体没有斜体，可以使用其他字体，或加粗，或其他字号，来表示强调

**Comment by ZhengtongDu** [comment]
> 中文字体没有斜体，可以使用其他字体，或加粗，或下划线，来表示强调

好的。谢谢！
