### ISSUE TITLE
想要正文的字体是宋体！！

### ISSUE THREAD

**Issue by cucJ2014** [TheNetAdmin/zjuthesis#139]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [ ] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [ ] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.3

Degree:
  - [x] graduate
    - [ ] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

学校要求正文 宋体，英文times new roman  但是fonts.tex中的字体主要用  仿宋～  被我导师看pdf一眼看出来了。。但是我不知道怎么修改fonts.tex才能改成宋体！  
**截图**

**其他信息**

**Comment by TheNetAdmin** [comment]
我不知道你具体的MacOS版本，不过把这里

https://github.com/TheNetAdmin/zjuthesis/blob/741d8327821b07eb125c05f81894bf5735874224/config/format/general/fonts.tex#L11-L36

改成

```LaTeX
\IfFileExists{ /System/Library/Fonts/PingFang.ttc }
{
    % MacOS El Capitan and later version
    % https://github.com/CTeX-org/ctex-kit/issues/351

    % Fonts
    %   Fix songti font invocation in `ctex` package on MacOS old version, to enable bold font
    %   Detailes in: https://github.com/TheNetAdmin/zjuthesis/issues/48
    %   Similar implementation: https://github.com/xueruini/thuthesis/blob/a86b0824da527268645571cc5fe3096d65a665b3/thuthesis.dtx#L1447-L1461
    \setCJKfamilyfont{zhfs}   {STFangsong}      [AutoFakeBold={\FakeBoldSize}]
    \setCJKfamilyfont{zhhei}  {Heiti SC Light}  [BoldFont={Heiti SC Medium}]
    \setCJKfamilyfont{zhkai}  {Kaiti SC}        [BoldFont={Kaiti SC Bold}]
    \setCJKfamilyfont{zhsong} {Songti SC Light} [BoldFont={Songti SC Bold}]
    
    \setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{Songti SC Light}
}
{
    % Older MacOS
    % Fonts
    \setCJKfamilyfont{zhfs}   {STFangsong} [AutoFakeBold={\FakeBoldSize}]
    \setCJKfamilyfont{zhhei}  {STHeiti}    [AutoFakeBold={\FakeBoldSize}]
    \setCJKfamilyfont{zhkai}  {STKaiti}    [AutoFakeBold={\FakeBoldSize}]
    \setCJKfamilyfont{zhsong} {STSong}     [AutoFakeBold={\FakeBoldSize}]

    \setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{STSong}
}
```

也就是把两个 `\setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{STFangsong}` 改成对应的宋体字体（各自上方一行）

**Comment by cucJ2014** [comment]
您好！我的macOS 是10.14.6 Mojave，
虽然能改成  STSong，但是它属于【华文宋体】，和【宋体】还不一样，我已经搜了一下午了，请问楼主还有可以解决的办法吗！

**Comment by muzimuzhi** [comment]
macOS 上没有你要的那个宋体（中易宋体），它是商业字体，只在 windows 上自带。

**Comment by TheNetAdmin** [comment]
> macOS 上没有你要的那个宋体（中易宋体），它是商业字体，只在 windows 上自带。

感谢提醒！

@cucJ2014 如果 MacOS 的中易宋体确实不满足要求的话，你可以尝试在 Windows 上编译论文，或者临时的解决方案是将 Windows 上的宋体复制到你的 MacOS 里，并在 fonts.tex 里设置相应的字体

**Comment by cucJ2014** [comment]
谢谢大家的帮助！！ 我昨天已经下载了SimSun安装之后在 font.tex 增加了
`\setCJKfamilyfont{zhsong} {SimSun Regular}     [AutoFakeBold={\FakeBoldSize}]`
因为系统字体册显示的是（ SimSun Regular），也尝试了 SimSun，但是编译的时候一直说：Not Found！  😢 马上要交盲审了，哎，主要我导师一眼就看出来说我的字体不是宋体，

**Comment by TheNetAdmin** [comment]
附上系统字体界面截图，编译得到的pdf文件，编译日志

想要快速得到帮助就提供足够的信息

**Comment by cucJ2014** [comment]
我本来代码都改回仿宋了，结果刚才想截图给大家看一下，就好了！现在是宋体了！！
![](https://tva1.sinaimg.cn/large/e6c9d24ely1go5h8y9h2xj21dc0q47iy.jpg)
![](https://tva1.sinaimg.cn/large/e6c9d24ely1go5h9btwxvj21ra0r6hcj.jpg)
![](https://tva1.sinaimg.cn/large/e6c9d24ely1go5ha1ik9dj214w0eaq6h.jpg)
