### ISSUE TITLE
博士论文致谢摘要标题居中附录标题居左

### ISSUE THREAD

**Issue by jiananwong** [TheNetAdmin/zjuthesis#142]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [x ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x ] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x ] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.3

Degree:
  - [ ] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/6096464/zjuthesis.log)

## 遇到的问题

管理学院要求博士论文致谢摘要标题居中附录标题居左，目前以上标题全部居左。已附学院模版。
[浙江大学管理学院研究生学位论文规范格式（09版）（新）.pdf](https://github.com/TheNetAdmin/zjuthesis/files/6096471/09.pdf)

**截图**

**其他信息**

**Comment by jiananwong** [comment]
已解决

**Comment by YaoZhongwei** [comment]
我也遇到相同的问题，请问如何设置？ @jiananwong

**Comment by Jessyfm** [comment]
请问如何解决？ @jiananwong @TheNetAdmin

**Comment by jialeli1** [comment]
请问一下，博士通用模板里面“摘要”怎么设置居中的呀？ @jiananwong @TheNetAdmin

**Comment by winterwindwang** [comment]
> 使用研究生模板但有摘要标题居中需求的同学可以参考：
> 
> 我在这个文件的L135-L137之间插入了一段新的自定义命令“\chapternonumcenter”，在设置摘要标题时调用这个新的命令即可，比如之前的“\chapternonum{摘要}”替换为“\chapternonumcenter{摘要}”。
> 
> 因为参考文献标题还需要居左，所以我新定义了一个居中版本的“chapternonum”，保留了原本的命令。
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/e4cdcb48f11b30ecb927e0b41718802f0a3ceab2/config/commands.tex#L132-L145
> 
> 自定义命令“\chapternonumcenter”：
> 
> ```
>     % 新定义的“居中”的chapternonum
>     \newcommand{\chapternonumcenter}[1]
>     {
>         \phantomsection
>         \addcontentsline{toc}{chapter}{#1}
>         \markboth{#1}{#1}
>         \begin{center}
>             \bfseries \zihao{3} #1	
>         \end{center}	
>         \setcounter{chapter}{0}
>     }
> ```

使用\quad可以增加文字间间隔，如\chapternonumcenter{摘 \quad 要}

**Comment by 321Fontsize** [comment]
> 使用\quad可以增加文字间间隔，如\chapternonumcenter{摘 \quad 要}

这种可以增加文字间隔，但是目录中的文字间隔也增加了，e.g.,

<img width="1030" height="276" alt="Image" src="https://github.com/user-attachments/assets/e5832895-c59d-499b-a2c6-18cf6681c5f9" />

上图中，我的命令是\chapternonumcenter{致\quad 谢}。请问这种问题如何解决呢？
