### ISSUE TITLE
reference中出现“[S.l. : s.n.]”

### ISSUE THREAD

**Issue by MARMOTatZJU** [TheNetAdmin/zjuthesis#145]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [X] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [X] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [X] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [ ] graduate
    - [X] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [X] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

reference中大量出现 "[S.l. : s.n.]"，经查含义为“无地点/无出版商”(source: https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Abbreviations/faq0007.html)

google scholar默认导出的bibtex中不含有address和publisher字段。请问是否有办法让reference不显示这两个信息？

**截图**

**其他信息**

**Comment by TheNetAdmin** [comment]
#47
