### ISSUE TITLE
参考文献中文字超出边界

### ISSUE THREAD

**Issue by MARMOTatZJU** [TheNetAdmin/zjuthesis#146]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [X] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [X] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [X] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [ ] graduate
    - [X] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [X] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

部分引文超出了右侧边距（如下截图），看了一下已有issues里并没有找到先例，请问如何解决？提前感谢～

**截图**

![image](https://user-images.githubusercontent.com/32362315/110268190-3c97ce80-7ffc-11eb-8e5e-0bfe1c504873.png)

**其他信息**

**Comment by hushidong** [comment]
至于换行的问题：按下面的原理处理：
1 {
2 %\hyphenation{Proce-edings}
3 \hyphenpenalty=5000 %断词阈值， 值越大越不容易出现断词
4 \tolerance=500 %丑度， 10000为最大无溢出盒子， 参考the texbook 第6章
5 \hbadness=100 %如果丑度超过hbadness这一阀值， 那么就会发出警告
6 \printbibliography[heading=subbibintoc,title=【参考文献】 ]
7 }

**Comment by MARMOTatZJU** [comment]
@hushidong 增加了"\hyphenpenalty=5000"后解决，感谢！
