### ISSUE TITLE
双面格式下章节间不自动留空白页

### ISSUE THREAD

**Issue by rosefun** [TheNetAdmin/zjuthesis#147]
## 可改进的内容

模板如果增加每章的第一页从正面开始打印，论文会根据美观。

## 预期结果

双面格式下，论文的每章的第一页都从正面开始排版。

**Comment by rosefun** [comment]
现在需要手动在章节前加入\cleardoublepage命令。

**Comment by TheNetAdmin** [comment]
你使用的是什么专业什么年级的设定？

当前的模板已经支持了每一章第一页从奇数页开始，我不清楚你所指的章是 `section` 还是 `chapter`，以及你用的是哪个年级的模板。

**Comment by rosefun** [comment]
chapter，使用了general的graduate模板

**Comment by TheNetAdmin** [comment]
嗯似乎确实有这个问题……我修复一下试试，可能之前某次更新把这个功能搞坏了

**Comment by TheNetAdmin** [comment]
尝试修复了一下，现在可以试试是否有效果
