### ISSUE TITLE
TeXLive 2020 中页眉格式 BUG

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#148]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.3 (df5708, master branch)

Degree:
  - [x] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/6118860/zjuthesis.log)

## 遇到的问题

在我本地的 Windows 上使用 TeXLive 2020 编译时，页眉中的 `章标题` 会包含 `CHAPTER` ，见下方截图。但使用 GitHub Action 自动编译就不会有这个问题 （使用 `adnrv/texlive:full` docker container 编译）。

**截图**

本地 TeXLive 2020 编译结果

![image](https://user-images.githubusercontent.com/18525442/110697976-e8c6ea00-81a1-11eb-874e-29c09175c04e.png)

GitHub Action 编译结果

![image](https://user-images.githubusercontent.com/18525442/110698106-1449d480-81a2-11eb-9062-e66d851c9a31.png)

**其他信息**

```
D:\Code\zjuthesis: latexmk --version

Latexmk, John Collins, 29 September 2020. Version 4.70b 

D:\Code\zjuthesis: xelatex --version
XeTeX 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX)
kpathsea version 6.3.2
Copyright 2020 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is       
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 65.1; using 65.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.10.1; using 2.10.1
Compiled with Graphite2 version 1.3.13; using 1.3.13
Compiled with HarfBuzz version 2.6.4; using 2.6.4
Compiled with libpng version 1.6.37; using 1.6.37
Compiled with poppler version 0.68.0
Compiled with fontconfig version 2.13.92; using 2.13.92
```

所有宏包已通过 `tlmgr update --self --all` 升级。

这两天排查完格式问题后 #126 ，研究一下这个 BUG 的来源并修复一下

**Comment by muzimuzhi** [comment]
是由 `fancyhdr` v4.0 引起的，`ctex` 更新了相关补丁，但没有发版。见 https://github.com/CTeX-org/ctex-kit/issues/554

**Comment by TheNetAdmin** [comment]
> 是由 `fancyhdr` v4.0 引起的，`ctex` 更新了相关补丁，但没有发版。见 https://github.com/CTeX-org/ctex-kit/issues/554

感谢说明！

**Comment by ltguo19** [comment]
最近在写博士论文，也遇到了同样的问题，感谢@muzimuzhi 提的解决方案，这里贴一下具体操作以方便其他同学：下载https://github.com/pietvo/fancyhdr/blob/V3.10/fancyhdr.sty ，用它替换本地的fancyhdr.sty文件。对于texlive，本地路径类似C:\texlive\2020\texmf-dist\tex\latex\fancyhdr\fancyhdr.sty

**Comment by HuiZhangDB** [comment]
感谢 @muzimuzhi @ltguo19 提供的解决方案，贴一下macos上的路径以方便有需要的同学：/usr/local/texlive/2020/texmf-dist/tex/latex/fancyhdr

**Comment by zepinglee** [comment]
可以在模板中的 `\fancypagestyle` 中重定义 `\chaptermark` 和 `\sectionmark`，这样就不依赖 `ctex` 的版本了。

**Comment by TheNetAdmin** [comment]
> 
> 
> 可以在模板中的 `\fancypagestyle` 中重定义 `\chaptermark` 和 `\sectionmark`，这样就不依赖 `ctex` 的版本了。

感谢指出，我修复一下加进去

**Comment by TheNetAdmin** [comment]
已经通过 `\chaptermark` 和 `\sectionmark` 修复，后续等 CTeX 等相关宏包更新后再考虑清理相关设定

**Comment by PanLiang0525** [comment]
大佬，我的页眉跟问题中的同学一样奇偶页是一样的，一般不是奇数页是浙江大学硕士论文，偶数页是章节号嘛，不知道咋改，感觉layout.tex文件好像区分了奇偶页，不太懂。ps我的系统信息和这位同学一样。

**Comment by TheNetAdmin** [comment]
> 大佬，我的页眉跟问题中的同学一样奇偶页是一样的，一般不是奇数页是浙江大学硕士论文，偶数页是章节号嘛，不知道咋改，感觉layout.tex文件好像区分了奇偶页，不太懂。ps我的系统信息和这位同学一样。

提出这个问题的人就是我……这个问题修复的BUG是：页眉里出现了"CHAPTER. "

你这个看上去是另一个问题，新开一个 issue 截图说明下

**Comment by PanLiang0525** [comment]
> > 大佬，我的页眉跟问题中的同学一样奇偶页是一样的，一般不是奇数页是浙江大学硕士论文，偶数页是章节号嘛，不知道咋改，感觉layout.tex文件好像区分了奇偶页，不太懂。ps我的系统信息和这位同学一样。
> 
> 提出这个问题的人就是我……这个问题修复的BUG是：页眉里出现了"CHAPTER. "
> 
> 你这个看上去是另一个问题，新开一个 issue 截图说明下

哦哦好的 但是你这样奇偶页页眉一样是可以的么
