### ISSUE TITLE
English template

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#15]
This template is made for Chinese users only, but if anyone is interested in the English template, we can discuss the details here:

1. What is the Zhejiang University English Thesis requirement?
2. Is there an official English template (_word_ version or requirement doc)?
3. Anything you think important.

I may make this English version later.

**Comment by TheNetAdmin** [comment]
Close this issue for now.

Feel free to reopen it to discuss the English version.

**Comment by HamzaSulayman** [comment]
Hi, the English version is just the translation of the Chinese version. No Chinese abstract is required also. 

Some colleges in ZJU have templates. I will share it when I get my hands on it.

**Comment by TheNetAdmin** [comment]
Thank you for the heads up.

Once you have the template, please post it here or send it to me via email, then reopen this issue.

**Comment by HamzaSulayman** [comment]
Hi, I couldn't find a template. But here are two English theses already published. 
[Ali Shoaib PhD.Thesis final print copy.pdf](https://github.com/TheNetAdmin/zjuthesis/files/3899847/Ali.Shoaib.PhD.Thesis.final.print.copy.pdf)
[Final PhD Thesis - Hassan Ahmad Gakal.pdf](https://github.com/TheNetAdmin/zjuthesis/files/3899848/Final.PhD.Thesis.-.Hassan.Ahmad.Gakal.pdf)

**Comment by TheNetAdmin** [comment]
I see there's a ZJU LOGO on top left, is that mandatory or part of format requirement?

**Comment by HamzaSulayman** [comment]
No, the ZJU logo is not mandatory.

**Comment by TheNetAdmin** [comment]
And another question, what is the requirement of reference format

**Comment by TheNetAdmin** [comment]
I guess the font for main content is Time right?

**Comment by HamzaSulayman** [comment]
Yes, Times New Roman 14 I think.

**Comment by HamzaSulayman** [comment]
The reference is usually numbered [1], but some colleges use names and years.

**Comment by TheNetAdmin** [comment]
I see, then what's the standard for bibliography?

**Comment by TheNetAdmin** [comment]
I'll make the English version these days. Once it's finished or I have some new question, I'll comment this issue.

**Comment by TheNetAdmin** [comment]
I just updated the English version, please download the PDF file with "-english" suffix from v5.0.0-rc2 to preview the template.

**Comment by TheNetAdmin** [comment]
I'll close this issue in the next week. If there is any bug or comment on the English version, please open a new issue.
