### ISSUE TITLE
目录行间距

### ISSUE THREAD

**Issue by zzzzhuque** [TheNetAdmin/zjuthesis#150]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.0-rc1

Degree:
  - [x] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics
  - [x] se

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/6146163/zjuthesis.log)

## 遇到的问题

软件学院要求目录行间距为单倍行距，但按照上述设置，目录行间距较大，应该如何调整呢

**截图**

![20210316124228](https://user-images.githubusercontent.com/31002842/111256962-34bbd800-8655-11eb-8e4a-2b589e124c39.jpg)

**其他信息**

**Comment by TheNetAdmin** [comment]
简单的解决方法是在这里

https://github.com/TheNetAdmin/zjuthesis/blob/df5708972a2260bcd56d4aefbc49e4ec2a8a1e2d/page/graduate/toc.tex#L4

插入类似如下代码，调整 `0.75` 的值到你认为合适的数值

```TeX
\renewcommand{\baselinestretch}{0.75}\normalsize
\markloc
\renewcommand{\baselinestretch}{1.0}\normalsize
```

**Comment by zzzzhuque** [comment]
你好，这个方法虽然可以让目录间距变小，但同时也会让正文部分的行间距变得很小，请问应该如何只修改目录呢

**Comment by TheNetAdmin** [comment]
那就修改这里的数值试试

https://github.com/TheNetAdmin/zjuthesis/blob/df5708972a2260bcd56d4aefbc49e4ec2a8a1e2d/config/format/major/se/layout.tex#L14

我看到你是在用 `se` 专业模板，所以可以在如上位置进行设置。如果你要切换其他模板，可将上述代码复制到 `config/format/major/general/layout.tex` 中

**Comment by zzzzhuque** [comment]
你好，我所使用的版本为：6.4.0-rc1，没有zjuthesis/config/format/major/se这个文件夹

**Comment by TheNetAdmin** [comment]
那你在issue模板里选的se?
