### ISSUE TITLE
如何嵌入markdown

### ISSUE THREAD

**Issue by MARMOTatZJU** [TheNetAdmin/zjuthesis#154]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [X] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [X] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [X] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [ ] graduate
    - [X] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [X] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

如何在latex中嵌入markdown文本？

尝试[Overleaf官方教程](https://www.overleaf.com/learn/how-to/Writing_Markdown_in_LaTeX_Documents)，显示：

```
Undefined control sequence
```

**截图**

**其他信息**

**Comment by muzimuzhi** [comment]
提供一个具体的、完整的例子
