### ISSUE TITLE
外文翻译需要题目

### ISSUE THREAD

**Issue by xhzhu0628** [TheNetAdmin/zjuthesis#155]
## 可改进的内容

请描述一下可改进的部分，例如“模板代码中使用了某某功能，但使用另一种功能更好

部分学院要求外文翻译需要翻译题目，但目前的外文翻译中摘要的命令\sectionnonum会导致原应在摘要前的题目出现在“外文翻译”的空白页上
![image](https://user-images.githubusercontent.com/66295967/113477511-ca0ff680-94b4-11eb-9823-ed482a948f9b.png)

## 代码与步骤

暂时是重写了新的\sectionnonum命令，删除了\cleardoublepage，摘要使用新的\sectionnonum

## 预期结果

![image](https://user-images.githubusercontent.com/66295967/113477529-ef9d0000-94b4-11eb-955c-da305713534c.png)

**Comment by TheNetAdmin** [comment]
这确实是个问题……

其本质是因为开题报告和最终论文使用的 “章” 不同，在开题报告里 “章” 使用了 `\chapter`，最终论文的 “章” 使用了 `\section`， 所以设置 `\cleardoublepage` 时同时设置了这两个命令

**Comment by TheNetAdmin** [comment]
新增了一个选项到 `\sectionnonum` 里
   1. 如果使用 `\sectionnonum{章节标题}` 则会默认调用 `\cleardoublepage`
   2. 如果使用 `\sectionnonum[openany]{章节标题}` 则会调用 `\clearpage`
   3. 如果使用 `\sectionnonum[none]{章节标题}` 则**不会**调用 `\cleardoublepage` 或 `\clearpage`
