### ISSUE TITLE
如何修改首页英文标题字体为Arial

### ISSUE THREAD

**Issue by xxwywzy** [TheNetAdmin/zjuthesis#156]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [x] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.0.2

Degree:
  - [ ] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

根据学院要求，英文论文题目需要设置为Arial字体，想请教一下如何仅对英文论文部分的字体进行修改（尝试了一些方法，但似乎无法仅修改英文论文的字体），谢谢！

**截图**

**其他信息**

**Comment by xxwywzy** [comment]
> 尝试修改这里
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/7fea4d7cd3c4223cf58fb2bb1b502c7eceef38b0/page/graduate/title-eng.tex#L4-L11
> 
> 插入一行 `\setromanfont{Arial}`，即
> 
> ```
> \begin{center}
>     % Chinese zihao{3} == English 16pt
>     \setromanfont{Arial}
>     \bfseries \zihao{3}
>     \begin{tabularx}{.8\textwidth}{X<{\centering}}
>         \uline{\hfill \TitleEng{} \hfill} \\
>         \uline{\hfill}
>     \end{tabularx}
> \end{center}
> ```
> 
> ![image](https://user-images.githubusercontent.com/18525442/114222854-f21faf80-9923-11eb-9b93-8de1c4554d29.png)

谢谢！字体已经修改成功了，还有一个小问题想请教一下，改完字体后封面上的英文字号有一些大，导致排版上分为了三行（之前用的是\zihao{4}），改成\zihao{-4}后又显得有些过小，尝试去修改表格宽度或者手动排版感觉效果都不是很好。我查了一下这两个字号分别对应英文的12pt和14pt，想请教一下有没有仅把英文标题修改为13pt字号的方法？

**Comment by TheNetAdmin** [comment]
这是一个表格环境，尝试把表格加宽呢

**Comment by TheNetAdmin** [comment]
哦没看到你已经调过表格宽度了，13pt看上去是一个比较不常见的字号，我还是建议调整表格宽度…

**Comment by TheNetAdmin** [comment]
或者无论如何也要使用13pt的话

https://tex.stackexchange.com/questions/310055/is-there-a-way-to-use-13pt-as-the-main-document-font-size-with-the-memoir-docume
