### ISSUE TITLE
如何修改表格字体但不影响封面

### ISSUE THREAD

**Issue by ZedongPeng** [TheNetAdmin/zjuthesis#157]
## 可改进的内容

目前模板中表格字体与论文字体一致，如果只调整表格字体需要怎么操作呢？

由于封面是基于tabular的，这个是需要解决的问题。

Related issue：#124
Related PR：#126

## 代码与步骤

如果可能的话请附上相关代码，或简要描述改进步骤

## 预期结果

如果可能的话请附上一份修改后的预期结果，如截图或命令行输出等

**Comment by TheNetAdmin** [comment]
你这issue用错issue模板了，我都不知道你用的什么zjuthesis设定，把'I need help'模板的信息复制过来填一遍

**Comment by ZedongPeng** [comment]
不好意思，那我先把这个Issue关了

**Comment by TheNetAdmin** [comment]
用 master 分支的 bc2bdad 或其后的代码，在这里设置正文的表格字体

https://github.com/TheNetAdmin/zjuthesis/blob/37a00e336ff6244129255c52e80e89bb5ce6492c/config/format/general/tables.tex#L4-L8
