### ISSUE TITLE
resizebox 导致表格后的字体变粗

### ISSUE THREAD

**Issue by ZedongPeng** [TheNetAdmin/zjuthesis#158]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [x] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：Commit ID: v6.4.3-7-gae48e26

Degree:
  - [x] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

使用resizebox导致表格之后的字体变粗，可见截图
相关Issue：#24   #134 

我使用#24 中的解决方法加入
```
\AtBeginEnvironment{table}{\special{pdf:code q}}
\AtEndEnvironment{table}{\special{pdf:code Q}}
```

然后就会出现表格单独一页，且有部分问题内容缺失的情况，可见截图。

复现的例子可见

https://www.overleaf.com/read/rypfvnxgpfxj

**截图**

![image](https://user-images.githubusercontent.com/15854830/114487047-7edaae00-9c41-11eb-807b-3ecf39c66e54.png)

![image](https://user-images.githubusercontent.com/15854830/114487695-a0886500-9c42-11eb-9251-533fa857fb51.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
我本地编译无法复现，但使用 Overleaf 确实出现了你提到的这个问题，让我研究下具体怎么解决

**Comment by TheNetAdmin** [comment]
简单测试了一下，如果不使用`\AtBeginEnvironment` 和 `\AtEndEnvironment`，直接插入 `\special` 的话应该就没有问题，我再测试一下如何修复

**Comment by TheNetAdmin** [comment]
我更新了一下代码，改用 `\appto` 和 `\preto` 来插入 `\special` 到浮动体的头尾，可以尝试一下新代码还有没有这个问题

**Comment by ZedongPeng** [comment]
嗯嗯，解决了，谢谢大佬
