### ISSUE TITLE
封面页长标题无法换行

### ISSUE THREAD

**Issue by Citing** [TheNetAdmin/zjuthesis#159]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [x] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.3

Degree:
  - [ ] graduate
    - [ ] master
    - [ ] doctor
  - [x] undergraduate

Major:
  - [x] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/6308772/zjuthesis.log)

## 遇到的问题
封面页中，毕业论文的标题长度超过单行长度，无法自动换行。

**截图**
<img width="610" alt="1" src="https://user-images.githubusercontent.com/36292994/114667643-49fa5400-9d32-11eb-87d5-ccbdff9596bc.png">

**其他信息**

**Comment by TheNetAdmin** [comment]
标题位于一个表格环境，最简单的解决方案是加一行表格，手动换行

https://github.com/TheNetAdmin/zjuthesis/issues/52#issuecomment-608995688
