### ISSUE TITLE
如何修改公式与文字之间的段落间距

### ISSUE THREAD

**Issue by ZedongPeng** [TheNetAdmin/zjuthesis#160]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [x] Overleaf

**TeX套件**

- [ ] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.3.3

Degree:
  - [x] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

我感觉模板中文字与公式之间的段落间距有点大，想调小一点。
查到可以用`\setlength\abovedisplayskip{1pt}`

我本来以为模版设置中已有相关参数的设置，只需要修改参数值，但好像没有找到。

想请教一下大佬，文字与公式段落间距的设置有什么操作建议吗？

**截图**

![image](https://user-images.githubusercontent.com/15854830/114915840-b0789280-9e56-11eb-8ea0-0a59043cc93c.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
代码给一份

**Comment by ZedongPeng** [comment]
重新检查了我的设置，是因为使用了align导致公式与文字之间的间距变大，如果换成equation，行距是没问题的。
Sorry

感谢大佬 @TheNetAdmin
