### ISSUE TITLE
CS模板英文标题过长时好像会出错

### ISSUE THREAD

**Issue by zy18051120439** [TheNetAdmin/zjuthesis#161]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：v7.0.1（v6.4.3也有此bug）

Degree:
  - [x] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/6325880/zjuthesis.log)

## 遇到的问题

主要问题：英文标题非常长的时候，在英文TITLE这边无法正常显示。
无伤大雅：中文标题无法居中。

**截图**

![U%V}~C%Q(U@VZT )SZ_XLFK](https://user-images.githubusercontent.com/14106965/115041045-ac0ab300-9f04-11eb-80fe-5059b6d93968.png)

**其他信息**

之前版本中，v6.4.3里，我在\page\graduate\master\cs\cover-eng里直接改英文TITLE，在cover-chn里改中文标题可以让它稍微居中。
![~O0`OTG%3BSC_9 QI{(Q9@S](https://user-images.githubusercontent.com/14106965/115041127-c2187380-9f04-11eb-921b-5da655560e95.png)
![W}L{U~3OBK(SJ0VU1F0`AZC](https://user-images.githubusercontent.com/14106965/115041215-d5c3da00-9f04-11eb-99a0-499642929976.png)

**Comment by zy18051120439** [comment]
英文标题我之前是这样改的。
![94)_VW@IE}48JL3PP(CJ (D](https://user-images.githubusercontent.com/14106965/115041573-3ce18e80-9f05-11eb-91a9-e8f3b6b48eee.png)

**Comment by TheNetAdmin** [comment]
什么是英文标题无法正常显示？具体什么问题？不能换行？没有空格？

**Comment by TheNetAdmin** [comment]
中文标题过长的时候就需要手动换行并居中，你中文标题的用法是对的

**Comment by zy18051120439** [comment]
> 什么是英文标题无法正常显示？具体什么问题？不能换行？没有空格？

是的，英文标题过长的时候就会不能换行，并且还把Autho、Supervisior这些挤下去了。

**Comment by TheNetAdmin** [comment]
标题都用了表格环境，换行需要手动添加一行表格。

https://github.com/TheNetAdmin/zjuthesis/issues/52

然后手动调整标题所在表格下方的垂直间距

https://github.com/TheNetAdmin/zjuthesis/blob/f12020e327f008c562537a15137ba1cb205cc99c/page/graduate/master/cs/cover-eng.tex#L29

**Comment by zy18051120439** [comment]
> 标题都用了表格环境，换行需要手动添加一行表格。
> 
> #52
> 
> 然后手动调整标题所在表格下方的垂直间距
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/f12020e327f008c562537a15137ba1cb205cc99c/page/graduate/master/cs/cover-eng.tex#L29

懂了，谢谢大佬。
大佬一直更新真的很好，之前的版本6.4.3还得自己手动去除空白页，去除完后我摘要的页眉还出bug了，结果v7.0.1都改了。
非常谢谢你，真的越更新越好。

**Comment by TheNetAdmin** [comment]
感谢支持！
