### ISSUE TITLE
subsection前后间距

### ISSUE THREAD

**Issue by zy18051120439** [TheNetAdmin/zjuthesis#162]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：v7.0.1

Degree:
  - [x] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/6326432/zjuthesis.log)

## 遇到的问题

在subsection的时候好像会遇到间距较大的问题。想问这是正常的吗，在之前使用6.4.3的时候没有注意过。

**截图**

用
![X~~L2W32LXMZ 9TKNH0MBW4](https://user-images.githubusercontent.com/14106965/115052385-766bc700-9f10-11eb-8374-6d0827b720d8.png)

![AGB QZ`HGK)IEYRA4LW9{7I](https://user-images.githubusercontent.com/14106965/115052393-78ce2100-9f10-11eb-927c-0acc8faab541.png)

**其他信息**

**Comment by zy18051120439** [comment]
图上3.2.4这一个subsection没有公式、图表，只有文字，但是与之前的间距似乎也较大？想问下是正常的吗。

**Comment by TheNetAdmin** [comment]
什么间距？subsection和页眉之间的垂直间距？

**Comment by zy18051120439** [comment]
> subsection和页眉之间的垂直间距？

和前一页的最后的文字的间距，前一页的文字最后有很多空白。是2张图，每张图都是跨页的。
我不清楚这是不是正常现象。
谢谢你。

**Comment by TheNetAdmin** [comment]
这种情况不需要手动调整，这个标题被放在新一页可能的原因是

如果放在上一页，那么上一页的空间只能容纳标题，不能容纳其后的正文，导致标题在上一页，正文在下一页，不太美观

**Comment by zy18051120439** [comment]
> 这种情况不需要手动调整，这个标题被放在新一页可能的原因是
> 
> 如果放在上一页，那么上一页的空间只能容纳标题，不能容纳其后的正文，导致标题在上一页，正文在下一页，不太美观

懂了，谢谢你。

**Comment by zy18051120439** [comment]
> 这种情况不需要手动调整，这个标题被放在新一页可能的原因是
> 
> 如果放在上一页，那么上一页的空间只能容纳标题，不能容纳其后的正文，导致标题在上一页，正文在下一页，不太美观

我后来还遇到了这样的情况。
![H3NPCN(SYV(2O)JZ2RDK{WI](https://user-images.githubusercontent.com/14106965/115101992-ec0c7d00-9f7a-11eb-9890-890fd182035d.png)
上图是v7.0.1的，多了一行“测试一下！”语句。
![P%(I`J35 OZX `QQ00R$ GB](https://user-images.githubusercontent.com/14106965/115102002-fc245c80-9f7a-11eb-9453-c80581ad8d1e.png)
上图是v7.0.1的。就感觉还是空白太多。
![6G4EZ5VUTQ@Z@`M H_~3YUE](https://user-images.githubusercontent.com/14106965/115102010-05152e00-9f7b-11eb-8f81-05a021f46d91.png)
上图是用v6.4.3编译的。好像把空白从页底放到了和图之间。
实际上肯定因为会写内容，不太会遇到这么大的空白，但是想问一下，如果要手动调的话有方法吗。

**Comment by TheNetAdmin** [comment]
没看懂你要调哪里，图上标一下你要的效果

**Comment by zy18051120439** [comment]
> 没看懂你要调哪里，图上标一下你要的效果

![4C52D~$~LI2WY9H`4%1W1B](https://user-images.githubusercontent.com/14106965/115102409-30991800-9f7d-11eb-9f16-890b439ea34a.png)
想问可以手动调整让这部分往前移一些吗，不一定是框选的全部。

**Comment by TheNetAdmin** [comment]
按理说你这里4.3.2里写上内容之后就有可能会被调整上去，看样子你这里还没写，我建议先写完内容再调整这些

**Comment by zy18051120439** [comment]
> 按理说你这里4.3.2里写上内容之后就有可能会被调整上去，看样子你这里还没写，我建议先写完内容再调整这些

好的，谢谢大佬。
