### ISSUE TITLE
奇偶页页眉没有区分

### ISSUE THREAD

**Issue by PanLiang0525** [TheNetAdmin/zjuthesis#166]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.3

Degree:
  - [x] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/6331124/zjuthesis.log)

## 遇到的问题

论文奇偶页页眉一样，都如下图所示。
**代码**

```TeX
% 可以重现你遇到的问题的代码
% 可使用多个代码框，分别填写不同文件内的代码
% 注明代码所在文件
```

**截图**

![image](https://user-images.githubusercontent.com/64391436/115143825-1eea6a00-a07c-11eb-9953-fa4334791868.png)

**其他信息**

C:\Users\dell>latexmk --version

Latexmk, John Collins, 26 Dec. 2019. Version 4.67

C:\Users\dell>xelatex --version
XeTeX 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX)
kpathsea version 6.3.2
Copyright 2020 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 65.1; using 65.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.10.1; using 2.10.1
Compiled with Graphite2 version 1.3.13; using 1.3.13
Compiled with HarfBuzz version 2.6.4; using 2.6.4
Compiled with libpng version 1.6.37; using 1.6.37
Compiled with poppler version 0.68.0
Compiled with fontconfig version 2.13.92; using 2.13.92

**Comment by TheNetAdmin** [comment]
研究生院规定的

![image](https://user-images.githubusercontent.com/18525442/115159084-46bedb00-a046-11eb-8b9e-bfb091133e63.png)

https://github.com/TheNetAdmin/zjuthesis/files/5784225/2016-grad-rules.pdf

**Comment by TheNetAdmin** [comment]
另

https://github.com/TheNetAdmin/zjuthesis/discussions/144#discussioncomment-439619

**Comment by PanLiang0525** [comment]
> 另
> 
> [#144 (reply in thread)](https://github.com/TheNetAdmin/zjuthesis/discussions/144#discussioncomment-4396SHIFE
非常感谢！！！！！！！
