### ISSUE TITLE
在线查重乱码

### ISSUE THREAD

**Issue by Kyfafyd** [TheNetAdmin/zjuthesis#168]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.0-rc1

Degree:
  - [ ] graduate
    - [ ] master
    - [ ] doctor
  - [x] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [x] isee
  - [ ] math
  - [ ] physics

**编译日志**
[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/6409426/zjuthesis.log)

## 遇到的问题

按照之前issue https://github.com/TheNetAdmin/zjuthesis/issues/14 里说的问题都试过了，但是在查重时候还是会乱码，显示重复率0%

**代码**

```TeX
% 可以重现你遇到的问题的代码
% 可使用多个代码框，分别填写不同文件内的代码
% 注明代码所在文件
```

**截图**

**其他信息**

**Comment by Kyfafyd** [comment]
已解决。
latex编译出来的pdf直接用于查重就不会乱码，不能用mac再编辑它。

**Comment by TheNetAdmin** [comment]
非常感谢你的尝试与分享，查重问题一直很少有人在这里讲解经验，我已经将这个问题更新到 #14 中
