### ISSUE TITLE
关于目录显示格式的一些问题

### ISSUE THREAD

**Issue by Kyfafyd** [TheNetAdmin/zjuthesis#169]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.0-rc1

Degree:
  - [ ] graduate
    - [ ] master
    - [ ] doctor
  - [x] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [x] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

**第一个问题**
<img width="390" alt="Screen Shot 2021-05-09 at 2 14 48 PM" src="https://user-images.githubusercontent.com/42490513/117562352-eb29bf80-b0d0-11eb-9980-217944933988.png">
比如上图目录中，怎么让这两项页码不显示在目录中

**第二个问题**
<img width="397" alt="Screen Shot 2021-05-09 at 2 19 23 PM" src="https://user-images.githubusercontent.com/42490513/117562445-8fac0180-b0d1-11eb-83a8-7c65c3f55003.png">
由于最终版毕业论文目录模版是开题报告的部分只显示chapter级的，怎么让开题报告（第二部分）的只显示chapter，同时还要保证第一部分显示到subsubsection（显示到subsubsection已经解决了，chapter那个还没解决）

**第三个问题**
怎么在开题报告（第二部分）目录一开始显示一行目录是 “指导教师对文献综述和开题报告具体内容要求”，同样和第一个问题一样，不显示页码。

**代码**

```TeX
% 可以重现你遇到的问题的代码
% 可使用多个代码框，分别填写不同文件内的代码
% 注明代码所在文件
```

**截图**

**其他信息**

**Comment by TheNetAdmin** [comment]
#29

**Comment by TheNetAdmin** [comment]
#68

**Comment by TheNetAdmin** [comment]
如果只改第二部分的目录层级，可以尝试把 #68 提到的代码插入到该目录对应的 `toc.tex` 文件

**Comment by Kyfafyd** [comment]
我尝试了 #29 和 #68 的操作，目录显示深度到subsubsection这个已经解决了。
但是目录里怎么让某一项不显示他的页码呢？因为我看 #29 的实现还是会在目录显示页码

**Comment by Kyfafyd** [comment]
> 如果只改第二部分的目录层级，可以尝试把 #68 提到的代码插入到该目录对应的 `toc.tex` 文件

这个插入到第二部分开题报告的 `toc.tex` 里面之后好像没用。`zjuthesis.tex`里没有 \inputpage{proposal/toc.tex}

**Comment by TheNetAdmin** [comment]
你这几个需求都比较特殊，去研究下 tocloft 宏包的文档吧，模板用了这个包来生成目录

**Comment by Kyfafyd** [comment]
关于目录里部分不显示页码的问题，可以通过以下方式解决：
```latex
\addtocontents{toc}{\cftpagenumbersoff{section}}
\inputpage{final/post}
\addtocontents{toc}{\cftpagenumberson{section}}
```

**Comment by TheNetAdmin** [comment]
NICE JOB

**Comment by Kyfafyd** [comment]
> 之前没看到还有第三个问题……
> 
> 可以在 “指导教师要求” 那一页加上这一行试试
> 
> ```
> \addcontentsline{toc}{chapter}{指导教师对文献综述和开题报告具体内容要求}
> ```

这个解决啦，谢谢

**Comment by TheNetAdmin** [comment]
关于第二个问题，我查了一些解决方案，然后添加了一个命令 `\changelocaltocdepth`

现在可以在这里

https://github.com/TheNetAdmin/zjuthesis/blob/f58f9ff2b54d6014bbfc2aeb42ee7943bbe784d4/zjuthesis.tex#L72-L74

插入该命令，例如

```TeX
% Proposal part
\changelocaltocdepth{0}
\renewcommand{\undergradcurrstage}{proposal}
\newrefsection
```

即可将开题报告部分的目录层级减少为 chapter 级别

![image](https://user-images.githubusercontent.com/18525442/119208766-70f62500-ba58-11eb-83df-3ae896f1dff0.png)

一个问题是 pdf bookmark 里，最终文档部分的层级也跟着改变了，但 pdf 内目录是正确的，所以应该影响不大

**Comment by Shanque469636** [comment]
> > 如果只改第二部分的目录层级，可以尝试把 [#68](https://github.com/TheNetAdmin/zjuthesis/issues/68) 提到的代码插入到该目录对应的 `toc.tex` 文件
> 
> 这个插入到第二部分开题报告的 `toc.tex` 里面之后好像没用。`zjuthesis.tex`里没有 \inputpage{proposal/toc.tex}

你好，请问开题报告部分该如何插入目录呢
