### ISSUE TITLE
关于目录

### ISSUE THREAD

**Issue by kii-chan-iine** [TheNetAdmin/zjuthesis#17]
请问
1. 目录怎么做到有深度呀，为什么调节tocdepth没有效果？
2. listoffigures 和 listoftables前面怎么设置才能以这样的方式： 图 1-1，而不是只有数字?

谢谢您！

**Comment by TheNetAdmin** [comment]
你可以给一份MWE吗？

**Comment by TheNetAdmin** [comment]
tocdepth应该在config/format/general/layout.tex里调节。
但这个设置可能会被专业模板覆盖，可以检查一下你使用的专业模板的设置

**Comment by TheNetAdmin** [comment]
listoffigures 和 listoftables 前面加 “图” “表” 是学校要求的么，是的话我可以直接加到模板里，不是的话我可以在这里讲一下怎么修改。

**Comment by kii-chan-iine** [comment]
关于添加“图”“表”的问题，我随便搜了几个学院的是有要求的（不确定是否全部这样）。麻烦您也在这里讲一下吧，这样我们也可以学习一下~thx~

目录深度的话，我使用的graduate的通用模板，我感觉也是被其他设置覆盖了，但苦于没有找到地方。如果您发现了，也麻烦您教一下，谢谢！

**Comment by TheNetAdmin** [comment]
你的zjuthesis.tex文件贴一下

**Comment by TheNetAdmin** [comment]
我刚试了一下docdepth是有效的，我不知道你改了什么或者想改成什么样，这个暂时没法帮你

**Comment by TheNetAdmin** [comment]
图表标题已经改好了

**Comment by kii-chan-iine** [comment]
谢谢您！目录的问题我没表述清楚，我是想问我该如何调，使得目录不同深度的左间距不一样。
我尝试用titletoc包调节，但是用了这个包图表标题又消失了。我想要类似以下的效果
1 绪论
&ensp; &ensp;1.1 节标题
&ensp;&ensp;&ensp;&ensp;         1.1.1 小节标题

**Comment by kii-chan-iine** [comment]
zjuthesis.tex我是用的下载下来的文档，没有改动。

**Comment by TheNetAdmin** [comment]
> 谢谢您！目录的问题我没表述清楚，我是想问我该如何调，使得目录不同深度的左间距不一样。
> 我尝试用titletoc包调节，但是用了这个包图表标题又消失了。我想要类似以下的效果
> 1 绪论
>    1.1 节标题
>      1.1.1 小节标题
> 烦请您指点下，谢谢！

哦这个简单，参考本科生模板的设置，代码在这里：
https://github.com/TheNetAdmin/zjuthesis/blob/b65c097af06e8026c8b867886be0ac1c3b84d5bb/config/format/general/layout.tex#L151-L157
具体效果可以看样例文件里的本科生模板pdf。

不要用`titletoc`，因为这个模板已经用了`tocloft`包了，只要按照上述代码设置就行。

官方模板没有目录项的左侧间距，所以我特地调整过的。

**Comment by TheNetAdmin** [comment]
如果问题已解决，请记得关闭此issue

**Comment by kii-chan-iine** [comment]
谢谢！
