### ISSUE TITLE
一些格式的bug

### ISSUE THREAD

**Issue by Kyfafyd** [TheNetAdmin/zjuthesis#170]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.0-rc1

Degree:
  - [ ] graduate
    - [ ] master
    - [ ] doctor
  - [x] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [x] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

**第一个问题**
毕业论文最终版目录页码应该是从`IX`开始，我用的版本`6.4.0-rc1`目录页码从 `I` 重新开始了。然后我试了一下最新的`7.0.1`版本也是这个问题。
<img width="498" alt="Screen Shot 2021-05-10 at 4 02 02 PM" src="https://user-images.githubusercontent.com/42490513/117625860-1089fc80-b1a9-11eb-90b2-7ffd66b9857e.png">

**第二个问题**
毕业论文正文绪论开始那一页页码不对，`6.4.0-rc1`和`7.0.1`都有这个问题。
<img width="567" alt="Screen Shot 2021-05-10 at 4 15 10 PM" src="https://user-images.githubusercontent.com/42490513/117627593-e5a0a800-b1aa-11eb-86b4-6e87157a833c.png">
```latex
\bodystyle
\cleardoublepage
\ifthenelse{\equal{\Type}{design}}
    {\part{毕业设计}}
    {\part{毕业论文（设计）}}
        
\inputbody{final/content}
```
上面代码改成这样就解决了
```latex
\coverstyle
\cleardoublepage
\ifthenelse{\equal{\Type}{design}}
    {\part{毕业设计}}
    {\part{毕业论文（设计）}}
        
\bodystyle
\inputbody{final/content}
```

第一个问题还没解决，求助！

**Comment by TheNetAdmin** [comment]
第一个问题可以把这一行去掉试试

https://github.com/TheNetAdmin/zjuthesis/blob/1ea6cfc95dc2de3061cd9921e97bc31f580fa980/page/undergraduate/final/toc.tex#L3

有些学院的模板的目录页是从 `I` 开始的

**Comment by TheNetAdmin** [comment]
第二个问题确实存在，我过几天更新一下修复代码，感谢指出

**Comment by Kyfafyd** [comment]
> 第一个问题可以把这一行去掉试试
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/1ea6cfc95dc2de3061cd9921e97bc31f580fa980/page/undergraduate/final/toc.tex#L3
> 
> 有些学院的模板的目录页是从 `I` 开始的
我看了我现在用的`6.4.0-rc1`版本本来就没有这一行代码。
我用release的这个版本最原始的代码编译了一下出来目录这一页也存在这个问题。

`7.0.1`去掉这行代码确实目录这一页就变成`IX`开始了。

请问之前是修改了哪里呢？我们学院要求是`IX`开始

**Comment by TheNetAdmin** [comment]
把这里

https://github.com/TheNetAdmin/zjuthesis/blob/0a265489c729fa72bedc12d0f7d498b313fa9e31/config/format/general/layout.tex#L38-L39

改成这样呢

https://github.com/TheNetAdmin/zjuthesis/blob/f3a5fa043d57058fef041920e05a62e747a338bf/config/format/general/layout.tex#L38

**Comment by Kyfafyd** [comment]
解决了
