### ISSUE TITLE
Mac系统使用texstudio，CTex-fontset和fontspec.sty报错

### ISSUE THREAD

**Issue by Yancy7** [TheNetAdmin/zjuthesis#18]
你好，不是很清楚texlive、texstudio和XeTex之类有什么区别，我之前一直是用TexStudio来编辑的，macOS系统。跑这个模板时报错。是不是要换一个编辑器才行？盼能指点解决方法，谢谢！
![image](https://user-images.githubusercontent.com/25807072/64502057-a4c9ff00-d2f6-11e9-9776-17e6018a224d.png)

**Comment by TheNetAdmin** [comment]
看图里第二行写了 cannot-use-pdflatex，说明你的TexStudio在用pdflatex，改成xelatex应该就好了。

**Comment by TheNetAdmin** [comment]
我没用过mac所以不太清楚应该装什么tex套件，但mac上的套件应该是会带XeTeX的

**Comment by TheNetAdmin** [comment]
我个人习惯使用TexLive+vscode，你可以查一下mac怎么用vscode设置Tex工程。我以前也用过TexStudio，后面觉得太难看了就换掉了……

**Comment by Yancy7** [comment]
感谢！已解决。网上查了一下，出现上述错误是由于：模板是采用xeLatex进行编译的，但是texstudio的默认编译方式为pdfLatex。需要对设置进行修改，才能使我们的文件编译通过，mac系统中的具体的步骤见图：
![image](https://user-images.githubusercontent.com/25807072/64502443-ba402880-d2f8-11e9-8aa2-bffed5924079.png)
修改好后运行发现生成pdf错误，可能是由于文件夹名含有中文的缘故？然后我换了个纯英文的位置就可以运行了。
同时，粗看了一下发现，和控制学院的格式要求有一些地方不一样（其他学院同学也先注意大致看一下吧），比如图片标题图xx后面是空格，而模板给的是冒号，不知道怎么改0-0…每次遇到问题都去百度也不是办法…有点担心之后如果还遇到类似问题，改latex花的时间可能比直接用word还多，所以大家可以权衡一下呀。
还是要感谢作者的辛劳付出，这个latex还是做得很棒的，相信大部分学院的论文主要部分都用得上。

**Comment by TheNetAdmin** [comment]
> 感谢！已解决。网上查了一下，出现上述错误是由于：模板是采用xeLatex进行编译的，但是texstudio的默认编译方式为pdfLatex。需要对设置进行修改，才能使我们的文件编译通过，mac系统中的具体的步骤见图：（在偏好设置里面，build，complile，改为xeLatex）
> ![image](https://user-images.githubusercontent.com/25807072/64502443-ba402880-d2f8-11e9-8aa2-bffed5924079.png)
> 修改好后运行发现生成pdf错误，可能是由于文件夹名含有中文的缘故？然后我换了个纯英文的位置就可以运行了。
> 同时，粗看了一下发现，和控制学院的格式要求有一些地方不一样（其他学院同学也先注意大致看一下吧），比如图片标题图xx后面是空格，而模板给的是冒号，不知道怎么改0-0…每次遇到问题都去百度也不是办法…有点担心之后如果还遇到类似问题，改latex花的时间可能比直接用word还多，所以大家可以权衡一下呀。
> 还是要感谢作者的辛劳付出，这个latex还是做得很棒的，相信大部分学院的论文主要部分都用得上。

如果有时间的话，可否总结一些和你们模板有出入的地方呢？
这样我就可以帮你们修改到模板里，不需要大家自行修改了。

我不是从控制学院毕业的所以不清楚具体要求，以前也有同学基于这个模板二次开发，然后把修改贡献到了这个模板。

如果你不熟悉GitHub和LaTeX的话，可否列出要求我来实现呢？

**Comment by TheNetAdmin** [comment]
@Yancy7 如果有空整理一下具体要求的话，请新开一个issue，这个issue先关掉了
