### ISSUE TITLE
Listoffigures中英文

### ISSUE THREAD

**Issue by kii-chan-iine** [TheNetAdmin/zjuthesis#180]
您好，我用以下的方式为图表添加了中英文caption，但是我们的listoffigures中需要只是中文的（目前是一个中文一个英文交替来），请问我该如何设置呀？
\begin{figure}[htb]
    \centering
    \includegraphics[width=5in]{./figure/chap_0/metabolites.png}
    \caption{中文。}

    \addtocounter{figure}{-1}
    \vspace{-5pt}
    \renewcommand{\figurename}{Figure}
    \caption{English.}

    \label{fig:chap0:metab}
\end{figure}

**Comment by TheNetAdmin** [comment]
把issue模板信息填写全，重开一个
