### ISSUE TITLE
图的caption包含中英文而图标清单中如何只保留中文？

### ISSUE THREAD

**Issue by kii-chan-iine** [TheNetAdmin/zjuthesis#181]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：7.1.1

Degree:
  - [x] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

无错误
## 遇到的问题

图表目录如何只保留中文
**代码**

```TeX
\begin{figure}[htb]
\centering
\includegraphics[width=5in]{./figure/chap_0/metab.png}
\caption{中文。}

\addtocounter{figure}{-1}
\vspace{-5pt}
\renewcommand{\figurename}{Figure}
\caption{English.}

\label{fig:chap0:metab}
\end{figure}
```

**截图**

![image](https://user-images.githubusercontent.com/17940410/119793441-2ddcfb80-bf09-11eb-8dcc-5a315032ebeb.png)
这里我想只保留中文
**其他信息**

**Comment by TheNetAdmin** [comment]
你这里figure有两个caption是要实现什么效果？一般只用一个。

**Comment by TheNetAdmin** [comment]
另外不要在figure环境使用格式设定代码，比如这里的renewcommand，格式设定都放在config目录下

**Comment by kii-chan-iine** [comment]
两个是想实现一个中文一个英文，但是我在图清单中只保留中文的

**Comment by kii-chan-iine** [comment]
![image](https://user-images.githubusercontent.com/17940410/119797344-b8732a00-bf0c-11eb-9174-992b34aa5eb2.png)
图片下面实现类似这样的效果

**Comment by kii-chan-iine** [comment]
如果不在figure下使用的话，请问您知道有什么其他方法可以实现以上的效果么？谢谢！

**Comment by TheNetAdmin** [comment]
这个格式需求我还是第一次碰到……我这两天看一下有什么办法

**Comment by kii-chan-iine** [comment]
谢谢！

**Comment by muzimuzhi** [comment]
宏包 `bicaption` 提供了浮动体双语标题的功能，它的宏包选项 `list=off` 可用来不把第二语言的标题加入 `\listoftables`。

**完整例子**
在导言区加入
```tex
\usepackage[list=off]{bicaption}
\DeclareCaptionOption{bi-second}[]{%
    \def\tablename{Table}%
    \def\figurename{Figure}%
}
\captionsetup[bi-second]{bi-second}
```
在正文中使用
```tex
\begin{figure}
  \centering
  \includegraphics{example-image}
  \bicaption{中文}{English}
\end{figure}
```
输出效果
![image](https://user-images.githubusercontent.com/6376638/119912214-940b6200-bf8d-11eb-981d-1c01bc9ab07c.png)
![image](https://user-images.githubusercontent.com/6376638/119912235-a1285100-bf8d-11eb-8c06-2e35282ff8f3.png)

**参考信息**
 - `ucasthesis` 中的[相关代码](https://github.com/mohuangrui/ucasthesis/blob/585bf6d947091238d8fde5a8802d58e9c1b62b36/Style/artratex.sty#L535-L542)
 - `caption` 和 `bicaption` 的宏包文档

**Comment by TheNetAdmin** [comment]
问题应该已经解决，感谢@muzimuzhi 帮忙解答，相关代码后续我会加到模板里

**Comment by kii-chan-iine** [comment]
谢谢！

**Comment by shangxiafeng** [comment]
您好~想问问如果引用图的标号 x.x错误应该怎么办呢？
此外还想问一下应该如何自定义 图 x.x勒？   比如设置成 图 1 图 2 图 3 而不是根据当前的标题级数引用
![image](https://user-images.githubusercontent.com/69114522/141458137-f1ae1c84-2fc2-4aed-845e-1264f9ed7b4c.png)

**Comment by muzimuzhi** [comment]
@shangxiafeng 新问题，请发新 issue
