### ISSUE TITLE
公式前后间距过大

### ISSUE THREAD

**Issue by dewe001** [TheNetAdmin/zjuthesis#184]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：7.1.1

Degree:
  - [ ] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/6635452/zjuthesis.log)

## 遇到的问题

答辩专家指出，公式与前后行文字间距过大。单个公式时感知不明显，但两相邻公式间空白很明显。
设置均为默认，不知该如何修改？
**代码**

content文件中代码：

```TeX
前文前文前文前文前文前文前文前文前文前文前文前文前文前文如下
\begin{equation}
	\bm{C}_i=[x_{i,1},x_{i,2},\dots,x_{i,r},y_{i,1},y_{i,2},\dots,y_{i,r}]^T.
\end{equation}
\begin{equation}
	\bm{C}_i=[x_{i,1},x_{i,2},\dots,x_{i,r},y_{i,1},y_{i,2},\dots,y_{i,r}]^T.
\end{equation}
其中，后文后文后文后文后文后文后文后文后文后文后文后文后文后文
```

**截图**

 ![1623379613(1)](https://user-images.githubusercontent.com/22814237/121623542-74eaf500-caa2-11eb-9acd-b3fa95acf394.jpg)
![image](https://user-images.githubusercontent.com/22814237/121623600-951ab400-caa2-11eb-938c-dfcf67415fcd.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
你的公式是怎么写的，给一段可以重现截图效果的样例 TeX 代码我看下

**Comment by dewe001** [comment]
> 你的公式是怎么写的，给一段可以重现截图效果的样例 TeX 代码我看下

已更新在问题中

**Comment by muzimuzhi** [comment]
用 `amsmath` 宏包提供的多行公式环境，不要一个公式一个 `equation` 环境。

```tex
\begin{align}
	\bm{C}_i &= [x_{i,1},x_{i,2},\dots,x_{i,r},y_{i,1},y_{i,2},\dots,y_{i,r}]^T, \\
	\bm{C}_i &= [x_{i,1},x_{i,2},\dots,x_{i,r},y_{i,1},y_{i,2},\dots,y_{i,r}]^T.
\end{align}
```

**Comment by dewe001** [comment]
> 用 `amsmath` 宏包提供的多行公式环境，不要一个公式一个 `equation` 环境。
> 
> ```
> \begin{align}
> 	\bm{C}_i &= [x_{i,1},x_{i,2},\dots,x_{i,r},y_{i,1},y_{i,2},\dots,y_{i,r}]^T, \\
> 	\bm{C}_i &= [x_{i,1},x_{i,2},\dots,x_{i,r},y_{i,1},y_{i,2},\dots,y_{i,r}]^T.
> \end{align}
> ```

有时可以，但有时需要一个公式一个编号

**Comment by muzimuzhi** [comment]
`align` 环境，就是一个公式一个编号。请实际运行一下，试一试。常见的多行公式编号需求，`amsmath` 包都能满足。

**Comment by TheNetAdmin** [comment]
我可以提供一个比较土的办法，直接用 `\vspace{}`，并给定一个负数值，比如 `\vspace{-20pt}`，插入到你两个公式环境之间。

如果问题不是特别频繁，只需要一个临时的修改措施，可以这么搞。（我自己写 paper 时临近 ddl 就会这么压缩页数）

**Comment by dewe001** [comment]
> `align` 环境，就是一个公式一个编号。新问题可以提供具体例子，具体讨论。

确实有用，感谢！

**Comment by dewe001** [comment]
> 我可以提供一个比较土的办法，直接用 `\vspace{}`，并给定一个负数值，比如 `\vspace{-20pt}`，插入到你两个公式环境之间。
> 
> 如果问题不是特别频繁，只需要一个临时的修改措施，可以这么搞。（我自己写 paper 时临近 ddl 就会这么压缩页数）

这个可以解决单个公式与前后文间距过大的问题，感谢！

**Comment by leesurelye** [comment]
```
\setlength\abovedisplayskip{1.5pt}
\setlength\belowdisplayskip{1.5pt}
```
使用这两个指令修改
