### ISSUE TITLE
目录页编码如何延续前页而不重新从1开始

### ISSUE THREAD

**Issue by Phantom-eva** [TheNetAdmin/zjuthesis#185]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：6.4.3

Degree:
  - [ ] graduate
    - [ ] master
    - [ ] doctor
  - [x] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [x] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

目录页编码为1,2，但学院要求正文body以前的内容页全部统一编码。

**代码**

```TeX
% 可以重现你遇到的问题的代码
% 可使用多个代码框，分别填写不同文件内的代码
% 注明代码所在文件
```

**截图**
![issue1](https://user-images.githubusercontent.com/47131826/121657096-19067900-ca6e-11eb-883a-e7762109596c.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
把这行注释掉试试

https://github.com/TheNetAdmin/zjuthesis/blob/9bc22e244dbd999271372af7b3fcccfbc602a09e/page/undergraduate/final/toc.tex#L3
