### ISSUE TITLE
图片和文字重叠

### ISSUE THREAD

**Issue by xlelephant** [TheNetAdmin/zjuthesis#186]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [x] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [ ] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [x] MikTex

**TeX Compiler**

- [ ] XeTeX
- [x] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [ ] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [x] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/6660986/zjuthesis.log)

## 遇到的问题
图片和文字是重合的，如论怎么设置figure的参数。

**代码**

```TeX
\begin{figure}[]
    \centering
    \includegraphics[width=.2\linewidth]{tf_diagram}
    \caption{FPGA的构成}
    \label{fig:mc_FPGA}
\end{figure}
```

**截图**

![image](https://user-images.githubusercontent.com/50734064/122175474-4a3fd880-ceb6-11eb-9a04-51c871a4c7f0.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
给一个完整的代码样例

**Comment by TheNetAdmin** [comment]
信息不足，如有问题请补充信息并重开此 issue

**Comment by linlinge** [comment]
我把编译器从LualaTex改到XeLaTeX就好了
