### ISSUE TITLE
封面学院过长无法一行显示问题

### ISSUE THREAD

**Issue by xfz329** [TheNetAdmin/zjuthesis#188]
## 可改进的内容

作者你好！我在使用你的博士论文模板时，也遇到了学院名过长无法一行显示的现象。自己摸索了下，已经修复。我在想以何种方式提交修复给你。

## 代码与步骤

1. 直接修改学院信息所在表格的整体宽度，视情况增加一定数值即可。此方式不需改动代码。在首页FAQ增加信息即可。
2. 参考定义双行标题、定义双行学院名。但由于表格增加一栏，为能在A4页面完整显示提交日期，需要相应对其他部分（如zju logo等）进行空间压缩。（但压缩哪些部分，压缩多少可能需要确定。）
烦请作者回复指教。

**Comment by TheNetAdmin** [comment]
如果提PR修复的话我倾向于双行的方式，因为

1. 这样不会破坏现有格式，即正在使用单行学院的同学不会看到封面表格宽度变化
2. 表格宽度改动比较直接，可能很多用户已经会改了
3. 双行功能更实用，例如某个学院名称长度超过整个页面宽度，那就必须使用多行了

双行封面的空白可以调整 `\vskip` 的数值，并加上判断条件，确保使用单行的同学不会看到格式变化。尽可能不要改动 LOGO 大小与文字字号。

这只是我个人的看法，如果你也有其他想法可以在这里继续讨论

另外非常感谢你对本项目的支持和贡献

**Comment by xfz329** [comment]
好的。我会尽快提交我的pr

**Comment by xfz329** [comment]
我已经进行了pr提交，并在以下论文设置下测试。如有遗漏之处，还请作者补充测试。
![1](https://user-images.githubusercontent.com/48663326/125426245-836be7c8-f3b1-4381-adba-7cba569e5460.png)

**Comment by xfz329** [comment]
我已经进行了pr提交，并在以下论文设置下测试。如有遗漏之处，还请作者补充测试。
![1](https://user-images.githubusercontent.com/48663326/125427673-f02ec8f1-5f05-4073-92e0-0fcb74ec08f1.png)

**Comment by xfz329** [comment]
发现我的pr没有听过自动化`pdf-diff`脚本测试，找了下应该是这里的原因[#103 ](https://github.com/TheNetAdmin/zjuthesis/issues/103)。
不过本身封面的大改动能通过才怪了，哈哈。
学习了，辛苦作者人工裁定了。
