### ISSUE TITLE
同时使用封面双栏中英文标题所引起的英文标题行距过大的问题

### ISSUE THREAD

**Issue by wang19950602** [TheNetAdmin/zjuthesis#193]
## 可改进的内容

在同时使用\titletwolines{}和\titleengtwolines{}这两个命令以实现封面中英文标题分行的时候，出现了英文标题的两行之间行距过大的问题，导致本应出现在封面的申请人姓名等信息被挤到了下一页，若能将英文标题的行距改为正常则更好。

## 代码与步骤

\documentclass[
    % Debugging Settings
    PrintFilePath   = false,            % print tex file path for each page
    % Layout Settings
    TwoSide         = true,             % set to false if don't need empty pages
    % Thesis Info
    StudentName     = name,
    StudentID       = ID,
    AdvisorName     = advisor,
    Grade           = 2021,            % only the year, no '级'
    Major           = EE,
    Department      = EE,
    SubmitDate      = 递交日期,
    MajorFormat     = general,
    Degree          = graduate,   % 'undergraduate' or 'graduate'
    Type            = thesis,          % 'thesis'   or 'design'
    Period          = final,           % 'proposal' or 'final'
    BlindReview     = false,           % 'false'    or 'true'
    Language        = chinese,         % 'chinese'  or 'english'
    % Graduate Thesis Info
    GradLevel       = doctor,          % 'master' or 'doctor'
    Topic           = robot,
    ColaboratorName = col,
    % Title
    Title           = 这是一个完整的中文标题,
    TitleEng        = {{这是一个完整的英文标题}}
]{zjuthesis}

%% Uncomment the following lines if you need multi line titles on cover pages
\titletwolines{这是一个完整的中文标题的前半部分}{这是一个完整的中文标题的后半部分}
\titleengtwolines{This is the first part of an English title}{This is the second part of an English title}

## 预期结果

希望在中英文标题都分两行的情况下，英文标题的行距不要过大，使得申请人姓名等信息能够出现在封面。

**Comment by TheNetAdmin** [comment]
看了一下，似乎和双行没有必然联系，根本原因应该是每一行的文字太长了，超出了该行的宽度。

调整封面的标题宽度可解，修改这里

https://github.com/TheNetAdmin/zjuthesis/blob/79bbf3e4589e4d3a367513eef8b3e730f646aa73/page/graduate/cover-chn.tex#L55

改成这样

```LaTeX
    \begin{tabularx}{\textwidth}{>{\fangsong}l X<{\centering}}
```

即 `.8\textwidth` 改成 `\textwidth`

![image](https://user-images.githubusercontent.com/18525442/132812946-416418fa-0fba-470a-ae3b-a9030c621997.png)

**Comment by wang19950602** [comment]
按您说的改了之后可以了，谢谢！

**Comment by Dayrker** [comment]
刚遇到这个问题，也被完美解决了！感谢！

**Comment by wang19950602** [comment]
您好，我已收到您的邮件，会尽快给您回信，谢谢！

**Comment by zhaohyin** [comment]
如果英文标题超过了两行，如何添加第三行？

**Comment by wang19950602** [comment]
您好，我已收到您的邮件，会尽快给您回信，谢谢！
