### ISSUE TITLE
编译后致谢部分全乱码问题

### ISSUE THREAD

**Issue by wang19950602** [TheNetAdmin/zjuthesis#196]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。
-->

**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [ ] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [x] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：8.0.0

Degree:
  - [x] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/7315591/zjuthesis.log)

## 遇到的问题

您好，我在编译论文时出现了论文致谢部分全部乱码的问题，但同样是使用\cleardoublepage和\chapternonum{}命令的摘要部分则可以编译成功并正确显示，请问这一问题如何解决，谢谢！

**代码**

```TeX
% 可以重现你遇到的问题的代码
% 可使用多个代码框，分别填写不同文件内的代码
% 注明代码所在文件
acknowledgement.tex文件的代码如下所示：

\cleardoublepage
\chapternonum{致谢}
光阴荏苒，岁月如梭……
```

**截图**

![乱码问题](https://user-images.githubusercontent.com/32090473/136658604-e7af2d1b-8ff6-4f67-b695-aabb829245d7.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
你的log里已经显示了编码问题。把 acknowledgement.tex转换成UTF-8编码，然后重新编译

![Screenshot_20211009-114004.png](https://user-images.githubusercontent.com/18525442/136670457-ba1f3e91-84b3-4b60-a11d-866926adf61a.png)

**Comment by wang19950602** [comment]
已解决，谢谢！
