### ISSUE TITLE
关于 latexmk 失败与在 vscode 下的使用问题

### ISSUE THREAD

**Issue by Zardinality** [TheNetAdmin/zjuthesis#2]
非常漂亮的工作！
我在使用时出现了一些问题：
* 按照 `README` 中说的，直接在根目录运行 `latexmk -xelatex -outdir=out zjutheis` 提示 `could not find file [zjuthesis] `， 如图：
![image](https://user-images.githubusercontent.com/13702822/39861247-9543d28a-5472-11e8-8156-4c4883274083.png)
* 我注意到你的 `.gitignore` 里有关于 vscode 的条目，请问你是在用 vscode 与 latex-workshop 在写作吗？如果是的话，能分享一下 recipe 吗（如果第一个问题没有得以解决）？

```
$ xelatex --version
XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017)
kpathsea version 6.2.3
```

**Comment by TheNetAdmin** [comment]
我看到你这里有个`missfont.log`，这个是STSong字体在当前环境下找不到会产生的文件，你可以先尝试从Windows复制STSong字体文件，安装到当前环境，再尝试编译一次呢？

**Comment by Zardinality** [comment]
@TheNetAdmin 这个 log 是我用自己之前的 recipe 运行时生成的。我的 OSX 下其实有仿宋和宋体，但是名字有所不同，分别是 `FangSong_GB2312-Regular` 和 `SimHei-Regular` ，我不知道在哪里可以设置一下这两个名称。
另外，我发现 latexmk 那条命令在我的终端里其实不用加最后的 `zjuthesis` ，直接运行即可。

**Comment by TheNetAdmin** [comment]
设置字体在`config/format/general/font`和`config/format/专业简称/font`下，后者会覆盖前者

**Comment by Zardinality** [comment]
问题解决，关闭此 issue 。
