### ISSUE TITLE
[BUG]表格自动编号问题

### ISSUE THREAD

**Issue by catonblack** [TheNetAdmin/zjuthesis#20]
**遇到的问题**
使用\autoref对表格进行自动编号，但是发现编译出来的编号不符合预期。

**重现步骤**
如何重现你遇到的问题：

1. 修改了哪里
修改了zjuthesis.tex中的Degree，在context.tex中添加了三个章节与表格。
2. 使用什么命令编译
latexmk
3. 产生了什么错误/输出结果哪里不对
我认为chapter1中的表格应该是表1.1；chapter2中的表格应该是表2.1；chapter3中的表格应该是表3.1。但是，这些生成的表格都叫表0.1。
4.修改过的文件/工程
[zjuthesis.zip](https://github.com/TheNetAdmin/zjuthesis/files/3803799/zjuthesis.zip)
生成的pdf
[zjuthesis.pdf](https://github.com/TheNetAdmin/zjuthesis/files/3803810/zjuthesis.pdf)

![批注 2019-11-04 194241](https://user-images.githubusercontent.com/15844110/68118742-b10bba80-ff3b-11e9-8bb8-8461e68b6dd6.jpg)

**环境**
 - zjuthesis版本: [v4.2.1]
- zjuthesis基础设置
```
\documentclass[
    StudentName = 姓名,
    StudentID   = 学号,
    AdvisorName = 指导教师,
    Grade       = 2014,
    Major       = 专业,
    Department  = 学院,
    Title       = 毕业论文/设计题目,
    SubmitDate  = 递交日期,
    MajorFormat = general,
    Degree      = graduate,
    Type        = thesis,
    Period      = final,
    BlindReview = false,
    Topic           = 研究方向,
    ColaboratorName = 合作导师
]{config/zjuthesis}
```
 - OS: [Windows10]
 - Tex套件: [Texlive]
 - Tex套件版本: [2019]
 - XeLaTex版本: (请附上`xelatex --version`命令的所有输出)
``` shell
XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX)
kpathsea version 6.3.1
Copyright 2019 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 63.1; using 63.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.9.1; using 2.9.1
Compiled with Graphite2 version 1.3.13; using 1.3.13
Compiled with HarfBuzz version 2.3.1; using 2.3.1
Compiled with libpng version 1.6.36; using 1.6.36
Compiled with poppler version 0.68.0
Compiled with fontconfig version 2.13.1; using 2.13.1
```

**Comment by catonblack** [comment]
我自己解决了/捂脸。。。在config\format\major\xxx\packages.tex中加上：
`\numberwithin{table}{chapter}`这就意味着表格编号跟着章走，之前是跟着节走

**Comment by TheNetAdmin** [comment]
可以参照这里的设定：

https://github.com/TheNetAdmin/zjuthesis/blob/f9a580ca914cd6d35889070ad2bbbf36b7a075de/config/format/general/numbering.tex#L6-L7

注意也要修改表格编号`\thetable`为`\thechapter.\arabic{table}`

**Comment by TheNetAdmin** [comment]
默认设置编号跟随节编号是因为：

1. 学校模板要求编号跟随"章编号"
2. 本模板使用的基础模板`ctexrep`提供的最高级别编号为`\chapter`，没有`\part`。但模板需要一个比“章”更高级别的编号

所以本模板将`\chapter`用作“部分”，将`\section`用作“章”，将`\subsection`用作“节”，以此类推

**Comment by catonblack** [comment]
OK， 了解了。多谢
