### ISSUE TITLE
外文翻译中引用图的标号不正确

### ISSUE THREAD

**Issue by shangxiafeng** [TheNetAdmin/zjuthesis#205]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [ ] graduate
    - [ ] master
    - [ ] doctor
  - [x] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/7528112/zjuthesis.log)

## 遇到的问题

在外文翻译中，引入图像的标号与标题级数不一致。

**代码**

```TeX
% 可以重现你遇到的问题的代码
% 可使用多个代码框，分别填写不同文件内的代码
% 注明代码所在文件
```

**截图**

![image](https://user-images.githubusercontent.com/69114522/141480566-7a228155-621d-425d-a906-563a80c89f77.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
请给一段可以复现问题的代码，可以将你现有代码精简一下贴上来
