### ISSUE TITLE
两行的英文论文题目中间空开了一行

### ISSUE THREAD

**Issue by BForever** [TheNetAdmin/zjuthesis#208]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2021 或更新的版本
- [ ] TeXLive 2020
- [ ] TeXLive 2019 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：8.1.1

Degree:
  - [x] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/7544702/zjuthesis.log)

## 遇到的问题

两行的英文论文题目中间空开了一行

**代码**

zjuthesis.tex第44行：
```TeX
% Uncomment the following lines if you need multi line titles on cover pages
\titletwolines{基于视觉SLAM的}{虚拟现实交互}
\titleengtwolines{Physical Cyber Space Interaction}{via Visual SLAM}
```

**截图**

![image](https://user-images.githubusercontent.com/28983398/141951935-ec4a3135-61e8-4cc2-a5df-879a616cc076.png)

**其他信息**

**Comment by hongyu007** [comment]
请问一下老哥是如何解决的呀？

**Comment by TheNetAdmin** [comment]
第一行的英文字符超宽了，挪一部分到第二行就好了，或者加宽标题所在的表格，操作方法搜一下GitHub issue就有了
