### ISSUE TITLE
CV的页眉显示了二级标题

### ISSUE THREAD

**Issue by BForever** [TheNetAdmin/zjuthesis#209]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [x] Overleaf

**TeX套件**

- [x] TeXLive 2021 或更新的版本
- [ ] TeXLive 2020
- [ ] TeXLive 2019 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：8.1.1

Degree:
  - [ ] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[output.log](https://github.com/TheNetAdmin/zjuthesis/files/7585647/output.log)

## 遇到的问题

CV的页眉显示了二级标题（seciton）而不是一级标题（chapter）

**代码**

body/graduate/post/cv.tex:
```TeX
\cleardoublepage
\chapternonum{作者简历}
\sectionnonum{教育经历}
\sectionnonum{发表论文}
\sectionnonum{已授权专利}
\sectionnonum{申请中专利}
```

**截图**

![image](https://user-images.githubusercontent.com/28983398/142967077-e1c40f20-7423-451b-984a-a43ae533cca1.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
我可以复现这个问题，尝试将这一行去掉呢

https://github.com/TheNetAdmin/zjuthesis/blob/93aadb9abc9663f1e7753aa410c2248078ba33c1/config/commands.tex#L117

我本地去掉这个 `\markboth` 后恢复正常了

**Comment by BForever** [comment]
> 我可以复现这个问题，尝试将这一行去掉呢
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/93aadb9abc9663f1e7753aa410c2248078ba33c1/config/commands.tex#L117
> 
> 我本地去掉这个 `\markboth` 后恢复正常了

去掉这行确实恢复正常了

**Comment by TheNetAdmin** [comment]
ok 我过两天把这个问题彻底修复一下

**Comment by TheNetAdmin** [comment]
已经修复，感谢指出
