### ISSUE TITLE
为和硕博是一个模板，这和官方的不一样啊

### ISSUE THREAD

**Issue by orange-xyz** [TheNetAdmin/zjuthesis#21]
模板出来的效果和官方给的doc模板效果差别有点大呀http://cspo.zju.edu.cn/2019/0904/c27174a1628255/page.htm

**Comment by TheNetAdmin** [comment]
我参照的的是“浙江大学研究生院网站”的编写规则：
http://grs.zju.edu.cn/redir.php?catalog_id=10038&object_id=12877

这是份2008年的规则，还有一份2016年的规则，可以在同一个网站上搜索到。

你给的这个应该是计算机学院给的模板，我看了一下，里面有很多地方不符合前面提到的编写规则。

**Comment by TheNetAdmin** [comment]
最简单的解决方案是对封面页和摘要页稍作修改，正文部分的格式应该还是符合校级要求的。

**Comment by TheNetAdmin** [comment]
我十二月有空可以修改一个计算机学院的版本出来，这段时间比较忙没空修改。

**Comment by TheNetAdmin** [comment]
刚更新了 CS 硕士模板，在 Release 5.0.0-rc2里可以下载文件名带有 "-cs-master" 的预览文件。

**Comment by TheNetAdmin** [comment]
Issue closed，如有其他关于计算机硕士模板的问题请新开issue
