### ISSUE TITLE
页眉字体问题

### ISSUE THREAD

**Issue by XanderShen** [TheNetAdmin/zjuthesis#210]
使用CS,graduate,thesis,master时遇到如下问题：

页眉字体不正确，模板中的页眉“浙江大学硕士学位论文”为仿宋，规定为宋体，以下是文档原文：
页眉、页脚文字均采用小五号宋体，左侧页眉为“浙江大学博（硕）士学位论文”，右侧为一级标题名称；页眉下横线可为单横线也可用上粗下细文武线。

**Comment by TheNetAdmin** [comment]
感谢指出，我修复了一下，试一下最新的 master 分支上的代码还有没有这个问题

**Comment by XanderShen** [comment]
问题解决，辛苦了~
