### ISSUE TITLE
第二个封面页一页放不下

### ISSUE THREAD

**Issue by cqupeng** [TheNetAdmin/zjuthesis#211]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2021 或更新的版本
- [ ] TeXLive 2020
- [ ] TeXLive 2019 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：8.2.0

Degree:
  - [ ] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/7677046/zjuthesis.log)
## 遇到的问题
第二个封面页一页放不下

**代码**

```TeX
% 可以重现你遇到的问题的代码
% 可使用多个代码框，分别填写不同文件内的代码
% 注明代码所在文件
```

**截图**

![image](https://user-images.githubusercontent.com/46516320/145234820-ffc18925-e830-4d5b-8437-dd9cd0255a0c.png)

**其他信息**

**Comment by muzimuzhi** [comment]
评阅人和委员太多了。

截图不完整，第一页有足够的空距塞下吗，如果把纵向间距都取消的话。学校/学院规范，允许一行写多个吗？

**Comment by cqupeng** [comment]
我在尝试把间距变小
![image](https://user-images.githubusercontent.com/46516320/145326039-ebdbf388-52bd-4d2d-8712-09a531d81468.png)
![image](https://user-images.githubusercontent.com/46516320/145326071-7db17e1b-d18d-49e6-814b-56963ec77765.png)

**Comment by TheNetAdmin** [comment]
你这里的问题可能是标题太长了，两种解决方案

1. 用双行标题，`zjuthesis.tex` 里有说明
2. 改一下标题栏宽度

https://github.com/TheNetAdmin/zjuthesis/blob/8c997fa961ead02f8b9457f6561d0ab1834cb379/page/graduate/title-chn.tex#L5

把 `.8\textwidth` 改成 `.85\textwidth`

**Comment by cqupeng** [comment]
感谢老铁，解决了
