### ISSUE TITLE
有序列表和无序列表行间距过大

### ISSUE THREAD

**Issue by richenyunqi** [TheNetAdmin/zjuthesis#212]
## 可改进的内容

有序列表和无序列表行间距过大，例如代码
```
abcdefg
\begin{itemize}
    \item a
    \item b
\end{itemize}

\begin{enumerate}
    \item a
    \item b
\end{enumerate}

abcdefg
```

渲染结果为：

![image](https://user-images.githubusercontent.com/28208967/145742125-1385813f-cffe-45cc-9026-da3391ab2b94.png)

希望能够减少有序列表和无序列表的行间距

**Comment by muzimuzhi** [comment]
zjuthesis 加载了 `enumitem`，可以试试
```tex
\setlist[enumerate]{itemsep=<glue>}
\setlist[itemize]{itemsep=<glue>}
```
其中的 `<glue>` 现在是 `4pt plus 2pt minus 1pt`。可以改小一些
