### ISSUE TITLE
双面格式下部分页面中段落间距问题

### ISSUE THREAD

**Issue by Zenith0618** [TheNetAdmin/zjuthesis#214]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [ ] TeXLive 2021 或更新的版本
- [ ] TeXLive 2020
- [x] TeXLive 2019 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：8.1.1

Degree:
  - [ ] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**
[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/7770025/zjuthesis.log)

## 遇到的问题

- 描述：对于文字没有填满的页面，单面格式(Twoside=false)下页面底部留白，段落间距正常；
双面格式下段落间距则会变大，底部没有留白。

- 目的：如何在双面格式下(Twoside=true)，使文字没有填满的页面中段落间距保持不变，页面底部留白

**截图**

- 单面pdf效果
![单面](https://user-images.githubusercontent.com/32241339/147259826-972dbdf8-e77f-442a-b2ee-4fba5527d6c5.png)
- 双面pdf效果
![双面](https://user-images.githubusercontent.com/32241339/147259835-46610d62-3e0b-49e1-a519-80d75a88c7b7.png)
- content.tex中相关代码：
![tex](https://user-images.githubusercontent.com/32241339/147259812-54ca5361-3669-486e-a30e-c645124a87b7.png)
**其他信息**

**Comment by TheNetAdmin** [comment]
这看上去是LaTeX自动调整的，因为双面格式下两个段落不能填满当前页面，但如果将下一节也放入当前页面就会溢出。

我的建议是你写完内容后再考虑这个间距，因为你内容的变化也会影响排版。

如果你确实要压缩间距，可以尝试在\section前一行加入\clearpage

**Comment by Zenith0618** [comment]
了解，非常感谢~
