### ISSUE TITLE
Texlive 2019编译不出Bibliography

### ISSUE THREAD

**Issue by lijinfeng0713** [TheNetAdmin/zjuthesis#22]
在升级TexLive到最新版本后，确实能成功解决伪粗体乱码的问题，但编译提示Bibliography为空，参考文献却无法正常编译和显示

**Comment by TheNetAdmin** [comment]
Log文件给一个？

**Comment by TheNetAdmin** [comment]
错误输出是什么

**Comment by TheNetAdmin** [comment]
以及把中间文件删除再重新编译呢

**Comment by hushidong** [comment]
注意编译方式：
xelatex jobname.tex
	biber jobname
	xelatex jobname.tex

文献编译使用的是biber，而不是bibtex

**Comment by lijinfeng0713** [comment]
> Log文件给一个？

ref.tex:2: LaTeX Warning: Empty bibliography on input line 2.
zjuthesis.tex: LaTeX Warning: There were undefined references.
zjuthesis.tex: Package biblatex Warning: Please (re)run Biber on the file:(biblatex)                zjuthesis(biblatex)                and rerun LaTeX afterwards.

**Comment by TheNetAdmin** [comment]
> > Log文件给一个？
> 
> ref.tex:2: LaTeX Warning: Empty bibliography on input line 2.
> zjuthesis.tex: LaTeX Warning: There were undefined references.
> zjuthesis.tex: Package biblatex Warning: Please (re)run Biber on the file:(biblatex) zjuthesis(biblatex) and rerun LaTeX afterwards.

看最后一条的提示，你应该是没有用`biber`跑一遍，按照@hushidong的办法编译一遍试试。

或者直接在根目录下运行`latexmk`，README里面有讲怎么编译。

**Comment by lijinfeng0713** [comment]
这个问题已将解决啦，主要是因为在使用biblatex没有指定backend，加上这个option就行，如下
`\usepackage[style=numeric,
            sorting=none,
            gbpub=false,
            backend=bibtex,
            bibstyle=gb7714-2015,
            citestyle=gb7714-2015]{biblatex}`

**Comment by hushidong** [comment]
你如果要一定要使用bibtex，那么这样是可以的，但可能会有样式方面的问题，你可以仔细检查一下。
最好的方式是后端使用biber,然后编译时用biber命令替代bibtex命令编译。
