### ISSUE TITLE
cs phd模板内容不全

### ISSUE THREAD

**Issue by WangHonglie** [TheNetAdmin/zjuthesis#221]
**所有如下信息都是必填项，包括截图和编译日志（有 LaTeX 经验的开发者可忽略此要求）。
缺失必要信息会导致本模板的开发者无法帮你定位问题。
任何缺失信息都有可能导致此问题被关闭且得不到任何解答。**

## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [x] Overleaf

**TeX套件**

- [x] TeXLive 2021 或更新的版本
- [ ] TeXLive 2020
- [ ] TeXLive 2019 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：8.3.0

Degree:
  - [ ] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

没有致谢，序言，勘误，独创性声明。
没有中英文题名页。
封面格式不对，递交日期没有居中，没有分类号和单位代码。
按照
**代码**

```TeX
% 可以重现你遇到的问题的代码
% 可使用多个代码框，分别填写不同文件内的代码
% 注明代码所在文件
```

**截图**

**其他信息**

**Comment by TheNetAdmin** [comment]
看你的描述你应该用master模板

**Comment by WangHonglie** [comment]
> 看你的描述你应该用master模板，这些都有
> 
> 另外，如果你想我修复这些问题，起码给个样例模板吧？你写这几句话我怎么修，封面长什么样，间距多少我啥都不知道

你好，因为学院模板里master和phd是一份，所以我以为应该是一样的。我可以自己按照需求从master里面引用这些，只是奇怪为什么在你的phd模板里没有，不知道是不是我学院下的版本不对。
这是我们学院的模板，确实只要按照master里的就可以。
<img width="495" alt="image" src="https://user-images.githubusercontent.com/33799979/154442467-1741679e-4683-4549-aa34-47ec22418a39.png">
<img width="492" alt="image" src="https://user-images.githubusercontent.com/33799979/154442552-7ec0730b-d966-4b8d-a32f-7238d6471310.png">

**Comment by TheNetAdmin** [comment]
那应该是因为今年计算机学院把模板更新成学校统一的模板了
 
#87

https://github.com/TheNetAdmin/zjuthesis-std/issues/2

你如果有计算机博士模板的word文件的话，在这里上传一份，我对照着更新一下

**Comment by WangHonglie** [comment]
> 那应该是因为今年计算机学院把模板更新成学校统一的模板了
> 
> #87
> 
> [TheNetAdmin/zjuthesis-std#2](https://github.com/TheNetAdmin/zjuthesis-std/issues/2)
> 
> 你如果有计算机博士模板的word文件的话，在这里上传一份，我对照着更新一下

好的，我再去学院官网确认下。
