### ISSUE TITLE
论文图注是否可以加冒号

### ISSUE THREAD

**Issue by Jackie-zk** [TheNetAdmin/zjuthesis#223]
### 可改进的内容

![image](https://user-images.githubusercontent.com/39890118/155525475-518ef847-f71f-4431-bc17-b499ba85c40a.png)
这个“图1.1：”的冒号不知是否规范。

**Comment by TheNetAdmin** [comment]
之前也有人提到过这个问题，学校的格式要求里有规定用什么分隔符吗，我可以统一改一下

**Comment by TheNetAdmin** [comment]
查了一下[本科生格式规范](https://github.com/TheNetAdmin/zjuthesis-std/blob/master/standard/undergraduate/general/rules2018.pdf)“2.3.2.2 图、表等标号”没有明确规定用哪个分隔符。

不过之前有同学提出要使用空格替代冒号，如果这是大家都在用的格式的话，我过后统一修改成空格好了。

**Comment by TheNetAdmin** [comment]
已改为空格分隔符
