### ISSUE TITLE
使用 \autoref 引用之后，数字与后续正文文本的间距会变小

### ISSUE THREAD

**Issue by Iridescent-Aurora** [TheNetAdmin/zjuthesis#224]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v8.4.0

### MajorFormat

general

### Degree

graduate

### Type

design

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

如截图中所示。“图1.1”是使用\autoref自动生成的，它与后面文字之间的距离会减小；而“表1.2”是手动打出来的，所以此时的字间距是正常的。请问有没有一种方法，能够在使用\autoref且不手动添加空格的情况下，使文本之间的字间距变得正常呢？

### 截图

![Fig1](https://user-images.githubusercontent.com/33147465/156530286-84b351f7-d121-48dd-aae1-a996ef878ced.png)
![Fig2](https://user-images.githubusercontent.com/33147465/156530313-07689d61-6ff5-4771-9d77-4f996ad70d68.png)

**Comment by TheNetAdmin** [comment]
两种做法，可以在`\autoref{}`后手动加一个空格，或者定义一个新命令`\autorefspace{}`然后替换当前所有的`\autoref{}`为新命令

```tex
\newcommand{\autorefspace}[1]{\autoref{#1}\space}
```

![image](https://user-images.githubusercontent.com/18525442/156681432-3cce1949-077a-480d-8b0f-38218fe736f7.png)
