### ISSUE TITLE
请问要上传带签名的电子版，应该如何加入到latex中呢

### ISSUE THREAD

**Issue by gujiaqivadin** [TheNetAdmin/zjuthesis#226]
学院最后要求上传带本人签名和导师签名的电子版，以何种形式加入到latex中比较好呢
大家有这个问题吗

**Comment by TheNetAdmin** [comment]
编译成pdf，手写签名然后上交带有签名的版本吧

**Comment by gujiaqivadin** [comment]
> 编译成pdf，手写签名然后上交带有签名的版本吧

最后要上交的是带签名的电子版论文，是说在pdf生成后，再编辑pdf加上手写签名的电子图片吗。

**Comment by TheNetAdmin** [comment]
对，签到pdf里面

**Comment by gujiaqivadin** [comment]
懂了 谢谢老哥

**Comment by TheNetAdmin** [comment]
Acrobat应该可以手写签名到pdf上吧，就没必要手动插入图片。

**Comment by gujiaqivadin** [comment]
> Acrobat应该可以手写签名到pdf上吧，就没必要手动插入图片。

可以 到时候我试试

**Comment by TheNetAdmin** [comment]
不客气，祝毕业顺利
