### ISSUE TITLE
CS模板添加术语表

### ISSUE THREAD

**Issue by SimonSungm** [TheNetAdmin/zjuthesis#228]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v8.5

### MajorFormat

cs

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

CS硕士模板如何添加术语表？找了一下只看到OPTEng的模板里有术语表，但不知道该怎么迁移到CS模板上

**Comment by TheNetAdmin** [comment]
https://github.com/TheNetAdmin/zjuthesis/blob/7e4ae759b5d6ad7c6d496b77d0322bd0517a35c8/page/graduate/doctor/opteng/toc.tex#L6-L9

**Comment by SimonSungm** [comment]
感谢，试了一下下面的办法能够work。

1.添加宏包\usepackage{nomencl}

2.在page/graduate/toc.tex的`\listoftables`后面添加如下内容
```
    \cleardoublepage 
    \phantomsection 
    \marklon 
    \printnomenclature[2cm] 
```

3.在config/format/major/cs/layout.tex中添加以下内容
```
% Term Table title, centered
\renewcommand{\nomname}{\makebox[\linewidth]{缩写、符号清单、术语表}}
% Term Table style
\newcommand{\nomdescr}[1]{
\parbox[t]{8.5cm}{\linespreadsingle{}\raggedright\strut #1 \strut}
}
\newcommand{\nomdescrchn}[1]{
    \hfill\parbox[t]{5cm}{\linespreadsingle{}\strut #1 \strut}\ignorespaces
}
\newcommand{\nomchn}[4][]{
\nomenclature[#1]{#2}{
\nomdescr{#3}
\nomdescrchn{#4}
}
}
\setlength{\nomitemsep}{2pt}
\makenomenclature
```

**Comment by badaolaziang** [comment]
您好，如果是普通专业的模板，想要添加术语表该怎么操作，我按照您这个方法操作之后，虽然不报错，但是文档上好像也不显示“术语表”（只有目录上显示了）

**Comment by SimonSungm** [comment]
> 您好，如果是普通专业的模板，想要添加术语表该怎么操作，我按照您这个方法操作之后，虽然不报错，但是文档上好像也不显示“术语表”（只有目录上显示了）

你有做第4步的术语定义吗，如果一个术语都没定义应该是不会显示术语表那一页的

**Comment by badaolaziang** [comment]
> 
有的，我在content.tex中加了两句，如下所示

\nomchn{$test$}{english}{中文描述}

但是好像并没有显示术语表那一页

**Comment by badaolaziang** [comment]
> > 您好，如果是普通专业的模板，想要添加术语表该怎么操作，我按照您这个方法操作之后，虽然不报错，但是文档上好像也不显示“术语表”（只有目录上显示了）
> 
> 你有做第4步的术语定义吗，如果一个术语都没定义应该是不会显示术语表那一页的

我再研究一下吧，感觉应该是可以的

**Comment by SimonSungm** [comment]
> > 
> 
> 有的，我在content.tex中加了两句，如下所示
> 
> \nomchn{$test$}{english}{中文描述}
> 
> 但是好像并没有显示术语表那一页


我又试了一遍，之前写的漏了一步

5.在config/format/general/heading.tex的`\newcommand{\marklot}{\addcontentsline{toc}{chapter}{表目录}}`的后面添加以下内容
```
    \newcommand{\listnomname}{缩写、符号清单、术语表}
    \newcommand{\marklon}{\addcontentsline{toc}{chapter}{缩写、符号清单、术语表}}
```
但这步不做应该是有报错的，如果还是不行的话我也不清楚了。

**Comment by badaolaziang** [comment]
> > > 
> > 
> > 
> > 有的，我在content.tex中加了两句，如下所示
> > \nomchn{testtesttest}{english}{中文描述}
> > 但是好像并没有显示术语表那一页
> 
> 我又试了一遍，之前写的漏了一步
> 
> 5.在config/format/general/heading.tex的`\newcommand{\marklot}{\addcontentsline{toc}{chapter}{表目录}}`的后面添加以下内容
> 
> ```
>     \newcommand{\listnomname}{缩写、符号清单、术语表}
>     \newcommand{\marklon}{\addcontentsline{toc}{chapter}{缩写、符号清单、术语表}}
> ```
> 
> 但这步不做应该是有报错的，如果还是不行的话我也不清楚了。

是的，我之前已经参考opteng.tex里面的相关部分把这两句加上了。
我现在总结遇到的问题是，它的更新好像不是很及时...即使完整编译，它不能把每次新增的术语加上，所以我之前在pdf上没看到 “缩写符号清单术语表”那两页...还是非常感谢您的回答~

**Comment by badaolaziang** [comment]
> > > > 
> > > 
> > > 
> > > 有的，我在content.tex中加了两句，如下所示
> > > \nomchn{testtesttest}{english}{中文描述}
> > > 但是好像并没有显示术语表那一页
> > 
> > 
> > 我又试了一遍，之前写的漏了一步
> > 5.在config/format/general/heading.tex的`\newcommand{\marklot}{\addcontentsline{toc}{chapter}{表目录}}`的后面添加以下内容
> > ```
> >     \newcommand{\listnomname}{缩写、符号清单、术语表}
> >     \newcommand{\marklon}{\addcontentsline{toc}{chapter}{缩写、符号清单、术语表}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但这步不做应该是有报错的，如果还是不行的话我也不清楚了。
> 
> 是的，我之前已经参考opteng.tex里面的相关部分把这两句加上了。 我现在总结遇到的问题是，它的更新好像不是很及时...即使完整编译，它不能把每次新增的术语加上，所以我之前在pdf上没看到 “缩写符号清单术语表”那两页...还是非常感谢您的回答~

更新一下评论，我目前发现上述问题主要是出现在编译方法上。因为我是使用本地的vscode+bibxe编译，此编译方法无法顺利更新《术语表》中的内容，但如果使用本模板默认推荐的latexmk方法编译，则可在/out文件夹内得到期望的包含合理《术语表》内容的pdf文件。
