### ISSUE TITLE
参考文献编译错误

### ISSUE THREAD

**Issue by michuanhaohao** [TheNetAdmin/zjuthesis#23]
![image](https://user-images.githubusercontent.com/23547900/69476758-31298f80-0e19-11ea-9eca-a9ee13da5869.png)

您好，感谢您的工作。我在编译参考文献的时候，使用\cite命令无法编译得到数字[1] [2] [3]之类的，用的是windows的texlive2019和tex studio客户端，直接用编译按钮编译，bib编译器已经选择为biber。

**Comment by TheNetAdmin** [comment]
尝试使用命令行直接编译呢？

下载一个新代码库，用命令行进入代码目录，用`latexmk -xelatex -outdir=out zjuthesis`，然后在新生成的out目录下找编译得到的pdf看一下。

**Comment by michuanhaohao** [comment]
> 尝试使用命令行直接编译呢？
> 
> 下载一个新代码库，用命令行进入代码目录，用`latexmk -xelatex -outdir=out zjuthesis`，然后在新生成的out目录下找编译得到的pdf看一下。


用命令就可以，真的神奇，但是生成的格式是错误的， 有一些字符不认识，然后名字也是大写的。应该是写到ref.bib里面是吧

![image](https://user-images.githubusercontent.com/23547900/69477095-06d9d100-0e1d-11ea-9fe1-f8c69565115e.png)

@inproceedings{kissme2012,
	title={Large scale metric learning from equivalence constraints},
	author={Koestinger, Martin and Hirzer, Martin and Wohlhart, Paul and Roth, Peter M and Bischof, Horst},
	booktitle={2012 IEEE conference on computer vision and pattern recognition},
	pages={2288--2295},
	year={2012},
	organization={IEEE}
}

**Comment by TheNetAdmin** [comment]
那应该是TexStudio没有正确用Biber编译，可能要额外设置一下。我很久没用TexStudio了所以不太清楚怎么设置。

关于格式的问题，可能要请教一下 @hushidong

**Comment by michuanhaohao** [comment]
好的，非常感谢。

tex studio已经搞定了 ，如果有人遇到问题，参考下面这幅图，F8 F6 F6 三连编译。

![image](https://user-images.githubusercontent.com/23547900/69477212-608ecb00-0e1e-11ea-9c6b-ccd42e258d7c.png)

格式问题我在研究下

**Comment by hushidong** [comment]
文献表格式中，姓名大写，出版项缺失的问题是有规定的。当然你自己想要修改也是可以的，请参考biblatex-gb7714-2015.pdf中的gbpub
和gbnamefmt
两个选项

**Comment by TheNetAdmin** [comment]
问题似乎已经解决了，如有其它问题请另开issue讨论吧

**Comment by ZJUGuoShuai** [comment]
给新来的同学一个快速参考：如果想参考文献英文名**不是全大写**，在`config/packages.tex`里修改这一行：

加上`gbnamefmt=lowercase`。
![捕获](https://user-images.githubusercontent.com/22856433/77239898-b92e7300-6c1a-11ea-9a1c-09739d842df7.PNG)

**Comment by zh0ngtian** [comment]
> 那应该是TexStudio没有正确用Biber编译，可能要额外设置一下。我很久没用TexStudio了所以不太清楚怎么设置。
> 
> 关于格式的问题，可能要请教一下 @hushidong
> 
> 研究生院要求的引用格式是`GB/T 7714－2005`，所以我这里是这样设置的：
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/4750afa50e09cdaf30858b663b0c54a8a8f42fc1/config/packages.tex#L14-L17

你好，我尝试把这段代码中的 2015 改为 2005 ，编译后无法显示参考文献，请问如果想用 `GB/T 7714-2005` 格式的参考文件，到底应该如何设置呢？

**Comment by TheNetAdmin** [comment]
Google一下有如下结果，需要手动安装并修改模板

https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style

**Comment by hushidong** [comment]
2015和2005没有大的差别的，特别是没有格式方面的差异，所以普通用户根本不会感觉其差异的，所以用2015就可以了。可以看一下标准文档本身，里头有详细说明。

**Comment by hushidong** [comment]
如果不需要doi那么加上一个选项，doi=false

**Comment by zh0ngtian** [comment]
> 2015和2005没有大的差别的，特别是没有格式方面的差异，所以普通用户根本不会感觉其差异的，所以用2015就可以了。可以看一下标准文档本身，里头有详细说明。

刚才看了下，好像是这样，谢谢！

**Comment by namenotexist** [comment]
请问vscode+texlive使用这个模板的教程有吗

**Comment by HelloTheWold** [comment]
同问 vscode+texlive 出现这个问题应该怎么设置？

**Comment by TheNetAdmin** [comment]
用命令行重新编译，或者参考README里的vscode设置教程
