### ISSUE TITLE
CS模板章节目录、图表目录均为空白

### ISSUE THREAD

**Issue by Melinda315** [TheNetAdmin/zjuthesis#230]
### 操作系统

MacOS

### TeX 套件

其他（请在问题描述中标明）

### TeX Compiler

XeTeX

### zjuthesis 版本号

v8.5.0

### MajorFormat

cs

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

doctor

### 问题描述

1. 目前使用sublime(LaTeXTools: A LaTeX Plugin for Sublime Text 2 and 3)对tex文件进行编译，对模板的修改为在content下新增chapters文件夹存放每一章内容；
2. 对应公式使用\label进行标注并希望通过\ref进行应用；
3. 显示Letax Warning：Reference undefined，然后对应位置的引用为图?? 或表??，章节目录、图表目录均为空白。

### 编译日志

```log
Documents/phd-thesis/body/graduate/chapters/chap4.tex:83: LaTeX Warning: Reference `sec:intro' on page 26 undefined on input line 83.

Documents/phd-thesis/body/graduate/chapters/chap4.tex:119: LaTeX Warning: Reference `eq:deep' on page 27 undefined on input line 119.
```

### 代码

\section{引言}
\label{sec:intro}

**Comment by Melinda315** [comment]
好像不行耶，用命令行之后还是显示“! I can't write on file `body/graduate/chapters/chap1.aux'.”

**Comment by Melinda315** [comment]
输出到out里就可以了！之前用sublime的话是在根目录下编译出pdf~感谢！

**Comment by 281LinChenjian** [comment]
请问具体是怎么才能输出到out？
