### ISSUE TITLE
图/表目录中，如何在不同章节的条目间增加一行明显的空白？

### ISSUE THREAD

**Issue by Iridescent-Aurora** [TheNetAdmin/zjuthesis#232]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v8.4.0

### MajorFormat

general

### Degree

graduate

### Type

design

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

在“图/表目录”里，目前版本的代码好像默认不支持在不同章节的条目之间添加空白行。现在想增加一行较为明显的空白，以示区分，如下方截图所示。请问如何增添代码，达到此目的？但同时，不要修改“目录”页中的章节间距。

### 截图

![picture](https://user-images.githubusercontent.com/33147465/158053375-1dd5b5f7-d9a8-4c40-9206-b321307ecb89.png)

**Comment by TheNetAdmin** [comment]
zjuthesis 使用了 `tocloft` 宏包来生成目录，参考 tocloft 使用文档第9页：

![image](https://user-images.githubusercontent.com/18525442/159090801-48af3355-1f39-42ce-92e7-562d2afc484d.png)

在这里

https://github.com/TheNetAdmin/zjuthesis/blob/24f0d4ce6efe6f0fb825226cdf2bff9cfb4eb732/config/format/general/layout.tex#L131-L135

插入一行

```TeX
\setlength{\cftbeforesecskip}   {0.5em}
```

可以得到

![image](https://user-images.githubusercontent.com/18525442/159090788-03b2d1f2-bb68-414e-95cf-6f63d6f6547d.png)

**Comment by Iridescent-Aurora** [comment]
你好，我可能没有表达清楚意思。我实际是想仅限在“图目录”和“表目录”里面进行操作，并且在“图1.XX”和“图2.1”这种地方，增加额外间隙。从视觉上看，来自第1章的图是一个小整体，第2章的图又是一个小整体。
![QQ截图20220319095326](https://user-images.githubusercontent.com/33147465/159102634-c0c91f7c-564e-4a0f-9e62-7bcb97bb4835.jpg)

**Comment by Iridescent-Aurora** [comment]
突然发现删除 toc.tex 中的 \renewcommand*{\addvspace}[1]{} 语句，就能达到目的了（笑哭）。此帖终结...
