### ISSUE TITLE
标题太长怎么办？

### ISSUE THREAD

**Issue by Qidong-Liu** [TheNetAdmin/zjuthesis#237]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

overleaf

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

doctor

### 问题描述

现在的标题是每一行最多12个字，超过12个字就会变型；另外标题如果比较长能拓展到三行吗？请赐教

**Comment by TheNetAdmin** [comment]
两种方法

1. 更改标题栏的宽度，当前为 `{.8\textwidth}`，可加宽至 `{.95\textwidth}`，代码位置
   https://github.com/TheNetAdmin/zjuthesis/blob/24f0d4ce6efe6f0fb825226cdf2bff9cfb4eb732/page/graduate/cover-chn.tex#L55
2. 手动修改封面页，将标题扩展至三行，参考现有的双行标题代码，代码位置
   https://github.com/TheNetAdmin/zjuthesis/blob/24f0d4ce6efe6f0fb825226cdf2bff9cfb4eb732/page/graduate/cover-chn.tex#L53-L82

**Comment by Mirocos** [comment]
> 

请问一下，这个`\begin{tabularx}{.8\textwidth}{>{\fangsong}l X<{\centering}} `的textwidth有上限吗，我调整到100之后整个题目标题就靠右了

**Comment by TheNetAdmin** [comment]
> > 
> 
> 请问一下，这个`\begin{tabularx}{.8\textwidth}{>{\fangsong}l X<{\centering}} `的textwidth有上限吗，我调整到100之后整个题目标题就靠右了
> 
> 

0到1

**Comment by Admin-OF-Admin** [comment]
> 两种方法
> 
> 1. 更改标题栏的宽度，当前为 `{.8\textwidth}`，可加宽至 `{.95\textwidth}`，代码位置
>    https://github.com/TheNetAdmin/zjuthesis/blob/24f0d4ce6efe6f0fb825226cdf2bff9cfb4eb732/page/graduate/cover-chn.tex#L55
> 2. 手动修改封面页，将标题扩展至三行，参考现有的双行标题代码，代码位置
>    https://github.com/TheNetAdmin/zjuthesis/blob/24f0d4ce6efe6f0fb825226cdf2bff9cfb4eb732/page/graduate/cover-chn.tex#L53-L82

请问这个有改好三行的例子吗？想参考一下

**Comment by haidaojuntuan** [comment]
> > > 
> > 
> > 
> > 请问一下，这个`\begin{tabularx}{.8\textwidth}{>{\fangsong}l X<{\centering}} `的textwidth有上限吗，我调整到100之后整个题目标题就靠右了
> 
> 0到1

同求三行标题代码

**Comment by Rui-R** [comment]
mark
