### ISSUE TITLE
使用Xelatex可以正常编译，但是使用LaTexmk就会报错？

### ISSUE THREAD

**Issue by whitemountain-blackwater** [TheNetAdmin/zjuthesis#239]
### Discussed in https://github.com/TheNetAdmin/zjuthesis/discussions/97

<div type='discussions-op-text'>

<sup>Originally posted by **TheNetAdmin** December  9, 2020</sup>

## 👋 欢迎来到 zjuthesis 的讨论版

此版面欢迎如下主题的讨论
  * 模板功能问题
  * 模板设置问题

工具 (如 TeXStudio) 使用相关问题请移步该工具的讨论版

BUG 报告与改进建议请使用 GitHub Issue 报告

使用Xelatex可以正常编译，但是使用LaTexmk就会报错？
![image](https://user-images.githubusercontent.com/59988132/160590759-9690472e-f0f9-42b8-a57c-61538e97b58f.png)
</div>

**Comment by Liubinggunzu** [comment]
我也是这个问题
