### ISSUE TITLE
测试并兼容 TeXLive 2022

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#242]
### 可改进的内容

测试用 TeXLive 2022 编译 zjuthesis

**Comment by RobinEllison** [comment]
我将模板更新了最新的版本（V 9.0.0），编译了我的论文，一切正常。
我的系统的基本信息
`cat /etc/os-release`

> NAME="Ubuntu"
> VERSION="20.04.4 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.4 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal

`tex --version`

> TeX 3.141592653 (TeX Live 2022)
> kpathsea version 6.3.4
> Copyright 2022 D.E. Knuth.
> There is NO warranty.  Redistribution of this software is
> covered by the terms of both the TeX copyright and
> the Lesser GNU General Public License.
> For more information about these matters, see the file
> named COPYING and the TeX source.
> Primary author of TeX: D.E. Knuth.
