### ISSUE TITLE
两行标题中间空了一行而不是最后面空一行

### ISSUE THREAD

**Issue by yuanxun-yx** [TheNetAdmin/zjuthesis#243]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

8.5.0

### MajorFormat

cs

### Degree

undergraduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

标题过长想使用两行标题，但是发现应该空的那一行不在最后而在两行标题中间。查看代码发现也没发现两行标题中间有`~&~\\`，非常奇怪。

### 截图

![cover](https://user-images.githubusercontent.com/60339729/165912778-dacf7faf-c0bd-42a9-bb66-e460f38fd651.png)

**Comment by yuanxun-yx** [comment]
测试了下发现标题第一行都会有上下额外的空行，并不是`~&~\\`所导致的，不知道是为什么。

**Comment by TheNetAdmin** [comment]
第一行标题太长了，把标题表格加宽，之前有类似的Issue问这个

**Comment by yuanxun-yx** [comment]
感谢回复，加宽后问题解决。
此外tabularx的换行问题你有头绪吗？2021版本就不能自动换行。

**Comment by TheNetAdmin** [comment]
不清楚
