### ISSUE TITLE
如何渲染德语字母或希腊字母

### ISSUE THREAD

**Issue by PAN-Ziyue** [TheNetAdmin/zjuthesis#245]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v8.5.0

### MajorFormat

cs

### Degree

undergraduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

参考文献的作者名称中有德国字母，编译渲染出的pdf中相应字母显示为空。

**in `ref.bib`**:

![image](https://user-images.githubusercontent.com/50222787/167363045-29f7a9ff-e97b-4f3c-943f-3d85b0239805.png)

**编译结果**:

![image](https://user-images.githubusercontent.com/50222787/167362991-514fa2f3-da5c-48e3-a36f-484a8145b955.png)

**Comment by TheNetAdmin** [comment]
常见且规范的做法是，在 ref.bib 的代码里使用 LaTeX 认可的方式来生成这些字符（例如 `{\"u}`），而不是直接使用 UTF-8 字符。

如何在 LaTeX 内输入这些字符可参考

https://tex.stackexchange.com/a/57745

按理说各大学术论文网站自动生成的 BiBTeX 会自动将这些字符处理为上文提到的格式，所以建议你尝试去其他论文网站导出一下 BiBTeX 试试。

**Comment by PAN-Ziyue** [comment]
> 常见且规范的做法是，在 ref.bib 的代码里使用 LaTeX 认可的方式来生成这些字符（例如 `{\"u}`），而不是直接使用 UTF-8 字符。
> 
> 如何在 LaTeX 内输入这些字符可参考
> 
> https://tex.stackexchange.com/a/57745
> 
> 按理说各大学术论文网站自动生成的 BiBTeX 会自动将这些字符处理为上文提到的格式，所以建议你尝试去其他论文网站导出一下 BiBTeX 试试。

我最开始的确是使用 `{\"u}` 等来escape这些字符的。但 `{\"u}` 也无法渲染出这些字符，所以后来我换成了UTF-8硬编码进行了一次尝试，但依然无法正常渲染：

**用了escpae char**：
![image](https://user-images.githubusercontent.com/50222787/167532055-a3cca2df-1f9b-40be-b236-6bb6d5221c77.png)

**渲染失败**：
![image](https://user-images.githubusercontent.com/50222787/167532105-ce69c67e-541f-475a-8cc1-514286c42b53.png)

**Comment by TheNetAdmin** [comment]
使用 `latexmk` 编译不会产生问题

![image](https://user-images.githubusercontent.com/18525442/167579587-101be229-cb81-4a4a-8c0d-e3c6ac8f79b5.png)


尝试清除所有中间文件，然后再使用 `latexmk` 编译呢

**Comment by PAN-Ziyue** [comment]
感谢学长的耐心支持，我找到了问题所在。

首先我查看了编译中间产物 `output.bbl`，发现 `{\"u}` 等转义字符已经被正确转义了

![image](https://user-images.githubusercontent.com/50222787/167600836-33ea3a3a-de83-4397-865e-05d3027cfb8e.png)

我猜测 tex 代码转换的过程没有问题，问题可能出在字体的渲染部分。

然后我在 `fonts/README.md` 中看到可以参考 CI 脚本获取所需的字体。我参考 CI 脚本获取了这些字体，然后与我自己先前用的字体做对比，发现 TimesNewRoman 系列字体的文件体积差别很大。

![image](https://user-images.githubusercontent.com/50222787/167601527-39e83975-ec8c-4fb8-87e2-38a79b3893c2.png)

> 第一条 `ls -al` 命令的结果是使用脚本中的命令获取的字体。第二条为我先前自己寻找的字体

替换，渲染成功

![image](https://user-images.githubusercontent.com/50222787/167601802-fea3f963-1d08-447c-93e7-0bce6f8171a7.png)
