### ISSUE TITLE
请求更新CS模板

### ISSUE THREAD

**Issue by lijinfeng0713** [TheNetAdmin/zjuthesis#25]
楼主您好，能否再更新一下CS的格式，计算机学院要求章的标题格式是带汉字的，而且居中的
![image](https://user-images.githubusercontent.com/9656113/69901489-46746000-13bd-11ea-9cd8-9cc3266ca924.png)
我们现在编译出来是这样的
![image](https://user-images.githubusercontent.com/9656113/69901498-70c61d80-13bd-11ea-8015-e6a57b0418ab.png)
不知这个应该如何改？（网上找到了一些解决方案。但不是很放心）

**Comment by lijinfeng0713** [comment]
找到一种解决办法，在config/format/general/numbering.tex中加入下面的几行

\ctexset{chapter={
  name={第\hspace{0.2em},\hspace{0.2em}章},
  beforeskip={0.5em plus .1em minus .1em},
  afterskip={1em plus .2em minus .2em},
  number={\arabic{chapter}},
  format={\centering},
  nameformat={\bfseries\songti\zihao{-2}},
  titleformat={\bfseries\songti\zihao{-2}},
  lofskip=0pt, % 删除图目录中章节之间的空行
  lotskip=0pt, % 同上，表的
}}

**Comment by TheNetAdmin** [comment]
硕士还是本科？模板文件有吗？

**Comment by lijinfeng0713** [comment]
> 硕士还是本科？模板文件有吗？

硕士模块，http://cspo.zju.edu.cn/_upload/article/files/98/c1/0a13ba104b96b30b2bcfe4049a67/c64229de-d89e-4cc2-b79a-980c1f67df56.doc
感谢
