### ISSUE TITLE
section 和后面段落之间的空白

### ISSUE THREAD

**Issue by lichang98** [TheNetAdmin/zjuthesis#253]
### 可改进的内容

section 和后面段落之间的空白不是固定的，有时候空白非常多

### 代码与步骤

建议可以添加 \titlespacing\section 设置一下

**Comment by TheNetAdmin** [comment]
一般来讲这个空白是 LaTeX 自动调整的，不需要手动介入，强行设定空白间距反而会造成一些问题，例如文字重叠等等。

你可以给一个代码加截图的例子我看看吗，如果空白间距特别大，说不定可以参考 https://github.com/TheNetAdmin/zjuthesis/issues/125#issuecomment-756714613

另一种调整方式是通过 CTeX 来调整标题前后间距
https://github.com/TheNetAdmin/zjuthesis/blob/1679782a0b83344060ea689dea4d5eb82ab1ab76/config/format/general/heading.tex#L17-L18
