### ISSUE TITLE
表格后有异常的空页

### ISSUE THREAD

**Issue by minimax4233** [TheNetAdmin/zjuthesis#254]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v8.6.0

### MajorFormat

cs

### Degree

undergraduate

### Type

design

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

不知道为什么会在上述两个表格之间会有空页产生, 而且不是完全的空白页, 页数会有编码, 相关修改是在body.tex中

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/8830392/zjuthesis.log)

### 代码

\clearpage
%!
\subsubsection{用例 2：已加入课程列表}
\begin{table}[H]
    \centering
    \caption{已加入课程列表}
    \label{tab:MyCourse}
    \begin{tabular}{l|l}
        \bottomrule
    用例    & 已加入课程列表          \\  \hline 
    主要参与者 & 学生     \\  \hline 
    目标    & 展示用户已加入的课程的列表，进入课程內容界面\\  \hline 
    前提条件  & 用户已经通过登录检查，并且有加入课程        \\  \hline 
    触发器   & 用户点击我的课程底部标签        \\  \hline 
    场景    & 1. 用户进行登录检查       \\  
          & 2. 选择我的课程界面       \\  
          & 3. 点击课程\\  
          & 4. 跳转到课程学习界面      \\  \hline 
    异常    & 1. 无法通过登录检查       \\  
          & 2. 服务器后台不可用（界面无法正常显示）\\  
          & 3. 无法正常显示服务端的课程信息 \\  \hline
    优先级   & 重要     \\  \hline 
    使用频率  & 频繁    \\  \hline 
    使用方式  & 移动应用程序\\ \bottomrule
    \end{tabular}
\end{table}
\clearpage
%!
\subsubsection{用例 3：课程內容查看}
\begin{table}[H]
    \centering
    \caption{课程內容查看}
    \label{tab:CourseContent}
    \begin{tabular}{l|l}
        \bottomrule
    用例    & 课程內容查看          \\  \hline 
    主要参与者 & 学生     \\  \hline 
    目标    & 展示课程的章节內容、作业信息、常见问题、公告     \\  \hline 
    前提条件  & 用户已经通过登录检查，已经加入该课程      \\  \hline 
    触发器   & 用户在我的课程界面点击课程名称        \\  \hline 
    场景    & 1. 在课程內容界面点击章节       \\  
          & 2. 显示课程所有章节列表       \\  
          & 3. 点击列表显示章节內的课件\\  
          & 4. 在课程內容界面点击作业信息      \\  
          & 5. 显示课程所有作业信息列表以及狀態      \\  
          & 6. 点击列表显示作业查看和下载功能      \\  
          & 7. 在课程內容界面点击常见问题      \\  
          & 8. 显示课程所有常见问题列表      \\  
          & 9. 点击常见问题名称下载有关文件      \\  
          & 10. 在课程內容界面点击公告      \\  
          & 11. 显示课程所有公告      \\  \hline
    异常    & 1. 服务器后台不可用（界面无法正常显示）       \\  
          & 2.  无法正常显示服务端的课程章节信息       \\  
          & 3. 无法正常显示服务端的课程作业信息 \\  
          & 4. 无法正常显示服务端的课程常见问题 \\  
          & 5. 无法正常显示服务端的课程公告 \\  \hline
    优先级   & 重要     \\  \hline 
    使用频率  & 频繁    \\  \hline 
    使用方式  & 移动应用程序   \\ \bottomrule       
    \end{tabular}
\end{table}

### 截图

![image](https://user-images.githubusercontent.com/23628957/171808157-cd542e92-866c-4937-a182-69f2b9b2214f.png)

**Comment by TheNetAdmin** [comment]
去掉这段代码正中间的那个\clearpage呢

**Comment by minimax4233** [comment]
去掉也有

「Zixuan Wang ***@***.***>」在 2022年6月4日 週六，上午4:34 寫道：

**Comment by TheNetAdmin** [comment]
![image](https://user-images.githubusercontent.com/18525442/172024000-baebd418-f369-4959-ace4-0628a9e69c1f.png)

代码在我这边一切正常，你尝试在一个新建的zjuthesis里使用你这段代码看还有没有问题

你的表格使用有个问题，不要使用单个 `\` 来换行表格，而是使用 `\\`

**Comment by minimax4233** [comment]
刪除用例 2表格后编译正常, 在次原封不动贴上用例 2 表格后空页情況没有在出现. 

原文是 \\ 贴上在github后显示成单个 \
