### ISSUE TITLE
Intellisense not working with \cite and \ref in VSCode + LaTeX Workshop

### ISSUE THREAD

**Issue by hkunzhe** [TheNetAdmin/zjuthesis#256]
### 操作系统

MacOS

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

8.7.0

### MajorFormat

cs

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

在 VSCode 下使用  LaTeX Workshop 插件进行本地编辑，插入 `\cite` 和 `\ref` 命令均无法触发[智能提示](https://github.com/James-Yu/LaTeX-Workshop/wiki/Intellisense) 。将 `config/path.tex` 中的 `\bibliography{body/ref.bib}` 移动到 `zjuthesis.tex` 中便可以触发 `\cite` 的智能提示，但是 `\ref` 的智能提示还是无法触发。

### 截图

移动前
![image](https://user-images.githubusercontent.com/30763967/172758447-4c02060a-77d7-4ca2-b35b-e3ec65c26cd5.png)

移动后
![image](https://user-images.githubusercontent.com/30763967/172758331-6b9304ed-2921-4539-a85a-a662b5e8b515.png)

**Comment by TheNetAdmin** [comment]
这应该是插件的问题不是模板的问题，我能想到的可能的解决办法就是，把编译输出目录从 out 改为项目根目录

**Comment by hkunzhe** [comment]
> 这应该是插件的问题不是模板的问题，我能想到的可能的解决办法就是，把编译输出目录从 out 改为项目根目录

试过了不行。插件是对 `.tex` 文件进行分析的，而不是对编译产生的中间文件。

**Comment by TheNetAdmin** [comment]
那就自行调整一下代码位置吧，ref的话，把\inputundergraduate展开，直接input各个文件，说不定能行

模板上没办法做这些修改，因为还有其他专业的模板要考虑
