### ISSUE TITLE
希望增加算法目录，同时改进算法的计数方式

### ISSUE THREAD

**Issue by lorentzbf** [TheNetAdmin/zjuthesis#259]
### 可改进的内容

希望论文模板中加上一个算法目录（特别是硕博士论文模板）。同时改进目前对算法的计数方式。目前无论算法在那一章，都是按1,2,3,4...的方式计数，希望改进版可以按照类似，算法2.1 算法2.1 算法3.1 算法3.2的方式计数。

### 代码与步骤

可能需要修改config中的numbering.tex, heading.tex, reference.tex等。

**Comment by TheNetAdmin** [comment]
感谢建议！我这周没有时间，下周有空我会看一下怎么实现

**Comment by lorentzbf** [comment]
感谢。

**Comment by TheNetAdmin** [comment]
新增了此项功能，现在可以在 `master` 分支使用此项功能，后续测试一段时间后会 release。
