### ISSUE TITLE
怎么让图目录只引用部分图caption的内容

### ISSUE THREAD

**Issue by HeadReaper-hc** [TheNetAdmin/zjuthesis#261]
### 操作系统

Windows

### TeX 套件

TeXLive 2020

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

doctor

### 问题描述

若一张图的标注为\caption{图展示。a图为....， b图为....}
然后在图目录中的超链接我只想显示图展示三个字，后面的不显示，请问该怎么做到

**Comment by TheNetAdmin** [comment]
贴个示例和代码，根据你的例子不一定要搞这么麻烦

**Comment by HeadReaper-hc** [comment]
例如以下代码：
\begin{figure}[h]
	\centering
	\includegraphics[width=0.495\textwidth]{data/introduction/1\_3-1.png}
	\includegraphics[width=0.47\textwidth]{data/introduction/1\_3-2.png}
	\caption{\label{fig:under-image}水下图像展示：其中左图来自Cave\cite{joshi2019experimental}数据集，图中展示了因光源问题带来的图像光照不均匀问题。右图来自Aqualoc\cite{ferrera2019aqualoc}数据集，展示了水下纹理性单一的问题。}
\end{figure}

==========================================
编译后图目录会显示：
图 1.3 水下图像展示：其中左图来自 Cave[20]数据集，图中展示了因光源问
题带来的图像光照不均匀问题。右图来自 Aqualoc[24]数据集，展示了
水下纹理性单一的问题。 ................................................................ 3

如果仅想显示：
图 1.3 水下图像展示...................................................................3
请问该怎么办
@TheNetAdmin

**Comment by TheNetAdmin** [comment]
尝试使用

```
\caption[水下图像展示]{\label{fig:under-image}水下图像展示：其中左图...}
```


https://tex.stackexchange.com/a/2854

**Comment by HeadReaper-hc** [comment]
@TheNetAdmin 方法可行，谢谢了
