### ISSUE TITLE
原文中的英文会超过行宽

### ISSUE THREAD

**Issue by wenxuwan** [TheNetAdmin/zjuthesis#265]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2020

### TeX Compiler

XeTeX

### zjuthesis 版本号

1.0

### MajorFormat

cs

### Degree

graduate

### Type

design

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

在代码中加代码片段，会超过行宽，求大佬指点。

### 截图

![image](https://user-images.githubusercontent.com/11661906/185788077-53e4858e-2ce9-490f-a9f9-885fd81907d1.png)

**Comment by TheNetAdmin** [comment]
你这是代码太长了，几种办法

1. 缩小代码环境字体大小
2. 开启代码环境自动换行 https://tex.stackexchange.com/a/116572
3. 将代码环境外包一层 `\resizebox` 来调整大小（我没这么使用过，但按理说应该可行）

**Comment by wenxuwan** [comment]
> 你这是代码太长了，几种办法
> 
> 1. 缩小代码环境字体大小
> 2. 开启代码环境自动换行 https://tex.stackexchange.com/a/116572
> 3. 将代码环境外包一层 `\resizebox` 来调整大小（我没这么使用过，但按理说应该可行）

好的，感谢老哥
