### ISSUE TITLE
页眉问题

### ISSUE THREAD

**Issue by HeadReaper-hc** [TheNetAdmin/zjuthesis#266]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

V9

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

doctor

### 问题描述

目前博士论文的页眉为浙江大学博士学位论文加章节标题的形式。
请问怎么改成奇数页显示章节标题，偶数页显示浙江大学博士论文的形式？

### 截图

![image](https://user-images.githubusercontent.com/42986202/186106664-10d533f1-159c-45c6-b07f-a8cd923f62da.png)

![image](https://user-images.githubusercontent.com/42986202/186106988-21bce1ab-4615-47da-b211-359b30c72855.png)
![image](https://user-images.githubusercontent.com/42986202/186107092-b9e74dbd-dc22-42ce-b90a-424251d19a83.png)

**Comment by TheNetAdmin** [comment]
当前设定位于

https://github.com/TheNetAdmin/zjuthesis/blob/38da3fd02cc1f5f110ccbe64e801937a3b6b2d9e/config/format/general/layout.tex#L47-L53

将其改为

``` TeX
\fancyhead[OL]{\zihao{-5} \songti \TitleTypeName}
\fancyhead[ER]{\zihao{-5} \songti \leftmark}
```

应该就可以了

相关使用方法可自行搜索 fancyhdr 用法与文档
