### ISSUE TITLE
使用MacOS进行本地编译时如何实现对FangSong等字体的支持？

### ISSUE THREAD

**Issue by JackieAnxis** [TheNetAdmin/zjuthesis#269]
### 操作系统

MacOS

### TeX 套件

TeXLive 2019 或更早的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

doctor

### 问题描述

Package fontspec: The font "FangSong" cannot be found.

**Comment by TheNetAdmin** [comment]
先升级Tex live到最新版本试试
