### ISSUE TITLE
《所在学院》信息过长导致换行

### ISSUE THREAD

**Issue by MforU** [TheNetAdmin/zjuthesis#271]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

doctor

### 问题描述

修改院系信息，由于名字过长，导致出现图1的自动换行现象，将名字去掉一个字之后，恢复正常。
![image](https://user-images.githubusercontent.com/34886627/190838516-9a312b46-bc5e-44af-9f2f-157144eaefea.png)
![image](https://user-images.githubusercontent.com/34886627/190838524-fc6cf9bf-26bd-4fa9-9127-cc17bdce1b4a.png)

**Comment by TheNetAdmin** [comment]
https://github.com/TheNetAdmin/zjuthesis/blob/38da3fd02cc1f5f110ccbe64e801937a3b6b2d9e/zjuthesis.tex#L49

先搜索再提问，类似问题讨论过多次了

**Comment by MforU** [comment]
谢谢 我搜索了一下 没有找到 《博士开题报告》的相关功能，请问是有什么设置的地方吗？不好意思打扰啦

**Comment by TheNetAdmin** [comment]
#237
