### ISSUE TITLE
标题默认如何修改成一行，封面超出一页

### ISSUE THREAD

**Issue by shallowdream-x** [TheNetAdmin/zjuthesis#274]
### 操作系统

MacOS

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

1. 论文的中文标题和英文标题默认都是两行，应该如何修改成一行？
2. 全部使用默认时出的pdf封面会多出一行到第二页，应该如何解决呢，这个问题我在overleaf上编译不会出现，但在mac平台上就会出现，使用的是texlive2022

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/9755207/zjuthesis.log)

### 代码

完全是源代码，只进行了一些设置修改
\documentclass[
    % Debugging Settings
    PrintFilePath   = false,            % print tex file path for each page
    % Layout Settings
    TwoSide         = true,             % set to false if don't need empty pages
    % Thesis Info
    StudentName     = 姓名,
    StudentID       = 学号,
    AdvisorName     = 指导教师,
    Grade           = 2014,            % only the year, no '级'
    Major           = 专业,
    Department      = 学院,
    SubmitDate      = 递交日期,
    MajorFormat     = general,
    Degree          = graduate,   % 'undergraduate' or 'graduate'
    Type            = thesis,          % 'thesis'   or 'design'
    Period          = final,           % 'proposal' or 'paper' or 'final'
    BlindReview     = false,           % 'false'    or 'true'
    Language        = chinese,         % 'chinese'  or 'english'
    % Graduate Thesis Info
    GradLevel       = master,          % 'master' or 'doctor'
    Topic           = 研究方向,
    ColaboratorName = 合作导师,
    % Title
    Title           = 毕业论文/设计题目,
    TitleEng        = {{Graduation Thesis Title}}
]{zjuthesis}

%% Uncomment the following lines if you need multi line titles on cover pages
% \titletwolines{毕业论文题目第一行}{毕业论文题目第二行}
% \titleengtwolines{English Title Line One}{Englisht Title Line Two}

%% Uncomment the following lines if you need multi line department names on cover pages
% \departmenttwolines{学院名第一行}{学院名第二行}

### 截图

<img width="446" alt="image" src="https://user-images.githubusercontent.com/44127914/195089739-2d7a53d9-a840-4d69-93b4-7212b9683135.png">

**Comment by cfzd** [comment]
@shallowdream-x @TheNetAdmin 
同问

**Comment by TheNetAdmin** [comment]
看样子似乎是垂直间距略大了一些导致页面溢出了，原因可能是新版的texlive里某些默认间距处理方式有所变化。

这种情况下不需要删除第二行标题，只需要略微减小垂直间距即可，研究生模板页面间距设定在这里

https://github.com/TheNetAdmin/zjuthesis/blob/master/page/graduate/cover-chn.tex

适当减少 `\vspace{}` 值应该就可以解决问题，比如将

https://github.com/TheNetAdmin/zjuthesis/blob/38da3fd02cc1f5f110ccbe64e801937a3b6b2d9e/page/graduate/cover-chn.tex#L18

修改为 `\vspace{-35pt}` 试试

**Comment by FightingYu** [comment]
> 

减少数值还是有问题，不过我发现我是因为英文名字太长导致，将名字缩短或者盲审不打印这些信息的时候就不会出现溢出到第二页。

**Comment by TheNetAdmin** [comment]
> > 
> 
> 减少数值还是有问题，不过我发现我是因为英文名字太长导致，将名字缩短或者盲审不打印这些信息的时候就不会出现溢出到第二页。

标题处于一个表格环境，可以尝试加宽那个表格，具体操作在之前的github issue里有提到，搜一下试试吧

**Comment by cfzd** [comment]
@shallowdream-x @FightingYu @TheNetAdmin 
因为负的space表示减少间距，而那个vspace的位置又在封面页的上方，所以我通过
`
\vspace{-50pt}
`
解决了这个问题。FYI.

**Comment by TheNetAdmin** [comment]
> @shallowdream-x @FightingYu @TheNetAdmin 因为负的space表示减少间距，而那个vspace的位置又在封面页的上方，所以我通过 `\vspace{-50pt}` 解决了这个问题。FYI.

哦确实是这样，我之前说反了

**Comment by wangxxxxx1996** [comment]
> 看样子似乎是垂直间距略大了一些导致页面溢出了，原因可能是新版的texlive里某些默认间距处理方式有所变化。
> 
> 这种情况下不需要删除第二行标题，只需要略微减小垂直间距即可，研究生模板页面间距设定在这里
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/master/page/graduate/cover-chn.tex
> 
> 适当减少 `\vspace{}` 值应该就可以解决问题，比如将
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/38da3fd02cc1f5f110ccbe64e801937a3b6b2d9e/page/graduate/cover-chn.tex#L18
> 
> 修改为 `\vspace{-50pt}` 试试

这样确实让所有行在一页中显示了，但多了一个空白页
