### ISSUE TITLE
目录部分编号问题

### ISSUE THREAD

**Issue by FightingYu** [TheNetAdmin/zjuthesis#275]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.0.0

### MajorFormat

cs

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

目录前面部分，致谢、摘要等序号编号不连贯，应该在哪里设置。

### 截图

![image](https://user-images.githubusercontent.com/75256893/196719070-e81404a9-dcb5-4960-bab8-589e31fda59b.png)

**Comment by TheNetAdmin** [comment]
什么编号？右侧的是页码不是章节编号

**Comment by FightingYu** [comment]
> 什么编号？右侧的是页码不是章节编号
哦哦，是我看错了
