### ISSUE TITLE
texstudio编译速度较长，请问大家如何提升编译速度

### ISSUE THREAD

**Issue by Admin-OF-Admin** [TheNetAdmin/zjuthesis#277]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

proposal

### BlindReview

true

### GradLevel

doctor

### 问题描述

如题，采用texstudio进行编译，目前只有30来页，但编译一次需要大几十秒，参考了网上的一个意见，但是没什么效果，想请问大家有没有什么加快编译速度的好方法呢？附上链接，https://blog.csdn.net/weixinhum/article/details/121056868

**Comment by TheNetAdmin** [comment]
试试命令行编译要多久？中文的latex相对来讲都要编译很久，我忘记我本科毕业论文当时的编译时间了，不过印象里时间不短。
