### ISSUE TITLE
目录的格式问题

### ISSUE THREAD

**Issue by ZJUDestiny** [TheNetAdmin/zjuthesis#28]
**遇到的问题**
光电学院本科生毕业设计开题报告和论文的模板中，一级标题为黑体小四，其余字体为仿宋小四（具体可见图片），latex编译的模板结果均为仿宋小四，请问这个该怎么改动

**截图**

模板截图：
![模板](https://user-images.githubusercontent.com/34738171/70858047-0a9cd700-1f35-11ea-948c-78695a432da9.png)
Latex截图：
![latex结果](https://user-images.githubusercontent.com/34738171/70858051-125c7b80-1f35-11ea-8c30-3debdf2d4bbc.png)

**环境**
 - zjuthesis版本: [4.2.1]

 - OS: [windows]
 - Tex套件: [Texlive]
 - Tex套件版本: [2019]
 - XeLaTex版本: (请附上`xelatex --version`命令的所有输出)
``` shell
XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX)
kpathsea version 6.3.1
Copyright 2019 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 63.1; using 63.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.9.1; using 2.9.1
Compiled with Graphite2 version 1.3.13; using 1.3.13
Compiled with HarfBuzz version 2.3.1; using 2.3.1
Compiled with libpng version 1.6.36; using 1.6.36
Compiled with poppler version 0.68.0
Compiled with fontconfig version 2.13.1; using 2.13.1
```

**其他信息**
其他你认为有帮助的信息

**Comment by LirongWu** [comment]
请问可以分享一下具体是怎么修改的吗？？感谢！！

**Comment by TheNetAdmin** [comment]
改这里试试看

https://github.com/TheNetAdmin/zjuthesis/blob/0e545cba40d481106df708c2a8d1d53f306fb990/config/format/general/layout.tex#L123
