### ISSUE TITLE
无法使用latexmk 生成参考文献

### ISSUE THREAD

**Issue by KailinXu** [TheNetAdmin/zjuthesis#282]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

不太清楚

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

您好，感谢您的工作。我在编译参考文献的时候，使用`latexmk -xelatex -outdir=out zjuthesis`仍无法得到参考文献。
我结构上只是对zjuthesis.tex进行了更改

这个是当前的代码
\usepackage{amsmath}
\usepackage{enumerate}
\usepackage{colortbl}

\usepackage{algorithm,algorithmic}
\usepackage{lipsum}
\usepackage{enumitem}
\usepackage{diagbox}
\usepackage{booktabs}
\usepackage{subfig}

\makeatletter
\newenvironment{breakablealgorithm}
  {% \begin{breakablealgorithm}
   \begin{center}
     \refstepcounter{algorithm}% New algorithm
     \hrule height.8pt depth0pt \kern2pt% \@fs@pre for \@fs@ruled 画线
     \renewcommand{\caption}[2][\relax]{% Make a new \caption
       {\raggedright\textbf{\ALG@name~\thealgorithm} ##2\par}%
       \ifx\relax##1\relax % #1 is \relax
         \addcontentsline{loa}{algorithm}{\protect\numberline{\thealgorithm}##2}%
       \else % #1 is not \relax
         \addcontentsline{loa}{algorithm}{\protect\numberline{\thealgorithm}##1}%
       \fi
       \kern2pt\hrule\kern2pt
     }
  }{% \end{breakablealgorithm}
     \kern2pt\hrule\relax% \@fs@post for \@fs@ruled 画线
   \end{center}
  }
\makeatother

\def\allfiles{}
\begin{document}

\coverstyle
\inputpage{cover}

\prevstyle
\inputpage{previous}
\inputpage{toc}

% Main contents
\bodystyle
\input{./body/graduate/chap1}
\input{./body/graduate/chap2}
\input{./body/graduate/chap3}
\input{./body/graduate/chap4}
\input{./body/graduate/chap5}

% Post part
\poststyle
\inputbody{post}
\end{document}

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/10187287/zjuthesis.log)

### 其他信息

一天前是能够顺利使用的，后面加了文字和一些新的文献就无法使用了。
之前也出现过类似的情况，两个小时后自动好了，未找到原因。

**Comment by TheNetAdmin** [comment]
把中间文件全部删除然后重新编译

**Comment by KailinXu** [comment]
您好，感谢您的回复，中间文件全部删除然后重新编译我试了，也没有用
后来我发现是bib文件中缺少了一个 逗号，导致无法编译成功，但是这个在log里面确实也没体现，下面是唯一的相关语句
LaTeX Warning: Citation 'zhou2021m' on page 15 undefined on input line 80.
加上逗号就可以了，感谢~
