### ISSUE TITLE
如何使用三行标题

### ISSUE THREAD

**Issue by Ryangyan** [TheNetAdmin/zjuthesis#283]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

两行命令是这个\titleengtwolines{}{}，但是因为标题过长需要使用三行，请问要怎么做呢？

**Comment by jhinkoo331** [comment]
遇到了同样的问题，求助 ;-)

**Comment by YJ131gG0D** [comment]
标题是用tabularx的表格渲染的，代码在page/cover-chn.tex里，需要三行的话手改一下英文论文题目的代码即可，但是三行会让下面的信息超出页面，我的做法是改标题的字体
![image](https://user-images.githubusercontent.com/39871494/208233476-9df343f6-5dac-49f5-9c11-ab1088a61ffe.png)

**Comment by Ryangyan** [comment]
> 标题是用tabularx的表格渲染的，代码在page/cover-chn.tex里，需要三行的话手改一下英文论文题目的代码即可，但是三行会让下面的信息超出页面，我的做法是改标题的字体和表格的宽度 ![image](https://user-images.githubusercontent.com/39871494/208233570-30eac7f1-6b33-481c-9dee-62102585627f.png)

感谢，非常有用

**Comment by Ryangyan** [comment]
已解决

**Comment by haidaojuntuan** [comment]
> 标题是用tabularx的表格渲染的，代码在page/cover-chn.tex里，需要三行的话手改一下英文论文题目的代码即可，但是三行会让下面的信息超出页面，我的做法是改标题的字体和表格的宽度 ![image](https://user-images.githubusercontent.com/39871494/208233570-30eac7f1-6b33-481c-9dee-62102585627f.png)

请问大佬如果确实需要三行以上的英文标题，如何去修改代码呢？

**Comment by YJ131gG0D** [comment]
把英文标题那边往下加行就可以
![image](https://user-images.githubusercontent.com/39871494/218243723-6375299a-c7c3-4c94-a658-b0c8beaf372e.png)
