### ISSUE TITLE
想请问一下该模板可以在texpad上运行嘛

### ISSUE THREAD

**Issue by yangye19960922** [TheNetAdmin/zjuthesis#284]
### 操作系统

MacOS

### TeX 套件

其他（请在问题描述中标明）

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

刚刚下载了这个模板，运行zjuthesis.tex可以成功运行，但是不知道为甚么怎么双击都没办法打开body文件夹下的content.tex文件进行内容编辑。

**Comment by TheNetAdmin** [comment]
没用过这个工具，建议自行搜索工具用法，我无法解答任何与工具有关的问题，只能解答与模板本身有关的问题
