### ISSUE TITLE
如何不生成图目录

### ISSUE THREAD

**Issue by ainokiseki** [TheNetAdmin/zjuthesis#285]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

9.0.0

### MajorFormat

cs

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

RT，尝试注释了若干语句，但都不对

**Comment by TheNetAdmin** [comment]
删掉以下几行

https://github.com/TheNetAdmin/zjuthesis/blob/7782d7341d93a06b3582160e66f5006fa4657b17/page/graduate/toc.tex#L9-L12
