### ISSUE TITLE
正文前页格式调整求助   感谢！！

### ISSUE THREAD

**Issue by FlotingDream** [TheNetAdmin/zjuthesis#286]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2020

### TeX Compiler

XeTeX

### zjuthesis 版本号

9.0.0

### MajorFormat

isee

### Degree

graduate

### Type

design

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

主要是关于正文前页格式调整求助。感谢！！ 
a.下边截了师兄的毕业论文图1。下边红色标注的图1是主要需要求助的部分，非常感谢！(ps 前页奇偶页眉好像没有加上)
b.如果能知道图2的表格怎么设置就更好了  感谢感谢！！！
c.一级标题（绪论 第二章啥的）跟“”目  次“”的上下位置是一样的例如图3，可能的话能不能教教我咋改。感谢感谢！！！
d.目前情况如图4   非常感谢！！
图1
![image](https://user-images.githubusercontent.com/50733815/208299893-e5567973-304b-4bfe-912e-12b1ca143262.png)
图2
![image](https://user-images.githubusercontent.com/50733815/208301545-1e0fb6b2-4a6f-424c-b911-703f50dd93a1.png)
图3
![image](https://user-images.githubusercontent.com/50733815/208300391-53fa1ad2-bd5e-4b75-95a3-f887d89c9099.png)
图4
![image](https://user-images.githubusercontent.com/50733815/208300487-6dc49056-54ea-4a91-8acd-b28d47367c3f.png)

**Comment by TheNetAdmin** [comment]
> 主要是关于正文前页格式调整求助。感谢！！
> a.下边截了师兄的毕业论文图1。下边红色标注的图1是主要需要求助的部分，非常感谢！(ps 前页奇偶页眉好像没有加上)

没太看懂你这里具体要达成什么效果

> b.如果能知道图2的表格怎么设置就更好了 感谢感谢！！！

直接在下方文件填写表格，如需去掉表格线请自行查阅latex表格使用方式

https://github.com/TheNetAdmin/zjuthesis/blob/7782d7341d93a06b3582160e66f5006fa4657b17/page/graduate/term-translation.tex

> c.一级标题（绪论 第二章啥的）跟“”目 次“”的上下位置是一样的例如图3，可能的话能不能教教我咋改。感谢感谢！！！

图3里没有 “目次”，不知道你的需求是什么

> d.目前情况如图4 非常感谢！！
