### ISSUE TITLE
关于/chapter和/chapternonum格式不统一

### ISSUE THREAD

**Issue by shallowdream-x** [TheNetAdmin/zjuthesis#288]
### 操作系统

MacOS

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

最新

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

控制学院论文要求对无编号标题（致谢，摘要，目录和参考文献）的字号要求（三号）和chapter的字号（小三号）要求不一样，我看模板里对于无编号标题用的是/chapternonum直接使用了/chapter的格式，那么如果字号不一致的话应该如何修改呢？感谢🙏

**Comment by TheNetAdmin** [comment]
修改以下这行

https://github.com/TheNetAdmin/zjuthesis/blob/7782d7341d93a06b3582160e66f5006fa4657b17/config/commands.tex#L110

参考这行上方本科生的设置

https://github.com/TheNetAdmin/zjuthesis/blob/7782d7341d93a06b3582160e66f5006fa4657b17/config/commands.tex#L23-L32

**Comment by shallowdream-x** [comment]
我也尝试过这样设置，设置之后会是这样，
<img width="507" alt="image" src="https://user-images.githubusercontent.com/44127914/208870643-9f692de3-f07c-4b92-a91b-f35be99181c8.png">
但这样我不知道该怎么设置段前和段后间距，要求段前24磅和段后18磅，
在之前的issue里看到尝试过在摘要前后加入\vspace{24pt}和\vspace{18pt}就会变成这个样子
<img width="516" alt="image" src="https://user-images.githubusercontent.com/44127914/208871417-e4287d4d-3a0f-4362-8671-11412a384f21.png">

**Comment by TheNetAdmin** [comment]
段前段后间距会被latex自动调整，如果不影响整体版面可以不用在意
