### ISSUE TITLE
如何去掉previous部分中的空白页

### ISSUE THREAD

**Issue by shallowdream-x** [TheNetAdmin/zjuthesis#289]
### 操作系统

MacOS

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

最新

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

学院要求只有正文部分需要空白页,previous部分不需要空白页,想求助一下怎么实现
我尝试了将previous部分的所有的/cleardoublepage替换成了/clearpage,但结果是中文摘要和英文摘要之间还会出现一页的空页,后来尝试之后发现是\chapternonum的原因,如果把\chapternonum删掉就不会多出一页空白页了,貌似是因为\chapternonum里面使用了\chapter的格式,里面是有\cleardoublepage的,因为正文部分还是需要空白页的,所以就产生矛盾了,想请教一下这个该如何解决.感谢🙏

**Comment by TheNetAdmin** [comment]
那就仿照本科生的 \chapternonum 重新定义研究生版本的这个宏，本科生版本的宏如下

https://github.com/TheNetAdmin/zjuthesis/blob/7782d7341d93a06b3582160e66f5006fa4657b17/config/commands.tex#L23-L32

**Comment by TheNetAdmin** [comment]
然后为 previous 页里单独定义一个特殊的宏例如 \chapternonumprevious 里面改用 \clearpage 就行
