### ISSUE TITLE
目录与光电模板格式不一致

### ISSUE THREAD

**Issue by ZJUDestiny** [TheNetAdmin/zjuthesis#29]
**遇到的问题**
光电学院本科生毕业设计的开题报告的模板中的目录格式与模板格式不一致
**重现步骤**
正常编译运行

请附上修改过的文件/工程

如果无法编译，请额外附上 log 文件，位于 out/zjuthesis.log

**截图**
光电模板：
![opt](https://user-images.githubusercontent.com/34738171/70922855-c529f800-2061-11ea-9af5-63490860f71e.PNG)
latex结果：
![latex](https://user-images.githubusercontent.com/34738171/70922870-cce99c80-2061-11ea-9dd0-09bb66ae6d9c.PNG)

**环境**
 - zjuthesis版本: [4.2.2]
- zjuthesis基础设置 **请将如下代码替换为你的`\documentclass`代码，注意隐藏个人信息**
```
\documentclass[
    StudentName = 姓名,
    StudentID   = 学号,
    AdvisorName = 指导教师,
    Grade       = 2014,
    Major       = 专业,
    Department  = 学院,
    Title       = 毕业论文/设计题目,
    SubmitDate  = 递交日期,
    MajorFormat = general,
    Degree      = undergraduate,
    Type        = thesis,
    Period      = final,
    BlindReview = false,
    Topic           = 研究方向,
    ColaboratorName = 合作导师
]{config/zjuthesis}
```
 - OS: [Windows]
 - Tex套件: [Texlive]
 - Tex套件版本: [2019]
 - XeLaTex版本: (请附上`xelatex --version`命令的所有输出)
``` shell
XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX)
kpathsea version 6.3.1
Copyright 2019 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 63.1; using 63.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.9.1; using 2.9.1
Compiled with Graphite2 version 1.3.13; using 1.3.13
Compiled with HarfBuzz version 2.3.1; using 2.3.1
Compiled with libpng version 1.6.36; using 1.6.36
Compiled with poppler version 0.68.0
Compiled with fontconfig version 2.13.1; using 2.13.1
```

**其他信息**
其他你认为有帮助的信息

**Comment by TheNetAdmin** [comment]
Word模板文件可以贴一下么

**Comment by TheNetAdmin** [comment]
看上去你们的模板里，考核表一项并不属于目录，像是直接打字上去的。

LaTeX里做这种事情比较麻烦，一个简单的解决办法是给LaTeX考核表的标题加个书名号，这样目录项也随之改变了。

**Comment by ZJUDestiny** [comment]
> Word模板文件可以贴一下么


[开题报告模板.docx](https://github.com/TheNetAdmin/zjuthesis/files/3971137/default.docx)

**Comment by ZJUDestiny** [comment]
> 看上去你们的模板里，考核表一项并不属于目录，像是直接打字上去的。
> 
> LaTeX里做这种事情比较麻烦，一个简单的解决办法是给LaTeX考核表的标题加个书名号，这样目录项也随之改变了。

最终考核表那一页的格式是与Latex里面一致的，只有目录不一致。好像光电本科最终论文的目录格式也是与Latex的模板不一致的。

**Comment by TheNetAdmin** [comment]
![image](https://user-images.githubusercontent.com/18525442/70961612-4793d580-20bd-11ea-9a1a-36c11d26ab45.png)

这个 `《浙江大学本科生文献综述和开题报告考核表》` 就不是目录的一部分……

如果你真的想要这个效果的话，我试试看能不能实现一下，过一会儿我贴代码在这里。

**Comment by TheNetAdmin** [comment]
定义这个新命令

```latex
\newcommand{\chapternonumtmp}[2]
{
    \phantomsection
    \addcontentsline{toc}{chapter}{#2}
    \begin{center}
        \bfseries \zihao{3} #1
    \end{center}
}
```

第一个参数是标题名，第二个参数是目录项名

然后在考核页内使用

```latex
\chapternonumtmp{浙江大学本科生文献综述和开题报告考核表}{《浙江大学本科生文献综述和开题报告考核表》}
```

**Comment by AlexPhoon** [comment]
```
\newcommand{\chapternonumtmp}[2]
{
    \phantomsection
    \addcontentsline{toc}{chapter}{#2}
    \begin{center}
        \bfseries \zihao{3} #1
    \end{center}
}
```
请问这个新的命令是加在哪个地方呢？

**Comment by TheNetAdmin** [comment]
> ```
> \newcommand{\chapternonumtmp}[2]
> {
>     \phantomsection
>     \addcontentsline{toc}{chapter}{#2}
>     \begin{center}
>         \bfseries \zihao{3} #1
>     \end{center}
> }
> ```
> 请问这个新的命令是加在哪个地方呢？

zjutgesis.cls的末尾

**Comment by AlexPhoon** [comment]
好的谢谢！

还有请问你说的 “第一个参数是标题名，第二个参数是目录项名” ，指的是这样吗？

```
\newcommand{\chapternonumtmp}[2]
{
    \phantomsection
    \addcontentsline{toc}{chapter}{《浙江大学本科生文献综述和开题报告考核表》}
    \begin{center}
        \bfseries \zihao{3}{浙江大学本科生文献综述和开题报告考核表}
    \end{center}
}
```
我加了之后目录是多了一项：

![image](https://user-images.githubusercontent.com/95166337/157163884-7c53cb2b-3e4e-4d8c-8da5-8f741ca5531a.png)

然后在考核页内也多了一行字：

![image](https://user-images.githubusercontent.com/95166337/157163659-70870631-5721-4b37-9e98-302117a3fe9d.png)

**Comment by AlexPhoon** [comment]
> > ```
> > \newcommand{\chapternonumtmp}[2]
> > {
> >     \phantomsection
> >     \addcontentsline{toc}{chapter}{#2}
> >     \begin{center}
> >         \bfseries \zihao{3} #1
> >     \end{center}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问这个新的命令是加在哪个地方呢？
> 
> zjutgesis.cls的末尾

好的谢谢~

**Comment by Shanque469636** [comment]
> > ```
> > \newcommand{\chapternonumtmp}[2]
> > {
> >     \phantomsection
> >     \addcontentsline{toc}{chapter}{#2}
> >     \begin{center}
> >         \bfseries \zihao{3} #1
> >     \end{center}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问这个新的命令是加在哪个地方呢？
> 
> zjutgesis.cls的末尾

请问如何只保留文字部分，不需要“……页码”的后半部分，感谢
