### ISSUE TITLE
编译的PDF不显示参考文献目录，以及引用文献的上标不是数字

### ISSUE THREAD

**Issue by yangye19960922** [TheNetAdmin/zjuthesis#290]
### 操作系统

MacOS

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

doctor

### 问题描述

可以正常编译，但是不显示参考文献的目录。还有一个问题就是，引用的文献，显示的上标不是数字，并且会出现超出页面宽度的问题。
<img width="581" alt="image" src="https://user-images.githubusercontent.com/36871131/209901725-cd8c9b4d-e292-4afd-9842-b2318e9a8237.png">

### 截图

<img width="566" alt="image" src="https://user-images.githubusercontent.com/36871131/209901652-c8b17a6c-e68c-4222-92db-3ce5858deaf2.png">

<img width="571" alt="image" src="https://user-images.githubusercontent.com/36871131/209901643-8c2bbe86-194d-46f4-a551-6f5a993a9a22.png">

**Comment by TheNetAdmin** [comment]
参考 readme 里的使用方式，你这里应该没有用 latexmk 去编译

**Comment by DongDaYo** [comment]
@TheNetAdmin 大佬您好，请问我用latexmk命令去编译了，还是出现这种情况了，怎么回事呀？

终端命令：
![Image](https://github.com/user-attachments/assets/e4ce962e-77b7-4819-8a6e-d450b49d41b2)
效果：

![Image](https://github.com/user-attachments/assets/d853dc03-dd47-4820-b6c5-8a45f47dff1f)
那个工字的右上角不太对

**Comment by LeHan-ZJU** [comment]
遇到了相同的问题，求问怎么解决的？
