### ISSUE TITLE
表头有“浙江大学硕士论文”字样，盲审前要去掉吗？

### ISSUE THREAD

**Issue by yangyuke001** [TheNetAdmin/zjuthesis#294]
### 可改进的内容

请问盲审前，论文中的表头有“浙江大学硕士论文”字样，盲审前要去掉吗？
如果要去掉，改怎么改呢？

感谢感谢！

**Comment by TheNetAdmin** [comment]
那就临时将如下宏里的文字改成空白吧

https://github.com/TheNetAdmin/zjuthesis/blob/7782d7341d93a06b3582160e66f5006fa4657b17/zjuthesis.cls#L93-L104
