### ISSUE TITLE
图片在同一section下会重新标号

### ISSUE THREAD

**Issue by shenyaojin** [TheNetAdmin/zjuthesis#298]
### 操作系统

Linux

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

其他（请在问题描述中标明）

### zjuthesis 版本号

9.0.0

### MajorFormat

general

### Degree

undergraduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

1. 在文献综述中插入数张图片
2. 使用默认设定（下载完模板后只执行1中操作），在根目录使用 **xelatex zjuthesis.tex
**编译。编译无报错。
3. 在同一个Section内，下面的三张图应该保持2.1, 2.2, 2.3输出
![image](https://user-images.githubusercontent.com/106902466/212548509-ee35c4ea-903f-416d-8833-07183c774ad6.png)
4. 但是第三张图重新回到2.1输出。

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/10420458/zjuthesis.log)

### 代码

如何复现问题：
```Tex
% /body/undergraduate/proposal/review/review.tex
\cleardoublepage
\newrefsection
\chapter{文献综述}

\section{背景介绍}
\par 正文格式与具体要求\cite{zjuthesisrules}

\subsection{小节}

\subsubsection{小节}

\section{国内外研究现状}

\subsection{研究方向及进展}

\begin{figure}[H]
    \centering
    \includegraphics[width=.2\linewidth]{logo/zju}
    \caption{\label{fig:zju-logo}浙江大学LOGO}
\end{figure}

\begin{figure}[H]
    \centering
    \includegraphics[width=.2\linewidth]{logo/zju}
    \caption{\label{fig:zju-logo1}浙江大学LOGO}
\end{figure}

\subsection{存在问题}

\begin{figure}[H]
    \centering
    \includegraphics[width=.2\linewidth]{logo/zju}
    \caption{\label{fig:zju-logo2}浙江大学LOGO}
\end{figure}

\section{研究展望}

\newpage
\begingroup
    \linespreadsingle{}
    \printbibliography[title={参考文献}]
\endgroup
```

原文件：
```Tex
\cleardoublepage
\newrefsection
\chapter{文献综述}

\section{背景介绍}
\par 正文格式与具体要求\cite{zjuthesisrules}

\subsection{小节}

\subsubsection{小节}

\section{国内外研究现状}

\subsection{研究方向及进展}

\subsection{存在问题}

\section{研究展望}

\newpage
\begingroup
    \linespreadsingle{}
    \printbibliography[title={参考文献}]
\endgroup
```

**Comment by TheNetAdmin** [comment]
可能是 #291 提到的问题，请尝试一下那里提出的解决办法，如果可行的话我就尽快修复一下

**Comment by shenyaojin** [comment]
> 可能是 #291 提到的问题，请尝试一下那里提出的解决办法，如果可行的话我就尽快修复一下

您是指调换下面的(1)和(2)吗？我尝试过问题依然存在😭


> ```
> \newcommand{\numberingstyle}
> {
>     \ifthenelse{\equal{\Degree}{undergraduate}}
>     {
>         \ifthenelse{\equal{\undergradcurrstage}{proposal}}
>         {
>             \chaptermajornumbering %(1)
>         }
>         {
>             \sectionmajornumbering %(2)
>         }
>     }
>     {
>         \chaptermajornumbering
>     }
> }
> ```

**Comment by TheNetAdmin** [comment]
Should be fixed now.
