### ISSUE TITLE
如何实现换章（chapter）不换页？

### ISSUE THREAD

**Issue by PeepYXB** [TheNetAdmin/zjuthesis#299]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

大佬好，感谢您的模板！非常有用！目前我遇到问题是这样的：
我对master final模板进行更改，用于攥写**个人读书报告**。
但我报告的实际情况是总章节数很多，而每章里的内容并不多，所以不希望在`\chapter`命令后自动翻页，这会显得报告空白面积很多，我希望能在同一页内继续新的chapter，就像图里这样，请问该如何修改代码？
<img src="https://user-images.githubusercontent.com/85994418/217028742-45903d72-40aa-4151-bfff-09fef8b1d657.jpg" width="500px">

**Comment by note286** [comment]
我建议你用`article`类，而不是`book`类。
