### ISSUE TITLE
texlive2018编译问题

### ISSUE THREAD

**Issue by FengHZ** [TheNetAdmin/zjuthesis#3]
用texlive2018编译会在使用包`\usepackage{chngcntr}`时报错，似乎是因为本身的版本问题。在该语句前加
```
\let\counterwithout\relax
\let\counterwithin\relax
```
可以解决。

**Comment by TheNetAdmin** [comment]
尝试tlmgr update --self --all升级一下呢

**Comment by FengHZ** [comment]
@TheNetAdmin 升级有效~错误不会重现了~该问题可以关闭~

**Comment by TheNetAdmin** [comment]
OK，issue关闭，如有问题可以重开。
