### ISSUE TITLE
参考文献列表的问题

### ISSUE THREAD

**Issue by Zhengxinyang** [TheNetAdmin/zjuthesis#30]
**遇到的问题**
文献综述和开题报告公用一个参考文献列表，如果希望这两个列表不一样该如何修改（比如文献综述引用了10篇文献，开题报告引用了20篇文献，这两个的参考文献列表应该是不一样的）

<img width="349" alt="image" src="https://user-images.githubusercontent.com/31161448/71309987-6097e000-2449-11ea-92b8-ccf06c8c5837.png">

**环境**
 - zjuthesis版本: [e.g. 4.2.1]
- zjuthesis基础设置 **请将如下代码替换为你的`\documentclass`代码，注意隐藏个人信息**
```
\documentclass[
    StudentName = 姓名,
    StudentID   = 学号,
    AdvisorName = 指导教师,
    Grade       = 2014,
    Major       = 专业,
    Department  = 学院,
    Title       = 毕业论文/设计题目,
    SubmitDate  = 递交日期,
    MajorFormat = general,
    Degree      = undergraduate,
    Type        = thesis,
    Period      = proposal,
    BlindReview = false,
    Topic           = 研究方向,
    ColaboratorName = 合作导师
]{config/zjuthesis}
```
 - OS: [MacOS]
 - Tex套件: [Texlive]
 - Tex套件版本: [e.g. 2018]
 - XeLaTex版本: (请附上`xelatex --version`命令的所有输出)
``` 
XeTeX 3.14159265-2.6-0.99999 (TeX Live 2018)
kpathsea version 6.3.0
Copyright 2018 SIL International, Jonathan Kew and Khaled Hosny.
```

**Comment by hushidong** [comment]
同一个文档内部有多个不同的文献表，可以使用refsection环境，把两个不同部分用该环境包起来，然后在其内部使用printbibliography

**Comment by hushidong** [comment]
用法可以参考
https://github.com/hushidong/biblatex-solution-to-latex-bibliography

**Comment by TheNetAdmin** [comment]
@huishidon 感谢提供了解决方案，不过需要注意的是我这个模板里用了\newrefsection ，这个似乎和 refsection 环境不能嵌套，所以 @Zhengxinyang 你注意要把模板里已有的 \newrefsection 改成 refsection 环境

**Comment by Zhengxinyang** [comment]
感谢

**Comment by Zhengxinyang** [comment]
> 同一个文档内部有多个不同的文献表，可以使用refsection环境，把两个不同部分用该环境包起来，然后在其内部使用printbibliography

感谢

**Comment by ZJUGuoShuai** [comment]
我发现只要在`proposal.tex`前面这里加个`\newrefsection`即可。
![image](https://user-images.githubusercontent.com/22856433/77839618-fc578b80-71b0-11ea-87f6-6c27d9e13ec8.png)
