### ISSUE TITLE
section, subsection, subsubsection 前后的垂直距离无法改变

### ISSUE THREAD

**Issue by Ed0806** [TheNetAdmin/zjuthesis#300]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

9.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

doctor

### 问题描述

在初始模板，其他地方均没有修改，我想缩小一下section, subsection, subsubsection 前后的垂直距离，我通过修改config/format/general/heading.tex文件中对应section, subsection, subsubsection中的beforeskip和afterskip的值没有效果，想问一下是不是我操作有误还是其他原因。

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/10709643/zjuthesis.log)

### 截图

![image](https://user-images.githubusercontent.com/42117385/218151210-68e370ef-12fd-4edc-b15e-d90bf4770ae1.png)

**Comment by TheNetAdmin** [comment]
属于ctex的设置问题，这些skip值是为ctex提供建议的间距值，并非一定能改变间距，请到ctex的GitHub寻求帮助，或查阅相关解决方式

**Comment by Ed0806** [comment]
好的 谢谢大佬！
