### ISSUE TITLE
fonts.tex \setCJKfamilyfont处报错-missing \begin{document}

### ISSUE THREAD

**Issue by michaelungs** [TheNetAdmin/zjuthesis#302]
### 操作系统

Linux

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

7782d73

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

在`config/format/general/fonts.tex`第46行，提示报错：`Missing \begin{document}`。若注释第12~50行代码，则能编译通过。

### 编译日志

*************************************************
* xeCJK warning: "CJKfamily-redef"
* 
* Redefining CJKfamily `zhfs' (FandolFang-Regular).
*************************************************

./config/format/general/fonts.tex:44: LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.

**Comment by TheNetAdmin** [comment]
看上去像是linux下的字体设置问题，你可以执行`bash script/ci/setup.sh`来设置字体环境，应该可以解决问题
