### ISSUE TITLE
博士开题报告格式不对

### ISSUE THREAD

**Issue by Lucas-Wye** [TheNetAdmin/zjuthesis#307]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

9.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

latexmk编译，博士论文开题报告模板不对，标题里面没有开题报告

### 截图

![image](https://user-images.githubusercontent.com/30680577/224925115-3e7e88d9-606e-4e6a-8abe-a49f2a808018.png)

正常的模板应该是：

![image](https://user-images.githubusercontent.com/30680577/224925202-e042431e-fb36-4542-aa35-e1ad6692f801.png)

**Comment by TheNetAdmin** [comment]
我之前没有见过博士的开题报告模板，请新开一个enhancement issue并附上模板，我修改一下当前的研究生模板应该就可以了
