### ISSUE TITLE
[BUG] 插图和附表的序号问题（符号序号未知是否存在此问题）

### ISSUE THREAD

**Issue by philosophy-signal** [TheNetAdmin/zjuthesis#31]
**遇到的问题**
插图和附表的序号是分章独立的，例如第二章第一节的第一张图片的序号是1.1，第三章第一节的第一张图片的序号也是1.1，附表的序号也出现相同的状况。那么在插图清单和附表清单中，序号就有重复。是否第二章第一节的第一张图片的序号定义为2.1.1，第三章第一节的第一张图片的序号定义为3.1.1 会更好？

**Comment by TheNetAdmin** [comment]
请附上你的代码，截图，和documentclass设定

**Comment by TheNetAdmin** [comment]
你说的大概是本科生模板的开题报告部分吧，我正在修复，初步修复代码已经在master分支上了 https://github.com/TheNetAdmin/zjuthesis/commit/aaee47d3aeaed532fb33676edcfd046fc91ad515

后续会发release

**Comment by philosophy-signal** [comment]
> 你说的大概是本科生模板的开题报告部分吧，我正在修复，初步修复代码已经在master分支上了 [aaee47d](https://github.com/TheNetAdmin/zjuthesis/commit/aaee47d3aeaed532fb33676edcfd046fc91ad515)
> 
> 后续会发release

抱歉近期忙碌所以没有及时回复，我用的CS专业的研究生模板。我更新了模板后，之前的问题已不存在。另有一问，之前在目录栏中有插图清单、附表清单，现在为什么取消了呢？
