### ISSUE TITLE
Latexmk编译报错

### ISSUE THREAD

**Issue by DarkDog74** [TheNetAdmin/zjuthesis#312]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

9.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

vscode latexmk编译报错

### 截图

![image](https://user-images.githubusercontent.com/35954871/227289198-8bde4206-1f62-4a79-b90f-696d6fd4707b.png)

**Comment by TheNetAdmin** [comment]
Should be fixed, latex workshop plugin is able to use Makefile to build the project so I added a Makefile to the root dir

**Comment by synesios** [comment]
i have met the  same question,so how to solve this error under the environment of letaxmk?
