### ISSUE TITLE
开题报告三合一中，开题报告和文献翻译共享文献引用

### ISSUE THREAD

**Issue by SiO-2** [TheNetAdmin/zjuthesis#314]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.0.0

### MajorFormat

cs

### Degree

undergraduate

### Type

thesis

### Period

proposal

### BlindReview

true

### GradLevel

master

### 问题描述

开题报告三合一的写作中，开题报告和文献翻译部分的文献引用是共享。在文献翻译中添加引用，对应的引用条目会同时被添加到文献翻译和开题报告的文献引用中，在开题报告中添加引用也是一样。

**Comment by SiO-2** [comment]
目前询问过的所有同学都存在这个问题

**Comment by TheNetAdmin** [comment]
Fixed
