### ISSUE TITLE
插入外文原文pdf后编译报错，无法生成pdf

### ISSUE THREAD

**Issue by cyf-2002** [TheNetAdmin/zjuthesis#317]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9

### MajorFormat

general

### Degree

undergraduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

在figure中插入了外文原文pdf，然后编译报错。重启后，删除中间件也无法解决
```Running 'xdvipdfmx -q -E -o "out/zjuthesis.pdf"  "out/zjuthesis.xdv"'
------------

xdvipdfmx:fatal: pdf_link_obj(): passed invalid object.

No output PDF file written.
Latexmk: Errors, in force_mode: so I tried finishing targets
Collected error summary (may duplicate other messages):
  xdvipdfmx: Command for 'xdvipdfmx' gave return code 256

D:\texlive\2023\bin\windows\runscript.tlu:921: command failed with exit code 12:
perl.exe d:\texlive\2023\texmf-dist\scripts\latexmk\latexmk.pl -f
```

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/11224107/zjuthesis.log)

### 代码

```tex
\cleardoublepage
\chapter{外文原文}

% Insert pdf version of original document
% Place the pdf under `/figure/`

\begin{center}
    \includepdf[
        pages=1-4,
        scale=0.75,
        pagecommand={\pagestyle{fancy}},
        frame, % remove this line if you don't want outer fram of pdf
    ]{mvc.pdf}
\end{center}
```

**Comment by TheNetAdmin** [comment]
似乎是pdf文件本身有点问题，你尝试插入其他pdf文件呢，比如之前编译得到的zjuthesis.pdf

**Comment by cyf-2002** [comment]
> 似乎是pdf文件本身有点问题，你尝试插入其他pdf文件呢，比如之前编译得到的zjuthesis.pdf

我试了别的也没用，但是报错信息变了。现在是这个
```
xdvipdfmx:fatal: Image inclusion failed for "./figure/peiyang.pdf" (page=1).
No output PDF file written.

**Comment by cyf-2002** [comment]
> 似乎是pdf文件本身有点问题，你尝试插入其他pdf文件呢，比如之前编译得到的zjuthesis.pdf

已经解决了，下载的pdf有问题，不过貌似全网都只有一个版本，谢谢

**Comment by cyf-2002** [comment]
我找到一个解决办法，如果下载下来的pdf不能使用，可以使用迅捷pdf的任意一个功能，我选择了去除水印，这样对原pdf改动较小。编辑后下载下来的pdf是可以使用的。
[在线一键去除PDF水印](https://app.xunjiepdf.com/pdfdelmark/)
