### ISSUE TITLE
[讨论] 硕士/博士论文模板中的问题

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#32]
当前的硕士/博士模板还存在一些问题，一些同学通过邮件联系到我，提出了一些建议，现在总结在这里。

如果大家有其他建议，也可以在这个issue里评论，我近期会统一修复。

**Comment by TheNetAdmin** [comment]
1. 博士论文题目是包含中英文的，所以documentclass是不是加个TitleEng设定？

2. Cover-chn里Title这个好像没传递过来，我看代码里直接写的是\uline{\hfill}。这个同Title.tex和Title-eng.tex。另外这样排版可能会有另一个问题，“中文论文题目”应该是和传入title的首行对齐。

   A: 这个近期会修复，设计之初给封面题目留空，是因为标题可能太长导致换行，所以留空让同学们自行换行。

3. 如果加上title-eng，考虑到英文标题里有空格，stringoption会自动删除空格，这个貌似也是个问题。

   A: 我认为英文论文题目出现次数较少，可能只出现一到两次，所以不太适合单独增加一个 documentclass 设定

4. 合作导师其实是可有可无的，是不是可以在stringoption里默认为false？

   A: 合作导师是为“同等学力”论文设计的，但目前没看到有人使用这个模板，我会考虑删除这个设定。

5. Cover-chn里“博士/硕士学位论文”这一行并不会根据GradLevel改变。

   A: 这个确实是个BUG，近期会修复

6. content里插入的浙江大学LOGO自动图索引貌似也有问题，应该是图1.1，表2.1同样也应该是1.1。

   A: 这个问题已经修复，见 commit id 64535 

7. MacOS缺少字体无法编译，是否可以随代码附带字体文件？

   A: 字体大多有版权，我无法随代码分发字体文件，但我会在README里说明要安装哪些字体

**Comment by Garrybest** [comment]
参考文献有时不需要上标。

> 文献[8]应用模糊 数学理论提出了检测不良数据的聚类方法。

使用命令`\cite{ref_xx}`只能让参考文献在语句中上标，该如何解决有时不需要上标的问题呢？

**Comment by TheNetAdmin** [comment]
> 参考文献有时不需要上标。
> 
> > 文献[8]应用模糊 数学理论提出了检测不良数据的聚类方法。
> 
> 使用命令`\cite{ref_xx}`只能让参考文献在语句中上标，该如何解决有时不需要上标的问题呢？

你确定有个下划线在大括号里面吗？如果有的话请改成 `-`。下划线一般用于标记上下标，不要用作命令。

**Comment by Garrybest** [comment]
> > 参考文献有时不需要上标。
> > > 文献[8]应用模糊 数学理论提出了检测不良数据的聚类方法。
> > 
> > 
> > 使用命令`\cite{ref_xx}`只能让参考文献在语句中上标，该如何解决有时不需要上标的问题呢？
> 
> @Garrybest 你确定有个下划线在大括号里面吗？如果有的话请改成 `-`。下划线一般用于标记上下标，不要用作命令。

这个地方下划线只是举例，实际上使用的命令是`\cite{具体的参考文献标记}`，只是不清楚该如何将这里的上标取消。

**Comment by TheNetAdmin** [comment]
@Garrybest 新开了一个issue，#34，在那里讨论一下。

**Comment by xxwywzy** [comment]
在博士论文模板中，当插入较长的图片或表格时，模板一般会另起一页插入这些图片或表格，导致图表前后的留白过多，有时还会引起段落之间的间距（空白）过大，之前有试过引入 \usepackage{setspace}，似乎可以使整体排版更加紧凑，但是发现会导致部分段落之间出现无法调节的较大间距，目前还没有找到比较好的解决方案。

**Comment by WangHonglie** [comment]
> 1. 博士论文题目是包含中英文的，所以documentclass是不是加个TitleEng设定？
> 2. Cover-chn里Title这个好像没传递过来，我看代码里直接写的是\uline{\hfill}。这个同Title.tex和Title-eng.tex。另外这样排版可能会有另一个问题，“中文论文题目”应该是和传入title的首行对齐。
>    A: 这个近期会修复，设计之初给封面题目留空，是因为标题可能太长导致换行，所以留空让同学们自行换行。
> 3. 如果加上title-eng，考虑到英文标题里有空格，stringoption会自动删除空格，这个貌似也是个问题。
>    A: 我认为英文论文题目出现次数较少，可能只出现一到两次，所以不太适合单独增加一个 documentclass 设定
> 4. 合作导师其实是可有可无的，是不是可以在stringoption里默认为false？
>    A: 在一些硕士模板中有用到 `合作导师`
> 5. Cover-chn里“博士/硕士学位论文”这一行并不会根据GradLevel改变。
>    A: 这个确实是个BUG，近期会修复
> 6. content里插入的浙江大学LOGO自动图索引貌似也有问题，应该是图1.1，表2.1同样也应该是1.1。
>    A: 这个问题已经修复
> 7. MacOS缺少字体无法编译，是否可以随代码附带字体文件？
>    A: 字体大多有版权，我无法随代码分发字体文件，但我会在README里说明要安装哪些字体

第四条:博士模板里合作导师不需要可以去掉吗?一直多一个横线

**Comment by TheNetAdmin** [comment]
似乎博士论文对封面的要求没有很严格，所以自行去掉应该是可以的，和学院发邮件确认一下就更好了
