### ISSUE TITLE
全文编译时图片标号有误

### ISSUE THREAD

**Issue by xxggoo** [TheNetAdmin/zjuthesis#321]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

9.0.0

### MajorFormat

general

### Degree

undergraduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

最终生成的final文件是既有论文又有开题报告的，开题报告中的章节是使用\section{} \subsection 这样编排的，图片标号得到时候也用的是 \sectionmajornumbering 这是正确的，但是这时候开题报告的章节最开始是\chapter，导致我们用 \sectionmajornumbering 无法得到正确的图片序号。

这样的问题在一开始如果只是写一下开题报告的话，是不会出现的，代码里写了：
`\newcommand{\numberingstyle}
{
    \ifthenelse{\equal{\Degree}{undergraduate}}
    {
        \ifthenelse{\equal{\undergradcurrstage}{proposal}}
        {
             \chaptermajornumbering
        }
        {
            \sectionmajornumbering
        }
    }
    {
        \chaptermajornumbering
    }
}`
所以只会在整个编译final文件的过程中，final里面的proposal 会出这个问题

### 代码

`\newcommand{\numberingstyle}
{
    \ifthenelse{\equal{\Degree}{undergraduate}}
    {
        \ifthenelse{\equal{\undergradcurrstage}{proposal}}
        {
             \chaptermajornumbering
        }
        {
            \sectionmajornumbering
        }
    }
    {
        \chaptermajornumbering
    }
}`

**Comment by TheNetAdmin** [comment]
尝试一下9.1.0版本呢，最新版里有修复图片编号不一致的问题

**Comment by TheNetAdmin** [comment]
Closed due to the lack of active response, please re-open if the bug persists.
