### ISSUE TITLE
Redefining CJKfamily `zhfs' (FangSong)undefined 这个warning需要理会嘛？

### ISSUE THREAD

**Issue by WangLuyu33** [TheNetAdmin/zjuthesis#322]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.1.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

doctor

### 问题描述

使用VS code配合Latex Workshop在本地使用latexmk进行编译。
编译可以通过。可以生成并预览论文的pdf文件。
但是会出现如截图中的5条warning。
请问这些warning有什么潜在的风险嘛？是否需要处理？

谢谢！

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/11438587/zjuthesis.log)

### 截图

![image](https://github.com/TheNetAdmin/zjuthesis/assets/31880176/ddb122c3-9f18-4824-83f4-bf99c565c8d9)

### 其他信息

参考xeCJK手册中的建议，使用
```
fc-list -f "%{family}\n" :lang=zh > zhfont.txt
```
将系统中的中文字体导出后，看到`FangSong` `SimHei` `KaiTi` `SimSun` 字体都有的。

通过TeX Live查看到CTeX包的版本是2.5.8，xeCJK包的版本是3.8.8。

**Comment by Palmer-C** [comment]
我也遇到同样的问题

**Comment by WangLuyu33** [comment]
> 

在这个 ./config/general/font.tex 文件里面有这样一段注释：

```
To use LuaTeX, we manually set the AutoFakeBold size for each font, 
because in LuaTeX, CTeX invokes luatexja which does not recognize a global
AutoFakeBold setting. So we need to set AutoFakeBold for each font.
```
所以是不是可以认为，不使用LuaTex而是XeLaTeX引擎的话，就不需要理会它了？

因为这个文件里面的代码是为了给LuaTex设定`AutoFakeBold`而设计的。

**Comment by TheNetAdmin** [comment]
一般不用理会，如果有特殊需求可以去 font.tex 里进行设定
