### ISSUE TITLE
CS 盲审打分被自动填充了满分

### ISSUE THREAD

**Issue by bittervan** [TheNetAdmin/zjuthesis#327]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.0.0

### MajorFormat

cs

### Degree

undergraduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

由体系群群友发现，最后的答辩小组得分被填充了满分，似乎应该是空着的？

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/11524253/zjuthesis.log)

### 代码

不添加任何content也能得到被填充的分数

### 截图

<img width="243" alt="image" src="https://github.com/TheNetAdmin/zjuthesis/assets/57927141/9c86b97c-f11e-4653-8ac7-829fcb8df43f">

**Comment by bittervan** [comment]
btw，似乎提交 log 的方式会 leak 一些论文内容？

**Comment by D10scxy** [comment]
可以在page/undergraduate/final/eval.tex里删掉\finaleval的参数

**Comment by bittervan** [comment]
> 可以在page/undergraduate/final/eval.tex里删掉\finaleval的参数

我知道，就是感觉一下子不少同学忘了删 [ac01]

**Comment by TheNetAdmin** [comment]
Fixed, thanks for pointing out!
