### ISSUE TITLE
本科毕业论文页码起始错误

### ISSUE THREAD

**Issue by D10scxy** [TheNetAdmin/zjuthesis#329]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.1.0

### MajorFormat

cs

### Degree

undergraduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

本科毕业论文的页码会从“第一部分 毕业论文”页开始计数，导致目录中起始页码为3

### 截图

<img width="662" alt="t" src="https://github.com/TheNetAdmin/zjuthesis/assets/53719086/57bffded-b31f-4c1b-b040-dc6e9aa4d103">

### 其他信息

在zjuthesis.tex第73行下添加一行可以临时解决：
```
\inputpage{final}{cover-part}
\setcounter{page}{1}
\inputbody{final/content}
```

**Comment by TheNetAdmin** [comment]
Fixed, thanks for pointing it out!
