### ISSUE TITLE
请问如何修改目录的字体？已编译通过

### ISSUE THREAD

**Issue by Dawn-LX** [TheNetAdmin/zjuthesis#33]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
请简要描述你遇到的问题

**重现步骤**
如何重现你遇到的问题：

1. 修改了哪里
2. 使用什么命令编译
3. 产生了什么错误/输出结果哪里不对
4.

请附上修改过的文件/工程

如果无法编译，请额外附上 log 文件，位于 out/zjuthesis.log

**截图**

- 重现步骤的截图
- 输出结果的截图
- 如果方便的话，也请附上其他有帮助的截图

**环境**
 - zjuthesis版本: [e.g. v3.0.0 或 3c8a471(commit id)]
- zjuthesis基础设置 **请将如下代码替换为你的`\documentclass`代码，注意隐藏个人信息**
```
\documentclass[
    StudentName = 姓名,
    StudentID   = 学号,
    AdvisorName = 指导教师,
    Grade       = 2014,
    Major       = 专业,
    Department  = 学院,
    Title       = 毕业论文/设计题目,
    SubmitDate  = 递交日期,
    MajorFormat = general,
    Degree      = undergraduate,
    Type        = thesis,
    Period      = final,
    BlindReview = false,
    Topic           = 研究方向,
    ColaboratorName = 合作导师
]{config/zjuthesis}
```
 - OS: [e.g. Linux/Windows/MacOS]
 - Tex套件: [e.g. Texlive/Miktex]
 - Tex套件版本: [e.g. 2019]
 - XeLaTex版本: (请附上`xelatex --version`命令的所有输出)
``` shell
XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019)
kpathsea version 6.3.1
Copyright 2019 SIL International, Jonathan Kew and Khaled Hosny.
```

**其他信息**
其他你认为有帮助的信息

**Comment by TheNetAdmin** [comment]
参照 `tocloft` 宏包的文档，修改这里

https://github.com/TheNetAdmin/zjuthesis/blob/9070d4ed316b6c94c91bda30e1adf0ed57cf7904/config/format/general/layout.tex#L123-L128

**Comment by Dawn-LX** [comment]
> 参照 `tocloft` 宏包的文档，修改这里
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/9070d4ed316b6c94c91bda30e1adf0ed57cf7904/config/format/general/layout.tex#L123-L128

太感谢了！问题解决了！
另外我想问一下关于字体的问题，\zihao{-4}是指小四字号吧？然后没有负号的\zihao{4}是四号？
然后不指定的就是默认使用config\format\general\fonts.tex中的FangSong，如果要指定黑体就在\zihao{-4}后面加\heiti    是这样吧？

**Comment by TheNetAdmin** [comment]
对，-4 就是小四，参见 ctex 文档。

\heiti 可以临时指定黑体，同参见 ctex 文档。

**Comment by TheNetAdmin** [comment]
你们是在用光电的模板么？最近有很多同学反映光电的目录和普通模板不同。如果是这样的话我可以做一个光电模板出来。

**Comment by Dawn-LX** [comment]
> 你们是在用光电的模板么？最近有很多同学反映光电的目录和普通模板不同。如果是这样的话我可以做一个光电模板出来。

不，我是海洋学院的，我们的模板目录好像就几个字体和general模板不同。还有就是general模板的每个section标题空的太多了，这个能调整嘛？虽然我们的模板好像也没说要空多少。不多general模板我觉得好像写没几个字加几个标题就一页没了

**Comment by TheNetAdmin** [comment]
改这里的 afterskip 和 beforeskip 试试

https://github.com/TheNetAdmin/zjuthesis/blob/9070d4ed316b6c94c91bda30e1adf0ed57cf7904/config/format/general/heading.tex#L4-L46

**Comment by Dawn-LX** [comment]
> 改这里的 afterskip 和 beforeskip 试试
> 
> https://github.com/TheNetAdmin/zjuthesis/blob/9070d4ed316b6c94c91bda30e1adf0ed57cf7904/config/format/general/heading.tex#L4-L46

谢谢！但是我改过了好像并没有用

**Comment by TheNetAdmin** [comment]
请把issue模板里的信息填一下，然后我帮你看一下是什么问题

**Comment by Dawn-LX** [comment]
> 请把issue模板里的信息填一下，然后我帮你看一下是什么问题

好的

**Comment by Dawn-LX** [comment]
> 请把issue模板里的信息填一下，然后我帮你看一下是什么问题

遇到的问题
修改了config\format\general\heading.tex中的section的beforeskip，改成5pt，看起来并没有变化

重现步骤
如何重现你遇到的问题：

修改了哪里

编译命令是这样的
`"latex-workshop.latex.tools": [  
    {
        "name": "xelatex",
        "command": "F:/texlive2019iso/MikTex2_9_7269/miktex/bin/x64/xelatex.exe",
        "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "%DOC%"
        ]
      },
        {
            "name": "biber",
            "command": "F:/texlive2019iso/MikTex2_9_7269/biber/bin/windows-x64/biber.exe",
            "args": [
                "%DOCFILE%"
            ]
        }
    ],
    "latex-workshop.latex.recipes": [
        {
            "name": "XeLaTeX Chain",
            "tools": [
                "xelatex",
                "biber",
                "xelatex",
                "xelatex"
            ]
        }
    ],`
以上是VS Code中的json设置文件。编译顺序是 "xelatex",->"biber", ->xelatex ->xelatex

截图

重现步骤的截图
输出结果的截图
如果方便的话，也请附上其他有帮助的截图
环境

zjuthesis版本: [e.g. v3.0.0 或 3c8a471(commit id)]
zjuthesis基础设置 请将如下代码替换为你的\documentclass代码，注意隐藏个人信息
\documentclass[
    StudentName = 姓名,
    StudentID   = 学号,
    AdvisorName = 指导教师,
    Grade       = 2014,
    Major       = 专业,
    Department  = 学院,
    Title       = 毕业论文/设计题目,
    SubmitDate  = 递交日期,
    MajorFormat = general,
    Degree      = undergraduate,
    Type        = thesis,
    Period      = proposal,
    BlindReview = false,
    Topic           = 研究方向,
    ColaboratorName = 合作导师
]{config/zjuthesis}
OS: Windows10 1909
Tex套件: basic-miktex-2.9.7269-x64
XeLaTex版本: (请附上xelatex --version命令的所有输出)
This is XeTeX, Version 3.14159265-2.6-0.999991 (MiKTeX 2.9.7250 64-bit)
entering extended mode
(g:/Graduate_Projection/zjuthesis/zjuthesis.tex
LaTeX2e <2019-10-01> patch level 3
(config/zjuthesis.cls

LaTeX Warning: You have requested document class `./config/zjuthesis',
               but the document class provides `zjuthesis'.

Document Class: zjuthesis Zhejiang University Thesis and Design Template, Zixua
n Wang zxwang42@gmail.com
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\kvoptions.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/graphics\keyval.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\ltxcmds.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\kvsetkeys.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\infwarerr.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\etexcmds.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/iftex\ifluatex.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/iftex\iftex.sty)))))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ctex\ctexrep.cls
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/l3kernel\expl3.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/l3kernel\expl3-code.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/l3kernel\l3deprecation.def))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/l3backend\l3backend-xdvipdfmx.def))

Document Class: ctexrep 2019/05/29 v2.4.16 Chinese adapter for class report (CT
EX)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/l3packages/xparse\xparse.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/l3packages/l3keys2e\l3keys2e.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ctex\ctexhook.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ctex\ctexpatch.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/base\fix-cm.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/base\ts1enc.def))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ms\everysel.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ctex/config\ctexopts.cfg)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/base\report.cls
Document Class: report 2019/10/25 v1.4k Standard LaTeX document class
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/base\size12.clo))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ctex/engine\ctex-engine-xetex.def
(F:\texlive2019iso\MikTex2_9_7269\tex/xelatex/xecjk\xeCJK.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/l3packages/xtemplate\xtemplate.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/fontspec\fontspec.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/fontspec\fontspec-xetex.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/base\fontenc.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/base\tuenc.def))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/fontspec\fontspec.cfg)))
(F:\texlive2019iso\MikTex2_9_7269\tex/xelatex/xecjk\xeCJK.cfg))
(F:\texlive2019iso\MikTex2_9_7269\tex/xelatex/xecjk\xeCJKfntef.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ulem\ulem.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/cjk\CJKfntef.sty)))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/zhnumber\zhnumber.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/zhnumber\zhnumber-utf8.cfg))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ctex/scheme\ctex-scheme-chinese-rep
ort.def
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ctex/config\ctex-name-utf8.cfg))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ctex\ctex-cs4size.clo)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ctex/fontset\ctex-fontset-windows.d
ef
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ctex/fontset\ctex-fontset-windowsne
w.def))) (F:\texlive2019iso\MikTex2_9_7269\tex/latex/ctex/config\ctex.cfg)
(config/packages.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/graphics\graphicx.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/graphics\graphics.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/graphics\trig.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/graphics-cfg\graphics.cfg)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/graphics-def\xetex.def)))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/geometry-de\geometry.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/iftex\ifpdf.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/iftex\ifvtex.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/iftex\ifxetex.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/xelatex/xetexconfig\geometry.cfg))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/tools\tabularx.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/tools\array.sty)) (multido.sty
(multido.tex  v1.42, 2010/05/14 <tvz>))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/fancyhdr\fancyhdr.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/titlesec\titlesec.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/tocloft\tocloft.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/multirow\multirow.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/makecell\makecell.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/hyperref\hyperref.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pdftexcmds\pdftexcmds.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\kvdefinekeys.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\pdfescape.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\hycolor.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\xcolor-patch.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\hopatch.sty)))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\letltxmacro.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\auxhook.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/hyperref\pd1enc.def)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\intcalc.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/00miktex\hyperref.cfg)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/hyperref\puenc.def)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/url\url.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\bitset.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\bigintcalc.sty))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\atbegshi.sty))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/hyperref\hxetex.def
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\stringenc.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\rerunfilecheck.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\atveryend.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\uniquecounter.sty)))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pdfpages\pdfpages.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/base\ifthen.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/tools\calc.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/eso-pic\eso-pic.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/xcolor\xcolor.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/graphics-cfg\color.cfg)))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pdfpages\ppxetex.def))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex\biblatex.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/etoolbox\etoolbox.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/logreq\logreq.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/logreq\logreq.def))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex\blx-dm.def)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex\blx-unicode.def)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex\blx-compat.def)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex\biblatex.def)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex-gb7714-2015\gb7714-2015.bb
x (F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex/bbx\numeric-comp.bbx
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex/bbx\numeric.bbx
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex/bbx\standard.bbx)))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/xstring\xstring.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/xstring\xstring.tex)))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex-gb7714-2015\gb7714-2015.cb
x (F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex/cbx\numeric-comp.cbx))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex\biblatex.cfg))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/siunitx\siunitx.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/amsmath\amstext.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/amsmath\amsgen.sty))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/translator\translator.sty))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/caption\caption.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/caption\caption3.sty))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/chngcntr\chngcntr.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/enumitem\enumitem.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/float\float.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/listings\listings.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/listings\lstmisc.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/listings\listings.cfg))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/xifthen\xifthen.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ifmtarg\ifmtarg.sty))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/amsfonts\amssymb.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/amsfonts\amsfonts.sty))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\bookmark.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\bkm-dvipdfm.def))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/zhlipsum\zhlipsum.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/zhlipsum\zhlipsum-utf8.def))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pgf/frontendlayer\tikz.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pgf/basiclayer\pgf.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pgf/utilities\pgfrcs.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/utilities\pgfutil-common.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/utilities\pgfutil-common-list
s.tex))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/utilities\pgfutil-latex.def
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/ms\everyshi.sty))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/utilities\pgfrcs.code.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf\pgf.revision.tex)))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pgf/basiclayer\pgfcore.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pgf/systemlayer\pgfsys.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/systemlayer\pgfsys.code.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/utilities\pgfkeys.code.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/utilities\pgfkeysfiltered.cod
e.tex)) (F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/systemlayer\pgf.cfg)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/systemlayer\pgfsys-xetex.def
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/systemlayer\pgfsys-dvipdfmx.d
ef
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/systemlayer\pgfsys-common-pdf
.def))))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/systemlayer\pgfsyssoftpath.co
de.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/systemlayer\pgfsysprotocol.co
de.tex))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcore.code.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmath.code.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathcalc.code.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathutil.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathparser.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathfunctions.code.te
x
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathfunctions.basic.c
ode.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathfunctions.trigono
metric.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathfunctions.random.
code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathfunctions.compari
son.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathfunctions.base.co
de.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathfunctions.round.c
ode.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathfunctions.misc.co
de.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathfunctions.integer
arithmetics.code.tex)))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmathfloat.code.tex))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfint.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcorepoints.code
.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcorepathconstru
ct.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcorepathusage.c
ode.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcorescopes.code
.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcoregraphicstat
e.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcoretransformat
ions.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcorequick.code.
tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcoreobjects.cod
e.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcorepathprocess
ing.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcorearrows.code
.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcoreshade.code.
tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcoreimage.code.
tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcoreexternal.co
de.tex))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcorelayers.code
.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcoretransparenc
y.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcorepatterns.co
de.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/basiclayer\pgfcorerdf.code.te
x)))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/modules\pgfmoduleshapes.code.
tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/modules\pgfmoduleplot.code.te
x)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pgf/compatibility\pgfcomp-version-0
-65.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pgf/compatibility\pgfcomp-version-1
-18.sty)) (F:\texlive2019iso\MikTex2_9_7269\tex/latex/pgf/utilities\pgffor.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pgf/utilities\pgfkeys.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/utilities\pgfkeys.code.tex))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/pgf/math\pgfmath.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmath.code.tex))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/utilities\pgffor.code.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/math\pgfmath.code.tex)))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/frontendlayer/tikz\tikz.code.
tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/libraries\pgflibraryplothandl
ers.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/modules\pgfmodulematrix.code.
tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/frontendlayer/tikz/libraries\
tikzlibrarytopaths.code.tex)))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/frontendlayer/tikz/libraries\
tikzlibrarycalc.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/frontendlayer/tikz/libraries\
tikzlibraryintersections.code.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/libraries\pgflibraryintersect
ions.code.tex
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/libraries\pgflibraryfpu.code.
tex)))
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/frontendlayer/tikz/libraries\
tikzlibrarythrough.code.tex)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/pgf/frontendlayer/tikz/libraries\
tikzlibrarybackgrounds.code.tex)) (config/path.tex) (config/commands.tex)
(config/format/format.tex (config/format/general/format.tex
(config/format/general/caption.tex) (config/format/general/layout.tex)
(config/format/general/heading.tex) (config/format/general/fonts.tex

Package xeCJK Warning: Redefining CJKfamily `\CJKrmdefault' (SimSun(0)).

) (config/format/general/reference.tex) (config/format/general/tables.tex)
(config/format/general/numbering.tex)) (config/format/major/general/format.tex)
(config/format/language.tex)) (config/version.tex))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/biblatex/lbx\english.lbx)
(F:\texlive2019iso\MikTex2_9_7269\tex/xelatex/xecjk\xeCJK-listings.sty)
(zjuthesis.aux) ABD: EverySelectfont initializing macros
*geometry* detected driver: pdftex
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/hyperref\nameref.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\refcount.sty)
(F:\texlive2019iso\MikTex2_9_7269\tex/generic/oberdiek\gettitlestring.sty))
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/oberdiek\pdflscape.sty
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/graphics\lscape.sty))
(zjuthesis.bbl)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/translator\translator-basic-diction
ary-English.dict)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/siunitx\siunitx-abbreviations.cfg)
ABD: EveryShipout initializing macros
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/amsfonts\umsa.fd)
(F:\texlive2019iso\MikTex2_9_7269\tex/latex/amsfonts\umsb.fd)
(page/undergraduate/proposal/cover.tex)
(page/undergraduate/proposal/previous.tex [-1] [0]
(page/undergraduate/proposal/thesis/previous.tex
Underfull \hbox (badness 10000) in paragraph at lines 3--5


Overfull \hbox (32.25787pt too wide) in paragraph at lines 12--15
[]\TU/TimesNewRoman(0)/m/n/14.05249 3. \TU/FangSong(0)/m/n/14.05249 外 文 翻 译 阅 读
 一 些 经 典 的 目 标 检 测 模 型 的 论 文 \TU/TimesNewRoman(0)/m/n/14.05249 (\TU/FangSong(0)
/m/n/14.05249 如 \TU/TimesNewRoman(0)/m/n/14.05249 Faster R-CNN,YOLO)\TU/FangSon
g(0)/m/n/14.05249 ，|
)) (page/undergraduate/proposal/toc.tex [1] [2] (zjuthesis.toc
Underfull \vbox (badness 5359) has occurred while \output is active [1])
[2]) (body/undergraduate/proposal/content.tex
(body/undergraduate/proposal/review/review.tex
一、

Overfull \hbox (1.55577pt too wide) in paragraph at lines 19--20
\TU/TimesNewRoman(0)/m/n/12.045 Classes (VOC) \TU/FangSong(0)/m/n/12.045 挑 战 赛$
[]$ 是 早 期 图 像 分 类 和 目 标 检 测 模 型 的 评 价 基 准 \TU/TimesNewRoman(0)/m/n/12.045 (benc
hmark)\TU/FangSong(0)/m/n/12.045 。|
[1] [2]) (body/undergraduate/proposal/proposal/proposal.tex [3] [4]
二、
(body/undergraduate/proposal/proposal/background.tex)
(body/undergraduate/proposal/proposal/content.tex)
(body/undergraduate/proposal/proposal/plan.tex) [5])
(body/undergraduate/proposal/translation/translation.tex [6]
三、
) (body/undergraduate/proposal/original/original.tex [7] [8]
四、
[9] [10] [11] [12])) (page/undergraduate/proposal/post.tex
(page/undergraduate/proposal/thesis/post.tex
(page/undergraduate/proposal/thesis/proposaleval.tex)))

Package caption Warning: Unused \captionsetup[table] on input line 4.
See the caption package documentation for explanation.

[13] (zjuthesis.aux) )
(see the transcript file for additional information)
Output written on zjuthesis.pdf (19 pages).
SyncTeX written on zjuthesis.synctex.gz.
Transcript written on zjuthesis.log.

**Comment by Dawn-LX** [comment]
> 请把issue模板里的信息填一下，然后我帮你看一下是什么问题

忘了说了，我的版本是zjuthesis-v5.0.0-rc2

**Comment by TheNetAdmin** [comment]
看到你已经close，是解决了吗？

以及可以参考 ctex 文档，修改 fixskip 选项来缩减 latex 自动添加的空隙。

**Comment by Dawn-LX** [comment]
> 看到你已经close，是解决了吗？
> 
> 以及可以参考 ctex 文档，修改 fixskip 选项来缩减 latex 自动添加的空隙。

没有解决，我加了fixskip = true 好像也没用，不过我发现这个间距是会自动调整的，我正文写多一点的话section名 的间距就变小了
