### ISSUE TITLE
引用时取消上标

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#34]
**遇到的问题**

复制自#32 @Garrybest

>参考文献有时不需要上标。
>
>>文献[8]应用模糊 数学理论提出了检测不良数据的聚类方法。
>
>使用命令\cite{refxx}只能让参考文献在语句中上标，该如何解决有时不需要上标的问题呢？

**重现步骤**

**截图**

**环境**

**其他信息**

其他你认为有帮助的信息

**Comment by TheNetAdmin** [comment]
@Garrybest 我明白你的意思了，你是想用一个“非上标”的引用来指代一篇论文是吧。

一般来讲你可以用 `\citep` 或 `\citet` 命令实现类似效果。这些命令会输出作者名加上标引用，这是常见的指代方式。

如果你一定要用非上标的编号来指代的话，你可以定义一个放大版的引用命令，比如这里：

https://www.cnblogs.com/jcleung/archive/2012/02/09/2343560.html

要注意的是，网上搜到一些解决方案使用了 `netbib` 宏包，但这个模板已经用了 `biblatex`，再使用 `netbib` 可能会出现预期之外的效果。

**Comment by Garrybest** [comment]
> @Garrybest 我明白你的意思了，你是想用一个“非上标”的引用来指代一篇论文是吧。
> 
> 一般来讲你可以用 `\citep` 或 `\citet` 命令实现类似效果。这些命令会输出作者名加上标引用，这是常见的指代方式。
> 
> 如果你一定要用非上标的编号来指代的话，你可以定义一个放大版的引用命令，比如这里：
> 
> https://www.cnblogs.com/jcleung/archive/2012/02/09/2343560.html
> 
> 要注意的是，网上搜到一些解决方案使用了 `netbib` 宏包，但这个模板已经用了 `biblatex`，再使用 `netbib` 可能会出现预期之外的效果。

谢谢您给的相关信息，我在此基础上搜索了一下，使用`\parencite{}`可以显示出这样的效果，问题已解决

**Comment by TheNetAdmin** [comment]
ok

**Comment by hushidong** [comment]
![Screenshot_20191224_131429](https://user-images.githubusercontent.com/20421795/71395136-a32b0980-264f-11ea-9c9b-4d47c527baca.jpg)

**Comment by hushidong** [comment]
引用命令latex提供了基本命令，其他命令则是由宏包定义的，这些宏包往往也会重定义基本命令。

采用bibtex的文献解决方案常用natbib来定义，像citet,citep这样的命令是该红宝先定义的，但因为本项目用的是biblatex的解决方案，所以我们不用讨论natbib

biblatex的解决方案中，命令由biblatex及样式包定义，本项目是biblatex-gb7714-2015,引用命令非常丰富，上述给出的只是一部分，包括citet和citep命令也支持，具体可以参考说明文档。之所以提供全面的命令，也是为了让用户无缝衔接，在更换参考文献解决方案时。比如原来使用citet的文档，内容不用任何修改，只要把natbib换成biblatex，以及使用biblatex的命令打印文献表，然后用bibber编译文献，那么就可以换过来了。

**Comment by MMUZAMMUL** [comment]
hello, why refrences not show in main document

**Comment by hushidong** [comment]
Using different cmds to implement different citation gives more convenience for users.
Now, you can use:
`\cite` to generate superscript citation
`\parencite` to generate inline citation



获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MMUZAMMUL** [comment]
I mean how to add reference page at end of document it is autometically not showing.

i already added ref in ref.bib
->No reference page at end of thesis 
secondly what is last data of phd computer science thesis submission zju 
![Uploading 1735797928353.png…]()

**Comment by MMUZAMMUL** [comment]
at end is just acknowledgement page after ending chapters

**Comment by MMUZAMMUL** [comment]
another issue is my thesis title is long , how to set on first page,
![1aa](https://github.com/user-attachments/assets/f33872df-cdf7-405c-ae03-43723f0207c8)

**Comment by MMUZAMMUL** [comment]
![2a](https://github.com/user-attachments/assets/9bcf5dcb-84d5-4fc9-9149-d1a80eb0ce91)
Not have any reference page even i added refresnce at all

**Comment by MMUZAMMUL** [comment]
![f432](https://github.com/user-attachments/assets/174a98fd-cf6e-43b7-a69f-c059dab720a9)
not appear at end of thesis

**Comment by hushidong** [comment]
You need to use biber to compile the reference, as zjuthesis uses biblatex.


获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MMUZAMMUL** [comment]
how to use it, ?? main have chapter only where and how to use biblatex., so that all references show at end of my thesis

**Comment by MMUZAMMUL** [comment]
I mean in content.txt refrence come how? at end of main document how to show
