### ISSUE TITLE
参考文献格式有问题

### ISSUE THREAD

**Issue by linlinge** [TheNetAdmin/zjuthesis#342]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.1.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

doctor

### 问题描述

本文用该模板进行编译之后得到的参考文献格式与要求不一致
下图是用模板生成的格式：
![image](https://github.com/TheNetAdmin/zjuthesis/assets/26290410/300b85c2-f71a-4233-80ad-fa1c57f9fc98)

正确的格式如下所示：
![image](https://github.com/TheNetAdmin/zjuthesis/assets/26290410/6d6e493f-c5b0-4034-89e8-5c4102db986a)

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/12587040/zjuthesis.log)

**Comment by TheNetAdmin** [comment]
#23 
https://github.com/TheNetAdmin/zjuthesis/blob/124ce4f0b2c05077690b0c16a2cd1e25b7c803bd/config/packages.tex#L17

提问前先查阅过往的issue和Discussion
