### ISSUE TITLE
盲审改为真之后不显示作者成果页

### ISSUE THREAD

**Issue by linlinge** [TheNetAdmin/zjuthesis#347]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.1.0

### MajorFormat

cs

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

doctor

### 问题描述

我再模板内把zjuthesis.tex让“BlindReview     = true”，结果作者的成果页不显示了。其中body\graduate\post\cv.tex中作者成果页，编写的内容如下：
```
\cleardoublepage
\chapternonum{攻读博士期间的主要成果和参与的课题}
\ifthenelse{\equal{\BlindReview}{true}}
{% For blind review
  隐去作者的成果列表
}

{% For submission
 未隐去作者的成果列表
}
```

**Comment by TheNetAdmin** [comment]
#132  it's the expected behavior

**Comment by TheNetAdmin** [comment]
You may change the following settings to bring back cv in blind review, and use your customized blind review version of cv

https://github.com/TheNetAdmin/zjuthesis/blob/957b0917b669bac8435f83b249e23926067d5dbe/body/graduate/post.tex#L3-L8

**Comment by linlinge** [comment]
Thank you very much!
