### ISSUE TITLE
关于论文英文题目过长的问题

### ISSUE THREAD

**Issue by linlinge** [TheNetAdmin/zjuthesis#348]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.1.0

### MajorFormat

cs

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

doctor

### 问题描述

下面这张图是我把词拆开来的排版，这个排版很正常：
<p align="center"> 
<img width="360" alt="未命名697508389" src="https://github.com/TheNetAdmin/zjuthesis/assets/26290410/19f5f7d4-22a9-4787-afbc-c1fb2f712ca0">
</p>

下面这两张图是不拆开来的排版，会多出一页。
<p align="center"> 
<img width="560" alt="未命名1697510272" src="https://github.com/TheNetAdmin/zjuthesis/assets/26290410/85ff091d-2cd8-477d-bff7-1642328f05a7">
</p>

请问如果我不想拆开"Normal"一词，如何修改模板呢？英文论文题目这一栏能拉宽吗？

**Comment by BZH110** [comment]
请问你解决了吗

**Comment by linlinge** [comment]
> 请问你解决了吗

还没解决

**Comment by wanghanhan** [comment]
请问你现在解决了吗？我的论文题目拆开两行都放不下，不知道咋办

**Comment by BZH110** [comment]
> 请问你现在解决了吗？我的论文题目拆开两行都放不下，不知道咋办

编辑\textwidth属性 一般加到1.1左右会够了

**Comment by leejean-wq** [comment]
我也遇到了这个问题，中文题目过长会发生截断

**Comment by WindChang1999** [comment]
像lz这个问题应该只要把 page/graduate/cover-chn.tex 中的对应表格的宽度改长一些就可以了。
<img width="919" alt="image" src="https://github.com/TheNetAdmin/zjuthesis/assets/47917003/3c839ce7-5cb4-4196-b5c6-53b881b94006">


如果两行也不够放，只能在这个位置硬编码成3行了
<img width="951" alt="image" src="https://github.com/TheNetAdmin/zjuthesis/assets/47917003/b99c0815-a82c-4e11-a7e9-4c7a7e269d62">
