### ISSUE TITLE
标题所用字体和正文字体不同

### ISSUE THREAD

**Issue by dongbo1998** [TheNetAdmin/zjuthesis#349]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.1.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

1. 如截图所示，似乎标题所用字体和正文字体不同，标题字体有点笔尖都会比较锋利

### 截图

![image](https://github.com/TheNetAdmin/zjuthesis/assets/112373841/a8c3a3a5-4cf1-4037-8b8c-c9c8d07d3be0)

### 其他信息

无

**Comment by TheNetAdmin** [comment]
这个应该是AutoFakeBold选项的自动设定。我们使用的中文字体都没有对应的粗体字体，所以文字加粗是通过latex的自动字体加粗功能实现，其加粗后的文字可能会与原本的字符有些许不同，但应该没有实质性影响
