### ISSUE TITLE
生成的pdf其中一页页眉为乱码

### ISSUE THREAD

**Issue by Wwy111** [TheNetAdmin/zjuthesis#350]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

问题如下图
![image](https://github.com/TheNetAdmin/zjuthesis/assets/43802960/b2cd9699-2e2e-4aa7-a0f5-6c37bb05671f)
原本没有此问题，我重新排版了部分图片的位置和大小之后，便出现如图所示的页眉矩形乱码。只在这一页出现，其他页没有出现。如果我不改动图片的位置和大小的话，不会有这个乱码。
log文件中与此相关的部分如下图
![image](https://github.com/TheNetAdmin/zjuthesis/assets/43802960/6794aa03-9ae5-4d08-a20b-0e6c0169927e)
已善用搜索

**Comment by note286** [comment]
你给一个完整的能复现问题的代码吧，可以直接上传文件。

**Comment by Wwy111** [comment]
> 你给一个完整的能复现问题的代码吧，可以直接上传文件。

这是整个工程文件，问题出现在 /body/graduate/hardware.tex，在pdf中出现问题的页数为第31页
[MyThesis.zip](https://github.com/TheNetAdmin/zjuthesis/files/13471601/MyThesis.zip)

**Comment by note286** [comment]
@Wwy111 我已经复现问题了，但是我无法解决这个问题，我猜测可能和xeCJK有关，你可以关注 https://github.com/CTeX-org/ctex-kit/issues/688 的最新情况。

**Comment by Wwy111** [comment]
> @Wwy111 我已经复现问题了，但是我无法解决这个问题，我猜测可能和xeCJK有关，你可以关注 [CTeX-org/ctex-kit#688](https://github.com/CTeX-org/ctex-kit/issues/688) 的最新情况。

好的，多谢

**Comment by note286** [comment]
@Wwy111 如果你的需求仅仅是使用带圈数字，我推荐你使用`circledtext`。

具体使用你可以看宏包文档，这里我给出简单的示例。

```latex
\documentclass{ctexart}
\usepackage{circledtext}
\begin{document}
\circledtext{1}
\circledtext*{1}
\end{document}
```

![image](https://github.com/TheNetAdmin/zjuthesis/assets/16207292/1a393830-6146-4070-8452-1eb57f4f8127)

**Comment by Wwy111** [comment]
> @Wwy111 我已经复现问题了，但是我无法解决这个问题，我猜测可能和xeCJK有关，你可以关注 [CTeX-org/ctex-kit#688](https://github.com/CTeX-org/ctex-kit/issues/688) 的最新情况。

整个文章里多处用到\ding，只有第三章中\ding放在段开头的情况会触发这个问题。目前我通过把\ding包在\textbf里面可以解决这个问题。
![image](https://github.com/TheNetAdmin/zjuthesis/assets/43802960/de633279-a17a-4bed-b155-35befd7e410c)
或者
![image](https://github.com/TheNetAdmin/zjuthesis/assets/43802960/aad80cd9-1130-46c0-ab7e-511d462e1992)

**Comment by Wwy111** [comment]
> @Wwy111 如果你的需求仅仅是使用带圈数字，我推荐你使用`circledtext`。
> 
> 具体使用你可以看宏包文档，这里我给出简单的示例。
> 
> ```
> \documentclass{ctexart}
> \usepackage{circledtext}
> \begin{document}
> \circledtext{1}
> \circledtext*{1}
> \end{document}
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/16207292/286449347-1a393830-6146-4070-8452-1eb57f4f8127.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjM5MjEsIm5iZiI6MTcwMTIyMzYyMSwicGF0aCI6Ii8xNjIwNzI5Mi8yODY0NDkzNDctMWEzOTM4MzAtNjE0Ni00MDcwLTg0NTItMWViNTdmNGY4MTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAyMDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YmUzOTBhMGQ5ZjE2Y2VhMmU3N2QwOTYzNWQ5NmM5YmFmNzllYmMxN2U3MDNlM2UxZGM3MGQxYmRiODFhODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u-7Pux3GZ5sr3PUo-zj_0Z5up4HBWCxpL_zlAOTauqA)

好的，多谢

**Comment by Entromorgan** [comment]
遇到了同样的问题，同用了\ding，只有特定页会出现，我的解决方法就是在那一页删一些内容…没有找具体的原因

**Comment by Entromorgan** [comment]
其实就是因为circledtext太丑了所以才找的\ding...，如果之后再遇到就试试，感谢！
