### ISSUE TITLE
arydshln库加入后 第一页排版出现问题

### ISSUE THREAD

**Issue by zjufkq** [TheNetAdmin/zjuthesis#354]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.1.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

加入\usepackage{arydshln}后第一页的排版出现问题，论文递交日期 变道下一页中

**Comment by TheNetAdmin** [comment]
可能是此宏包修改了表格的默认高度，导致封面使用的表格（用于写作者姓名等信息）过高，把其下面的内容顶到了下一页。

可以适当修改封面页的垂直空白数值，例如
https://github.com/TheNetAdmin/zjuthesis/blob/6c5b5f7d9917ee66fd63a52307fed3b6ab997da5/page/graduate/cover-chn.tex#L128-L136
