### ISSUE TITLE
单双页页边距不一致的问题&chapter前会出现使用\vspace无法解决的额外空行

### ISSUE THREAD

**Issue by TianyuFan0504** [TheNetAdmin/zjuthesis#358]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

undergraduate

### Type

thesis

### Period

proposal

### BlindReview

true

### GradLevel

master

### 问题描述

1.单双页页边距不一致，导致跨页段落无法对齐，注意到以前的issue中提到了这一点
https://github.com/TheNetAdmin/zjuthesis/issues/44#issue-576780606
应该已经在v5版本之后解决，但我仍出现了这个问题。
问题如图：
![problem2](https://github.com/TheNetAdmin/zjuthesis/assets/87062283/1feb294f-a32a-4c23-a333-0c5777c766b6)

2.另外，使用\chapter命令时会出现与页眉的空行，这一空行无法通过\vspace处理
https://github.com/TheNetAdmin/zjuthesis/issues/125#issuecomment-757040458 这一分析中也有这个问题，不知道目前有没有什么办法解决
问题如图，左侧是编译所得，右侧是word模板
![problem1](https://github.com/TheNetAdmin/zjuthesis/assets/87062283/5c073fba-82c2-4231-b33a-af95a3d4becc)

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/13737307/zjuthesis.log)

**Comment by zst1406217** [comment]
我也有此问题！

**Comment by darrrt** [comment]
可以修改heading中 `chapter `的`beforeskip=-21pt,afterskip=5pt`，但是没找到word的行距是怎么算的

**Comment by TianyuFan0504** [comment]
> 可以修改heading中 `chapter `的`beforeskip=-21pt,afterskip=5pt`，但是没找到word的行距是怎么算的

word行距可以参考这个issue https://github.com/TheNetAdmin/zjuthesis/issues/125#issue-782058456
不过感觉审核时候应该也是目测。。我看了下官方word模板有些地方也怪怪的QAQ

**Comment by note286** [comment]
关于奇偶页左右页边距不同，这是由于需要双面打印，还有装订，自然奇偶页左右页边距不同，这是正常现象。可通过在文档类参数中设置`TwoSide=false`来改为奇偶页左右页边距相同。

**Comment by note286** [comment]
标题样式请通过`ctex`的接口来设置，例如，如果需要移除章标题前的垂直间距，可以在加载文档类之后使用如下代码设置：

```latex
\ctexset{chapter/fixskip=true,chapter/beforeskip=0pt}
```
