### ISSUE TITLE
图目录两页之间的空白较多

### ISSUE THREAD

**Issue by Rui-R** [TheNetAdmin/zjuthesis#359]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.1.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

编译生成的图目录包含两页，其中第一页末尾的空白很多，文字直接跳到第二页去了。请问下这种情况该怎么调整呀？

### 截图

<img width="608" alt="image" src="https://github.com/TheNetAdmin/zjuthesis/assets/53163198/d9044790-3593-426c-93c5-fed39f13c7a0">

**Comment by TheNetAdmin** [comment]
如果图目录占不满一页，会用空白内容填充一页，这是为了让标题起始于页面顶部而非页面中间

同时如果有TwoSide=true选项，则会额外填充一个空白页，这是为了让标题所在页面永远处于双面打印的册子的右手侧

这都是正常的设定，可以不需理会，除非学院有额外要求
