### ISSUE TITLE
如何切换使用\supercite 和 \cite  ?

### ISSUE THREAD

**Issue by Dawn-LX** [TheNetAdmin/zjuthesis#36]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
我使用\cite的时候参考文献是用上标的形式引用的，请问如何切换使用上标和正常的 [2]
学校的毕业论文格式要求中是这样说的
![image](https://user-images.githubusercontent.com/48169011/71503323-aa505280-28af-11ea-9ccc-1b896699aa02.png)

我在网上自己查找过方法，但是我看到的都是如何把正常的[2]改为上标的[2]，
例如 
\newcommand[2][]\supercite{%
 \textsuperscript{\cite[#1]{#2}}}
但是我现在只用普通的\cite就是上标形式的
请问怎么修改？

**重现步骤**
如何重现你遇到的问题：

1. 修改了哪里
2. 使用什么命令编译
3. 产生了什么错误/输出结果哪里不对
4.

请附上修改过的文件/工程

如果无法编译，请额外附上 log 文件，位于 out/zjuthesis.log

**截图**

- 重现步骤的截图
- 输出结果的截图
- 如果方便的话，也请附上其他有帮助的截图

**环境**
 - zjuthesis版本:  v5.0.0-rc2
- zjuthesis基础设置 **请将如下代码替换为你的`\documentclass`代码，注意隐藏个人信息**
```
\documentclass[
    StudentName = 姓名,
    StudentID   = 学号,
    AdvisorName = 指导教师,
    Grade       = 2014,
    Major       = 专业,
    Department  = 学院,
    Title       = 毕业论文/设计题目,
    SubmitDate  = 递交日期,
    MajorFormat = general,
    Degree      = undergraduate,
    Type        = thesis,
    Period      = final,
    BlindReview = false,
    Topic           = 研究方向,
    ColaboratorName = 合作导师
]{config/zjuthesis}
```
 - OS: [e.g. Linux/Windows/MacOS]
 - Tex套件: [e.g. Texlive/Miktex]
 - Tex套件版本: [e.g. 2019]
 - XeLaTex版本: (请附上`xelatex --version`命令的所有输出)
``` shell
XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019)
kpathsea version 6.3.1
Copyright 2019 SIL International, Jonathan Kew and Khaled Hosny.
```

**其他信息**
其他你认为有帮助的信息

**Comment by TheNetAdmin** [comment]
见issue #34

**Comment by hushidong** [comment]
现在好像咱们已经形成了某种意识，有问题先百度搜，包括我自己也这样，但往往搜索不到对症的东西。
像这类专业的东西，我们也许可以换个观念，首先去搜索问题本身的来源方，然后是相关专业论坛，最后再是百度。
就像做事一样，找对的人来做事往往效率高，但这又往往不容易。借这个问题感慨一下。

**Comment by hushidong** [comment]
上交，同济，复旦的模板也都用了biblatex，所以他们那边的问题，也会有一定的参考性，比如:
https://github.com/sjtug/SJTUThesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by TheNetAdmin** [comment]
感觉有必要做一个WIKI了……近期有空搞一下
