### ISSUE TITLE
通用模板页边距不正确

### ISSUE THREAD

**Issue by RicardoAGu** [TheNetAdmin/zjuthesis#360]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

编译出来的实际页边距比geometry.tex里的大，上下多了约1.5cm，左右多了1cm
![image](https://github.com/TheNetAdmin/zjuthesis/assets/69185358/757e3bd9-37c5-4e54-9a60-d7a77c7dc462)
![IMG_20231224_201843_edit_576728693139079](https://github.com/TheNetAdmin/zjuthesis/assets/69185358/2890f9d0-8739-415a-b69b-48f0b61ae40e)

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/13761808/zjuthesis.log)

**Comment by TheNetAdmin** [comment]
好问题，我还真的没用尺子量过实际的边距……你是尝试修改边距然后发现代码与实际不符么？

或许可以将页面边框显示出来，同时使用`layout`宏包打印页边框的实际数值，看是否和代码不符。参见如下问题的回答一和回答二

https://tex.stackexchange.com/questions/42329/displaying-page-construction-guides
