### ISSUE TITLE
参考文献顺序问题

### ISSUE THREAD

**Issue by guanggaofei** [TheNetAdmin/zjuthesis#362]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

undergraduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

能否将参考文献的标注顺序改为著者-出版年制，以及在引用中采用著者-出版年制，\citeauthor命令只能输出作者
还有能否更新一份更详细的参考文档？

**Comment by note286** [comment]
将`config\packages.tex`中的`style=gb7714-2015`改为`style=gb7714-2015ay`。

**Comment by guanggaofei** [comment]
那有没有办法做到中文在前，英文在后呢？我们老师的课程论文是这样要求的
同时，style中的gb7714-2015是bibtex自带的还是由其它宏包导入的？

**Comment by hushidong** [comment]
style=gb7714-2015ay，默认是中文在前，英文在后的。如果不行加上 gblanorder =chineseahead，选项试试。

packages.TEX 下修改
\usepackage[
    style=gb7714-2015ay,
    gblanorder =chineseahead，
    %gbcitelocal=chinese,   % Uncomment if you want \citeauthor{} in "et al." format. GitHub PR (#324)
    % gbpub=false,         % Uncomment if you do NOT want '[S.l. : s.n.]' in reference entries, GitHub Issue (#47)
    % gbnamefmt=lowercase, % Uncomment if you do NOT want uppercase author names in reference entries, GitHub Issue (#23)
]{biblatex}

**Comment by hushidong** [comment]
那就改成，gblanorder =englishahead

**Comment by mcxhjljy** [comment]
如截图所示，目前在package.tex中采用style=gb7714-2015的方式对参考文献进行排序，也就是按照引用的顺序，但是学院规定的格式为按照英文字母进行排序，尝试采用style=gb7714-2015ay的设置后，能够实现著者年份制，但格式上有较大不同。想求一个学院规定格式的代码，谢谢各位好心人
<img width="787" alt="截屏2024-01-06 下午5 13 38" src="https://github.com/TheNetAdmin/zjuthesis/assets/155810910/85254b51-3c05-4b09-94fc-2313ca1ab80f">
<img width="465" alt="截屏2024-01-06 下午5 20 49" src="https://github.com/TheNetAdmin/zjuthesis/assets/155810910/bf1b279d-41ed-47fd-a31a-337f62939409">
<img width="454" alt="截屏2024-01-06 下午5 16 19" src="https://github.com/TheNetAdmin/zjuthesis/assets/155810910/007e67e0-2962-4558-8984-e0336277d39c">

**Comment by hushidong** [comment]
排序有专门的选项的，是sorting

你加上选项：
sorting=gb7714-2015, gblanorder =englishahead 

就好了
