### ISSUE TITLE
参考文献格式问题

### ISSUE THREAD

**Issue by mcxhjljy** [TheNetAdmin/zjuthesis#363]
### 操作系统

MacOS

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

undergraduate

### Type

thesis

### Period

proposal

### BlindReview

false

### GradLevel

master

### 问题描述

如截图所示，目前在package.tex中采用style=gb7714-2015的方式对参考文献进行排序，也就是按照引用的顺序，但是学院规定的格式为按照英文字母进行排序，尝试采用style=gb7714-2015ay的设置后，能够实现著者年份制，但格式上有较大不同。想求一个学院规定格式的代码，谢谢各位好心人

### 代码

\usepackage[
    %style=gb7714-2015ay
    style=gb7714-2015,
    % gbcitelocal=chinese, % Uncomment if you want \citeauthor{} in "et al." format. GitHub PR (#324)
    % gbpub=false,         % Uncomment if you do NOT want '[S.l. : s.n.]' in reference entries, GitHub Issue (#47)
    % gbnamefmt=lowercase, % Uncomment if you do NOT want uppercase author names in reference entries, GitHub Issue (#23)
    gbnamefmt=lowercase
]{biblatex}

### 截图

<img width="787" alt="截屏2024-01-06 下午5 13 38" src="https://github.com/TheNetAdmin/zjuthesis/assets/155810910/a13d3574-a685-487a-9fc8-b507e79603a4">
<img width="454" alt="截屏2024-01-06 下午5 16 19" src="https://github.com/TheNetAdmin/zjuthesis/assets/155810910/b120f984-7ca7-466e-a9b6-3fe7340a9cbd">
<img width="465" alt="截屏2024-01-06 下午5 20 49" src="https://github.com/TheNetAdmin/zjuthesis/assets/155810910/a20ed740-ef75-4db7-9561-4aa6e0c44856">

**Comment by TheNetAdmin** [comment]
zjuthesis 使用了 [biblatex-gb7714-2015](https://github.com/hushidong/biblatex-gb7714-2015) 宏包，所以查询该宏包的文档，应该在zjuthesis原有的选项上，加入 `sorting=nyt` 选项即可

参见 https://github.com/hushidong/biblatex-gb7714-2015/blob/15db5aaf6834b2359c605227726c67d1350bc660/README.md?plain=1#L458-L460

注意是在 zjuthesis 的默认选项上新增此选项，而不是直接复制该文档中的选项
