### ISSUE TITLE
关于硕士毕业论文封面“硕士学位论文”改为“硕士专业学位论文”的修改方式

### ISSUE THREAD

**Issue by yuewenzheng** [TheNetAdmin/zjuthesis#365]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

9.1.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

![1704655162247(1)](https://github.com/TheNetAdmin/zjuthesis/assets/84398356/756cf22b-11e4-40ad-ae28-186e0fcdd70c)
![1704655183289](https://github.com/TheNetAdmin/zjuthesis/assets/84398356/c081683a-cd28-4ef0-863a-05ac891e3c73)
球球惹，本呆瓜是专硕（应该是图1的封面），用的学硕师兄的模板（现在是图2的状态），这个论文封面“硕士学位论文”改为“硕士专业学位论文”的修改方式是啥呀，真的没找到哇。跪求解答

**Comment by MartinLwx** [comment]
改这里重新编译一下就行https://github.com/TheNetAdmin/zjuthesis/blob/6c5b5f7d9917ee66fd63a52307fed3b6ab997da5/zjuthesis.cls#L98-L100

**Comment by CrazyDumpling** [comment]
把type改为design
