### ISSUE TITLE
Twoside模式下如何删除章与章之间自动的空白页

### ISSUE THREAD

**Issue by mcxhjljy** [TheNetAdmin/zjuthesis#366]
### 操作系统

MacOS

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

undergraduate

### Type

thesis

### Period

proposal

### BlindReview

false

### GradLevel

master

### 问题描述

如截图所示，使用Twoside=true在编译开题报告proposal的时候，如何操作才能够保留目录后的空白页，**但是取消掉chapter与chapter之间的空白页**，比如在截图中希望正文中上一个chapter有内容的最后一页（第7页）与下一个chapter（第9页）的内容不会因为Twoside自动设置的空白页（第8页）而分开。（尝试过利用Twoside=false，但是上面的页眉又和学院要求的奇偶页的格式矛盾了）

### 截图

<img width="308" alt="截屏2024-01-08 下午9 13 31" src="https://github.com/TheNetAdmin/zjuthesis/assets/155810910/63ed7a51-08c7-4609-8194-2ba296ce254b">

**Comment by TheNetAdmin** [comment]
TwoSide选项是传入给`ctexrep`包的

https://github.com/TheNetAdmin/zjuthesis/blob/6c5b5f7d9917ee66fd63a52307fed3b6ab997da5/zjuthesis.cls#L54-L61

所以详细的控制方式应该查询一下ctex宏包的使用说明

但我认为你现在的需求可以使用如下步骤解决：
1. 设置 TwoSide 为 false
2. 注释或删除如下几行用于修改 `\cleardoublepage` 的代码 https://github.com/TheNetAdmin/zjuthesis/blob/6c5b5f7d9917ee66fd63a52307fed3b6ab997da5/config/commands.tex#L6-L14
3. 重新编译
4. （如果还有前言部分页面没有插入空白页）手动在前言部分页面加入 `\cleardoublepage` 命令
