### ISSUE TITLE
请问如何插入子图？

### ISSUE THREAD

**Issue by Dawn-LX** [TheNetAdmin/zjuthesis#37]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
您好！我希望能够插入子图，例如1.1(a)，1.1(b)这样
现在我用
\begin{figure}[htbp]
    \begin{minipage}[t]{0.5\linewidth}
    \centering
    \includegraphics[width=\linewidth]{review/Venn.png}
    \caption{\label{aa} this is aa}
    \end{minipage}%
    \begin{minipage}[t]{0.5\linewidth}
    \centering
    \includegraphics[width=\linewidth]{review/Venn.png}
    \caption{\label{bb}this is a caption}
    \end{minipage}%
    \caption{ pics}
\end{figure}
这样插入图片的话显示的是1.1和1.2
我用subfigure显示我未定义，是不是应该加入\newcommand\subfigure什么的？应该在在哪加怎么加？
能否帮助我一下，谢谢！！
**重现步骤**
如何重现你遇到的问题：

1. 修改了哪里
2. 使用什么命令编译
3. 产生了什么错误/输出结果哪里不对
4.

请附上修改过的文件/工程

如果无法编译，请额外附上 log 文件，位于 out/zjuthesis.log

**截图**
![image](https://user-images.githubusercontent.com/48169011/71537623-919c7700-2959-11ea-8099-8622bff3c84f.png)

**Comment by TheNetAdmin** [comment]
用 subcaption 宏包试试

https://tex.stackexchange.com/questions/13625/subcaption-vs-subfig-best-package-for-referencing-a-subfigure
