### ISSUE TITLE
中文参考文献的作者姓名展示混乱问题

### ISSUE THREAD

**Issue by tianc43** [TheNetAdmin/zjuthesis#372]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

使用如下代码直接引用中文参考文献时会导致显示混乱，
![image](https://github.com/TheNetAdmin/zjuthesis/assets/37445838/2c1efea2-2a51-4254-bd65-4f3d51f86af2)
![image](https://github.com/TheNetAdmin/zjuthesis/assets/37445838/693339a5-b173-4af3-81bd-ed6ce0682ec6)
可以正确显示的代码为：（逗号用花括号包含，作者整体用花括号包含）
![image](https://github.com/TheNetAdmin/zjuthesis/assets/37445838/3db61f1b-baac-4036-bc88-68ade64cd29f)
![image](https://github.com/TheNetAdmin/zjuthesis/assets/37445838/22137897-5923-468d-98c2-2b7f59227444)

**Comment by hushidong** [comment]
作者之间连接符是 and ，不是逗号。
