### ISSUE TITLE
请问导入overleaf和导入texstudio的源码文件有什么区别，是否可以相互使用

### ISSUE THREAD

**Issue by hero-y** [TheNetAdmin/zjuthesis#373]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.1.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

请问导入overleaf和导入texstudio的源码文件有什么区别？
我原本是在overleaf上写论文的，但是overleaf经常很慢，所以想迁移到texstudio上。但是用texstudio好像不能编译overleaf的工程。
并且也看到了楼主对overleaf和texstudio分别提供了源代码文件，所以是不是二者的源代码文件有区别导致的？

**Comment by TheNetAdmin** [comment]
应该没有什么区别，我自己是不使用texstudio的，所以不清楚有什么具体问题。

我推荐使用vscode，安装latex workshop插件，并安装texlive，作为本地编译环境。
