### ISSUE TITLE
设置致谢、摘要居中后，如何修改上下间距？

### ISSUE THREAD

**Issue by chengzhongyi8** [TheNetAdmin/zjuthesis#375]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2019 或更早的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

doctor

### 问题描述

您好，我修改了致谢、摘要以及 Abstract 居中，参考了 [#142](https://github.com/TheNetAdmin/zjuthesis/issues/142#issuecomment-1487984065)，在`commands.tex`中新增了`\chapternonumcenter`函数。
现在想修改这三个标题的上下间距使其一致，尝试添加`\vspace*{10pt}}`没有用。请问该如何解决？谢谢！

### 截图

我现在的样子是：
![WeChatee2c98324eaa6dcfc317b5c1db89f065](https://github.com/TheNetAdmin/zjuthesis/assets/58238523/074149b1-5b95-4696-bdf6-300c7e2ebce2)
我想要修改的样子是：
![WeChatc6b794cc2e454f7999ae37a435a6c380](https://github.com/TheNetAdmin/zjuthesis/assets/58238523/d2c9b5bd-072f-4e3e-998c-2f5a6dd7a0dd)

**Comment by Metro1998** [comment]
你好，我想知道你是怎么解决的
