### ISSUE TITLE
参考文献数字序号不是左对齐

### ISSUE THREAD

**Issue by ddddouzii** [TheNetAdmin/zjuthesis#379]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

doctor

### 问题描述

目前参考文献数字序号是右对齐的，希望能左对齐排列
![参考文献截图](https://github.com/TheNetAdmin/zjuthesis/assets/88706066/1ab2e07f-1dd6-4740-b3d5-3d88f6931f22)

### 截图

![参考文献截图](https://github.com/TheNetAdmin/zjuthesis/assets/88706066/fb53ded2-ec1e-40ab-8378-a45f88fc9ee0)

**Comment by hushidong** [comment]
https://github.com/hushidong/biblatex-gb7714-2015/blob/master/README.md?plain=1#L712

**Comment by ddddouzii** [comment]
> https://github.com/hushidong/biblatex-gb7714-2015/blob/master/README.md?plain=1#L712

感谢，已解决
