### ISSUE TITLE
[BUG]矩阵输入

### ISSUE THREAD

**Issue by zjulsy** [TheNetAdmin/zjuthesis#38]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
在conttent.tex输入矩阵后，编译会有问题。
```
Misplaced alignment tab character &.
\begin{pmatrix} a&
```

**重现步骤**
conttent.tex的内容很少，如下：
```
\chapter{绪论}
\begin{equation}
\begin{pmatrix} a&b1\\c&d \end{pmatrix}
\end{equation}
```

**Comment by TheNetAdmin** [comment]
你忘记引用这个包了吧

\usepackage{amsmath}

![image](https://user-images.githubusercontent.com/18525442/71553332-1f0ac480-2a49-11ea-9663-332f629d4e75.png)
