### ISSUE TITLE
将 overleaf 下载到本地后统计字数

### ISSUE THREAD

**Issue by chengzhongyi8** [TheNetAdmin/zjuthesis#382]
### 操作系统

MacOS

### TeX 套件

TeXLive 2019 或更早的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

doctor

### 问题描述

我在 overleaf 里写好后下载到本地，然后使用 `latexmk -xelatex -outdir=out zjuthesis`编译后想统计字数。但是运行 latexmk 后出现以下几个报错：
- 首先是字体类的，但是我的fonts目录下已经根据 readme 中的要求将所需要的字体加进去了
```
1. Package fontspec Warning: Font "Songti SC Light" does not contain requested
(fontspec)                Script "CJK".
```
```
2.Package xeCJK Warning: Redefining CJKfamily `\CJKrmdefault'
(xeCJK)                (SongtiSCLight(0)).
```
- 然后像是一些包的报错？
```
- ! Package array Error:  Illegal pream-token (C): `c' used.

See the array package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.31     \end{tabular}}
                       
? 

! Package array Error:  Illegal pream-token (1.35cm): `c' used.

See the array package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.31     \end{tabular}}
                       
? 

! Package array Error:  Illegal pream-token (C): `c' used.

See the array package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.31     \end{tabular}}
                       
? 

! Package array Error:  Illegal pream-token (1.35cm): `c' used.

See the array package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.31     \end{tabular}}

```

https://github.com/TheNetAdmin/zjuthesis/issues/90#issue-748014824 和这个报错很像，但似乎没有找到解决办法

### 截图

<img width="278" alt="图片" src="https://github.com/TheNetAdmin/zjuthesis/assets/58238523/66a3ac09-671f-4ca3-81a2-5911d799e2ae">
<img width="916" alt="图片" src="https://github.com/TheNetAdmin/zjuthesis/assets/58238523/9a5f79ed-0e01-4b30-a434-bc932a08f068">
<img width="592" alt="图片" src="https://github.com/TheNetAdmin/zjuthesis/assets/58238523/b0999050-279d-4b1f-adf7-75c97f91e6d2">
<img width="565" alt="图片" src="https://github.com/TheNetAdmin/zjuthesis/assets/58238523/30286875-6cb5-4abc-be6d-d2786b2e591e">

以及参考文献中，中文文献都是这种小方块。

**Comment by TheNetAdmin** [comment]
tex代码里也要重新指定字体，你也已经参考如下脚本修改了tex代码吗？

https://github.com/TheNetAdmin/zjuthesis/blob/0464c71837748cc4ca0ef57aeb5d0bee4b75ef2b/script/ci/setup.sh#L37-L60

**Comment by chengzhongyi8** [comment]
我是直接从overleaf上把我的论文文件下载下来的，解压打开后 script目录下只有 utlies 这一个文件夹，里面是`word_counts.sh `和 `word_counts.ps1`两个文件。

**Comment by yberlin** [comment]
脚本执行的时候提示texcount not found 怎么办

**Comment by TheNetAdmin** [comment]
> 脚本执行的时候提示texcount not found 怎么办

这个命令是texlive提供的，检查一下你的path系统变量是否包含了texlive的所有目录。可以参考一些texlive的安装教程。
