### ISSUE TITLE
TwoSide设定为false后，页码变为自动居中

### ISSUE THREAD

**Issue by minionschen** [TheNetAdmin/zjuthesis#386]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

设定zjuthesis.tex中的TwoSide为false以去掉空页，但是页码也会变为自动居中，预期是仅去掉空页但页码位置仍在左右两侧

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/14585823/zjuthesis.log)

### 截图

![image](https://github.com/TheNetAdmin/zjuthesis/assets/84710999/6e4b114b-c985-4362-9b97-a7b6653a9416)

**Comment by minionschen** [comment]
补充：还有一个问题是图片的title该如何设定才能和图片更贴近一点，现在图片的上下文间隔有点过大

**Comment by TheNetAdmin** [comment]
第一个问题可以参考fancyhdr宏包，更改如下代码

https://github.com/TheNetAdmin/zjuthesis/blob/0464c71837748cc4ca0ef57aeb5d0bee4b75ef2b/config/format/general/layout.tex#L46-L75

第二个问题没有特别好的解决办法，要么使用一些宏包调整间距，要么手动在图片环境里使用 `\vspace{-10pt}` 或者类似的的命令来减少纵向间距。如果图片不多可以采取第二种做法。
