### ISSUE TITLE
[BUG]master cs 的 cover-chn 指导教师的两栏都为导师，应该为一栏导师，一栏合作导师

### ISSUE THREAD

**Issue by philosophy-signal** [TheNetAdmin/zjuthesis#39]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
请简要描述你遇到的问题

**重现步骤**
如何重现你遇到的问题：

文件page/graduate/master/cs/cover-chn.tex 的57行应该该为 `            ~           & \uline{\hfill \ColaboratorName \hfill} \\`

**Comment by philosophy-signal** [comment]
cover-eng 同

**Comment by TheNetAdmin** [comment]
已修复，谢谢提醒
