### ISSUE TITLE
生成图目录时，在尚未填满一页时就另起一页

### ISSUE THREAD

**Issue by VigorLWC** [TheNetAdmin/zjuthesis#392]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v9.1.0

### MajorFormat

cs

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

图目录包含三页，然而第二页还未占据半页就另起了一页。

### 截图

![1](https://github.com/TheNetAdmin/zjuthesis/assets/50977151/68e258b7-7a96-4e23-863e-8d68b04404a9)
![2](https://github.com/TheNetAdmin/zjuthesis/assets
![3](https://github.com/TheNetAdmin/zjuthesis/assets/50977151/2b157e61-e6fe-4261-8ade-7cb3c8cda868)
/50977151/66c9acce-045d-4f25-ae03-60896bea07dc)

**Comment by VigorLWC** [comment]
截图丢失了一部分，重新传一次。
![1](https://github.com/TheNetAdmin/zjuthesis/assets/50977151/5198061c-5a3e-46af-a403-0e1a6eeba28b)
![2](https://github.com/TheNetAdmin/zjuthesis/assets/50977151/6f4f71f0-fd20-4097-b690-3108c30b5f16)
![3](https://github.com/TheNetAdmin/zjuthesis/assets/50977151/014e1c86-cf30-4a0b-9fdd-282d04f3dff6)

**Comment by TheNetAdmin** [comment]
这个问题没怎么见过，尝试清理中间文件然后重新编译呢？

**Comment by TheNetAdmin** [comment]
似乎没有后续跟进了，我猜测问题已经解决？暂时关闭issue，如仍有问题可以重开issue

**Comment by 281LinChenjian** [comment]
请问为什么我的目录、图目录和表目录不会自动生成，有谁知道是哪里出了问题吗？
