### ISSUE TITLE
使用gbcitelocal=chinese，但参考文献仍显示et al 而不是等人

### ISSUE THREAD

**Issue by HeanyGao** [TheNetAdmin/zjuthesis#393]
### 操作系统

Windows

### TeX 套件

TeXLive 2020

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

doctor

### 问题描述

config/packages里使用
\usepackage[
    style=gb7714-2015,
    gbcitelocal=chinese,   % Uncomment if you want \citeauthor{} in "et al." format. GitHub PR (#324)
    gbpub=false,         % Uncomment if you do NOT want '[S.l. : s.n.]' in reference entries, GitHub Issue (#47)
    gbnamefmt=lowercase, % Uncomment if you do NOT want uppercase author names in reference entries, GitHub Issue (#23)
]{biblatex}
在\citet或\citeauthor时，中文作者可以显示 等人，但是英文作者还是et al.
想请问是哪里设置不对吗？

**Comment by hushidong** [comment]
TeXLive 2020 比较老，当时可能没有实现。

换个新版的texlive 就会好了。

```
\documentclass{article}
\usepackage{ctex}
\usepackage[backend=biber, style=gb7714-2015,gbcitelocal=chinese]{biblatex}

\begin{filecontents}[force,noheader]{\jobname.bib}
  @book{hickman2016,
  title = {Space {{Is Power}}: {{The Seven Rules}} of {{Territory}}},
  author = {Hickman, John and others},
  editor={Latham, Michael E.},
  date = {2016},
  publisher = {Lexington Books},
  location = {Lanham}
  }

  @book{guojianlong2017,
  title = {中央帝国的财政密码},
  author = {郭建龙  and others},
  date = {2017-04},
  publisher = {鹭江出版社},
  location = {厦门}
  }
  \end{filecontents}
  \addbibresource{\jobname.bib}

\begin{document}

\textcite{guojianlong2017}

\textcite{hickman2016}

\printbibliography[heading=bibliography]
\end{document} 
```

结果：
![图片](https://github.com/TheNetAdmin/zjuthesis/assets/20421795/77d81925-08fa-4701-b044-503af70f0ffa)

**Comment by HeanyGao** [comment]
感谢回复！

**Comment by HeanyGao** [comment]
更新成2021版解决问题，如果想用等人而不是等的话，参考#367
