### ISSUE TITLE
按照github 提示的cs doctor模板配置之后章节的标题在中间，怎么改成在左侧呀？

### ISSUE THREAD

**Issue by hustcxx** [TheNetAdmin/zjuthesis#394]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

10.1

### MajorFormat

cs

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

doctor

### 问题描述

本来模板中的小章节标题是在左侧的，但是把专业改成cs，gradlevel改成doctor之后就居中了，但是学校的模板要求确实是在左侧。
![image](https://github.com/TheNetAdmin/zjuthesis/assets/25922168/871b1552-dc86-47d0-a545-1cf4b0d418f9)

**Comment by TheNetAdmin** [comment]
更改这里，参考 ctex 宏包的文档即可

https://github.com/TheNetAdmin/zjuthesis/blob/0464c71837748cc4ca0ef57aeb5d0bee4b75ef2b/config/format/major/cs/heading.tex#L6-L50
