### ISSUE TITLE
\signature如何添加信息

### ISSUE THREAD

**Issue by leisong-zju** [TheNetAdmin/zjuthesis#398]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v.10.0.1

### MajorFormat

general

### Degree

undergraduate

### Type

design

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

\signature指令创建了签名的位置和时间，请问我应该在哪里编辑才能将信息填写进去？
![screenshot-1713753988997](https://github.com/TheNetAdmin/zjuthesis/assets/97544984/5860f7cb-0dec-472c-a012-5862c3919971)

**Comment by xfz329** [comment]
我上次好像回答过，你参考下这个看看https://github.com/TheNetAdmin/zjuthesis/discussions/97#discussioncomment-8625455
顺便反馈下效果

**Comment by TheNetAdmin** [comment]
我觉得在顶层zjuthesis实现一些config，或者在各个特殊页面内实现一些config，可能会更方便一些，回头我有空看看怎么改。

**Comment by zjuklay** [comment]
感谢
可以修改，但是会统一修改所有日期，使用可能不方便

**Comment by xfz329** [comment]
或者可以尝试修改下这个命令的参数个数，年月日均作为参数，我调整看一下。稍等下，本科模板我没太用过

**Comment by xfz329** [comment]
> 我觉得在顶层zjuthesis实现一些config，或者在各个特殊页面内实现一些config，可能会更方便一些，回头我有空看看怎么改。
感觉现在同学们对模板的个性化定制需求确实蛮多的了

**Comment by xfz329** [comment]
设置好了
修改config/command.tex,定义一个可修改年月日的签名命令\signaturewithdate如下
```tex
\newcommand{\signaturewithdate}[4]
{
    \begin{flushright}
        \bfseries \zihao{-4}
        #1 \underline{\multido{}{5}{\quad}} \\
        #2 年 #3 月 #4 日
    \end{flushright}
}
```
![1714023702024](https://github.com/TheNetAdmin/zjuthesis/assets/48663326/cfc1dca3-c7e5-4f9f-bceb-148675351b02)

此后可在需要日期的位置使用此命令进行修改，如修改/page/undergraduate/job.tex
```tex
\cleardoublepage{}
\sectionnonum{本科生毕业论文（设计）任务书}

{
    \bfseries
    \noindent 一、题目：\\
    \noindent 二、指导教师对毕业论文（设计）的进度安排及任务要求：\\

    \vskip 50mm

    \noindent 起讫日期 20 \quad 年 \quad  月 \quad  日 \quad 至 \quad 20 \quad  年 \quad  月  \quad 日
    \begin{flushright}
        \bfseries \zihao{-4}
            指导教师（签名） \underline{\multido{}{5}{\quad}} 职称 \underline{\multido{}{5}{\quad}}
    \end{flushright}

    \noindent 三、系或研究所审核意见：\\

    \mbox{} \vfill
    \signaturewithdate{负责人（签名）}{2024}{4}{25}
}
```
最后的编译效果如下
![image](https://github.com/TheNetAdmin/zjuthesis/assets/48663326/6a23d7c4-5be0-43e5-a3a2-99d620487ce9)

**Comment by xfz329** [comment]
@TheNetAdmin 如果觉得该功能可以保留，我可以提个pr

**Comment by xfz329** [comment]
> 感谢 可以修改，但是会统一修改所有日期，使用可能不方便
如无必要，可以不close issue。close后也不要重新开启。
最好保持open

**Comment by zjuklay** [comment]
好的感谢！！

**Comment by xfz329** [comment]
你在全面测试下，我没用过本科模板，只在这个页面测试下了

**Comment by xfz329** [comment]
那就好的

**Comment by TheNetAdmin** [comment]
> @TheNetAdmin 如果觉得该功能可以保留，我可以提个pr

@xfz329 这个很好呀！提个pr之后ci test应该也会检查格式，即便有问题也会发现的

**Comment by xfz329** [comment]
https://github.com/TheNetAdmin/zjuthesis/pull/406
