### ISSUE TITLE
编译时候提示找不到参考文献

### ISSUE THREAD

**Issue by lsq** [TheNetAdmin/zjuthesis#4]
![screenshot_20180526-182818_01](https://user-images.githubusercontent.com/1617256/40575227-c6ed586c-6113-11e8-9ce6-8130ead91ccc.png)
编译出来的pdf文件没有参考文献，错误信息如图片上显示

**Comment by TheNetAdmin** [comment]
编译命令，所有目录下的文件都是什么

**Comment by TheNetAdmin** [comment]
tlmgr --version看一下texlive的版本

**Comment by lsq** [comment]
@TheNetAdmin 
![screenshot_20180526-191552](https://user-images.githubusercontent.com/1617256/40575542-58a72256-6119-11e8-957a-31f50eb0778e.png)

**Comment by TheNetAdmin** [comment]
编译命令是latexmk -xelatex吗

**Comment by lsq** [comment]
@TheNetAdmin 是用`latexmk -xelatex` 编译的，`biber --version` 结果是:

```
No command 'biber' found, did you mean:
 Command 'bibtex' from package 'texlive-bin'
```

**Comment by TheNetAdmin** [comment]
你的texlive可能没装全，缺了biber这个工具

**Comment by TheNetAdmin** [comment]
@lsq 问题解决了吗

**Comment by lsq** [comment]
@TheNetAdmin 没有，好像biber是个perl脚本，在termux上不好安装

**Comment by TheNetAdmin** [comment]
@lsq 安装一个完全版的texlive应该可以解决，texlive发行版是自带这个工具的

**Comment by hushidong** [comment]
@lsq 兄弟，想向你请教一下，termux中安装biber的方法。能不能写个教程，实在是对cpan那套编译不熟悉。

**Comment by lsq** [comment]
你在termux中下载[biber](https://github.com/plk/biber), 然后安装CPAN（termux手册上有），按照biber documents目录里面pdf说明编译就可以了

**Comment by lsq** [comment]
附上在Termux中编译biber的方法：
### 先安装perl
`
pkg install perl
`
`
cpan App::cpanminus
`

### git clone biber
`git clone https://github.com/plk/biber.git`

### 安装依赖文件
`cpanm Module::Build`
`cpanm PAR::Packer`
### 编译
`cd biber`
`perl ./Build.PL`
### 出现相关问题
`Build installdeps`

--------------------------------------
**有问题附上具体错误信息**
