### ISSUE TITLE
参考文献格式问题

### ISSUE THREAD

**Issue by minionschen** [TheNetAdmin/zjuthesis#402]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

参考文献同一条目换行时，如何才能调节行间距

### 编译日志

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/15106616/zjuthesis.log)

### 截图

![image](https://github.com/TheNetAdmin/zjuthesis/assets/84710999/8ed0ba83-cafd-475e-81cc-ed22152f4f11)

**Comment by xfz329** [comment]
修改body/graduate/post/ref.tex为
```tex
\cleardoublepage
\begingroup
    % \linespreadsingle{}
    \linespreadonehalf{}
    \printbibliography[title={参考文献}]
\endgroup
```
就可以调整行间距了

**Comment by minionschen** [comment]
> 修改body/graduate/post/ref.tex为
> 
> ```
> \cleardoublepage
> \begingroup
>     % \linespreadsingle{}
>     \linespreadonehalf{}
>     \printbibliography[title={参考文献}]
> \endgroup
> ```
> 
> 就可以调整行间距了

谢谢老哥！
