### ISSUE TITLE
如何在目录中将致谢和摘要添加在“第一部分 毕业论文”之后

### ISSUE THREAD

**Issue by TianyuFan0504** [TheNetAdmin/zjuthesis#403]
### 操作系统

MacOS

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

undergraduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

在模板中，注意到“致谢”和“摘要”也要添加在目录之中，但由于出现顺序分别是致谢、摘要、第一部分 毕业论文，导致直接加入目录时会出现如下图所示问题：
<img width="560" alt="截屏2024-04-26 13 13 12" src="https://github.com/TheNetAdmin/zjuthesis/assets/87062283/26ae4ef2-26ba-4e0e-b656-48ca567a7b8c">
模板中要求的格式为：
<img width="498" alt="截屏2024-04-26 13 09 42" src="https://github.com/TheNetAdmin/zjuthesis/assets/87062283/d983b2c9-2ed1-45d7-a65a-9f4ac8cfd1d4">
目前尝试过：
1.在绪论之前开一页空白页+手动页码然后命名为致谢添加进目录，但是这样会导致后续页码全部乱掉
2.把“第一部分 毕业论文”提前，但是没有找到这个在哪里🥺

**Comment by iks-ran** [comment]
一个不怎么成熟的方法，在page下新建tex文件，我命名为了toc-previous
```latex
\addcontentsline{toc}{section}{承诺书 \hspace{30cm}}

\section*{致~谢}
\addcontentsline{toc}{section}{致~谢}
\cleardoublepage

\section*{摘~要}
\addcontentsline{toc}{section}{摘~要}
\cleardoublepage
```

之后修改zjuthesis.tex
```latex
      ...
      \bodystyle
      \inputpage{final}{cover-part}

      % toc 增页
      \prevstyle
      \inputpage{final}{toc-previous}
      \bodystyle
      % toc 增页

      \resetpagecounter{}
      \inputbody{final/content}
      \inputbody{final/post}
      ...
```
<img width="593" alt="Screenshot 2024-05-04 at 01 57 56" src="https://github.com/TheNetAdmin/zjuthesis/assets/114058278/699395d4-2e54-43a6-bb2b-463ee05a3714">

目录中其他部分也可以如法炮制，最后删掉acrobat增页就行，学院给的模版从逻辑关系上是不成立的（起码从latex toc的角度来说应该是这样？），不知道ftygg有没有好的解决办法
