### ISSUE TITLE
[BUG]硕博士模板参考文献、附录、作者简历的页码

### ISSUE THREAD

**Issue by Garrybest** [TheNetAdmin/zjuthesis#41]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
硕博士模板中参考文献、附录、作者简历部分没有显示页码，但在目录中却显示了他们的页码，看起来不是很合理。

**Comment by TheNetAdmin** [comment]
已修复，请使用最新的master分支commit https://github.com/TheNetAdmin/zjuthesis/commit/a6d2fd429902023001838bb0e90b194ddfd31a33
