### ISSUE TITLE
参考文献引用格式问题

### ISSUE THREAD

**Issue by leisong-zju** [TheNetAdmin/zjuthesis#411]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

undergraduate

### Type

design

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

安装texlive2024在本地进行编译，参考文献在ref.bib文件中添加，编译报错。
在网上检索是因为使用biber编译的原因，但是此前的相关issue指出正确用法就是使用biber，请问应该怎么解决呀

### 截图

![微信截图_20240507203336](https://github.com/TheNetAdmin/zjuthesis/assets/97544984/46a1e968-e543-40d3-87a4-be114929f4d6)
![微信截图_20240507203353](https://github.com/TheNetAdmin/zjuthesis/assets/97544984/714f8fb2-d413-40f1-8d27-afc688f39aba)

**Comment by Wendaoi** [comment]
同样的问题bd

**Comment by TheNetAdmin** [comment]
Compile with `latexmk` command and it should automatically work with biber. The VS Code plug-in's default compilation recipe may not work well, just use `latexmk` command, or check how vscode works with the settings in this repo:

https://github.com/TheNetAdmin/zjuthesis/blob/9476151fc2815b3d42a6613d38286ad8a379e704/.vscode/settings.json#L4

**Comment by leisong-zju** [comment]
清理临时文件后，使用latexmk命令编译解决了，感谢帮助
