### ISSUE TITLE
如何修改参考文献部分页眉内容

### ISSUE THREAD

**Issue by koriyyy** [TheNetAdmin/zjuthesis#413]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

cs

### Degree

undergraduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

1. 想要把参考文献一节的页眉修改为“参考文献”或直接删除。感谢

**Comment by TheNetAdmin** [comment]
页眉是使用 `\fancyhead` 设置的，例如这里
https://github.com/TheNetAdmin/zjuthesis/blob/9476151fc2815b3d42a6613d38286ad8a379e704/config/format/general/layout.tex#L20-L44

如果是简单的去除参考文献页眉的话，有两种选择

第一种是修改`\inputbody{final/post}`的位置，移动使其位于`\poststyle`之后
https://github.com/TheNetAdmin/zjuthesis/blob/9476151fc2815b3d42a6613d38286ad8a379e704/zjuthesis.tex#L82-L85

因为`\poststyle`已经定义页眉为空，只需移动 `final/post` 让它使用 `\poststyle` 即可
https://github.com/TheNetAdmin/zjuthesis/blob/9476151fc2815b3d42a6613d38286ad8a379e704/config/format/general/layout.tex#L211-L225

第二种是在参考文献代码（如下）之前添加 `\fancyhead{}`
https://github.com/TheNetAdmin/zjuthesis/blob/9476151fc2815b3d42a6613d38286ad8a379e704/body/undergraduate/final/post.tex#L2-L6
