### ISSUE TITLE
表格：字体及大小如何设置

### ISSUE THREAD

**Issue by minionschen** [TheNetAdmin/zjuthesis#414]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.0

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

表格字体需要设置为5号宋体，应如何配置

**Comment by TheNetAdmin** [comment]
直接在表格环境中指定字体大小即可，参考ctex文档。表格环境中的字体大小不会影响表格外的设定。
