### ISSUE TITLE
biber报错，参考文献不显示

### ISSUE THREAD

**Issue by Mabiux** [TheNetAdmin/zjuthesis#416]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

10.0.1

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

因为编译时biber报错导致无法显示参考文献，直接下载原模版，按照命令行编译的方法，还是出现同样报错

### 编译日志

[zjuthesis.log](https://github.com/user-attachments/files/15525035/zjuthesis.log)

### 截图

![image](https://github.com/TheNetAdmin/zjuthesis/assets/97380597/e0c448a5-6638-42b8-aba6-5794de693323)
![image](https://github.com/TheNetAdmin/zjuthesis/assets/97380597/f7106522-d2d3-4b7d-94aa-3f569faf4cac)

**Comment by hushidong** [comment]
清理一下biber缓存的文件，应该是在系统默认的临时文件夹下。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Mabiux ***@***.***>
Sent: Sunday, June 2, 2024 7:04:19 PM
To: TheNetAdmin/zjuthesis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TheNetAdmin/zjuthesis] biber报错，参考文献不显示 (Issue #416)


操作系统

Windows

TeX 套件

TeXLive 2021 或更新的版本

TeX Compiler

XeTeX

zjuthesis 版本号

10.0.1

MajorFormat

general

Degree

graduate

Type

thesis

Period

final

BlindReview

true

GradLevel

master

问题描述

因为编译时biber报错导致无法显示参考文献，直接下载原模版，按照命令行编译的方法，还是出现同样报错

编译日志

zjuthesis.log<https://github.com/user-attachments/files/15525035/zjuthesis.log>

代码

No response

截图

image.png (view on web)<https://github.com/TheNetAdmin/zjuthesis/assets/97380597/e0c448a5-6638-42b8-aba6-5794de693323>
image.png (view on web)<https://github.com/TheNetAdmin/zjuthesis/assets/97380597/f7106522-d2d3-4b7d-94aa-3f569faf4cac>

其他信息

No response

―

**Comment by Mabiux** [comment]
是我截图里的这个行文件夹吗，那个我删了之后重新运行，然后文件夹又出现了
![image](https://github.com/TheNetAdmin/zjuthesis/assets/97380597/7251c7c9-43b6-4b24-831b-94f47339065a)

**Comment by hushidong** [comment]
就是会出现的，只要不报错就好了。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hushidong** [comment]
更新一下biblatex和biber好了。

然后测试的时候，用命令行

xelatex jobname.TEX
biber jobname
xelatex jobname.tex

测试看结果有没有问题。

**Comment by Mabiux** [comment]
这两天直接重装了一次latex，更新完用biber还是报错，然后查到用biber.exe --winunicode zjuthesis，这样可以显示参考文献，但是字体和格式好像不对？
![image](https://github.com/TheNetAdmin/zjuthesis/assets/97380597/5dcad332-9b3e-4021-9779-2f453f99489d)
这里看起来编号、行距、字体都不太对劲

**Comment by Mabiux** [comment]
用latexmk也试过了，out文件夹下的pdf还是不显示参考文献
