### ISSUE TITLE
如何去除空白页的页码与页眉

### ISSUE THREAD

**Issue by leisong-zju** [TheNetAdmin/zjuthesis#419]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

undergraduate

### Type

design

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

之前的issue提出的解决办法是5.0版本，现在的版本不适用，请问应该在哪里修改才能将摘要和正文部分空白页中的页眉页脚去除

**Comment by Sec-ant** [comment]
引 `emptypage` 这个包会自动把所有由 `\cleardoublepage` 生成的空白页改为完全空白的：

```latex
\usepackage{emptypage}
```

https://tex.stackexchange.com/a/21630
