### ISSUE TITLE
如何减少章节(/chapter)前的空白？

### ISSUE THREAD

**Issue by liutongya** [TheNetAdmin/zjuthesis#42]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
每章节前空白太大，请问需要修改什么地方？

**Comment by TheNetAdmin** [comment]
哪里的空白，可以截图说明一下吗

**Comment by liutongya** [comment]
<img width="744" alt="WX20200111-225914@2x" src="https://user-images.githubusercontent.com/39849161/72206218-19d85b80-34c6-11ea-8687-f65d839e9d88.png">

**Comment by TheNetAdmin** [comment]
你说的是数字 `1` 和 `引言`之间的空白吧？

尝试在这里

https://github.com/TheNetAdmin/zjuthesis/blob/f127255dca73b3f528b617bd578d71844ecf1a98/config/format/general/heading.tex#L56-L63

添加代码

```latex
aftername=\vspace{-10pt},
```

详情见 `ctex` 文档 第 7 节 章节标题格式设置

**Comment by liutongya** [comment]
我指的是1 引言页面上面的空白，比学校的模版空白大很多

**Comment by TheNetAdmin** [comment]
调整 `beforeskip`， 并添加 `fixskip=true`，然后在页面内填充满文字。
