### ISSUE TITLE
研究生开题报告封面输出两页

### ISSUE THREAD

**Issue by ZYuan99** [TheNetAdmin/zjuthesis#422]
### 操作系统

MacOS

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

false

### GradLevel

master

### 问题描述

1. 修改 zjuthesis.tex 中的 undergraduate -> graduate
2. latexmk编译
3. 编译正确, 封面显示错误, 递交日期一行出现在pdf第二页
4. 递交日期一行应该出现在pdf第一页
<img width="385" alt="截屏2024-06-19 下午4 03 47" src="https://github.com/TheNetAdmin/zjuthesis/assets/111180791/edcd8baa-cbd5-4436-8c1d-5501bf166868">

### 编译日志

[zjuthesis.log](https://github.com/user-attachments/files/15898494/zjuthesis.log)

**Comment by TheNetAdmin** [comment]
修改一下页面内的 `\vskip` 数值即可，应该是编译器计算纵向间距时有误差

**Comment by lun-gary** [comment]
在page/graduate/master/cover-chn.tex中，修改128行内容 “\ifthenelse{\equal{\DepartmentLines}{1}}” ，将数字1改为2即可
