### ISSUE TITLE
请问符号术语清单怎么在页面居中

### ISSUE THREAD

**Issue by InvokerH** [TheNetAdmin/zjuthesis#424]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

opteng

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

术语清单只有标题能居中，具体的列表只能在页面左对齐

### 代码

在commands.tex里面的代码是这样：
% Term Table title, centered
\renewcommand{\nomname}{\makebox[\linewidth]{主要符号说明}}
% Term Table style
\newcommand{\nomdescr}[1]{
    \parbox[t]{8.5cm}{\linespreadsingle{}\raggedright\strut #1 \strut}
}
\newcommand{\nomdescrchn}[1]{
    \hfill\parbox[t]{5cm}{\linespreadsingle{}\strut #1 \strut}\ignorespaces
}
\newcommand{\nomchn}[4][]{
    \nomenclature[#1]{#2}{
        \nomdescr{#3}
        \nomdescrchn{#4}
    }
}

在toc.tex里的相关代码是这样：
\cleardoublepage
\phantomsection
\marklon

\printnomenclature[4cm]
\nomenclature[01]{$a$或$A$}{标量}
\nomenclature[02]{$\mathbf{a}$或$\mathbf{A}$}{向量或矩阵}

### 截图

![图片2](https://github.com/TheNetAdmin/zjuthesis/assets/104074096/92cf7544-2043-4641-ae71-82d7d6a74ea3)

**Comment by TheNetAdmin** [comment]
参考这里的实现呢
https://github.com/TheNetAdmin/zjuthesis/blob/master/page/graduate/term-translation.tex

**Comment by InvokerH** [comment]
> 参考这里的实现呢 https://github.com/TheNetAdmin/zjuthesis/blob/master/page/graduate/term-translation.tex

谢谢，已经解决啦
