### ISSUE TITLE
$$公式环境中的数字不是times new roman，该怎么设置？

### ISSUE THREAD

**Issue by InvokerH** [TheNetAdmin/zjuthesis#425]
### 操作系统

Windows

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

opteng

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

$$公式环境中的数字不是times new roman，但英文字母好像是times new roman，该怎么把数字也设成times new roman？

### 截图

![图片2](https://github.com/TheNetAdmin/zjuthesis/assets/104074096/1df8a2ff-5c2e-4068-98a5-d8661aa805b0)
截图里面除了最后的“34”是在正文中输入的，其他的在$$公式环境中输入，字体明显不一样

**Comment by synesios** [comment]
我也发现了这个问题，请问解决了吗

**Comment by synesios** [comment]
但是我也注意到，equation环境里面的数字也是和正文不一样的字体。

**Comment by InvokerH** [comment]
> 但是我也注意到，equation环境里面的数字也是和正文不一样的字体。

没有完全解决，用了类似于times的字体，可以参考https://www.zhihu.com/question/391007830

**Comment by synesios** [comment]
> > 但是我也注意到，equation环境里面的数字也是和正文不一样的字体。
> 
> 没有完全解决，用了类似于times的字体，可以参考https://www.zhihu.com/question/391007830

我还发现，我正文里面的字母的字体和公式环境里面的不一样，这是合理的吗？？？
![image](https://github.com/user-attachments/assets/f6fd30f0-dee9-4f5b-9891-1c2b19ad3501)

**Comment by InvokerH** [comment]
> > > 但是我也注意到，equation环境里面的数字也是和正文不一样的字体。
> > 
> > 
> > 没有完全解决，用了类似于times的字体，可以参考https://www.zhihu.com/question/391007830
> 
> 我还发现，我正文里面的字母的字体和公式环境里面的不一样，这是合理的吗？？？ ![image](https://private-user-images.githubusercontent.com/97509569/355049725-f6fd30f0-dee9-4f5b-9891-1c2b19ad3501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDkxMTQsIm5iZiI6MTcyMjkwODgxNCwicGF0aCI6Ii85NzUwOTU2OS8zNTUwNDk3MjUtZjZmZDMwZjAtZGVlOS00ZjViLTk4OTEtMWMyYjE5YWQzNTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAxNDY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZTQ0YzA4YjhiYTc5MzNjNjBhMmQzZDEyYzUzNzVjY2Q1Y2E2Zjk0MTQ1ODYwODZkM2UzMmE2NjI1MzM3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Sg1w8N2BFQWLBBwvI4AMb8GPHeYW7Xqy69tDxe5Qa0)

 我没碰到这个问题诶，我是直接用了amsmath包，\usepackage{amsmath}

**Comment by xfz329** [comment]
> > > 但是我也注意到，equation环境里面的数字也是和正文不一样的字体。
> > 
> > 
> > 没有完全解决，用了类似于times的字体，可以参考https://www.zhihu.com/question/391007830
> 
> 我还发现，我正文里面的字母的字体和公式环境里面的不一样，这是合理的吗？？？ ![image](https://private-user-images.githubusercontent.com/97509569/355049725-f6fd30f0-dee9-4f5b-9891-1c2b19ad3501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNTQ2ODEsIm5iZiI6MTcyNTE1NDM4MSwicGF0aCI6Ii85NzUwOTU2OS8zNTUwNDk3MjUtZjZmZDMwZjAtZGVlOS00ZjViLTk4OTEtMWMyYjE5YWQzNTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDAxMzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMGVhZGEzZWVhMTI5MzJmYWJmNGJkMDg4ZDE3ZjhmNDczYTA1NWFiMDg0ZjY2OGZkODRmZjkwMWIxNjI5NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nn_FEV9iHB8GMbF5DgvX3e9IWl-A01LRUREZqZFuKn8)

使用数学环境 $$，在环境里面编译你的公式
