### ISSUE TITLE
字体warning，字体完全错误

### ISSUE THREAD

**Issue by AlbertiPot** [TheNetAdmin/zjuthesis#428]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

graduate

### Type

thesis

### Period

final

### BlindReview

true

### GradLevel

doctor

### 问题描述

不管是overleaf，还是Mac，都会warning如图，字体也不对
![Screenshot 2024-10-07 at 19 37 37](https://github.com/user-attachments/assets/a26f3f0e-bb54-4bb3-bcfc-4c62dfca5acc)

**Comment by DuYawen1215** [comment]
你好，遇到了同样的问题，请问解决了吗

**Comment by AlbertiPot** [comment]
> 你好，遇到了同样的问题，请问解决了吗

你好，没有解决。mac系统，在overleaf和本地编译要么报错，要么warning字体不对。完全按照教程弄字体了。
最后是在mac上先写完，在同学的win上调整吧，win上编没问题，字体对

**Comment by TheNetAdmin** [comment]
我在我的mac上直接编译是可以的，我猜可能是某些版本的macos缺失字体？

贴一个完整的zjuthesis.log，以及 `fc-list` 命令的完整输出吧，我再详细看看是哪里的问题
