### ISSUE TITLE
生成目录没有显示

### ISSUE THREAD

**Issue by Michaelsssssheng** [TheNetAdmin/zjuthesis#43]
**遇到的问题**
目录页只显示目录，没有其他的内容。mac的TEX live。编译没有问题，其他内容都正常。
[zjuthesis（被拖移）.pdf](https://github.com/TheNetAdmin/zjuthesis/files/4280639/zjuthesis.pdf)

**Comment by muzimuzhi** [comment]
生成该 pdf 的对应的 tex 文件是什么？

**Comment by TheNetAdmin** [comment]
把issue模板填一遍，我不知道你哪个环节出问题了。

**Comment by TheNetAdmin** [comment]
把编译生成的中间文件全部删除，然后重新编译试试

**Comment by Michaelsssssheng** [comment]
是TexLive版本的问题，更新成2019的就都好了
