### ISSUE TITLE
公式字体中\mathcal花写和原来的字体差距太大

### ISSUE THREAD

**Issue by Th0masAndy** [TheNetAdmin/zjuthesis#430]
### 可改进的内容

因为引入了mathptmx包之和，mathcal花写体和原来差距较大，容易与常规写法有出入

### 代码与步骤

在mathptmx包下面加入两行代码就可以恢复花写字体
\usepackage{mathptmx} % Use times font in equation env (#426 #425)
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}
\DeclareSymbolFont{largesymbols}{OMX}{cmex}{m}{n}

**Comment by Jh271441** [comment]
在config/packages.txt下添加：
```
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}
\DeclareSymbolFont{largesymbols}{OMX}{cmex}{m}{n}
```
