### ISSUE TITLE
参考文献跨页两端无法对齐

### ISSUE THREAD

**Issue by michuanhaohao** [TheNetAdmin/zjuthesis#44]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
参考文献奇数页和偶数页的两边间距不一样

**重现步骤**
如何重现你遇到的问题：

1. 修改了哪里：未修改参考文献部分
2. 使用什么命令编译：F8 F6 F6编译
3. 未对齐

请附上修改过的文件/工程

如果无法编译，请额外附上 log 文件，位于 out/zjuthesis.log

**截图**

![image](https://user-images.githubusercontent.com/23547900/76066667-01b62180-5fc9-11ea-9293-7ad15aa3ddba.png)

- 输出结果的截图
- 如果方便的话，也请附上其他有帮助的截图
![image](https://user-images.githubusercontent.com/23547900/76066755-27dbc180-5fc9-11ea-974c-85f611add7a4.png)

**环境**
 - zjuthesis版本: [e.g. v3.0.0 或 3c8a471(commit id)]
- zjuthesis基础设置 **请将如下代码替换为你的`\documentclass`代码，注意隐藏个人信息**
```
\documentclass[
    StudentName = xx,
    StudentID   = xx,
    AdvisorName = xx,
    Grade       = xx,            % only the year, no '级'
    Major       = xx,
    Department  = xx,
    Title       = 毕业论文/设计题目,
    SubmitDate  = 递交日期,
    MajorFormat = general,
    Degree      = graduate,   % 'undergraduate' or 'graduate'
    Type        = thesis,          % 'thesis'   or 'design' or 'equal'(only for graduate)
    Period      = final,           % 'proposal' or 'final'
    BlindReview = false,           % 'false'    or 'true'
    % Below only for 'graduate'
    Topic           = xx, 
    ColaboratorName = xx
]{config/zjuthesis}
```
 - OS: win10
 - Tex套件: Texlive
 - Tex套件版本: 2019
 - XeLaTex版本: (请附上`xelatex --version`命令的所有输出)
``` shell
XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019)
kpathsea version 6.3.1
Copyright 2019 SIL International, Jonathan Kew and Khaled Hosny.
```

**其他信息**
其他你认为有帮助的信息

**Comment by TheNetAdmin** [comment]
左侧红框的不对齐应该是单双页页边距不同导致的，我查一下代码再看怎么修复。右侧不对齐看上去是因为参考文献条目缺少空格导致的，能把对应的条目贴一下么？

**Comment by TheNetAdmin** [comment]
以及你用的zjuthesis版本是什么？可以在config/version.tex中查到

**Comment by michuanhaohao** [comment]
\newcommand{\zjuthesisversion}{4.2.1}

谢谢啊，我需要改动哪个地方，论文写完了，不想重新pull

**Comment by TheNetAdmin** [comment]
> \newcommand{\zjuthesisversion}{4.2.1}
> 
> 谢谢啊，我需要改动哪个地方，论文写完了，不想重新pull

https://github.com/TheNetAdmin/zjuthesis/blob/f8c58277850ef4a537f313013e27d91afbdfc798/config/format/general/layout.tex#L1-L23

**Comment by michuanhaohao** [comment]
改好了，谢谢，但是出现了新问题，正文里面章节从偶数页开始，但是目录里面显示的是奇数页

![image](https://user-images.githubusercontent.com/23547900/76158214-7ebed380-614e-11ea-94a1-eac81164ce02.png)

![image](https://user-images.githubusercontent.com/23547900/76158218-8b432c00-614e-11ea-881c-7751ef36da52.png)

如上图，目录显示15页，但是实际是16开始

**Comment by michuanhaohao** [comment]
好像是双页判定哪里出了问题，我直接手动插入空白页解决了

**Comment by TheNetAdmin** [comment]
把中间文件全部删除，然后用命令行重新编译一遍呢？

**Comment by michuanhaohao** [comment]
不行，手动插入空白页可以，应该是双页判定出了问题，很奇怪

**Comment by muzimuzhi** [comment]
> 好像是双页判定哪里出了问题，我直接手动插入空白页解决了

我编译模板中的示例文档，无法复现问题。能否提供一个可复现问题的例子？

**Comment by michuanhaohao** [comment]
@muzimuzhi 感觉忽略这个问题吧，我之前也是好好的，突然就遇到问题，如果只是我一个人的问题，那就是偶然出现的，而且这个手动解决也很简单。如果有人遇到了同样的问题再解决吧，辛苦了。

**Comment by TheNetAdmin** [comment]
暂时搁置，如果有人还遇到类似问题可重开这个 issue
