### ISSUE TITLE
如何修改参考文献的行距为1.5倍

### ISSUE THREAD

**Issue by ninedayhx** [TheNetAdmin/zjuthesis#447]
### 操作系统

Overleaf

### TeX 套件

TeXLive 2021 或更新的版本

### TeX Compiler

XeTeX

### zjuthesis 版本号

v10.0.1

### MajorFormat

general

### Degree

graduate

### Type

design

### Period

final

### BlindReview

true

### GradLevel

master

### 问题描述

使用overleaf进行编译，所标注的参考文献的行间距过短，需要将其调整为1.5倍行距，看了一下代码，似乎是在目录config/format/general/layout.tex的第211行修改对应的poststyle，但是不知道如何继续修改
![image](https://github.com/user-attachments/assets/470f4bcc-530b-4dd1-a2ba-e2f2cdb060db)

**Comment by winterwindwang** [comment]
请问解决了吗？

**Comment by ninedayhx** [comment]
在post/ref.tex中修改对应的如下代码
```
\cleardoublepage
\begingroup
    %\linespreadsingle{}
    \linespreadonehalf{}
    \printbibliography[title={参考文献}]
\endgroup
```

**Comment by idolkider-jpg** [comment]
请问我的目录中没有出现参考文献，但在正文结尾有出现行距很小的一页参考文献，并且没有标题，是否是因为post/ref.tex里面只有\cleardoublepage
\begingroup
    %\linespreadsingle{}
    \linespreadonehalf{}
    \printbibliography[title={参考文献}]
\endgroup 以上代码的原因？
