### ISSUE TITLE
修改页眉文字字体

### ISSUE THREAD

**Issue by yiran98** [TheNetAdmin/zjuthesis#45]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
请简要描述你遇到的问题

**重现步骤**
如何重现你遇到的问题：

1. 修改了哪里
2. 使用什么命令编译
3. 产生了什么错误/输出结果哪里不对
4.

请附上修改过的文件/工程

如果无法编译，请额外附上 log 文件，位于 out/zjuthesis.log

**截图**

- 重现步骤的截图
- 输出结果的截图
- 如果方便的话，也请附上其他有帮助的截图

**环境**

|项目|内容|
|:-|:-|
| 操作系统 | [e.g. Linux/Windows/MacOS] |
| Tex套件 | [e.g. Texlive/Miktex] |
| Tex套件版本 | [e.g. 2019] |
| zjuthesis.log | [使用命令行编译一遍，然后将 out/zjuthesis.log 附在此issue] |

**其他信息**
其他你认为有帮助的信息

请问如何修改页眉的字体为宋体？

**Comment by TheNetAdmin** [comment]
如果你在用 `undergraduate` 的 `general` 模板，修改这里

https://github.com/TheNetAdmin/zjuthesis/blob/f8c58277850ef4a537f313013e27d91afbdfc798/config/format/general/layout.tex#L42-L48

改为

```
 \newcommand{\commonhead} 
 { 
     \fancyhead{} 
     \fancyhead[EL]{\zihao{-5} \songti \TitleTypeName} 
     \fancyhead[OR]{\zihao{-5} \songti \Title} 
     \renewcommand{\headrulewidth}{0.6pt} 
 } 
```

---

如果在用其他模板，可能需要修改这里
https://github.com/TheNetAdmin/zjuthesis/blob/f8c58277850ef4a537f313013e27d91afbdfc798/config/format/general/layout.tex#L67-L71

或者各专业模板下对应的代码

**Comment by yiran98** [comment]
解决了！非常感谢！
