### ISSUE TITLE
参考文献中出现“[S.l. : s.n.]”

### ISSUE THREAD

**Issue by zjulsy** [TheNetAdmin/zjuthesis#47]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
自动生成的参考文献中出现很多“[S.l. : s.n.]”
比如：BAILER C, FINCKH M, LENSCH H P. Scale robust multi view stereo[C]//European
Conference on Computer Vision. [S.l. : s.n.], 2012: 398-411.

请问这个问题可以怎么解决

**Comment by qiaott** [comment]
在packages.tex中，把：
\usepackage[style=numeric,
            sorting=none,
            bibstyle=gb7714-2015,
            citestyle=gb7714-2015]{biblatex}
改成：
\usepackage[style=numeric,
            sorting=none,
            gbpub=false,
            bibstyle=gb7714-2015,
            citestyle=gb7714-2015]{biblatex}
就可以解决

**Comment by hushidong** [comment]
楼上正解。

不过有一点需要说明：
设置style等价于同时设置bibstyle和citestyle，所以上面代码中`style=numeric,`其实是不需要的，可以改写为：
```
\usepackage[style=gb7714-2015,
sorting=none,
gbpub=false]{biblatex}
```

**Comment by TheNetAdmin** [comment]
> 楼上正解。
> 
> 不过有一点需要说明：
> 设置style等价于同时设置bibstyle和citestyle，所以上面代码中`style=numeric,`其实是不需要的，
> 同时gb7714-2015样式默认sorting=none，所以也可以去掉。
> 
> 所以代码可以改写为：
> 
> ```
> \usepackage[style=gb7714-2015,
> gbpub=false]{biblatex}
> ```

感谢指出多余的设置，这些是多余的设置代码我编写模板时写入的，在下一个版本中我会进行精简

**Comment by zjulsy** [comment]
爱你们，摸摸大

**Comment by MARMOTatZJU** [comment]
> 楼上正解。
> 
> 不过有一点需要说明：
> 设置style等价于同时设置bibstyle和citestyle，所以上面代码中`style=numeric,`其实是不需要的，
> 同时gb7714-2015样式默认sorting=none，所以也可以去掉。
> 
> 所以代码可以改写为：
> 
> ```
> \usepackage[style=gb7714-2015,
> gbpub=false]{biblatex}
> ```

@hushidong 感谢提供帮助。

不过从兼容性的角度看，显式提供应该会更为“安全”？因为不同版本的宏包，默认值可能不一样？

**Comment by hushidong** [comment]
国标要求给出的。所以默认给出。
