### ISSUE TITLE
无需为 ctexrep 文档类使用 `heading=true` 选项

### ISSUE THREAD

**Issue by muzimuzhi** [TheNetAdmin/zjuthesis#50]
`heading=true` 选项只对 `ctex` 宏包有意义，调整章节样式的功能在 `ctex` 文档类中总是提供。

https://github.com/TheNetAdmin/zjuthesis/blob/2a54a3c0e4ced1b77c09f23ac2dc0065855c6060/config/zjuthesis.cls#L44-L49

**Comment by muzimuzhi** [comment]
PS: 也许可以为 Enhancement 单设一类 issue template。

**Comment by TheNetAdmin** [comment]
> PS: 也许可以为 Enhancement 单设一类 issue template。

感谢你的建议，已经修复了代码，并增加了一个 issue template
