### ISSUE TITLE
请问如何将正文的字体增大一号？

### ISSUE THREAD

**Issue by hietwll** [TheNetAdmin/zjuthesis#51]
感谢分享nice的模板！有个小小的问题，我想将正文的字体增大一号，应该去哪个文件里设置？

**Comment by TheNetAdmin** [comment]
在 config/zjuthesis.cls 中将这里的 -4 (小四)改为 4 (四号)

```
\LoadClass[
zihao=-4,
UTF8,
twoside
]{ctexrep}

```

**Comment by muzimuzhi** [comment]
ctex 的文档类选项 `zihao` 只支持 `zihao=-4|5|false` 三个值，不支持 `zihao=4`。

相关源码
```tex
    zihao .choice: ,
    zihao .value_required:n = true ,
    zihao /     5  .code:n = { \int_gset:Nn \g_@@_font_size_int { 0 } } ,
    zihao /    -4  .code:n = { \int_gset:Nn \g_@@_font_size_int { 1 } } ,
    zihao / false  .code:n = { \int_gset:Nn \g_@@_font_size_int { 2 } } ,
```
https://github.com/CTeX-org/ctex-kit/blob/72b67db47189e50ea219a693003a0aaaa4c8b391/ctex/ctex.dtx#L3387-L3391

正文字号（`\normalsize`）的调整是个系统工程，涉及
 - `\small`、`\large` 等字号切换命令的重定义。例如 `\normalsize` 改成 14pt，那么 `\large` 可能就要改成 17pt
 - 一些间距的调整，例如行间公式前后的纵向间距

具体数值的设定是一个设计任务。ctex 宏集对应 `zihao=-4` 提供了配置文件 `kpsewhich ctex-cs4size.clo`，对应 `zihao=5` 的是 `kpsewhich ctex-c5size.clo`，可以仿照定制自己的字号配置文件。

只修改当前字号时，可以使用 ctex 宏集提供的 `\zihao` 命令。

**Comment by TheNetAdmin** [comment]
@muzimuzhi 感谢指出

**Comment by hietwll** [comment]
是的，我尝试过在config/zjuthesis.cls 改字号，编译报错。看来字体调整牵一发动全身，还是不调整了。感谢两位及时帮助~
