### ISSUE TITLE
英语标题如何换行

### ISSUE THREAD

**Issue by chao-song** [TheNetAdmin/zjuthesis#52]
windows10系统，tex2019环境，graduate模式，编辑完zjuthesis后直接cmd运行latexmk，尝试了插入\\, 增加{}等多种方案，均失败

**Comment by chao-song** [comment]
windows10系统，tex2019环境，编辑完zjuthesis后直接cmd运行latexmk，尝试了插入\\, 增加{}等多种方案，均失败

**Comment by TheNetAdmin** [comment]
贴一下你的代码和你预期的结果

**Comment by chao-song** [comment]
> 贴一下你的代码和你预期的结果

\documentclass[
    StudentName     = 姓名1,
    StudentID       = 12345678,
    AdvisorName     = 姓名2,
    Grade           = 2000,            % only the year, no '级'
    Major           = 专业,
    Department      = 学系,
    Title           = 中文题目,
    SubmitDate      = 递交日期,
    MajorFormat     = physics,
    Degree          = graduate,   % 'undergraduate' or 'graduate'
    Type            = thesis,          % 'thesis'   or 'design'
    Period          = final,           % 'proposal' or 'final'
    BlindReview     = false,           % 'false'    or 'true'
    Language        = chinese,         % 'chinese'  or 'english'
    % Below only for 'graduate'
    GradLevel       = doctor,          % 'master' or 'doctor'
    Topic           = 主题,
    ColaboratorName = 合作导师,
    TitleEng        = {{this is the english title of my thesis}}
]{./config/zjuthesis}

\newcommand{\inputundergraduate}
{
    \ifthenelse{\equal{\Period}{final}}
    {
        % Final thesis
        % Final part
        \newcommand{\undergradcurrstage}{final}
        \newrefsection
        
        \coverstyle
        \inputpage{final/cover}

        \prevstyle
        \inputpage{final/previous}
        \inputpage{final/toc}

        \bodystyle
        \cleardoublepage
        \ifthenelse{\equal{\Type}{design}}
            {\part{毕业设计}}
            {\part{毕业论文}}
        
        \inputbody{final/content}

        \poststyle
        \inputpage{final/post}

        % Proposal part
        \renewcommand{\undergradcurrstage}{proposal}
        \newrefsection

        \coverstyle
        \cleardoublepage
        \ifthenelse{\equal{\Type}{design}}
            {\part{毕业设计开题报告}}
            {\part{毕业论文开题报告}}

        \inputpage{proposal/cover}
        \inputpage{proposal/previous}
        
        \bodystyle
        \inputbody{proposal/content}

        \poststyle
        \inputpage{proposal/post}
    }
    {
        % Thesis proposal
        \newcommand{\undergradcurrstage}{proposal}

        \coverstyle
        \inputpage{proposal/cover}
    
        % 'proposal' previous part uses 'empty' page style,
        % as shown in cs undergrad template.
        \inputpage{proposal/previous}
        
        \prevstyle
        \inputpage{proposal/toc}
    
        \bodystyle
        \inputbody{proposal/content}
        
        \poststyle
        \inputpage{proposal/post}
    }
}

\newcommand{\inputgraduate}
{
    \coverstyle
    \inputpage{cover}

    \prevstyle
    \inputpage{previous}
    \inputpage{toc}
    
    % Main contents
    \bodystyle
    \inputbody{content}

    % Post part
    \poststyle
    \inputbody{post}
}

\begin{document}

\ifthenelse{\equal{\Degree}{undergraduate}}
{
    \inputundergraduate{}
}
{
    \inputgraduate{}
}
\end{document}

**Comment by chao-song** [comment]
> this is the english title of my thesis

我希望编译成pdf后英文题目能够分两行显示

**Comment by TheNetAdmin** [comment]
你是要封面上分两行还是页眉分两行？

**Comment by chao-song** [comment]
> {{this is the english \ title of my thesis}}

我希望编译成pdf后英文题目能够分两行显示

**Comment by chao-song** [comment]
封面上

**Comment by chao-song** [comment]
> 你是要封面上分两行还是页眉分两行？
![image](https://user-images.githubusercontent.com/15336150/78418835-91a3c580-7672-11ea-8653-2e26c69bef3c.png)

**Comment by chao-song** [comment]
> > 你是要封面上分两行还是页眉分两行？
> > ![image](https://user-images.githubusercontent.com/15336150/78418835-91a3c580-7672-11ea-8653-2e26c69bef3c.png)

如图，标题直接超出了页面

**Comment by chao-song** [comment]
> > > 你是要封面上分两行还是页眉分两行？
> > > ![image](https://user-images.githubusercontent.com/15336150/78418835-91a3c580-7672-11ea-8653-2e26c69bef3c.png)
> 
> 如图，标题直接超出了页面，但是中文标题可以自动换行

![image](https://user-images.githubusercontent.com/15336150/78419819-ff082400-767b-11ea-970e-c107b0682358.png)
绕了很多方法，基本都会卡在这个错误上（cmd直接运行最新版本代码提供的latexmk）

**Comment by chao-song** [comment]
> > > > 你是要封面上分两行还是页眉分两行？
> > > > ![image](https://user-images.githubusercontent.com/15336150/78418835-91a3c580-7672-11ea-8653-2e26c69bef3c.png)
> > 
> > 
> > 如图，标题直接超出了页面，但是中文标题可以自动换行
> 
> ![image](https://user-images.githubusercontent.com/15336150/78419819-ff082400-767b-11ea-970e-c107b0682358.png)
> 绕了很多方法，基本都会卡在这个错误上（cmd直接运行最新版本代码提供的latexmk）

终极解决方案：直接修改pdf文件，放弃使用该页面。

**Comment by TheNetAdmin** [comment]
额这个情况下，我的建议是直接修改丰年对应的Tex📃，手动输入题目并分成两行

**Comment by chao-song** [comment]
> 额这个情况下，我的建议是直接修改封面对应的Tex 文件，手动输入题目并分成两行

谢谢，你应该是指修改page/中的covert_chn.tex吧？应该是可行的。不过作为小小的建议，希望以后的版本中，在zjuthesis.tex中输入英文标题时，能够支持标题换行。

**Comment by SonpKing** [comment]
同英文封面不能换行
