### ISSUE TITLE
\hbar无法正常显示

### ISSUE THREAD

**Issue by chao-song** [TheNetAdmin/zjuthesis#53]
用本模板编译出来的\hbar如下图：
![image](https://user-images.githubusercontent.com/15336150/78469618-8b3a4a00-7755-11ea-93bb-7b70aea156ab.png)
同一台电脑上，简单写一个文档编译结果如下：
![image](https://user-images.githubusercontent.com/15336150/78469702-2fbc8c00-7756-11ea-9ca7-6f623195f1be.png)

使用本模板时，具体是将zjuthesis.tex中设置为中文，专业为physics，其余用直接下载的模板中的命令，直接运行模板中的latexmk编译，即可发现这一问题

**Comment by muzimuzhi** [comment]
没细看原因。在载入 `ctexrep` 文档类之前，加一行
```tex
\PassOptionsToPackage{no-math}{fontspec}
```
能解决问题。具体源码位置在
https://github.com/TheNetAdmin/zjuthesis/blob/48d534f377c36b2b713e17b3211b95d2abe618dc/config/zjuthesis.cls#L43-L48

**Comment by TheNetAdmin** [comment]
我测试了一下，似乎是`Times New Roman`字体的问题

```
\documentclass[
    zihao=-4,
    UTF8,
    twoside]{ctexrep}

\setCJKmainfont{FangSong}
\setmainfont{Times New Roman}
\begin{document}
    $\hbar$
\end{document}
```
给出了如下结果

![2020-04-05_02-15](https://user-images.githubusercontent.com/18525442/78471112-78872d00-76e3-11ea-857d-d66f97d04f91.png)


但删除`\setmainfont{Times New Roman}`后给出如下结果

![2020-04-05_02-17](https://user-images.githubusercontent.com/18525442/78471120-8dfc5700-76e3-11ea-8a93-037363ab558b.png)

@muzimuzhi 提供的办法是可行的，我这就更新一下代码

**Comment by TheNetAdmin** [comment]
代码已经更新到master分支，最近会release新的版本

**Comment by muzimuzhi** [comment]
> 似乎是`Times New Roman`字体的问题

嗯。看了实现，
 - latex2e 里 `\hbar` 的原始定义是 `\DeclareRobustCommand\hbar{{\mathchar'26\mkern-9muh}}`，对应字体编码 OT1 下 Computer Modern Roman 的八进制第 26 个符号，参考 `texdoc encguide`, sec. A.1 
 - fontspec 不使用 `no-math` 选项、不加载 euler 或 lucida 相关字体包时，`\hhar` 被重定义为
`\renewcommand{\hbar}{{\mathchar"AF\mkern-9mu h}}`，相当于调用了当前正文字体的 U+00AF (Macron) 符号。

issue 报告的问题，是因为 Times New Roman 的 U+00AF 比较高，和 Latin Modern Math 的 h 不匹配。问题本质是字体搭配使用的事。

PS：xelatex 下更建议用 unicode-math 配置数学字体。
