### ISSUE TITLE
导航栏没有“目录”

### ISSUE THREAD

**Issue by qiaott** [TheNetAdmin/zjuthesis#55]
**遇到的问题**
突然发现，用acrobat打开pdf没有目录这个索引。
![image](https://user-images.githubusercontent.com/17823028/78870772-f9795800-7a46-11ea-9787-1f4d123deb87.png)
应该是 摘要，abstract，目录，图目录，表目录吧？
求教怎么样可以加上目录？
@TheNetAdmin

**Comment by TheNetAdmin** [comment]
代码已经更新到 master 分支，你可以下载尝试一下看还有没有问题

**Comment by qiaott** [comment]
可以了！！感谢！ @TheNetAdmin
