### ISSUE TITLE
如何去掉图目录，表目录中的章节之间的间距？

### ISSUE THREAD

**Issue by qiaott** [TheNetAdmin/zjuthesis#56]
**遇到的问题**
请简要描述你遇到的问题
![image](https://user-images.githubusercontent.com/17823028/78948272-05f1c500-7ac8-11ea-8b16-834de7276adc.png)
![image](https://user-images.githubusercontent.com/17823028/78948316-24f05700-7ac8-11ea-8888-87f3e79c9e09.png)

源代码中，图目录，表目录都会出现那个标红的间距。
不想要上图中标红的那个间距，如何可以在代码中去除那个间距？

**重现步骤**
原模版中，多复制几个图，表格，和章节就可。

感谢！

**Comment by TheNetAdmin** [comment]
已修复，在 `tocloft` 包的文档中有解决方案样例。

修复后的代码在master分支，可以下载尝试一下。

**Comment by muzimuzhi** [comment]
这个间距是在 `\chapter` 命令内部写入 `.lof/.lot` 文件的，所以属于章节样式的一部分。`ctex` 宏集提供了现成的选项
```tex
\ctexset{
  % 默认值都是是 `10pt`
  chapter/lofskip=0pt,
  chapter/lotskip=0pt
}
```

不清楚学校（不同院系）的样式规定中对这个 skip 的要求是否一致。

**Comment by TheNetAdmin** [comment]
这个解决方案更通用一点，我过后修改下

**Comment by muzimuzhi** [comment]
> 这个间距是在 `\chapter` 命令内部写入 `.lof/.lot` 文件的，所以属于章节样式的一部分。

调整后重新表述：这个间距，
 - 在样式上属于图表目录，应该由类似 `tocloft` 的宏包负责
 - 在实现上由 `\chapter` 的内部命令（标准文档类中是 `\@chapter`）写入 `.lof/.lot` 文件，
 - 所以，实践上由章节标题宏包（如 `ctex/ctexheading` 和 `titlesec`）提供配置接口（因为它们本就需要重定义章节标题命令）。
