### ISSUE TITLE
版本更新之后参考文献字体格式不对了

### ISSUE THREAD

**Issue by Y-Sindo** [TheNetAdmin/zjuthesis#57]
**遇到的问题**

大概从提交deeea8b99812f7ae164efd7470bbc6deee14aee0开始，编译出来的参考文献格式跟原来不一样了
**重现步骤**
使用当前最新版本ced45ebc188d8ce4ce0e851c0e1b3f7154b558a5编译
编译命令即`latexmk`

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/4464015/zjuthesis.log)

**截图**
这是新的格式
![Screen Shot 2020-04-11 at 12 13 26](https://user-images.githubusercontent.com/15143836/79035112-e1900880-7bed-11ea-9c0a-6d0342136a5b.png)

这是原格式
<img width="508" alt="Screen Shot 2020-04-11 at 12 14 30" src="https://user-images.githubusercontent.com/15143836/79035136-01bfc780-7bee-11ea-9d04-491ef6a23cdb.png">

**环境**
```
\documentclass[
    StudentName     = 姓名,
    StudentID       = 学号,
    AdvisorName     = 指导教师,
    Grade           = 2014,            % only the year, no '级'
    Major           = 计算机,
    Department      = 学院,
    Title           = 毕业论文/设计题目,
    SubmitDate      = 递交日期,
    MajorFormat     = cs,
    Degree          = graduate,   % 'undergraduate' or 'graduate'
    Type            = thesis,          % 'thesis'   or 'design'
    Period          = final,           % 'proposal' or 'final'
    BlindReview     = true,           % 'false'    or 'true'
    Language        = chinese,         % 'chinese'  or 'english'
    % Below only for 'graduate'
    GradLevel       = master,          % 'master' or 'doctor'
    Topic           = 研究方向,
    ColaboratorName = 合作导师,
    TitleEng        = {{Graduation Thesis Title}}
]{./config/zjuthesis}
```
|项目|内容|
|:-|:-|
| 操作系统 | [MacOS] |
| Tex套件 |TexLive |
| Tex套件版本 | 2019 |
| zjuthesis.log | [zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/4464015/zjuthesis.log) |

**其他信息**

**Comment by TheNetAdmin** [comment]
这个是为了修复 #46 提到的问题，如果你需要原来的那个样式，可以将参考文献的设置回退到那个版本，修改内容参考可 https://github.com/TheNetAdmin/zjuthesis/commit/ffd072c4879dde0fd6f4c5dd3cd29f2dd7ff7487

**Comment by TheNetAdmin** [comment]
我看你在使用计算机学院的专业版本，今年的计院模板有详细要求参考文献的字体与字号吗？

以及可否上传一份格式要求，然后我查下是否符合计院要求？

**Comment by Y-Sindo** [comment]
似乎只有一份word模板

**Comment by Y-Sindo** [comment]
> 我看你在使用计算机学院的专业版本，今年的计院模板有详细要求参考文献的字体与字号吗？
> 
> 以及可否上传一份格式要求，然后我查下是否符合计院要求？
似乎只有一份word模板

**Comment by TheNetAdmin** [comment]
#46 提到的要求来自校级模板规范，issue 内附有链接。

我觉得如果计院没有特别规定的话，可以问下学院的老师，用校级模板的规范是否符合要求。

或者有空的话可否查看一下word模板里参考文献的格式是什么

**Comment by TheNetAdmin** [comment]
> http://cspo.zju.edu.cn/2019/0904/c27174a1628255/page.htm

我现在不在浙大了，所以打不开校内链接……

**Comment by Y-Sindo** [comment]
> > http://cspo.zju.edu.cn/2019/0904/c27174a1628255/page.htm
> 
> 我现在不在浙大了，所以打不开校内链接……

https://1drv.ms/w/s!AuEpQ2-5p_3SpBRDznHMAxUtfw5x?e=ydV7ue

这是onedrive链接

感觉之前那个就可以了,我自己改回去吧~主要是不知道在哪里改.

**Comment by TheNetAdmin** [comment]
我查看了下word模板，里面的参考文献部分应该是宋体五号单倍行距，对应了代码的最新版本。如果回退到旧版本就变成了仿宋小四1.5倍行距。我个人建议你再和学院确认下比较好

**Comment by Y-Sindo** [comment]
> 我查看了下word模板，里面的参考文献部分应该是宋体五号单倍行距，对应了代码的最新版本。如果回退到旧版本就变成了仿宋1.5倍行距。我个人建议你再和学院确认下比较好

感谢耐心回答～我这边看到的是小四，1.25行距诶，另外上一批毕业的人有用1.5行距的。可能这个不是太重要的吧……
下面是对比。
![Screen Shot 2020-04-12 at 15 27 19](https://user-images.githubusercontent.com/15143836/79063094-2d1be280-7cd2-11ea-9db9-b207c185a577.png)

**Comment by TheNetAdmin** [comment]
可能是因为我用 Linux 下的 WPS 打开有问题吧……
