### ISSUE TITLE
英语引文符号字体的问题

### ISSUE THREAD

**Issue by Y-Sindo** [TheNetAdmin/zjuthesis#58]
**遇到的问题**
所有的英文引文符号都是小蝌蚪形状的，而不是Times New Roman的两直竖

**重现步骤**
`latexmk`编译.

原文:
这是英文引号测试""""""

**截图**
奇怪的引号:
![Screen Shot 2020-04-11 at 12 31 42](https://user-images.githubusercontent.com/15143836/79035369-6aa83f00-7bf0-11ea-9dfc-8071db645154.png)

正常的引号:

**环境**
```
\documentclass[
    StudentName     = 姓名,
    StudentID       = 学号,
    AdvisorName     = 指导教师,
    Grade           = 2014,            % only the year, no '级'
    Major           = 计算机,
    Department      = 学院,
    Title           = 毕业论文/设计题目,
    SubmitDate      = 递交日期,
    MajorFormat     = cs,
    Degree          = graduate,   % 'undergraduate' or 'graduate'
    Type            = thesis,          % 'thesis'   or 'design'
    Period          = final,           % 'proposal' or 'final'
    BlindReview     = true,           % 'false'    or 'true'
    Language        = chinese,         % 'chinese'  or 'english'
    % Below only for 'graduate'
    GradLevel       = master,          % 'master' or 'doctor'
    Topic           = 研究方向,
    ColaboratorName = 合作导师,
    TitleEng        = {{Graduation Thesis Title}}
]{./config/zjuthesis}
```
|项目|内容|
|:-|:-|
| 操作系统 | MacOS |
| Tex套件 | TexLive |
| Tex套件版本 | 2019 |
| zjuthesis.log |[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/4464030/zjuthesis.log)|

**其他信息**
我发现我的word和excel也会自动把直的引号替换成小蝌蚪引号……

**Comment by muzimuzhi** [comment]
> **遇到的问题**
> 所有的英文引文符号都是小蝌蚪形状的，而不是Times New Roman的两直竖

这是正确的行为。
 - 输出效果方面，充当名词所有格、强调和引用的引号都要是带方向的、「小蝌蚪形状的」。「两直竖」的引号，只在特殊情况如音标、代码中使用。
参考知乎讨论[英文引号中的直双引号「""」和弯双引号「“”」在使用上有什么区别？]。(https://www.zhihu.com/question/23008549)
 - 输入方式方面，参考文档 [lshort-zh-cn](http://mirrors.ctan.org/info/lshort/chinese/lshort-zh-cn.pdf) 第 2.3.5 节。

**Comment by Y-Sindo** [comment]
> > **遇到的问题**
> > 所有的英文引文符号都是小蝌蚪形状的，而不是Times New Roman的两直竖
> 
> 这是正确的行为。
> 
> * 输出效果方面，充当名词所有格、强调和引用的引号都要是带方向的、「小蝌蚪形状的」。「两直竖」的引号，只在特殊情况如音标、代码中使用。
>   参考知乎讨论[英文引号中的直双引号「""」和弯双引号「“”」在使用上有什么区别？]。(https://www.zhihu.com/question/23008549)
> * 输入方式方面，参考文档 [lshort-zh-cn](http://mirrors.ctan.org/info/lshort/chinese/lshort-zh-cn.pdf) 第 2.3.5 节。

非常感谢～～
