### ISSUE TITLE
如何统计字数

### ISSUE THREAD

**Issue by Lucas-Wye** [TheNetAdmin/zjuthesis#59]
生成的pdf统计字数比较麻烦，latex有没有相关的方法可以进行字数统计？

**Comment by TheNetAdmin** [comment]
LaTeX没有特别好的字数统计方式。一个可行的办法是将LaTeX转换成Word或者纯文本，然后统计字数，`pandoc`这个工具可以用来做转换，转换效果还可以。

**Comment by Lucas-Wye** [comment]
谢谢，我用`texcount` 进行统计了

**Comment by TheNetAdmin** [comment]
NICE

**Comment by TheNetAdmin** [comment]
我在 2ad353c 中添加了一个脚本，调用 `texcount` 来统计字数

**Comment by Asudy** [comment]
请问如果使用overleaf编辑，是不是无法使用 `word_count.sh` 脚本进行字数统计？如果可以，请问应该如何运行呀？如果不能，是否有其它方式可以方便地进行字数统计？

**Comment by Lucas-Wye** [comment]
> 请问如果使用overleaf编辑，是不是无法使用 `word_count.sh` 脚本进行字数统计？如果可以，请问应该如何运行呀？如果不能，是否有其它方式可以方便地进行字数统计？

overleaf应该是没法直接统计的，可以将整个项目下载到本地，然后再运行脚本进行统计。

**Comment by Asudy** [comment]
> > 请问如果使用overleaf编辑，是不是无法使用 `word_count.sh` 脚本进行字数统计？如果可以，请问应该如何运行呀？如果不能，是否有其它方式可以方便地进行字数统计？
> 
> overleaf应该是没法直接统计的，可以将整个项目下载到本地，然后再运行脚本进行统计。 @Asudy

好吧。谢谢！👍
