### ISSUE TITLE
Mac下好像没有仿宋字体

### ISSUE THREAD

**Issue by YaoZhongwei** [TheNetAdmin/zjuthesis#6]
请问报了以下2个错误要怎么处理？我把Fangsong换成mac下的STFangsong还是报了同样的错误
<img width="1265" alt="fangsong" src="https://user-images.githubusercontent.com/42103822/43716405-a0d3f13c-99b6-11e8-8524-e2958d7ada7a.png">

**Comment by TheNetAdmin** [comment]
- 理论上讲使用STFangsong是可以的，因为ctex宏包就用了这个字体，你尝试新建一个文档，内容如下，编译查看仿宋字体有没有生效
```latex
\documentclass{ctexart}

\begin{document}
    {\fangsong 仿宋字体}
    其他字体
\end{document}
```

- 如果确定是缺少FangSong字体的话，将Windows下的仿宋字体复制过来安装就行
- 如果仍然报错，尝试用命令行或者设置界面查看字体是否可以找到
- 还不行的话请把.log文件附上来，我帮你看下具体原因

**Comment by YaoZhongwei** [comment]
不知道是什么情况，fangsong字体我也已经下载了。
[missfont.log](https://github.com/TheNetAdmin/zjuthesis/files/2263187/missfont.log)
<img width="1453" alt="default" src="https://user-images.githubusercontent.com/42103822/43726917-1157651c-99d3-11e8-939e-4b961823326e.png">
<img width="597" alt="font" src="https://user-images.githubusercontent.com/42103822/43726971-42b60b9a-99d3-11e8-9fa7-a86848c93011.png">

**Comment by TheNetAdmin** [comment]
还有问题吗？没有问题就关掉这个issue了。

**Comment by TheNetAdmin** [comment]
关闭issue，如果问题没解决，可以评论并重开issue。
