### ISSUE TITLE
插入PDF文件显示空白页面

### ISSUE THREAD

**Issue by MrNobodyCali** [TheNetAdmin/zjuthesis#60]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
在插入外文翻译原文的PDF文件时，输出的PDF中都是空白页面。

**重现步骤**
正常步骤，把PDF文件放在figure/文件夹下，也修改了original.tex里的PDF文件名

**环境**

|项目|内容|
|:-|:-|
| 操作系统 | Windows |
| Tex套件 | Texlive |
| Tex套件版本 |  2020 |

**其他信息**
我想插入的PDF文件因为年代久远，其实是扫描文件，在尺寸上比毕设文档略宽，但我也尝试过fitpaper=true命令，也调小过scale命令，但都是空白输出，不知道这具体是什么原因呢？
[segmental.pdf](https://github.com/TheNetAdmin/zjuthesis/files/4626084/segmental.pdf)

**Comment by TheNetAdmin** [comment]
插入后编译得到的pdf文件以及log文件附一份我看下

**Comment by TheNetAdmin** [comment]
还有个可能可行的办法：

用pdf阅读器打开你要插入的pdf文件(segmental.pdf)，然后用“打印成pdf”功能输出一个副本，再尝试插入这个新输出的副本，看是否有效

**Comment by MrNobodyCali** [comment]
嗯嗯很感谢！我通过windows自带的打印成PDF功能，输出的新文件可以顺利插入！

**Comment by TheNetAdmin** [comment]
NICE
