### ISSUE TITLE
征集工具使用教程

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#61]
现在的 zjuthesis 使用说明里提供了 Visual Studio Code 的使用说明，但有不少用户在使用其他工具，如 Sublime，TeXStudio 等。

如果同学们有空的话，能否在这里写一下你们如何使用某工具编写 zjuthesis 论文？

我会把这里的工具使用心得整理并写入 zjuthesis 使用说明，以方便更多同学查阅。

**Comment by bobbybi7801** [comment]
我是一个新手，2周之前并不知道有LaTex存在，偶然发现了zixuan学霸这个开源模板，因为我第一次在线安装XeLaTex失败，我先从在线工具overleaf开始入手，README中overleaf指南足够让一个新手建立自己的项目（通过导入zjuthesis-overleaf-v6.0.1），用overleaf的好处是不需要安装LaTex，并且集成版本管理工具，可以管理自己的版本。缺点是编译速度慢。后来根据下面blog的信息，先下载离线ISO，成功安装XeLeTex 2020 （2019的iso找不到了），编辑器我用的是TexStudio. zjuthesis-v6.0.1可以直接在TexStudio中编译，前提是配置好工具（以下blog有介绍）。

https://blog.csdn.net/qq_33749437/article/details/105883479?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522159900493419724843312098%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=159900493419724843312098&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_ecpm_v3~pc_rank_v2-4-105883479.first_rank_ecpm_v3_pc_rank_v2&utm_term=TeXLive2020&spm=1018.2118.3001.4187

**Comment by HaroldZ** [comment]
说一下在Mac OS下用Sublime Text编译zjuthesis的方法：

Requirements: 安装MacTex [https://www.tug.org/mactex/](url) 和 Sublime Text

1.在Sublime Text中点击 Tools→ Commond Palette或快捷键command + shift + P进入命令面板，输入PCI，选择Package Control: Install Package，输入LatexTools，选择后自动安装

2.打开Preference→Package settings→LatexTools→Settings-User，在打开的界面中找到 builder-settings，在osx的括号中写入以下代码，如图所示：
`"script_commands":[
  "latexmk -pv"
  ]`
<img width="515" alt="image" src="https://user-images.githubusercontent.com/14771013/98932754-b6222300-251a-11eb-95c0-769e5410ad81.png">

3.用Sublime Text打开zjuthesis.tex, 按快捷键command + B进行编译即可。

Tips：在body文件夹下的每个.tex文件开头加上`%!TEX root = ../../zjuthesis.tex` (zjuthesis.tex文件的路径)，这样可以从任意一个.tex文件编译整个工程，而不用每次打开zjuthesis.tex进行编译。

**Comment by alone-tree** [comment]
我通常喜欢用TeXstudio来编辑latex文件，但在使用过程中发现这个模板有一些bug，用TeXstudio无法生成参考文献，用XeLaTeX和latexmt都不行，只能生成正文。但用VScode就可以正常使用。

工具版本：TeXstudio3.0.1 + TeXLive2020

**Comment by TheNetAdmin** [comment]
模板没有bug，每个commit都是编译成功的，TeXStudio使用方法你自己上网去搜

**Comment by TheNetAdmin** [comment]
Issue 已经 pin 到主页，此 Issue 关闭

如有新的教程，直接在下方回复即可

**Comment by TheNetAdmin** [comment]
另一个 TeX Studio 相关的使用教程 https://github.com/TheNetAdmin/zjuthesis/discussions/98#discussioncomment-256735
