### ISSUE TITLE
关于附录标题、公式设置

### ISSUE THREAD

**Issue by MrNobodyCali** [TheNetAdmin/zjuthesis#62]
**遇到的问题**
我在附录中要划分多个段落，我在\sectionnonum{附录}后，均按照\subsection{}及以下等级划分，但是会出现0.x.x的问题，这是因为“附录”这个section是不编号的缘故吗？另外，我尝试使用\appendix指令，也无法得到后续标题前带A.x.x这样的格式，请问有什么解决办法吗？当然，公式也是同样的问题。

**Comment by TheNetAdmin** [comment]
我刚更新了附录实现，请尝试使用master分支上最新版的代码。

**Comment by TheNetAdmin** [comment]
最好不要用\appendix，这个宏会将其后所有的section设为附录格式，从而影响后面的正文部分。

**Comment by MrNobodyCali** [comment]
啊哈！超级感谢您的帮助，我还想提一些我在使用中遇到的问题和解决办法：
1. 建议在新增的`\newcommand{\appendixsubsecmajornumbering}`命令下，再加一下`\ctexset{subsubsection/number = \Alph{subsection}.\arabic{subsubsection}}`，否则即便是`\subsection`能够自适应，`\subsubsection`依然保持和参考文献一样的`section.x.x`。

2. 由于第一部分没有`chapter`，在使用定义/定理的时候，会造成`0.x.x`的同样的问题。我的解决办法是在`zjuthesis.tex`下新增命令（主要是第二句），似乎这里默认`chapter`为最高等级：
> \newtheorem{Definition}{\hspace{0em}定义}[section]
> \renewcommand{\theDefinition}{\arabic{section}.\arabic{Definition}}

3. 在公式自动编号上，似乎的确是按照`/section.x`来定义的，但是这个具体的`x`会随着新的`subsection`重新归为`1`，于是在不同的`subsection`下，会出现重复的公式编号，比如`\section-1`。我目前只能手动在新的`subsection`前设置`\setcounter{equation}{x}`，`x`是这个`section`内已有的需要编号的公式数目。

**Comment by TheNetAdmin** [comment]
感谢你提供的这些建议，我已经将 “建议1” 插入代码中。

过几天有空我会将剩余的建议插入代码。

**Comment by TheNetAdmin** [comment]
前段时间一直没空处理后续的建议2和3，今天尝试了一下：

- 建议 2 提到了定义 (Definition) 和定理 (Theorem) 环境的编号问题，当前 zjuthesis 并没有使用这两个环境，所以暂时不插入相关代码。不过如果有需要的同学发现了这个问题，有一个通用的解决方法，适用于大多数自定义环境的编号：
  - 在 `config/format/general/numbering.tex` 下添加自定义环境的编号规则，可以参考现有的代码来添加：
     https://github.com/TheNetAdmin/zjuthesis/blob/8d25856483ae764700c987b56ab543d7b801145e/config/format/general/numbering.tex#L1-L71
   - 注意当前模板不同部分使用了不同编号规则，这些规则都定义在不同的 `\***majornumbering` 命令中（如上代码所示），为了确保兼容性，请务必在每个 `\***majornumbering`  命令中都添加相应的编号规则，可参考各个命令已有的实现。

- 建议 3 提到了公式编号随着 `\subsection` 清零，我在最新模板中尚未复现这个问题，如果有同学观察到同样问题的话，可否附一份运行样例，然后我来尝试修复。

最后感谢此 issue 的提出者提供的各项建议！
