### ISSUE TITLE
目录中两个chapter间隔较大

### ISSUE THREAD

**Issue by ZJUDestiny** [TheNetAdmin/zjuthesis#63]
请务必按照这个模板报告问题，否则我很难帮助你找到问题。

**遇到的问题**
在生成的目录中两个chapter间距较大，应该不是仅仅有行距

**重现步骤**
正常编译运行

请附上修改过的文件/工程

**截图**

![image](https://user-images.githubusercontent.com/34738171/82306675-ef595a80-99f1-11ea-81f4-a874fc0a1090.png)
上面是两个chapter的间距，下面是正常的行间距，因为我只有四个chapter罗列，这样看起来很不和谐

**环境**

|项目|内容|
|:-|:-|
| 操作系统 | [Windows] |
| Tex套件 | [Texlive] |
| Tex套件版本 | [2019] |
| zjuthesis.log | [使用命令行编译一遍，然后将 out/zjuthesis.log 附在此issue] |

**其他信息**
其他你认为有帮助的信息

**Comment by TheNetAdmin** [comment]
可以参考这里的实现

https://github.com/TheNetAdmin/zjuthesis/blob/0830e1776a56bd2754eecac3178a7acb8dd35d68/config/format/general/layout.tex#L148-L155

这里我给研究生博士生模板的目录设置了“章节目录项上方空白为0”，可以将`\setlength{\cftbeforechapskip}  {0em}`复制到本科生模板设置项里。

**Comment by TheNetAdmin** [comment]
已经更新代码，使用master分支最新的commit应该可以解决这个问题。

**Comment by ZJUDestiny** [comment]
请问一下，本科模板中，目录的part与下方的行间距可以调成part字号的1.5倍行间距吗？或者直接用vspace调。但我在整个工程中没有找到调part在目录中格式的地方
![image](https://user-images.githubusercontent.com/34738171/82411538-87178100-9aa4-11ea-909d-f7b3e4023966.png)

**Comment by TheNetAdmin** [comment]
用命令 `texdoc tocloft` 查一下文档就知道怎么设置了，`zjuthesis` 模板用的就是 `tocloft` 宏包来设定目录的。

你这个可能要设置`\cftbeforechapskip`或者`\cftbeforesecskip`（参见`tocloft`文档`2.3 Typesetting the entries`），但设置这两个都是牵一发动全身，要慎重使用。

我觉得本科生论文没有必要太过纠结目录的间隔问题，只要不产生歧义即可。可以多花些时间编写和修订论文正文部分。
