### ISSUE TITLE
我毕设题目有点长，封面题目那里会换行，有点不太好看，求大佬帮帮我

### ISSUE THREAD

**Issue by hanxane** [TheNetAdmin/zjuthesis#64]
rt，Latex用得不好，自己试了下不太会改，求大佬帮帮忙！
![TIM截图20200523222525](https://user-images.githubusercontent.com/62021940/82733124-56ee0d80-9d44-11ea-8b29-519af1e8814d.png)

**Comment by TheNetAdmin** [comment]
我不懂你想要什么效果

**Comment by TheNetAdmin** [comment]
这个题目栏是一个`tabularx`表格，如果你不想让题目换行，那就加宽表格就行了

https://github.com/TheNetAdmin/zjuthesis/blob/1e67352ec04715afee34b9bc0ce4d665cff73338/page/undergraduate/final/cover.tex#L38

把这里的`.7\textwidth`改成`1.0\textwidth`，这是极限长度，也可以修改为其他值

**Comment by hanxane** [comment]
感谢大佬！能改成想要的效果啦
