### ISSUE TITLE
求大佬再帮帮忙，双页的空页带页眉页脚和页码

### ISSUE THREAD

**Issue by hanxane** [TheNetAdmin/zjuthesis#65]
![TIM截图20200526114521](https://user-images.githubusercontent.com/62021940/82858480-97b57480-9f46-11ea-89cf-f79ef826ac17.png)
开题报告部分是正常的，但是论文正文的双页的空页会带页眉页脚和页码。我应该是没修改过代码。求大佬再帮帮忙看一看！

**Comment by TheNetAdmin** [comment]
开题报告部分的空白双数页也是带页眉页脚的

![image](https://user-images.githubusercontent.com/18525442/82859061-89297780-9eca-11ea-8bde-6c612173a36d.png)

**Comment by TheNetAdmin** [comment]
这里用个例子说明如何让空白的双页不带页眉页脚：

1. 比如你想让最终论文的摘要部分前面的双页空白页不带页眉页脚
2. 先修改这里的代码
https://github.com/TheNetAdmin/zjuthesis/blob/1e67352ec04715afee34b9bc0ce4d665cff73338/config/commands.tex#L2-L16
将第12行的`\thispagestyle{#1} `注释掉，像这样：
```TeX
\makeatletter
\newcommand{\cleardoublestylepage}[1]
{
    \clearpage
    \if@twoside
        \ifodd\c@page
            % do nothing
        \else
            \thispagestyle{#1} ~
            \newpage
            % \thispagestyle{#1}
        \fi
    \fi
}
\makeatother
```

3. 然后修改摘要部分的页面，将这里的代码
https://github.com/TheNetAdmin/zjuthesis/blob/1e67352ec04715afee34b9bc0ce4d665cff73338/body/undergraduate/final/abstract.tex#L1-L4
第一行修改为`\cleardoublestylepage{empty}`，修改后变成：
```TeX
\cleardoublestylepage{empty}
\begin{center}
    \bfseries \zihao{3} 摘要
\end{center}
```
4.重新编译，得到摘要前不带页眉页脚的双页空白页
![image](https://user-images.githubusercontent.com/18525442/82859511-cb9f8400-9ecb-11ea-987d-01e45f36dec1.png)

**Comment by hanxane** [comment]
谢谢大佬解答！我现在正文前也会有空白页占页码，正文是从第三页开始的，请问这个也是需要同样的修改方法吗？

![TIM截图20200526121016](https://user-images.githubusercontent.com/62021940/82859831-62128a80-9f4a-11ea-9ffd-c78a3a8c2527.png)

**Comment by TheNetAdmin** [comment]
对

**Comment by TheNetAdmin** [comment]
似乎问题已经解决，如有问题可以重开此issue
