### ISSUE TITLE
如何设置目录部分加粗等

### ISSUE THREAD

**Issue by Lucas-Wye** [TheNetAdmin/zjuthesis#67]
**遇到的问题**
目前学院要求目录满足如下文件中的条件，其中需要部分字体加粗，并且目录中的第二部分只要一级标题，当前模版中要如何针对部分目录标题进行字体修改？
http://www.isee.zju.edu.cn/_upload/article/files/df/ab/b35d3ab94f1287062a4754501648/f33811cc-5cb6-456e-85d6-f755bc75d42b.docx

**Comment by TheNetAdmin** [comment]
你提到的两个问题分别有如下解决方案：

### 1. 加粗字体

我看到你发来的要求中需要加粗目录项，目录页码以及两者之间的省略号，这里以加粗`chapter`级别目录为例，将这里的代码

https://github.com/TheNetAdmin/zjuthesis/blob/1e67352ec04715afee34b9bc0ce4d665cff73338/config/format/general/layout.tex#L124-L126

修改为

```TeX
\renewcommand{\cftchapfont}         {\zihao{-4}\bfseries}
\renewcommand{\cftchapleader}       {\bfseries\cftdotfill{\cftchapdotsep}}
\renewcommand{\cftchappagefont}     {\bfseries}
```

然后使用`latexmk`重新编译，得到效果如图 (一 文献综述 已经加粗，包含省略号和页码)

![image](https://user-images.githubusercontent.com/18525442/83936718-1a2a0980-a77b-11ea-8a3e-aa3353cc25ff.png)

### 2. 简化第二部分目录

这个要求比较难以实现，如果不想大量修改正文代码，有一个简单解决方案

使用 `latexmk` 编译一遍后，在 `out` 目录下寻找 `zjuthesis.toc` 并打开，删除不需要的目录项并保存

然后回到项目代码根目录，使用命令 `xelatex -pdf -output-directory=out zjuthesis.tex` **编译一次**，即可在 `out/zjuthesis.pdf` 中得到简化版目录

**注意**：第二次编译使用了 `xelatex` 命令，而不是 `latexmk` 命令；第二次编译只可执行一次，如执行多次，可能会将目录更新为原始样式，即包含了规范要求隐藏的目录项。

所以简化第二部分目录最好在正文完稿后，准备提交之前，最后一次编译时进行

**Comment by Lucas-Wye** [comment]
That is very kind of you! Thank you very much!!!
