### ISSUE TITLE
参考文献部分只有第一页有页码

### ISSUE THREAD

**Issue by xdbc** [TheNetAdmin/zjuthesis#69]
自动生成的参考文献，只有第一页有页码和页眉，后面的页面没有页码、页眉

第一页有页眉
![image](https://user-images.githubusercontent.com/14344887/84863333-5dec0f80-b0a7-11ea-997f-5bd0f0bda6d1.png)

第一页的页码，第二页没有页眉
![image](https://user-images.githubusercontent.com/14344887/84863282-4ca30300-b0a7-11ea-9b43-3690fb6f6a5f.png)

后面没有页码，也没有页眉了
![image](https://user-images.githubusercontent.com/14344887/84863462-8bd15400-b0a7-11ea-9a87-ed2bb65c794d.png)

**Comment by TheNetAdmin** [comment]
你用的什么模板设置？填一下issue模板里的表格

**Comment by TheNetAdmin** [comment]
https://github.com/TheNetAdmin/zjuthesis/blob/039d6f98e2aa3160722ea27b318028c0b95d7c68/body/graduate/post.tex#L2

把这一行移到正文部分
