### ISSUE TITLE
提示ISSUE模板缺失内容

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#70]
## 可改进的内容

新提出的issue大多没有遵循issue模板，导致信息不够全面，需要后续沟通获取信息才能解决issue。

issue模板的意义在于让新的issue在最开始就提供尽可能详细的信息，确保代码作者可以第一时间回复并解决问题。但不遵循issue模板会降低沟通效率。

所以后续会添加一个GitHub Action或Bot，检查每个新issue的内容是否遵循了相关issue模板，并提示缺失的模板内容。

**Comment by muzimuzhi** [comment]
可能的例外情况：有经验的用户发的简洁的问题报告。

**Comment by TheNetAdmin** [comment]
对于可能出现的“有经验用户发送了简洁issue”的情况（@muzimuzhi 对此issue的回复，我收到了邮件提醒但没有在网页上看到这条回复）

我考虑是否可以将提醒范围局限在“第一次在本repo发送issue的用户”。而且提醒机制只是GitHub bot自动添加的一个回复，并不直接关闭问题，这样issue提出者也可以忽略这个提醒。

**Comment by muzimuzhi** [comment]
> 对于可能出现的“有经验用户发送了简洁issue”的情况（@muzimuzhi 对此issue的回复，我收到了邮件提醒但没有在网页上看到这条回复）

后来我注意到已经有 Enhancement issue template，感觉它可以作为兜底选择，就删除了之前的评论。抱歉带来不便。

> 而且提醒机制只是GitHub bot自动添加的一个回复，并不直接关闭问题，这样issue提出者也可以忽略这个提醒。

很棒

**Comment by TheNetAdmin** [comment]
最近的 issue 都比较遵守 issue 模板，这项功能暂时推后。
