### ISSUE TITLE
[Enhancement] 标签 help wanted 的使用

### ISSUE THREAD

**Issue by muzimuzhi** [TheNetAdmin/zjuthesis#71]
## 可改进的内容

现状描述

 - help wanted 标签是 repo issue 自带的几个标签之一，github 给的简短介绍是 extra attention is needed，[长介绍](https://help.github.com/en/github/managing-your-work-on-github/about-labels)是 Indicates that a maintainer wants help on an issue or pull request
 - 实际使用时 help wanted 可以有两种含义，1）维护者向整个社区寻求帮助，2）提问者向活跃者（通常至少包含维护者）寻求帮助。使用第一种含义的项目例如 [texstudio-org/texstudio](https://github.com/texstudio-org/texstudio/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)，当前项目使用的是第二种。前述 github 提供的长介绍，描述的是第一种。
 - github 目前的推送机制，watch 了项目的人，项目的每一个新 issue 都会出现在他的 notifications 中。我 watch 了当前项目后，发现自己会在 github 主页看到添加了 help wanted 标签的当前项目的所有新 issue。
 - 出现在 github 主页，这是更强的一种提醒。每一个 i-need-help 类型的 issue 都这样提醒，我觉得提醒太强了。我没测试过，是否「通过 issue template 自动添加标签的 issue，都会出现在项目关注者的 github 主页」，也可能 help wanted 标签是一个特殊的标签，或者这种行为是可配置的。

个人建议

 - i-need-help 类型的新 issue，不自动添加标签（或者添加其他标签，以不出现在项目关注者的 github 主页、只出现在 notifications 为目的）；经过交流和尝试，觉得有需要提高关注程度的，维护者手动添加 help wanted 或类似标签。其他两类 issue template 的行为不变。

**Comment by TheNetAdmin** [comment]
有道理，我先测试一下是否可以修改特定标签的提醒方式，如果不能就直接去掉`help wanted`标签

**Comment by TheNetAdmin** [comment]
对我来讲，某些issue停留在GitHub主页也是比较头疼的问题，我没有找到定制标签notification行为的功能。我刚尝试用一个自定义的标签 `I-need-help` 新建了一个issue，你这边还有在GitHub主页显示吗？

如果还在主页显示的话我就去掉自动label功能

**Comment by muzimuzhi** [comment]
> 你这边还有在GitHub主页显示吗？

不显示

**Comment by TheNetAdmin** [comment]
OK，这个问题先这样解决，之后还有什么问题可以继续讨论
