### ISSUE TITLE
附录的目录项跳转有误

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#74]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [x] Linux/Docker
- [x] Overleaf

**TeX套件**

- [x] TeXLive 2019 或更新的版本
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex
- [x] Overleaf

**zjuthesis 版本**

版本号：6.0.0

## 遇到的问题

编译生成的本科生模板 pdf 中，目录项“附录”的跳转位置是正确的， 但目录项“A 一个附录”跳转错误，跳到了“2.1 节标题”

**截图**

![image](https://user-images.githubusercontent.com/18525442/86874043-7478fb80-c094-11ea-818a-90946e543c08.png)

**Comment by muzimuzhi** [comment]
### 问题简化及分析
hyperref 使用当前计数器的值记录超链接跳转位置。附录节因为没有递增 `section`，小节「附录 A」的实际编号也是 2.1。这样一个文件里有了两个名为 `subsection.2.1` 的跳转位置，因为实现原因，第二个被丢弃，于是点击「附录 A」的 PDF 书签，跳转到了第一处 2.1 节的位置。

简化后的例子：
```tex
\documentclass{article}
\usepackage{hyperref}

\makeatletter
% 输出当前 label 信息，是一个 5-tuple，其中第五个总是空的
% 其中，\@currentHref 对应了超链接目标名
% （详见 nameref.sty 里对 \label 的重定义）
\def\showLabelInfo{%
  \@currentlabel,\thepage,\@currentlabelname,\@currentHref}
\makeatother

\begin{document}
\section{title}
\subsection{title}\showLabelInfo
\subsection{title}\showLabelInfo

\phantomsection
\section*{title}
\addcontentsline{toc}{section}{title}%
\setcounter{subsection}{0}
\renewcommand{\thesubsection}{\Roman{subsection}}

\subsection{title}\showLabelInfo
\subsection{title}\showLabelInfo

content\newpage
content
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/86890768-67114f00-c130-11ea-8f30-6d96082077b2.png)
从输出可以看到，超链接目标名（pdf named destination）`\@currentHref` 重复了。

### 可能的解决方案
如果附录节总是出现在 section 末尾，且附录节中一定不使用 section 计数器的当前值，那么在 `\sectionnonum` 里递增 `section` 计数器即可
```diff
diff --git a/config/commands.tex b/config/commands.tex
index 6f3f063..c6b1fab 100644
--- a/config/commands.tex
+++ b/config/commands.tex
@@ -40,6 +40,7 @@
         \begin{center}
             \bfseries \zihao{3} #1
         \end{center}
+        \stepcounter{section}
         \setcounter{subsection}{0}
     }
 }
```

**Comment by TheNetAdmin** [comment]
感谢提供帮助！

**Comment by TheNetAdmin** [comment]
最终是在 `\appendixsubsecmajornumbering` 和 `\appendixsecmajornumbering` 里各自增加了 `\stepcounter`，因为 `\secnonum` 和 `\chapnonum`  在前置章节也有使用，直接修改会影响正文章节。
