### ISSUE TITLE
[BUG] 章节格式和往年样例不同

### ISSUE THREAD

**Issue by MARMOTatZJU** [TheNetAdmin/zjuthesis#76]
## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [X] Overleaf

**TeX套件**

- [ ] TeXLive 2019 或更新的版本
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex
- [X] Overleaf

**zjuthesis 版本**

版本号：6.0.2

**编译日志**

## 遇到的问题

ZJU-thesis的代码未经修改直接编译得到的章节的格式和我从师兄处得到的往年样例不同。具体区别见下面的截图部分。

具体区别是，ZJU-thesis采用阿拉伯数字对章节编号，但是往年样例使用中文（如“第一章”）编号。

**截图**

样例硕士论文
![image](https://user-images.githubusercontent.com/32362315/93300055-af33a880-f828-11ea-88c9-c16bed76c706.png)

ZJU-thesis编译得到的结果
![image](https://user-images.githubusercontent.com/32362315/93300121-d25e5800-f828-11ea-84a5-d6d90b7a7fde.png)

**其他信息**

**Comment by MARMOTatZJU** [comment]
[UPDATE]
查看了[grs上的编写规则](http://grs.zju.edu.cn/redir.php?catalog_id=10038&object_id=12877)后，发现latex模版中的编号和grs的规则是相合的。
![image](https://user-images.githubusercontent.com/32362315/93302598-d55b4780-f82c-11ea-92c0-0eb4553eef45.png)

**Comment by TheNetAdmin** [comment]
这个中文编号的样例看上去似乎是早先版本的，我后来更新过一些具体的样式设计，并且针对计算机学院的要求做了一些修正。如果你需要用中文编号的话，可以参考计算机专业的硕士模板

https://github.com/TheNetAdmin/zjuthesis/blob/69b02fd04f0a9217b1b19edc21c204b49412a587/config/format/major/cs/heading.tex#L10-L18

**Comment by TheNetAdmin** [comment]
计算机专业的硕士模板样例pdf文件可以在resease页面内下载到，可以看下是否符合要求

**Comment by TheNetAdmin** [comment]
暂时关闭，如有问题请重开issue
