### ISSUE TITLE
xelatex miktex 编译出的文献引用标识错误

### ISSUE THREAD

**Issue by zkmbdbbdd** [TheNetAdmin/zjuthesis#77]
## 系统信息

**操作系统**

- [10] Windows

**TeX套件**

- [最新] MikTex

**zjuthesis 版本**

版本号：6.0.2

**编译日志**
Rc files read:
  .latexmkrc
Latexmk: This is Latexmk, John Collins, 17 Apr. 2020, version: 4.69a.
Latexmk: making output directory 'out'
Latexmk: applying rule 'xelatex'...
Rule 'xelatex': The following rules & subrules became out-of-date:
      'xelatex'
------------
Run number 1 of rule 'xelatex'
------------
------------
Running 'xelatex -outdir=out -no-pdf -recorder -output-directory="out"  "zjuthesis.tex"'
------------

Sorry, but xelatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\zkm\AppData\Local\MiKTeX\miktex\log\xelatex.log
Latexmk: fls file doesn't appear to have been made.
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  xelatex: Command for 'xelatex' gave return code 1
      Refer to 'out/zjuthesis.log' for details
----------------------
This message may duplicate earlier message.
Latexmk: Failure in processing file 'zjuthesis.tex':
   (Pdf)LaTeX didn't generate the expected log file 'out/zjuthesis.log'
----------------------
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.

## 遇到的问题
编译后引用显示错误

**截图**
![image](https://user-images.githubusercontent.com/42455038/94403233-b602d980-019f-11eb-80a1-daec2e7a18d8.png)

**其他信息**
一般用 xelatax 命令编译主文件 zjuthesis.tex，可以编译成功，但出来的 pdf 引用标识有问题，latexmk 无法运行成功

**Comment by zkmbdbbdd** [comment]
![image](https://user-images.githubusercontent.com/42455038/94403852-9c15c680-01a0-11eb-96bc-11378a3e58d2.png)

**Comment by TheNetAdmin** [comment]
清除所有中间文件再用latexmk编译呢？

我从没用过miktex，也可以试试卸载miktex改用texlive

**Comment by zkmbdbbdd** [comment]
> 清除所有中间文件再用latexmk编译呢？
> 
> 我从没用过miktex，也可以试试卸载miktex改用texlive

清除也没用，解压出来直接 latexmk 结果就这样。
好的我试试。texlive对硬盘太不友好了，无比臃肿，就换的miktex哈哈

**Comment by zkmbdbbdd** [comment]
> > 清除所有中间文件再用latexmk编译呢？
> > 我从没用过miktex，也可以试试卸载miktex改用texlive
> 
> 清除也没用，解压出来直接 latexmk 结果就这样。
> 好的我试试。texlive对硬盘太不友好了，无比臃肿，就换的miktex哈哈

使用texlive 的 latexmk出来是正确的，对比后明白了，这模板如果用 miktex 的 xelatex 直接编译，虽然能够编译成功，但得到的 PDF 文献引用会错误显示

**Comment by muzimuzhi** [comment]
@zkmbdbbdd 
> 好的我试试。texlive对硬盘太不友好了，无比臃肿，就换的miktex哈哈

texlive 可以不完整安装
