### ISSUE TITLE
[TIPs] Miktex无法 latexmk 成功解决办法

### ISSUE THREAD

**Issue by zkmbdbbdd** [TheNetAdmin/zjuthesis#78]
## 系统信息

**操作系统**

- [10] Windows

**TeX套件**

- [4.0.1] MikTex

**zjuthesis 版本**

版本号：6.0.2

**编译日志**

## 遇到的问题
如果直接用 latexmk 会报错

**截图**
![image](https://user-images.githubusercontent.com/42455038/95641103-f8e37c00-0ad2-11eb-9ddf-61ac328125cd.png)

**解决办法**
用记事本打开zjuthesis里的.latexmkrc文件，把第三行改为 $xelatex="xelatex";，也就是去掉 -outdir 这条参数

**Comment by TheNetAdmin** [comment]
Nice job!

**Comment by TheNetAdmin** [comment]
已经 pin 到 issue 主页
