### ISSUE TITLE
[BUG]博士模版中文封面标题字体不一致

### ISSUE THREAD

**Issue by dawnos** [TheNetAdmin/zjuthesis#79]
## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2019 或更新的版本
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex
- [ ] Overleaf

**zjuthesis 版本**

版本号：6.0.2

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5416167/zjuthesis.log)

## 遇到的问题

博士模版中文封面标题字体不一致：标题的第一个字的字体是正确的，后面的字的字体不正确。
模版直接从github下载，zip格式。只修改了zjuthesis.tex两个地方：
- Degree          = graduate
- GradLevel       = doctor

**截图**

<img width="471" alt="tmp" src="https://user-images.githubusercontent.com/2622870/96726014-23430c80-13e4-11eb-98f9-28410b31f2a7.png">

**其他信息**

暂无

**Comment by TheNetAdmin** [comment]
似乎是有这个bug，在GitHub release页面下载的pdf里也有这个问题，这些pdf是在Linux环境下编译的。

但在Windows下编译没有见到这个问题，我对比了你提供的log和我在Windows下编译时的log，发现你的log中多了这个部分（1374行）：

```
Package fontspec Warning: Font "FandolFang-Regular" does not contain requested
(fontspec)                Script "CJK".


Package fontspec Info: Font family 'FandolFang-Regular(0)' created for font
(fontspec)             'FandolFang-Regular' with options
(fontspec)             [Script={CJK},Extension={.otf},AutoFakeBold={4}].
(fontspec)              
(fontspec)              This font family consists of the following NFSS
(fontspec)             series/shapes:
(fontspec)              
(fontspec)             - 'normal' (m/n) with NFSS spec.:
(fontspec)             <->"[FandolFang-Regular.otf]/OT:language=dflt;"
(fontspec)             - 'small caps'  (m/sc) with NFSS spec.: 
(fontspec)             - 'bold' (b/n) with NFSS spec.:
(fontspec)             <->"[FandolFang-Regular.otf]/OT:language=dflt;embolden=4
;"
(fontspec)             - 'bold small caps'  (b/sc) with NFSS spec.: 
```

不知为何这里调用了Fandol系列的宋体字体，并且将宋体应用到了“业论文/设计题目”这几个字上，按理说mac下的宋体应该调用 `Songti SC`才对，而且也不应该将宋体应用到题目上：
https://github.com/TheNetAdmin/zjuthesis/blob/62f3e08f06791f3b0d3f100271e5f410fbea6d8a/config/format/general/fonts.tex#L11-L16

可否将你系统里的字体列举一下贴到这里呢？

**Comment by muzimuzhi** [comment]
@dawnos 如果你在用 macOS 10.15 及以上版本，那么和 https://github.com/CTeX-org/ctex-kit/issues/455 是同一个问题。更新 ctex 到 v2.5 及以上版本（log 里显示，你目前为 v2.4.16），或使用 `fontset=macnew` 文档类选项，均能修复问题。

**Comment by TheNetAdmin** [comment]
我将 TexLive 从 2019 升级到 2020 后，Linux 下编译得到的 pdf 也不再出现类似的字体问题（对比 v6.0.3 与 v6.0.2 的 `zjuthesis-graduate-doctor-general-thesis-final.pdf
`），可以尝试更新到 TexLive 2020。

**Comment by dawnos** [comment]
感谢 @TheNetAdmin @muzimuzhi 的帮助，他们指出的问题是对的。
我原来用的是texlive2020，但里面的ctex没有升级到2.5（默认是2.4）。升级后问题就解决了。
