### ISSUE TITLE
[Enhancement]支持LuaTeX

### ISSUE THREAD

**Issue by URenko** [TheNetAdmin/zjuthesis#80]
因为物理系涉及高能物理的话就经常要画费曼图，而目前画费曼图比较强大且用的多的包是[TikZ-Feynman](https://www.overleaf.com/learn/latex/feynman_diagrams#TikZ-Feynman)，但是这个包必须要求LuaTeX（其他的话会回退到基本算法，显示效果很差）。
虽然也可以另行编译出来再插入，但一是麻烦，二是无法放入公式中。
故是否有可能添加对LuaTeX的支持。

**Comment by TheNetAdmin** [comment]
我目前还没尝试过LuaTeX，这两天有空我试用一下看看有哪些问题。

你尝试过用LuaTeX编译zjuthesis么，有遇到哪些问题吗

**Comment by TheNetAdmin** [comment]
LuaTeX可以直接编译，在项目根目录使用命令 `latexmk -pdflua -outdir=out` 即可。使用前要将 `out` 目录删除，以免之前 XeTeX 生成的中间文件与 LuaTeX混淆。

但 LuaTeX 似乎不能使用 xeCJK 的 `AutoFakeBold` 选项，所以其编译得到的 pdf 中，中文粗体都没有加粗，我正在寻找解决方案。

**Comment by TheNetAdmin** [comment]
通过 `\setCJKmainfont[AutoFakeBold={4}]{\FangSongFontName}` 可以将正文中的仿宋字体加粗，但封面的仿宋以及全文其他类字体没有加粗。

**Comment by TheNetAdmin** [comment]
似乎找到了全局的解决方案，我清理下代码就更新

**Comment by TheNetAdmin** [comment]
粗体问题已在 d439922 以及 8ccbaa9 中修复，现在可直接用 `latexmk -pdflua -outdir=out` 进行编译，并且正文中的字体可正常加粗。

**Comment by URenko** [comment]
在overleaf上试了下，效果很好
