### ISSUE TITLE
字体错误问题

### ISSUE THREAD

**Issue by IronShannon** [TheNetAdmin/zjuthesis#82]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [x] LuaTeX版本

版本号：6.0.4

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5434464/zjuthesis.log)

## 遇到的问题

编译之后提醒缺失字体（! Package fontspec Error: The font "SimKai" cannot be found.），但试了其他版本（v6.0.0，v6.0.3）却能够顺利编译，没有出现这个问题。

**截图**

**其他信息**

**Comment by muzimuzhi** [comment]
应用
```diff
diff --git a/config/format/general/fonts.tex b/config/format/general/fonts.tex
index 3db9d12..f99ca7d 100644
--- a/config/format/general/fonts.tex
+++ b/config/format/general/fonts.tex
@@ -39,7 +39,7 @@
     % Windows or other platform
     \setCJKfamilyfont{zhfs}   {FangSong} [AutoFakeBold={\FakeBoldSize}]
     \setCJKfamilyfont{zhhei}  {SimHei}   [AutoFakeBold={\FakeBoldSize}]
-    \setCJKfamilyfont{zhkai}  {SimKai}   [AutoFakeBold={\FakeBoldSize}]
+    \setCJKfamilyfont{zhkai}  {Kaiti}   [AutoFakeBold={\FakeBoldSize}]
     \setCJKfamilyfont{zhsong} {SimSun}   [AutoFakeBold={\FakeBoldSize}]

     \setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{FangSong}
```
后，再试试？我不在 win 下，抱歉没法实际测试。

根据 https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#simplified-chinese，win10 预装的楷体，字体名为 `KaiTi`，字体文件名为 `Simkai.ttf`（此处 `k` 为小写）。

**Comment by IronShannon** [comment]
> 应用
> 
> ```diff
> diff --git a/config/format/general/fonts.tex b/config/format/general/fonts.tex
> index 3db9d12..f99ca7d 100644
> --- a/config/format/general/fonts.tex
> +++ b/config/format/general/fonts.tex
> @@ -39,7 +39,7 @@
>      % Windows or other platform
>      \setCJKfamilyfont{zhfs}   {FangSong} [AutoFakeBold={\FakeBoldSize}]
>      \setCJKfamilyfont{zhhei}  {SimHei}   [AutoFakeBold={\FakeBoldSize}]
> -    \setCJKfamilyfont{zhkai}  {SimKai}   [AutoFakeBold={\FakeBoldSize}]
> +    \setCJKfamilyfont{zhkai}  {Kaiti}   [AutoFakeBold={\FakeBoldSize}]
>      \setCJKfamilyfont{zhsong} {SimSun}   [AutoFakeBold={\FakeBoldSize}]
> 
>      \setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{FangSong}
> ```
> 
> 后，再试试？我不在 win 下，抱歉没法实际测试。
> 
> 根据 [https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#simplified-chinese，win10](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#simplified-chinese%EF%BC%8Cwin10) 预装的楷体，字体名为 `KaiTi`，字体文件名为 `Simkai.ttf`（此处 `k` 为小写）。

按照这个操作一遍还是不行，不过将上面提到的那一句`\setCJKfamilyfont{zhkai}  {SimKai}   [AutoFakeBold={\FakeBoldSize}]`注释掉再进行编译就可以了，谢谢哈~

**Comment by TheNetAdmin** [comment]
Emmm似乎最近更新的字体处理代码比较草率，我再修复一下试试看

**Comment by TheNetAdmin** [comment]
> > 应用
> > ```diff
> > diff --git a/config/format/general/fonts.tex b/config/format/general/fonts.tex
> > index 3db9d12..f99ca7d 100644
> > --- a/config/format/general/fonts.tex
> > +++ b/config/format/general/fonts.tex
> > @@ -39,7 +39,7 @@
> >      % Windows or other platform
> >      \setCJKfamilyfont{zhfs}   {FangSong} [AutoFakeBold={\FakeBoldSize}]
> >      \setCJKfamilyfont{zhhei}  {SimHei}   [AutoFakeBold={\FakeBoldSize}]
> > -    \setCJKfamilyfont{zhkai}  {SimKai}   [AutoFakeBold={\FakeBoldSize}]
> > +    \setCJKfamilyfont{zhkai}  {Kaiti}   [AutoFakeBold={\FakeBoldSize}]
> >      \setCJKfamilyfont{zhsong} {SimSun}   [AutoFakeBold={\FakeBoldSize}]
> > 
> >      \setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{FangSong}
> > ```
> > 
> > 
> > 后，再试试？我不在 win 下，抱歉没法实际测试。
> > 根据 [https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#simplified-chinese，win10](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#simplified-chinese%EF%BC%8Cwin10) 预装的楷体，字体名为 `KaiTi`，字体文件名为 `Simkai.ttf`（此处 `k` 为小写）。
> 
> 按照这个操作一遍还是不行，不过将上面提到的那一句`\setCJKfamilyfont{zhkai} {SimKai} [AutoFakeBold={\FakeBoldSize}]`注释掉再进行编译就可以了，谢谢哈~

我在 win10 下面也遇到了这个问题，刚查了一下 ctex 的代码（texdoc ctex v2.5.5 `14.15.2.6 windows`）应该改成 `KaiTi`，而非 `SimKai` 或 `Kaiti`。最新的修复已经release。

**Comment by IronShannon** [comment]
谢谢~新版本编译之后没有问题
