### ISSUE TITLE
论文标题的格式问题

### ISSUE THREAD

**Issue by ZeallYang** [TheNetAdmin/zjuthesis#84]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis 版本**

版本号：6.0.1

**编译日志**

## 遇到的问题
编辑Title时候，题目格式有问题: 文字无法居中，且多了第三条下划线。

**截图**
![未命名1603713983](https://user-images.githubusercontent.com/31650023/97170582-e5b8f780-17c6-11eb-980b-927263a16d55.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
看起来你是在用研究生模板，那么相关的页面位于：

https://github.com/TheNetAdmin/zjuthesis/blob/42fec39181ff128e128dd31bc7ea10f57c77fe8c/page/graduate/cover-chn.tex#L33-L43

参照这里的注释手动换行中文标题即可

**Comment by ZeallYang** [comment]
谢谢，这个问题已经解决了。还有个问题想咨询下，比如参考文献，附录，勘误表，之类的标题，现在是左对齐的，我想居中该怎么调整。
![未命名1603759505](https://user-images.githubusercontent.com/31650023/97243219-c8207800-1830-11eb-9c96-a78d2b6066b3.png)
![未命名1603759519](https://user-images.githubusercontent.com/31650023/97243223-c9ea3b80-1830-11eb-932b-0dfe07c77d41.png)

**Comment by TheNetAdmin** [comment]
这些不带编号的标题使用了 `\chapternonum` 命令，其定义位于

https://github.com/TheNetAdmin/zjuthesis/blob/42fec39181ff128e128dd31bc7ea10f57c77fe8c/config/commands.tex#L97-L115

将这里的 `flushleft` 改为 `center` 即可居中。

其余带编号的标题使用了 `CTeX` 宏包的设定，均位于

https://github.com/TheNetAdmin/zjuthesis/blob/42fec39181ff128e128dd31bc7ea10f57c77fe8c/config/format/general/heading.tex#L49-L90

其具体用法参见 `CTeX` 宏包的文档 （如果本地安装了 TexLive 的话，可以用命令 `texdoc ctex` 快速打开 `CTeX` 的文档）

**Comment by ZeallYang** [comment]
谢谢，这个问题也已经解决了。然后我想改一下二级标题和三级标题的段前和段后间距，为什么不起作用。不知道是不是我改的不对
![未命名1603802726](https://user-images.githubusercontent.com/31650023/97303502-70682800-1895-11eb-872f-ff4b8d7f4519.png)

**Comment by muzimuzhi** [comment]
1. 模板里的设置应该已经符合学校要求，为什么会有修改段前段后间距的需求？
2. 不要发代码截图，请发文本形式、他人可复制的代码。最好能发完整的、他人复制后能直接编译的例子。

**Comment by ZeallYang** [comment]
不好意思，我是看到之前的师兄们word模板的段落前后间距都是这么设置的，所以想调整下保持一致。
代码如下：

{
    \ctexset
    {
        part =
        {
            format=\centering\zihao{-0}\bfseries,
            nameformat=\centering\heiti\fontsize{48}{48}\bfseries,
        },
        chapter =
        {
            format=\raggedright\zihao{-3}\bfseries,
            name={},
            number=\arabic{chapter},
            beforeskip=12pt,
            afterskip=6pt
        },
        section =
        {
            format=\raggedright\zihao{4}\bfseries,
            name={},
            number=\arabic{chapter}.\arabic{section},
            beforeskip=6pt,     % 原：13 13
            afterskip=6pt
        },
        subsection =
        {
            format=\raggedright\zihao{-4}\bfseries,
            name={},
            number=\arabic{chapter}.\arabic{section}.\arabic{subsection},
           beforeskip=7pt,     % 原：13 13
           afterskip=0pt
        },
        subsubsection =
        {
            format=\raggedright\zihao{-4},
            name={},
            aftername=~,
            numbering=true,
            number=\arabic{chapter}.\arabic{section}.\arabic{subsection}.\arabic{subsubsection},
            beforeskip=0pt,
            afterskip=0pt
        }
    }
}

**Comment by muzimuzhi** [comment]
1. 可以编辑原评论，删掉截图，换成文本。记得把文本放进 fenced code block 里去，参考 https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown 和 https://github.github.com/gfm/#fenced-code-blocks
1. 模板的价值就在于已经替你把样式设置好了。段间距是不是真有调整的必要，可以咨询模板作者。
1. Word 和 LaTeX 的段落模型不一样，具体参数无法简单对应。

**Comment by TheNetAdmin** [comment]
> 1. 可以编辑原评论，删掉截图，换成文本。记得把文本放进 fenced code block 里去，参考 https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown 和 https://github.github.com/gfm/#fenced-code-blocks
> 2. 模板的价值就在于已经替你把样式设置好了。段间距是不是真有调整的必要，可以咨询模板作者。
> 3. Word 和 LaTeX 的段落模型不一样，具体参数无法简单对应。

感谢帮忙回复

@ZeallYang 如果你有段前段后间距问题，请另开一个 issue，截图描述你想要达成的效果，然后附上修改前后代码与前后截图对比，说明哪里不符合你的预期，同时附上编译 log 文件。

这个 issue 已经解决了 "论文标题格式问题"。
