### ISSUE TITLE
documentclass 的设置在最新版本 LaTeX 中不可用

### ISSUE THREAD

**Issue by zkmbdbbdd** [TheNetAdmin/zjuthesis#86]
## 系统信息

**操作系统**

- [10] Windows

**TeX套件**

- [20.11] MikTex

**TeX Compiler**

- XeTeX

**zjuthesis**

版本号：v6.0.5

Degree:
  -  graduate
    -  master

Major:
  -  physics
**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5515843/zjuthesis.log)

## 遇到的问题
无论怎么设置主文件zjuthesis/zjuthesis.tex，编译结果总是本科生毕业论文

**截图**

![image](https://user-images.githubusercontent.com/42455038/98648536-605e4700-2371-11eb-8f1c-70a3539b79c6.png)

**其他信息**

**Comment by TheNetAdmin** [comment]
似乎和 #85 是类似的问题，但我看到你在用MikTeX，尝试用TeXLive看是否能解决问题

**Comment by TheNetAdmin** [comment]
可否将你整个模板文件包括生成的中间文件以及pdf打包发上来，我查一下有哪些问题。

**Comment by TheNetAdmin** [comment]
我似乎能复现这个问题，可能是最新版本的 TeXLive 2020 有关的问题，我之前在用这个版本，XeTeX 可以正常读取参数:

```
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex 2020.10.22)  10 NOV 2020 00:38
```

但使用 `tlmgr update --self --all` 更新到如下版本，也出现了参数无效的问题:

```
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex 2020.11.10)  10 NOV 2020 00:49
```

同时在 #85 中的如下版本也有类似问题:

```
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex 2020.11.1)  1 NOV 2020 19:16
```

**Comment by TheNetAdmin** [comment]
查阅 `kvoptions` 的文档 (2020-10-07 v3.14) 时发现如下内容，不知道是否和当前 BUG 有关:

![image](https://user-images.githubusercontent.com/18525442/98651832-9bb83180-22ef-11eb-9d71-22a5787f352a.png)

**Comment by TheNetAdmin** [comment]
最新版本的 LuaTeX 也出现了类似问题

**Comment by TheNetAdmin** [comment]
临时的解决方案是在 `config/zjuthesis.cls` 中直接写入各个选项的值，我最近有空的话研究一下解决方案。

刚尝试过使用 `l3keys2e` 替代 `kvoptions`，但仍无法获得 `documentclass` 传入的值：

```TeX
\RequirePackage{l3keys2e}
\ExplSyntaxOn
\keys_define:nn { zjuthesis }
{
    StudentName .tl_set:N = \StudentName,
    StudentID .tl_set:N = \StudentID,
    AdvisorName .tl_set:N = \AdvisorName,
    Grade .tl_set:N = \Grade,
    Major .tl_set:N = \Major,
    Department .tl_set:N = \Department,
    Title .tl_set:N = \Title,
    TitleEng .tl_set:N = \TitleEng,
    SubmitDate .tl_set:N = \SubmitDate,
    Degree .tl_set:N = \Degree,
    MajorFormat .tl_set:N = \MajorFormat,
    Type .tl_set:N = \Type,
    Period .tl_set:N = \Period,
    BlindReview .tl_set:N = \BlindReview,
    Language .tl_set:N = \Language,
    GradLevel .tl_set:N = \GradLevel,
    ColaboratorName .tl_set:N = \ColaboratorName,
    Topic .tl_set:N = \Topic,
}

\ProcessKeysOptions { zjuthesis }

\ExplSyntaxOff
```

**Comment by TheNetAdmin** [comment]
似乎 LaTeX2e repo 里有报告类似问题:

https://github.com/latex3/latex2e/issues/422

**Comment by TheNetAdmin** [comment]
问题应该已经解决，可以尝试使用最新的代码 (master 分支或 6.1.0 release)

**Comment by TheNetAdmin** [comment]
最新版本的 zjuthesis 应该已经解决了这个问题，如仍有问题请重开 issue

**Comment by PhelypeOleinik** [comment]
Hi @TheNetAdmin. I see you've already solved the problem at your end, but the issue is now fixed in LaTeX and should be available in a few days with patch release 3.

**Comment by TheNetAdmin** [comment]
> Hi @TheNetAdmin. I see you've already solved the problem at your end, but the issue is now fixed in LaTeX and should be available in a few days with patch release 3.

Thank you very much for the notice! @PhelypeOleinik 

I will try the new release once it's available
