### ISSUE TITLE
适配计算机学院博士学位论文模板

### ISSUE THREAD

**Issue by HaroldZ** [TheNetAdmin/zjuthesis#87]
计算机学院的博士学位论文模板和通用的博士模板的格式也有很多不一样的地方，如果楼主有时间可以也对应适配一下。

计算机学院博士学位论文模板地址：http://cspo.zju.edu.cn/_upload/article/files/88/17/fc02cbfe4195a109ed1e1f01cc75/a55a1290-f1b4-436d-a0d2-0e5be0812cff.doc

**Comment by HaroldZ** [comment]
似乎除了封面等少数地方，博士模板和硕士模板字体格式基本一致，我目前临时解决方案是直接改了config/format/major/cs下面的每个文件，去掉了`\AND \equal{\GradLevel}{master}`

另外在Mac OS下，计算机学院硕士论文模板有个字体的bug，因为config/format/major/cs/fonts.tex中默认字体设置的是SimSun，而这个字体是windows系统下独有的定制宋体，在Mac OS下编译后会报错。

解决方案是把fonts.tex中的默认字体改成Mac OS下的宋体 STSong 
`\setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{STSong}`

**Comment by TheNetAdmin** [comment]
我更新了 cs 相关的模板设置，去除了 `\AND \equal{\GradLevel}{master}` 并且修复了字体设置。

但学位论文模板是一个浙大内网地址，我无法访问，可否直接将模板文件上传到这个 issue 内？

**Comment by HaroldZ** [comment]
模版文件：
[博士学位论文模板.docx](https://github.com/TheNetAdmin/zjuthesis/files/5527816/default.docx)

博士论文的封面也和硕士基本一致，只需要把中文封面的“硕士学位论文”改成“博士学位论文”，英文封面的“Master of Engineer”改成“Doctor of Philosophy”，再加上原创性声明。所以Page部分我也直接拿了master/cs下的改了改复用了。

**Comment by TheNetAdmin** [comment]
我更新了 CS 博士论文的封面，不过模板里并没有看到原创性声明这一页，所以暂时没有加入模板

**Comment by HaroldZ** [comment]
另外又发现两个格式不对的地方：
1.图编号和表编号的格式是图1-1，不是图1.1
2.摘要部分的页码应该是小写罗马数字，而不是大写罗马数字，并且目录部分和摘要部分是分开编号的

**Comment by TheNetAdmin** [comment]
最新的代码应该已经修复了这些编号与页码样式，可以尝试 master 分支上最新的 commit

**Comment by TheNetAdmin** [comment]
发布新版本包含计院博士模板，如果 zjuthesis 与计院博士模板仍有出入的话，请重开 issue
