### ISSUE TITLE
[BUG]计算机学院模版页边距问题

### ISSUE THREAD

**Issue by HaroldZ** [TheNetAdmin/zjuthesis#88]
计算机学院的模板的页边距似乎有问题，和页眉的长度没有对齐，在奇数页右边会多出一块空白，偶数页则是左边多出一块空白，如图所示
<img width="516" alt="image" src="https://user-images.githubusercontent.com/14771013/99500940-046d7100-29b6-11eb-94a0-73fa1501622e.png">
<img width="389" alt="image" src="https://user-images.githubusercontent.com/14771013/99500883-edc71a00-29b5-11eb-897b-51a27fff7017.png">

**其他信息**
似乎是cs/layout.tex里面定义的\geometry的问题，如果把hmargin改成和general模板的一致大小就不会出现此问题。

**Comment by TheNetAdmin** [comment]
这个本来是用于修复标题页边距的设定，过两天我抽空再改下
