### ISSUE TITLE
计算机硕士英文页格式错误

### ISSUE THREAD

**Issue by lgqfhwy** [TheNetAdmin/zjuthesis#89]
## 系统信息

**操作系统**

- [ ] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [x] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：v6.2.0

Degree:
  - [ ] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics
**编译日志**

## 遇到的问题

计算机硕士英文页的封面，里面只有Title是英文的，而Author, Supervisor, Subject, College也要求填英文的(或者拼音)，原来的模板是直接填的中文的，我自己已经加上变量改了过来。但是英文页的支持好像有问题，一是英文中不识别空格了，二是突然的间距过大。

**截图**

下图右边为编译结果，左边为我添加的变量。
![zjuthesis](https://user-images.githubusercontent.com/16728136/99617873-308efd80-2a5b-11eb-8831-288c692afc95.PNG)

**其他信息**

**Comment by TheNetAdmin** [comment]
空格问题参考下面英文题目的写法加上双大括号

**Comment by TheNetAdmin** [comment]
间距过大也是因为没有空格，第一个问题解决后应该不存在间距问题，但可能需要多行显示，那样的话建议直接把内容写入封面代码，不要用变量传入
