### ISSUE TITLE
package biblatex error ：style' gb7714 - 2015' not found

### ISSUE THREAD

**Issue by mitghtyr** [TheNetAdmin/zjuthesis#9]
![image](https://user-images.githubusercontent.com/46819870/51394914-6ff61580-1b76-11e9-9cce-b0b01a120de5.png)

如图，我和室友(Windows和mac系统下)都出现了该问题，报错后pdf文件可以出来，但是参考文献没法显示，cite全部报错，请问有什么解决思路吗？
尝试按照[【A biblatex implementation of the GB/T7714-2015 bibliography style|为什么我之前使用样式style=caspervector进行编译没有问题，换成style=gb7714-2015后，编译就出现错误？】](https://github.com/hushidong/biblatex-gb7714-2015)上解决方案在文件夹下放那四个文件，结果gb7714-2015.bbx报了很多错，document都无法begin了……

求助呀~

**Comment by TheNetAdmin** [comment]
这是缺少了宏包`biblatex-gb7714-2015`

你安装的是什么发行版本，如果是TexLive的话是完全安装吗？

如果是Windows的话应该是安装的TexLive，你可以用`tlmgr install biblatex-gb7714-2015`来安装这个包。MAC我没用过，但应该用包管理器就可以。安装完记得把GitHub上面的几个文件去掉。

如果安装这个包之后还不能用，建议你完全安装一下TexLive或者其他发行版。

**Comment by TheNetAdmin** [comment]
问题还存在么？没问题的话我就关闭issue了

**Comment by TheNetAdmin** [comment]
issue暂时关闭，如果还有问题可以重开

**Comment by mitghtyr** [comment]
嗷！！！感谢回复！不好意思才看到，我试试您的方法，看看能不能行，再次感谢！！

祝一切顺利！

Zixuan Wang <notifications@github.com> 于2019年1月19日周六 上午2:47写道：
