### ISSUE TITLE
mac上安装mactex后，使用vscode的latex workshop编译不了，好像是找不到中文路径，请问需要做什么修改吗

### ISSUE THREAD

**Issue by yuwl798180** [TheNetAdmin/zjuthesis#90]
你好，我使用mac安装的最新的mactex后，结合vscode的latex workshop，无法编译，编译时间特别久（约300s）后，只有几页英文内容，中文内容好像都无法显示。
请问我是需要额外做什么特殊配置吗？

我用的git clone最新仓库的方法。

ps：最新的mactex由于xx问题，不再集成tex live utility，bib desk，coco aspell。请问是否因为这个原因？

## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [ ] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex
- [x] MacTex

**TeX Compiler**

- [ ] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [ x] graduate
    - [ ] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(/Users/leo/Documents/GitHub/zjuthesis/zjuthesis.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06> (./zjuthesis.cls
Document Class: zjuthesis Zhejiang University Thesis and Design Template, Zixuan Wang zxwang42@gmail.com
(./config/version.tex) (/usr/local/texlive/2020/texmf-dist/tex/latex/kvoptions/kvoptions.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/graphics/keyval.sty) (/usr/local/texlive/2020/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty) (/usr/local/texlive/2020/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)) (/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/ctexrep.cls (/usr/local/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-xdvipdfmx.def))
Document Class: ctexrep 2019/05/29 v2.4.16 Chinese adapter for class report (CTEX)
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/ctexhook.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/ctexpatch.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/base/fix-cm.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/base/ts1enc.def)) (/usr/local/texlive/2020/texmf-dist/tex/latex/ms/everysel.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/config/ctexopts.cfg) (/usr/local/texlive/2020/texmf-dist/tex/latex/base/report.cls
Document Class: report 2019/12/20 v1.4l Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/size12.clo)) (/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/engine/ctex-engine-xetex.def (/usr/local/texlive/2020/texmf-dist/tex/xelatex/xecjk/xeCJK.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/fontspec/fontspec.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/base/fontenc.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/fontspec/fontspec.cfg))) (/usr/local/texlive/2020/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg)) (/usr/local/texlive/2020/texmf-dist/tex/xelatex/xecjk/xeCJKfntef.sty (/usr/local/texlive/2020/texmf-dist/tex/generic/ulem/ulem.sty))) (/usr/local/texlive/2020/texmf-dist/tex/latex/zhnumber/zhnumber.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/zhnumber/zhnumber-utf8.cfg)) (/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/scheme/ctex-scheme-chinese-report.def (/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/config/ctex-name-utf8.cfg)) (/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/ctex-cs4size.clo) (/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-fandol.def

Package fontspec Warning: Font "FandolSong-Regular" does not contain requested
(fontspec)                Script "CJK".

)) (/usr/local/texlive/2020/texmf-dist/tex/latex/ctex/config/ctex.cfg) (./config/packages.tex (/usr/local/texlive/2020/texmf-dist/tex/latex/graphics/graphicx.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/graphics/graphics.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/graphics/trig.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/graphics-cfg/graphics.cfg) (/usr/local/texlive/2020/texmf-dist/tex/latex/graphics-def/xetex.def))) (/usr/local/texlive/2020/texmf-dist/tex/latex/geometry/geometry.sty (/usr/local/texlive/2020/texmf-dist/tex/generic/iftex/ifvtex.sty (/usr/local/texlive/2020/texmf-dist/tex/generic/iftex/iftex.sty))) (/usr/local/texlive/2020/texmf-dist/tex/latex/tools/tabularx.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/tools/array.sty)) (/usr/local/texlive/2020/texmf-dist/tex/latex/multido/multido.sty (/usr/local/texlive/2020/texmf-dist/tex/generic/multido/multido.tex  v1.42, 2010/05/14 <tvz>)) (/usr/local/texlive/2020/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/titlesec/titlesec.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/tocloft/tocloft.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/multirow/multirow.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/makecell/makecell.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/hyperref.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/pdftexcmds/pdftexcmds.sty (/usr/local/texlive/2020/texmf-dist/tex/generic/infwarerr/infwarerr.sty)) (/usr/local/texlive/2020/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty) (/usr/local/texlive/2020/texmf-dist/tex/generic/pdfescape/pdfescape.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/hycolor/hycolor.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/auxhook/auxhook.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/pd1enc.def) (/usr/local/texlive/2020/texmf-dist/tex/generic/intcalc/intcalc.sty) (/usr/local/texlive/2020/texmf-dist/tex/generic/etexcmds/etexcmds.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/puenc.def) (/usr/local/texlive/2020/texmf-dist/tex/latex/url/url.sty) (/usr/local/texlive/2020/texmf-dist/tex/generic/bitset/bitset.sty (/usr/local/texlive/2020/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty)) (/usr/local/texlive/2020/texmf-dist/tex/generic/atbegshi/atbegshi.sty)) (/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/hxetex.def (/usr/local/texlive/2020/texmf-dist/tex/generic/stringenc/stringenc.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/atveryend/atveryend.sty) (/usr/local/texlive/2020/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty))) (/usr/local/texlive/2020/texmf-dist/tex/latex/pdfpages/pdfpages.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/base/ifthen.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/tools/calc.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/eso-pic/eso-pic.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/xcolor/xcolor.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/graphics-cfg/color.cfg))) (/usr/local/texlive/2020/texmf-dist/tex/latex/pdfpages/ppxetex.def)) (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/biblatex.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/etoolbox/etoolbox.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/logreq/logreq.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/logreq/logreq.def)) (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/blx-dm.def) (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/blx-unicode.def) (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/blx-compat.def) (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/biblatex.def) (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex-gb7714-2015/gb7714-2015.bbx (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/bbx/numeric-comp.bbx (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/bbx/numeric.bbx (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/bbx/standard.bbx))) (/usr/local/texlive/2020/texmf-dist/tex/generic/xstring/xstring.sty (/usr/local/texlive/2020/texmf-dist/tex/generic/xstring/xstring.tex))) (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex-gb7714-2015/gb7714-2015.cbx (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/cbx/numeric-comp.cbx)) (/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/biblatex.cfg)) (/usr/local/texlive/2020/texmf-dist/tex/latex/siunitx/siunitx.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/amsmath/amstext.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/amsmath/amsgen.sty)) (/usr/local/texlive/2020/texmf-dist/tex/latex/translator/translator.sty)) (/usr/local/texlive/2020/texmf-dist/tex/latex/caption/caption.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/caption/caption3.sty)) (/usr/local/texlive/2020/texmf-dist/tex/latex/chngcntr/chngcntr.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/enumitem/enumitem.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/float/float.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/listings/listings.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/listings/lstmisc.sty) (/usr/local/texlive/2020/texmf-dist/tex/latex/listings/listings.cfg)) (/usr/local/texlive/2020/texmf-dist/tex/latex/xifthen/xifthen.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/ifmtarg/ifmtarg.sty)) (/usr/local/texlive/2020/texmf-dist/tex/latex/amsfonts/amssymb.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/amsfonts/amsfonts.sty)) (/usr/local/texlive/2020/texmf-dist/tex/latex/bookmark/bookmark.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/bookmark/bkm-dvipdfm.def))) (./config/path.tex) (./config/commands.tex) (./config/format/format.tex (./config/format/general/format.tex (./config/format/general/caption.tex) (./config/format/general/layout.tex) (./config/format/general/heading.tex) (./config/format/general/fonts.tex
kpathsea: Running mktextfm FangSong/OT
/usr/local/texlive/2020/texmf-dist/web2c/mktexnam: Could not map source abbreviation O for OT.
/usr/local/texlive/2020/texmf-dist/web2c/mktexnam: Need to update /usr/local/texlive/2020/texmf-dist/fonts/map/fontname/special.map?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input OT
This is METAFONT, Version 2.7182818 (TeX Live 2020) (preloaded base=mf)

kpathsea: Running mktexmf OT

! I can't find file `OT'.
<*> \mode:=ljfour; mag:=1; ; nonstopmode; input OT
                                                  
Please type another input file name
! Emergency stop.
<*> \mode:=ljfour; mag:=1; ; nonstopmode; input OT
                                                  
Transcript written on mfput.log.
grep: OT.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input OT' failed to make OT.tfm.
kpathsea: Appending font creation commands to missfont.log.

kpathsea: Running mktextfm FangSong/OT
/usr/local/texlive/2020/texmf-dist/web2c/mktexnam: Could not map source abbreviation O for OT.
/usr/local/texlive/2020/texmf-dist/web2c/mktexnam: Need to update /usr/local/texlive/2020/texmf-dist/fonts/map/fontname/special.map?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input OT
This is METAFONT, Version 2.7182818 (TeX Live 2020) (preloaded base=mf)

kpathsea: Running mktexmf OT

! I can't find file `OT'.
<*> \mode:=ljfour; mag:=1; ; nonstopmode; input OT
                                                  
Please type another input file name
! Emergency stop.
<*> \mode:=ljfour; mag:=1; ; nonstopmode; input OT
                                                  
Transcript written on mfput.log.
grep: OT.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input OT' failed to make OT.tfm.

kpathsea: Running mktextfm FangSong/OT
/usr/local/texlive/2020/texmf-dist/web2c/mktexnam: Could not map source abbreviation O for OT.
/usr/local/texlive/2020/texmf-dist/web2c/mktexnam: Need to update /usr/local/texlive/2020/texmf-dist/fonts/map/fontname/special.map?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input OT
This is METAFONT, Version 2.7182818 (TeX Live 2020) (preloaded base=mf)

kpathsea: Running mktexmf OT

还有很多类似的内容，粘贴不了了，因为超出最大内容
                       

./page/graduate/title-eng.tex:26: LaTeX3 Error: Control sequence
(LaTeX3)       
\c__xeCJK_xeCJK/SimSun(0)/b/n/15.05624/quanjiao/dim/bound/left/：/tl
(LaTeX3)        already defined.

For immediate help type H <return>.
 ...                                              
                                                  
l.26     \end{tabularx}
                       
./page/graduate/title-eng.tex:26: Cannot use \XeTeXglyphbounds with nullfont; not a native platform font.
<recently read> \tex_XeTeXglyphbounds:D 
                                        
l.26     \end{tabularx}
                       

./page/graduate/title-eng.tex:26: LaTeX3 Error: Control sequence
(LaTeX3)       
\c__xeCJK_xeCJK/SimSun(0)/b/n/15.05624/quanjiao/dim/bound/right/：/tl
(LaTeX3)        already defined.

For immediate help type H <return>.
 ...                                              
                                                  
l.26     \end{tabularx}
                       

./page/graduate/title-eng.tex:26: LaTeX3 Error: Control sequence
(LaTeX3)        \c__xeCJK_xeCJK/SimSun(0)/b/n/15.05624/quanjiao/dim/width/：/tl
(LaTeX3)        already defined.

For immediate help type H <return>.
 ...                                              
                                                  
l.26     \end{tabularx}
                       
./page/graduate/title-eng.tex:26: Missing ) inserted for expression.
<to be read again> 
                   1
l.26     \end{tabularx}
                       

./page/graduate/title-eng.tex:26: LaTeX3 Error: Control sequence
(LaTeX3)        \c__xeCJK_xeCJK/SimSun(0)/b/n/15.05624/quanjiao/dim/dimen/：/tl
(LaTeX3)        already defined.

For immediate help type H <return>.
 ...                                              
                                                  
l.26     \end{tabularx}
                       
(That makes 100 errors; please try again.)
Output written on out/zjuthesis.pdf (4 pages).
SyncTeX written on out/zjuthesis.synctex.gz.
Transcript written on out/zjuthesis.log.

## 遇到的问题

**截图**

**其他信息**

**Comment by yuwl798180** [comment]
折腾不动了，暂时使用了你提供的overleaf版本。编译没有问题。

**Comment by yuwl798180** [comment]
但是使用cs模板时（graduate）（master），单双页存在留白，看了下往届的都不存在留白，不知道这个应该怎么修改？

**Comment by TheNetAdmin** [comment]
双页留白是为了正反面双面打印设计的，不必修改

**Comment by yuwl798180** [comment]
你好，我看了下往届师兄师姐的毕业论文，都没有单双页留白，织网上的2020年最新我们学院硕士论文也没有留白。

请问这个去掉留白，应该怎么修改？

**Comment by yuwl798180** [comment]
你好，我又认真看了下，注意到正文内容是没有问题的，有问题的是页头的部分。
单双页的页头都突出了一部分，和#88是同一个问题。硕士的cs论文也有这个问题。

我这个就不再留言了，希望大佬早日修复bug。（月底就要交毕设了。。

**Comment by muzimuzhi** [comment]
@yuwl798180 每一个单独问题，都请务必单独开一个 issue。

**Comment by zhaohyin** [comment]
我也遇到了和你类似的问题，请问你这边解决掉这么问题了么？

**Comment by TheNetAdmin** [comment]
碰到问题请新开issue
