### ISSUE TITLE
段首空格问题

### ISSUE THREAD

**Issue by Marco2018** [TheNetAdmin/zjuthesis#91]
## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [x] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [ ] general
  - [x] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

**截图**

**其他信息**

编译之后如下所示：
![捕获](https://user-images.githubusercontent.com/23646963/100075604-1ef28f00-2e7b-11eb-89a9-d2a0fd0ff7eb.PNG)

不知道该如何改成段首空格的那种格式，谢谢各位！

**Comment by TheNetAdmin** [comment]
cs硕士生模板没有这一页

**Comment by Marco2018** [comment]
您好，我的设置是这样子的
Major    = cs,
Degree   = graduate
GradLevel   = master

运行xelatex zjuthesis
biber zjuthesis
xelatex zjuthesis之后是有这一页的....

**Comment by TheNetAdmin** [comment]
我本地编译没有这一页

[zjuthesis.pdf](https://github.com/TheNetAdmin/zjuthesis/files/5594781/zjuthesis.pdf)

补全issue模板的信息，把zjuthesis.log文件和你编译得到的pdf文件附上来看一下

用 latexmk 命令编译，这是 README 里写过的

**Comment by Marco2018** [comment]
啊 我去查了一下，之前误用了ragged2e这个所以出现了这种问题，问题解决啦 谢谢
