### ISSUE TITLE
\chapternonum 和 \sectionnonum 的垂直间距与其他标题不统一

### ISSUE THREAD

**Issue by xxwywzy** [TheNetAdmin/zjuthesis#93]
## 系统信息

**操作系统**

- [ ] Windows
- [x] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [x] TeXLive 2020 或更新的版本
- [ ] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：overleaf-v6.0.2

Degree:
  - [x] graduate
    - [ ] master
    - [x] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

## 遇到的问题

根据学院要求，除致谢外，摘要、术语表、目录、参考文献、附录、个人简历等部分均需添加页眉。我按照模板中提供的 common 样式进行设置后，可以满足上述要求，但是模板中这些页面的自定义标题 \chapternonum 在当前设置下与页眉的间距过近，导致整体的样式有一些奇怪。想请教一下是否可以对 \chapternonum 进行进一步的自定义来改变其与页眉与正文之间的间距，或者通过其他方法实现这一效果？

**截图**

<img width="553" alt="截屏2020-11-27 下午11 00 30" src="https://user-images.githubusercontent.com/8501941/100462298-05647800-3105-11eb-89b0-ea1bbf710acb.png">

**其他信息**

**Comment by TheNetAdmin** [comment]
最简单的解决办法是在这些\chapternonum前加\vspace并指定间距大小

**Comment by xxwywzy** [comment]
> 最简单的解决办法是在这些\chapternonum前加\vspace并指定间距大小

刚才试了一下，在标题后面增加间距是没有问题的，但是标题与页眉之间的间距这样设置似乎并不会发生变化

![截屏2020-11-28 上午10 53 46](https://user-images.githubusercontent.com/8501941/100492537-1a262780-3168-11eb-980d-60af2e6e45fb.png)

**Comment by TheNetAdmin** [comment]
这似乎是一个存留已久的 BUG，我刚进行了修复，可以查看 16c68cd 的修改，现在应该所有标题的上下垂直间距都统一了

**Comment by TheNetAdmin** [comment]
16c68cd 中的修复造成了另一个问题：新的 `\sectionnonum` 和 `\chapternonum` 会覆盖 pagestyle，我再研究下如何修改比较合适

**Comment by TheNetAdmin** [comment]
在 1ae0218 做出了进一步修复，使得 previous，body 和 post 部分的 chapter pagestyle 与该部分原有 pagestyle 保持统一

**Comment by xxwywzy** [comment]
感谢修复！如果想要 previous 中部分界面显示页眉的话，一种简单的方法是在对应界面再添加 \assignpagestyle{\chapter}{common} 与 \pagestyle{common} 即可（会作用于该界面之后的所有部分）PS: 目录首页的页眉更改还需要修改 layout.tex 中的 \tocloftpagestyle 命令。

**Comment by TheNetAdmin** [comment]
> 感谢修复！如果想要 previous 中的部分界面显示页眉的话，一种简单的方法是在对应界面再添加 \assignpagestyle{\chapter}{common} 与 \pagestyle{common} 即可（会作用于该界面之后的所有部分）PS: 目录首页的页眉更改还需要修改 layout.tex 中的 \tocloftpagestyle 命令。

可能更简单的做法是把 common 的设置复制到 previous 里面

**Comment by xxwywzy** [comment]
> > 感谢修复！如果想要 previous 中的部分界面显示页眉的话，一种简单的方法是在对应界面再添加 \assignpagestyle{\chapter}{common} 与 \pagestyle{common} 即可（会作用于该界面之后的所有部分）PS: 目录首页的页眉更改还需要修改 layout.tex 中的 \tocloftpagestyle 命令。
> 
> 可能更简单的做法是把 common 的设置复制到 previous 里面

233这样做的话部分 previous 界面想保留空白页眉设置的话是不是会无法实现或者需要改更多的部分（比如只需要致谢部分不添加页眉）

**Comment by TheNetAdmin** [comment]
那就单独把致谢页改成 empty，在该页添加：

```LaTeX
\thispagestyle{empty}
```

**Comment by xxwywzy** [comment]
> 那就单独把致谢页改成 empty，在该页添加：
> 
> ```
> \thispagestyle{empty}
> ```

似乎因为 \assignpagestyle{\chapter} 的存在，这样改并不会显示空白页眉，但加上的话所有之后的 previous 界面都会变掉，感觉还是处理后面的页面比较合理（处理前面的可能会影响后面）

**Comment by TheNetAdmin** [comment]
Emm似乎我给出的办法是有点naive了，不过前置页面就这几页，手动改完一次以后应该就不用再改了。

另外问一下，可以新开issue上传你们学院具体的毕业论文模板和相关要求么，我有空可以尝试做一个模板方便之后的同学使用。

**Comment by xxwywzy** [comment]
> Emm似乎我给出的办法是有点naive了，不过前置页面就这几页，手动改完一次以后应该就不用再改了。
> 
> 另外问一下，可以新开issue上传你们学院具体的毕业论文模板和相关要求么，我有空可以尝试做一个模板方便之后的同学使用。

可以的！不过我们学院有一个很长的 checklist，我感觉有一些条目现在的模板还不满足（因为checklist是以word为模板设置的），要不我最近再整理一下有问题的地方，然后全部改完后一起提交？checklist 我可以先上传在这里

[生仪学院学位论文规范性审查表.pdf](https://github.com/TheNetAdmin/zjuthesis/files/5610246/default.pdf)

**Comment by TheNetAdmin** [comment]
OK，什么时候整理完毕直接新开issue，附上各种文件与要求，我会抽空开发的。

这个问题已经解决的话就可以 close issue 了
