### ISSUE TITLE
 各年级各专业的模板要求汇总

### ISSUE THREAD

**Issue by TheNetAdmin** [TheNetAdmin/zjuthesis#94]
今后在这个 Issue 内汇总各年级各专业的毕业模板要求，以方便查阅

**Comment by TheNetAdmin** [comment]
## 本科生模板

| 专业 | 相关文件 |
| :---: | :---:|
| general | |
| cs | |

**Comment by TheNetAdmin** [comment]
## 研究生模板

| 专业 | 硕士模板要求 | 博士模板要求 |
| :---: | :---: | :---: |
| general ||

**Comment by rosefun** [comment]
[浙江大学研究生学位论文word版本](https://share.weiyun.com/duM8jRRV)

**Comment by TheNetAdmin** [comment]
> [浙江大学研究生学位论文word版本](https://share.weiyun.com/duM8jRRV)

我这没法下载，请直接将word文件拖拽到GitHub comment的对话框里，这样可以直接上传到GitHub

**Comment by rosefun** [comment]
[浙江大学研究生学位论文编写规则.zip](https://github.com/TheNetAdmin/zjuthesis/files/5800069/default.zip)

**Comment by xxwywzy** [comment]
[Uploading 生仪学院学位论文规范性审查表.pdf…]()

**Comment by xxwywzy** [comment]
[生仪学院学位论文规范性审查表.pdf](https://github.com/TheNetAdmin/zjuthesis/files/5833891/default.pdf)

**Comment by haochengxia** [comment]
[2021 cse & isee 本科生毕业论文(设计)模板.zip](https://github.com/TheNetAdmin/zjuthesis/files/6511166/2021.cse.isee.zip)

**Comment by TheNetAdmin** [comment]
> 
> 
> [2021 cse & isee 本科生毕业论文(设计)模板.zip](https://github.com/TheNetAdmin/zjuthesis/files/6511166/2021.cse.isee.zip)

@haochengxia 这个压缩包似乎损坏了，我这无法解压。有空的话可否将几个文档单独上传到这里呢

**Comment by haochengxia** [comment]
[控制学院_浙江大学本科生毕业论文模板.pdf](https://github.com/TheNetAdmin/zjuthesis/files/6525801/_.pdf)
[控制学院_浙江大学本科生毕业设计模板.pdf](https://github.com/TheNetAdmin/zjuthesis/files/6525802/_.pdf)

**Comment by haochengxia** [comment]
[信电学院_浙江大学本科生毕业论文（设计）（模板）.zip](https://github.com/TheNetAdmin/zjuthesis/files/6525806/_.zip)

**Comment by YaoZhongwei** [comment]
[浙江大学经济学院博士学位论文模板（2019版）.docx](https://github.com/TheNetAdmin/zjuthesis/files/8145889/2019.docx)
[浙江大学经济学院博士学位论文模板（2019版）.pdf](https://github.com/TheNetAdmin/zjuthesis/files/8145890/2019.pdf)

**Comment by TheNetAdmin** [comment]
> [浙江大学经济学院博士学位论文模板（2019版）.docx](https://github.com/TheNetAdmin/zjuthesis/files/8145889/2019.docx) [浙江大学经济学院博士学位论文模板（2019版）.pdf](https://github.com/TheNetAdmin/zjuthesis/files/8145890/2019.pdf)

感谢提供文件，我看了一下这似乎是浙大2019年对博士生论文的统一格式规范？如果是的话我可以统一订正一下博士生模板。

以及是否可以提供一个发布了博士生论文格式规范的校内网址？我可以去查看一下。

**Comment by YaoZhongwei** [comment]
> > [浙江大学经济学院博士学位论文模板（2019版）.docx](https://github.com/TheNetAdmin/zjuthesis/files/8145889/2019.docx) [浙江大学经济学院博士学位论文模板（2019版）.pdf](https://github.com/TheNetAdmin/zjuthesis/files/8145890/2019.pdf)
> 
> @YaoZhongwei 感谢提供文件，我看了一下这似乎是浙大2019年对博士生论文的统一格式规范？如果是的话我可以统一订正一下博士生模板。
> 
> 以及是否可以提供一个发布了博士生论文格式规范的校内网址？我可以去查看一下。

这是[经济学院](http://www.cec.zju.edu.cn/bgxz_36446/list.htm)发布的一个模板，尚不清楚是否是全校统一的博士生论文模板。校内地址为[浙江大学经济学院研究生论文写作模板（2019）](http://www.cec.zju.edu.cn/_upload/article/files/3a/73/f8a2b8c3454c80c81b28366ced88/7773ac7b-51b5-485e-80ae-3c55f5fe4888.rar)
