### ISSUE TITLE
overleaf与本地同步

### ISSUE THREAD

**Issue by ZedongPeng** [TheNetAdmin/zjuthesis#95]
## 可改进的内容
Repo 提供了overleaf和本地编译两种方式。

我想实现overleaf和本地通过git交互（overleaf professional提供的功能），但是试了一下，本地编译版本在overleaf上无法编译，overleaf版本在本地无法编译。

有什么通用的方法吗？

## 预期结果
本地修改push到gihub上，overleaf可以自动同步，overleaf上的修改也可以到pull到本地，两边都可以进行编译

**Comment by TheNetAdmin** [comment]
FAQ里有写，删除.latexmkrc文件 https://github.com/TheNetAdmin/zjuthesis/blob/master/docs/FAQ.md

**Comment by ZedongPeng** [comment]
谢谢小哥，删除.latexmkrc文件并修改`config/format/general/font.tex`就可以了
