### ISSUE TITLE
图片、公式、文献引用都失败了，求助

### ISSUE THREAD

**Issue by pch9520** [TheNetAdmin/zjuthesis#99]
win10+vscode+TexLive2019+xelatex+graduate

LaTeX Warning: Reference `fig:pedgomode' on page 12 undefined on input line 89.

LaTeX Warning: Citation 'duchi' on page 17 undefined on input line 218.

LaTeX Warning: Reference `equ:2-7' on page 18 undefined on input line 231.

zjuthesis.log链接我放下面了

图片、公式、文献引用都失败了，求助，感谢！

## 系统信息

**操作系统**

- [x] Windows
- [ ] MacOS
- [ ] Linux/Docker
- [ ] Overleaf

**TeX套件**

- [ ] TeXLive 2020 或更新的版本
- [x] TeXLive 2019
- [ ] TeXLive 2018 或更早的版本
- [ ] MikTex

**TeX Compiler**

- [x] XeTeX
- [ ] LuaTeX

**zjuthesis**

版本号：

Degree:
  - [ ] graduate
    - [x] master
    - [ ] doctor
  - [ ] undergraduate

Major:
  - [x] general
  - [ ] cs
  - [ ] isee
  - [ ] math
  - [ ] physics

**编译日志**

[zjuthesis.log](https://github.com/TheNetAdmin/zjuthesis/files/5682357/zjuthesis.log)

## 遇到的问题

**截图**

**其他信息**

**Comment by TheNetAdmin** [comment]
什么信息都没有我怎么帮你？至少把必要信息填好，改了什么代码，用了什么工具编译

**Comment by pch9520** [comment]
> 什么信息都没有我怎么帮你？至少把必要信息填好，改了什么代码，用了什么工具编译

我补充了一些

**Comment by TheNetAdmin** [comment]
自己上网搜解决方法吧，我没法帮你

**Comment by pch9520** [comment]
解决了，是之前码字的时候不小心用了中文花括号，改成英文花括号就可以了
